"""Foundation curriculum graph. Does not train. MOD-02A is completed evidence."""
from __future__ import annotations

from typing import Any

from wrim_promptbook.identity import BUDGETS, PHRASE_REF, RMR1_EXTRA_UNSEEN_RECALL, STRATEGY_CEILING


def _school(
    sid: str,
    *,
    name: str,
    purpose: str,
    status: str,
    next_ids: list[str],
    authorized: list[str],
    prohibited: list[str],
    success: list[str],
    failure: list[str],
    repair: str,
    return_if: list[str],
    missions: list[dict[str, Any]],
    notes: str = "",
) -> dict[str, Any]:
    budget = BUDGETS.get(sid, {"kind": "none", "lm_tokens": 0})
    return {
        "id": sid,
        "name": name,
        "purpose": purpose,
        "status": status,
        "next": next_ids,
        "authorized_actions": authorized,
        "prohibited_actions": prohibited,
        "token_budget": budget,
        "strategy_ceiling": STRATEGY_CEILING,
        "success_criteria": success,
        "failure_criteria": failure,
        "repair_path": repair,
        "return_to_commander_if": return_if,
        "missions": missions,
        "notes": notes,
    }


def curriculum_graph() -> dict[str, Any]:
    schools = [
        _school(
            "SCHOOL_00_TRUTH_REPRODUCIBILITY",
            name="Truth / Reproducibility",
            purpose="Prove environment and lineage before any experiment.",
            status="REQUIRED_PREFLIGHT",
            next_ids=["SCHOOL_01_RESPONSE_CONTROL"],
            authorized=["verify_hashes", "verify_tokenizer", "verify_lock", "read_checkpoints"],
            prohibited=["train", "promote"],
            success=["canonical_match", "parent_hash_match", "tokenizer_match", "stage3_baseline_readable"],
            failure=["hash_mismatch", "lock_contention", "checkpoint_unreadable"],
            repair="Repair environment or return boundary. Do not train.",
            return_if=["FROZEN_HASH_VIOLATION", "TRAINER_GOVERNANCE_FAILURE"],
            missions=[{"id": "VERIFY_WRIM_TRUTH", "trainable": [], "frozen": ["all"]}],
        ),
        _school(
            "SCHOOL_01_RESPONSE_CONTROL",
            name="Response Control",
            purpose="Assistant-entry, span, EOS, ramble, empty, multi-turn reset.",
            status="ESTABLISHED_REGRESSION_ONLY",
            next_ids=["SCHOOL_02_STRUCTURED_ENTRY"],
            authorized=["regression_eval"],
            prohibited=["unfreeze_body", "change_tokenizer"],
            success=["eos_stopping", "empty_low", "ramble_controlled", "multi_turn_reset"],
            failure=["newline_attractor_return", "no_eos"],
            repair="Reopen only if future failures appear.",
            return_if=[],
            missions=[{"id": "RESPONSE_CONTROL_REGRESSION", "trainable": [], "frozen": ["all"]}],
        ),
        _school(
            "SCHOOL_02_STRUCTURED_ENTRY",
            name="Structured Entry",
            purpose="Preserve EA1 first-token classes.",
            status="ESTABLISHED",
            next_ids=["SCHOOL_03_STRUCTURED_CONTINUATION"],
            authorized=["eval_entry_classes"],
            prohibited=["remove_ea1_globally", "train_ea1_without_gate"],
            success=["blue_cat_dog_no_entry_retained"],
            failure=["structured_entry_collapse"],
            repair="Restore EA1+RA1 identity from parent 000010.",
            return_if=[],
            missions=[{"id": "EA1_IDENTITY", "trainable": [], "frozen": ["base", "ra1"]}],
            notes="EA1 remains useful for natural entry. Do not remove globally.",
        ),
        _school(
            "SCHOOL_03_STRUCTURED_CONTINUATION",
            name="Structured Continuation",
            purpose="Preserve RA1 phrase continuation.",
            status="ESTABLISHED",
            next_ids=["SCHOOL_04_RESPONSE_MODE_ROUTING"],
            authorized=["eval_phrase"],
            prohibited=["enlarge_ra1", "train_ra1_without_gate"],
            success=[f"phrase>={PHRASE_REF['phrase']}", "paraphrase>=3"],
            failure=["phrase_destroyed_by_bypass_on_structured"],
            repair="Fail-closed structured route EA1+RA1.",
            return_if=[],
            missions=[{"id": "RA1_IDENTITY", "trainable": [], "frozen": ["base", "ea1"]}],
            notes="Protected capability. phrase 17 blue 3 no 5 dog 5 cat 4 two 6 three 10 paraphrase 3.",
        ),
        _school(
            "SCHOOL_04_RESPONSE_MODE_ROUTING",
            name="Response-Mode Routing",
            purpose="Learn when RA1 should apply. STRUCTURED=EA1+RA1 NATURAL=EA1+BYPASS.",
            status="EXPERIMENTAL_PASS_WITH_GENERALIZATION_AND_REGRESSION_WORK_REMAINING",
            next_ids=["SCHOOL_05_NATURAL_ENTRY", "SCHOOL_04B_ROUTER_DATA_REMEDIATION"],
            authorized=["import_mod02a_evidence", "router_eval_readonly", "enter_04b_explicitly"],
            prohibited=["rerun_mod02a_by_default", "install_rmr1_production", "train_na1", "implement_ne1"],
            success=["MOD_02A_ROUTER_PROOF=PASS already recorded"],
            failure=["false_natural_destroys_phrase"],
            repair="SCHOOL_04B callable remediation. Do not block School 05.",
            return_if=["ROUTER_REPRESENTATION_BOUNDARY"],
            missions=[
                {
                    "id": "MOD_02A",
                    "status": "COMPLETED",
                    "trainable": ["rmr1"],
                    "frozen": ["base", "ea1", "ra1", "na1", "lm_head", "tok_emb", "transformer"],
                    "do_not_rerun": True,
                    "extra_unseen_recall": RMR1_EXTRA_UNSEEN_RECALL,
                    "production_ready": False,
                    "two_token_regression_open": True,
                }
            ],
            notes=(
                "MOD-02A implemented and completed. Linear 514. extra-unseen 0.45 vs probe 0.65. "
                "ROUTER_PRODUCTION_READY=NO. ROUTER_REGRESSION_OPEN=YES on two-token val (1 vs 3). "
                "Do not treat routing as pending. Do not install in War Room runtime."
            ),
        ),
        _school(
            "SCHOOL_04B_ROUTER_DATA_REMEDIATION",
            name="Router Data Remediation",
            purpose="Callable lane for extra-unseen routing, template leakage, two-token regression.",
            status="CALLABLE_NOT_CURRENT",
            next_ids=["SCHOOL_04_RESPONSE_MODE_ROUTING", "SCHOOL_05_NATURAL_ENTRY"],
            authorized=["audit_templates", "new_router_curriculum_version", "recalibrate_threshold_on_val_only"],
            prohibited=["train_on_extra_unseen", "enlarge_to_mlp_without_commander", "block_school_05"],
            success=["extra_unseen_recall_meaningfully_up", "two_token_identity_restored", "val_false_natural_still_low"],
            failure=["official_fit_extra_fail_after_3_strategies"],
            repair="After 3 distinct data strategies return ROUTER_REPRESENTATION_BOUNDARY.",
            return_if=["ROUTER_REPRESENTATION_BOUNDARY", "SCIENTIFIC_LANE_EXHAUSTED"],
            missions=[{"id": "ROUTER_DATA_REMEDIATION", "status": "AVAILABLE", "trainable": ["rmr1"], "frozen": ["all_wrim"]}],
        ),
        _school(
            "SCHOOL_05_NATURAL_ENTRY",
            name="Natural Entry",
            purpose="Diagnose and, only if gated, bound a NE1 capacity proof. Token1 is the bottleneck.",
            status="CURRENT",
            next_ids=["SCHOOL_06_NATURAL_CONTINUATION"],
            authorized=[
                "natural_entry_diagnostic",
                "token1_rank_attractor_map",
                "gold_token1_ceiling",
                "ea1_residual_probe",
                "leakage_audit",
                "plan_ne1_but_do_not_auto_build",
            ],
            prohibited=[
                "automatically_create_ne1",
                "train_ea1_ra1_base",
                "use_learned_router_in_first_ne1_proof",
                "train_on_heldout_eval",
                "install_rmr1",
            ],
            success=[
                "diagnostic_complete",
                "ne1_decision_recorded",
                "if_ne1_trained: extra_unseen_token1_and_greedy_improve",
            ],
            failure=["token1_not_earliest_failure", "gold_token1_does_not_unlock_span"],
            repair="Data/objective redesign using current EA1 before any NE1.",
            return_if=["ARCHITECTURE_CHANGE_REQUIRED", "SCIENTIFIC_LANE_EXHAUSTED"],
            missions=[
                {
                    "id": "NATURAL_ENTRY_NE1_REVIEW",
                    "status": "CURRENT",
                    "kind": "DIAGNOSTIC_AND_DECISION",
                    "trainable": [],
                    "frozen": ["base", "ea1", "ra1", "rmr1", "lm_head", "tok_emb"],
                    "options": ["A_data_objective_redesign_ea1", "B_bounded_ne1_proof", "C_other_entry_mechanism"],
                    "ne1_auto_create": False,
                }
            ],
            notes=(
                "EA1+BYPASS official 3 extra 1; EA1-off+BYPASS 2/0. Gold token1 3→6 / 1→9. "
                "EA1 residual cosine phrase-vs-natural ~0.984. Attractors: no dog blue red ok. "
                "RMR1 frozen experimental, not part of first NE1 proof. If NE1: B32 entry-only "
                "pre_lm_head zero-init train NE1 only; natural=NE1 then BYPASS; structured EA1+RA1 protected; "
                "oracle NATURAL mode for capacity proof; budget 102400 extend once to 204800."
            ),
        ),
        _school(
            "SCHOOL_06_NATURAL_CONTINUATION",
            name="Natural Continuation",
            purpose="After entry is corrected, test whether frozen-base BYPASS span is enough.",
            status="PENDING",
            next_ids=["SCHOOL_07_NATURAL_GENERALIZATION"],
            authorized=["free_greedy", "gold_prefix_1_2_3", "prefix_depth"],
            prohibited=["revive_na1_without_token2plus_localization"],
            success=["bypass_sufficient_or_failure_localized_to_span"],
            failure=["entry_still_broken"],
            repair="Do not revive NA1 unless entry is established AND bypass span is insufficient.",
            return_if=[],
            missions=[{"id": "NATURAL_CONTINUATION_BYPASS_TEST", "trainable": [], "frozen": ["all"]}],
        ),
        _school(
            "SCHOOL_07_NATURAL_GENERALIZATION",
            name="Natural Generalization",
            purpose="Train/val/extra-unseen/family/paraphrase/adversarial-template must stay distinct.",
            status="PENDING",
            next_ids=["SCHOOL_08_MULTI_TURN_CONVERSATION"],
            authorized=["contamination_audit", "heldout_eval"],
            prohibited=["train_on_extra_unseen", "merge_public_metrics"],
            success=["extra_unseen_and_family_holdout_reported_separately"],
            failure=["template_memorization_only"],
            repair="New dataset version + hash + lineage. No silent mutation.",
            return_if=["DATA_BOUNDARY_REQUIRES_NEW_CORPUS_SOURCE", "EVALUATION_SUITE_CONTAMINATION"],
            missions=[{"id": "NATURAL_GENERALIZATION_GATES", "trainable": [], "frozen": ["eval_suites"]}],
        ),
        _school(
            "SCHOOL_08_MULTI_TURN_CONVERSATION",
            name="Multi-turn Conversation",
            purpose="Two/three-turn continuity, route reset, mode changes. Not persistent memory.",
            status="PENDING",
            next_ids=["SCHOOL_09_INSTRUCTION_FOLLOWING"],
            authorized=["multi_turn_eval", "route_reset_eval"],
            prohibited=["claim_long_term_memory"],
            success=["structured_to_natural_and_reverse_no_leak", "followup_continuity"],
            failure=["route_latch_leaks_across_eos"],
            repair="Reuse RMR1 latch/EOS tests; do not conflate with Ra'el memory.",
            return_if=[],
            missions=[{"id": "MULTI_TURN_CONTEXT_WINDOW", "trainable": [], "frozen": []}],
        ),
        _school(
            "SCHOOL_09_INSTRUCTION_FOLLOWING",
            name="Instruction Following",
            purpose="Brief, JSON, code-only, explain, list, transform, classify, extract, constraints.",
            status="PENDING",
            next_ids=["SCHOOL_10_GENERAL_LANGUAGE"],
            authorized=["instruction_eval", "instruction_corpus_train", "ne1_instruction_capacity", "ir1_instruction_capacity", "iia1_internal_adapter"],
            prohibited=["train_on_eval_answers", "train_on_graduation", "body_unfreeze", "install_rmr1", "ne1_more_of_same", "ir1_lower_lr_retry", "ir1_b64"],
            success=["format_constraints_heldout", "multi_family_val_and_holdout_improve"],
            failure=["ignores_negative_constraints", "train_only_memorization"],
            repair="IIA1 internal last-4-layer rank-8 residual after NE1 and IR1 failure.",
            return_if=["DATA_BOUNDARY_REQUIRES_NEW_CORPUS_SOURCE", "ARCHITECTURE_CHANGE_REQUIRED", "SCIENTIFIC_LANE_EXHAUSTED", "CAPACITY_BOUNDARY_REQUIRES_MODEL_SCALE_CHANGE", "GRADIENT_HARD_STOP_UNRESOLVED"],
            missions=[{
                "id": "IIA1_CAPACITY_PROOF",
                "trainable": ["iia1"],
                "frozen": ["base", "ea1", "ra1", "ne1", "ir1", "lm_head", "tok_emb", "rmr1", "na1"],
                "parent": "WRIM1-UH1-AC2-NE1-000001/step-40",
                "oracle": "IIA1_INTERNAL",
                "budget": 204800,
            }],
        ),
        _school(
            "SCHOOL_10_GENERAL_LANGUAGE",
            name="General Language",
            purpose="Held-out QA, definitions, short explanation, summary, classification.",
            status="PENDING",
            next_ids=["SCHOOL_11_REASONING_FOUNDATION"],
            authorized=["heldout_language_eval"],
            prohibited=["train_on_general_eval"],
            success=["heldout_language_improves_without_nl_nll_regression"],
            failure=["independent_nl_nll_regresses"],
            repair="Retention floor vs STEP_400.",
            return_if=[],
            missions=[{"id": "GENERAL_LANGUAGE_HELD_OUT", "trainable": [], "frozen": ["eval_nl"]}],
        ),
        _school(
            "SCHOOL_11_REASONING_FOUNDATION",
            name="Reasoning Foundation",
            purpose="Small measurable reasoning. Do not claim advanced reasoning.",
            status="PENDING",
            next_ids=["SCHOOL_12_STRUCTURED_OUTPUT"],
            authorized=["one_two_step_deduction_eval"],
            prohibited=["train_on_eval_answers", "claim_advanced_reasoning"],
            success=["exact_and_semantic_tracked_separately"],
            failure=["eval_contamination"],
            repair="Separate train/eval reasoning sets.",
            return_if=["EVALUATION_SUITE_CONTAMINATION"],
            missions=[{"id": "REASONING_FOUNDATION_SMALL", "trainable": [], "frozen": []}],
        ),
        _school(
            "SCHOOL_12_STRUCTURED_OUTPUT",
            name="Structured Output",
            purpose="Preserve JSON/code NLL and simple schemas.",
            status="PENDING",
            next_ids=["SCHOOL_13_TOOL_USE_READINESS"],
            authorized=["json_code_eval"],
            prohibited=["regress_code_json_nll"],
            success=["code_json_nll_not_worse_than_parent"],
            failure=["code_or_json_nll_regression"],
            repair="Retention eval bundle.",
            return_if=[],
            missions=[{"id": "STRUCTURED_OUTPUT_RETENTION", "trainable": [], "frozen": []}],
            notes="Independent NL NLL ~6.972 general ~5.247 code ~3.579 json ~3.282.",
        ),
        _school(
            "SCHOOL_13_TOOL_USE_READINESS",
            name="Tool-use Readiness",
            purpose="Recognize tool need, category, bounded args, interpret result. No unrestricted tools.",
            status="PENDING",
            next_ids=["SCHOOL_14_SELF_EVALUATION"],
            authorized=["tool_readiness_eval"],
            prohibited=["unrestricted_autonomous_tool_execution"],
            success=["tool_category_and_arg_construction_heldout"],
            failure=["executes_tools_outside_war_room_governance"],
            repair="Keep governance in War Room, not WRIM.",
            return_if=["SECURITY_GOVERNANCE_VIOLATION"],
            missions=[{"id": "TOOL_USE_READINESS", "trainable": [], "frozen": []}],
        ),
        _school(
            "SCHOOL_14_SELF_EVALUATION",
            name="Self-evaluation / Uncertainty",
            purpose="Unknown, insufficient evidence, needs tool, needs clarification, confidence bucket.",
            status="PENDING",
            next_ids=["SCHOOL_15_FOUNDATION_GRADUATION"],
            authorized=["uncertainty_behavior_eval"],
            prohibited=["claim_calibrated_probability_if_unproven"],
            success=["refuses_or_defers_when_unsupported"],
            failure=["hallucinated_certainty"],
            repair="Behavior eval only until calibration is measured.",
            return_if=[],
            missions=[{"id": "UNCERTAINTY_BEHAVIOR", "trainable": [], "frozen": []}],
        ),
        _school(
            "SCHOOL_15_FOUNDATION_GRADUATION",
            name="Foundation Graduation",
            purpose="Frozen WRIM-FOUNDATION-GRADUATION-1-v1.0.0. Never train on it. Never self-promote.",
            status="PENDING",
            next_ids=["RAEL_00_FOUNDATION_INGESTION"],
            authorized=["run_graduation_suite_readonly"],
            prohibited=["train_on_graduation_suite", "self_promote", "change_canonical", "start_stage3b", "start_rael_training"],
            success=["FOUNDATION_READY_FOR_GRADUATION_REVIEW returned to Commander"],
            failure=["FOUNDATION_NOT_READY_CONTINUE_CURRICULUM"],
            repair="Continue earlier school. Stage3 floor 5/6 prefer 6/6 never 4/6.",
            return_if=["FOUNDATION_READY_FOR_GRADUATION_REVIEW", "CANONICAL_PROMOTION_DECISION_REQUIRED"],
            missions=[{"id": "FOUNDATION_GRADUATION_REVIEW", "trainable": [], "frozen": ["graduation_suite"]}],
        ),
    ]
    rael = []
    for i, (rid, name, purpose) in enumerate([
        ("RAEL_00_FOUNDATION_INGESTION", "Foundation ingestion", "Design only. Ingest graduated WRIM, do not auto-train Ra'el."),
        ("RAEL_01_IDENTITY_ORCHESTRATION", "Identity / orchestration contract", "Ra'el is not a renamed WRIM checkpoint."),
        ("RAEL_02_COUNCIL_ROUTING", "Council routing", "Design Council integration."),
        ("RAEL_03_TOOL_USE_GOVERNANCE", "Tool-use governance", "War Room remains tool governor."),
        ("RAEL_04_PERSISTENT_MEMORY", "Persistent memory integration", "Not School 08 context-window chat."),
        ("RAEL_05_WORLD_LEARNING", "World-learning interface", "Design only."),
        ("RAEL_06_PLANNING", "Planning / decomposition", "Design only."),
        ("RAEL_07_SELF_EVALUATION", "Self-evaluation", "Design only."),
        ("RAEL_08_SPECIALIST_ROUTING", "Specialist routing", "Future sparse experts; no full MoE in Genesis."),
        ("RAEL_09_CONTINUOUS_BOUNDED_LEARNING", "Continuous bounded learning", "Design only."),
        ("RAEL_10_SOVEREIGN_RUNTIME", "Sovereign runtime integration", "Design only."),
    ]):
        nxt = [rael[i + 1][0]] if False else []
        rael.append(_school(
            rid,
            name=name,
            purpose=purpose,
            status="DESIGN_ONLY_AFTER_FOUNDATION_GRADUATION",
            next_ids=[],
            authorized=["design_document"],
            prohibited=["rael_training", "auto_execute"],
            success=["bridge_document_complete"],
            failure=["false_relabel_wrim_as_rael"],
            repair="Return RAEL_POST_FOUNDATION_EXECUTION_AUTHORIZATION.",
            return_if=["RAEL_POST_FOUNDATION_EXECUTION_AUTHORIZATION"],
            missions=[{"id": rid, "status": "DESIGN_ONLY", "trainable": [], "frozen": ["all"]}],
        ))
    for i, node in enumerate(rael):
        if i + 1 < len(rael):
            node["next"] = [rael[i + 1]["id"]]
    return {
        "id": "WRIM_GENESIS_FOUNDATION_CURRICULUM_v1",
        "canonical": "STEP_400",
        "parent": "WRIM1-UH1-AC2-EA1-000010/step-25",
        "current_school": "SCHOOL_05_NATURAL_ENTRY",
        "current_mission": "NATURAL_ENTRY_NE1_REVIEW",
        "mod_02a_imported": True,
        "mod_02a_do_not_rerun": True,
        "school_04_callable_remediation": "SCHOOL_04B_ROUTER_DATA_REMEDIATION",
        "schools": schools,
        "rael_bridge": rael,
        "advancement_rule": (
            "May advance without Commander if school success, retention floors, token accounting, "
            "gradient safety pass, and no architecture/canonical/promotion action is required."
        ),
        "ordinary_bugs": "Fix, validate, continue. Do not return to Commander.",
        "scientific_vs_engineering": [
            "IMPLEMENTATION_FAILURE",
            "DATA_FAILURE",
            "OBJECTIVE_FAILURE",
            "CAPACITY_FAILURE",
            "ROUTING_FAILURE",
            "GENERALIZATION_FAILURE",
            "RETENTION_FAILURE",
            "ARCHITECTURE_BOUNDARY",
        ],
    }


def school_by_id(graph: dict[str, Any], sid: str) -> dict[str, Any]:
    for s in graph["schools"] + graph["rael_bridge"]:
        if s["id"] == sid:
            return s
    raise KeyError(sid)


def ordered_school_ids(graph: dict[str, Any]) -> list[str]:
    return [s["id"] for s in graph["schools"]]
