"""Promptbook identity and frozen WRIM truth. Does not train."""
from __future__ import annotations

from pathlib import Path

from wrim_cpt_identity import TOKENIZER_SHA
from wrim_cpt5_identity import CANONICAL_CHECKPOINT, CANONICAL_HASH, TOKENIZER_ID
from wrim_hvu_identity import CKPT_BASE, DATA_ROOT, TOKENIZER_EXPECTED_SHA

PROMPTBOOK_ID = "WRIM_GENESIS_FOUNDATION_MASTER_PROMPTBOOK_v1"
PROMPTBOOK_VERSION = "v1"
REPO_SPEC_DIR = Path(__file__).resolve().parents[3] / "docs" / "wrim" / "promptbook"
LIVE_DIR_NAME = "WRIM_PROMPTBOOK_LIVE"
LIVE_DIR = Path(DATA_ROOT) / LIVE_DIR_NAME

CANONICAL = CANONICAL_CHECKPOINT
CANONICAL_MODEL_HASH = CANONICAL_HASH
PARENT_RUN = "WRIM1-UH1-AC2-EA1-000010"
PARENT_STEP = "step-25"
PARENT_CHECKPOINT = f"{PARENT_RUN}/{PARENT_STEP}"
PARENT_HASH = "8e6505954602961d7b432362b67633aa1cc798f7a7b4262624edb3ed213323fb"
PARENT_CKPT = Path(CKPT_BASE) / PARENT_RUN / PARENT_STEP
ARCHITECTURE_ID = "WRIM-G-20M-v1-option-A-UH1-AC2-EA1-RA1"
ARCHITECTURE_FAMILY = ARCHITECTURE_ID
D_MODEL = 256
N_LAYERS = 18
N_HEADS = 4
D_FF = 768
CTX = 512
VOCAB = 15126
PARAM_COUNT_APPROX = 23_123_200
EA1_PARAMS = 16640
RA1_PARAMS = 16640
NA1_PARAMS = 16640
RMR1_PARAMS = 514

TOKENIZER_NAME = TOKENIZER_ID
TOKENIZER_HASH = TOKENIZER_EXPECTED_SHA or TOKENIZER_SHA
SUITE_SHA = "934ff60bcd179ec643257fbfaa30f2a3a7621b175fc7d3c3d0efc30d946d5ac4"

STAGE3_FLOOR = 5
STAGE3_PREFER = 6
STAGE3_CURRENT = 6
MAX_TRAINERS = 1
GRAD_PREFERRED = 6.5
GRAD_HARD = 8.0
STRATEGY_CEILING = 3

CURRENT_SCHOOL = "SCHOOL_05_NATURAL_ENTRY"
CURRENT_MISSION = "NATURAL_ENTRY_NE1_REVIEW"
SCHOOL_04_STATUS = "EXPERIMENTAL_PASS_WITH_GENERALIZATION_AND_REGRESSION_WORK_REMAINING"

MOD02A_REPORT = Path(DATA_ROOT) / "WRIM_GENESIS_MOD_02A_RESPONSE_MODE_ROUTER_REPORT.json"
MOD02A_ARTIFACT = Path(DATA_ROOT) / "WRIM_RMR1_MOD02A"
RMR1_HASH = "aeeaee97fdc7b965667736480413c8e4b95f3b46d462623bb9b52a5c18dd6684"
RMR1_THRESHOLD = 0.75
RMR1_EXTRA_UNSEEN_RECALL = 0.45
FROZEN_BASE_HASH = "90db7bcbe27dd1c146e2de9283b9da83d039efde35946c29e548f02863192ea3"
EA1_HASH = "5faadd16f1313c542c036d91e2fe6859e9cddd9fb2027ea2cae70d00cad8809b"
RA1_HASH = "bda36d0318cad8b0a3c00ed102c3d08a1f258eceea8365a1d09f190585f18120"

PHRASE_REF = {
    "phrase": 17,
    "blue": 3,
    "no": 5,
    "dog": 5,
    "cat": 4,
    "two": 6,
    "three": 10,
    "paraphrase": 3,
}

BUDGETS = {
    "SCHOOL_04_RESPONSE_MODE_ROUTING": {"kind": "classification", "lm_tokens": 0, "examples": 4096},
    "SCHOOL_04B_ROUTER_DATA_REMEDIATION": {"kind": "classification", "lm_tokens": 0, "examples": 4096},
    "SCHOOL_05_NATURAL_ENTRY": {"kind": "lm", "lm_tokens": 204_800, "extend_once_to": 204_800},
    "SCHOOL_06_NATURAL_CONTINUATION": {"kind": "lm", "lm_tokens": 409_600},
    "SCHOOL_07_NATURAL_GENERALIZATION": {"kind": "lm", "lm_tokens": 409_600},
    "SCHOOL_08_MULTI_TURN_CONVERSATION": {"kind": "lm", "lm_tokens": 204_800},
    "SCHOOL_09_INSTRUCTION_FOLLOWING": {"kind": "lm", "lm_tokens": 819_200},
    "SCHOOL_10_GENERAL_LANGUAGE": {"kind": "lm", "lm_tokens": 204_800},
    "SCHOOL_11_REASONING_FOUNDATION": {"kind": "lm", "lm_tokens": 204_800},
    "SCHOOL_12_STRUCTURED_OUTPUT": {"kind": "lm", "lm_tokens": 102_400},
    "SCHOOL_13_TOOL_USE_READINESS": {"kind": "none", "lm_tokens": 0},
    "SCHOOL_14_SELF_EVALUATION": {"kind": "none", "lm_tokens": 0},
    "SCHOOL_15_FOUNDATION_GRADUATION": {"kind": "none", "lm_tokens": 0},
    "BR1_UPPER_BODY_PLASTICITY": {"kind": "lm", "lm_tokens": 409_600},
}
# Remaining Foundation development after School 04. Router is not LM tokens.
RECOMMENDED_MASTER_LM_TOKEN_CEILING = 2_048_000

STATE_NAME = "WRIM_GENESIS_FOUNDATION_STATE.json"
LEDGER_NAME = "WRIM_GENESIS_EXPERIMENT_LEDGER.jsonl"
REGISTRY_NAME = "WRIM_GENESIS_CHECKPOINT_REGISTRY.json"
MATRIX_NAME = "WRIM_GENESIS_CAPABILITY_MATRIX.json"
GOVERNANCE_NAME = "WRIM_GENESIS_GOVERNANCE.json"
BOUNDARIES_NAME = "WRIM_GENESIS_RETURN_BOUNDARIES.json"
EVAL_MANIFEST_NAME = "WRIM_GENESIS_EVALUATION_MANIFEST.json"
GRAPH_NAME = "WRIM_GENESIS_CURRICULUM_GRAPH.json"
PROMPTBOOK_JSON_NAME = "WRIM_GENESIS_FOUNDATION_MASTER_PROMPTBOOK_v1.json"
PROMPTBOOK_MD_NAME = "WRIM_GENESIS_FOUNDATION_MASTER_PROMPTBOOK_v1.md"
RAEL_BRIDGE_NAME = "WRIM_GENESIS_RAEL_DEVELOPMENT_BRIDGE_v1.md"
BUILD_REPORT_NAME = "WRIM_GENESIS_FOUNDATION_MASTER_PROMPTBOOK_V1_BUILD_REPORT.json"

EXPERIMENT_STATUSES = (
    "PLANNED",
    "PREFLIGHT",
    "RUNNING",
    "PAUSED",
    "COMPLETED",
    "REJECTED",
    "BLOCKED",
    "INVALID",
    "QUARANTINED",
)

RETURN_BOUNDARIES = [
    "FOUNDATION_READY_FOR_GRADUATION_REVIEW",
    "CANONICAL_PROMOTION_DECISION_REQUIRED",
    "ARCHITECTURE_CHANGE_REQUIRED",
    "SCIENTIFIC_LANE_EXHAUSTED",
    "DATA_BOUNDARY_REQUIRES_NEW_CORPUS_SOURCE",
    "CAPACITY_BOUNDARY_REQUIRES_MODEL_SCALE_CHANGE",
    "TOKEN_BUDGET_EXPANSION_BEYOND_MASTER_CEILING",
    "FROZEN_HASH_VIOLATION",
    "TRAINER_GOVERNANCE_FAILURE",
    "GRADIENT_HARD_STOP_UNRESOLVED",
    "INSTRUCTION_REPRESENTATION_OR_DATA_TRANSFER_FAILURE",
    "INSTRUCTION_DATA_OBJECTIVE_BOUNDARY",
    "CAPACITY_BOUNDARY_REVIEW_REQUIRED",
    "DATA_BOUNDARY_REQUIRES_RETENTION_REPLAY_CORPUS",
    "BODY_PLASTICITY_PROOF_PASS",
    "PLASTICITY_RETENTION_TRADEOFF",
    "REPRESENTATION_GENERALIZATION_FAILURE",
    "BASE_CAPACITY_OR_PRETRAINING_BOUNDARY",
    "EVALUATION_SUITE_CONTAMINATION",
    "SECURITY_GOVERNANCE_VIOLATION",
    "MODEL_PROMOTION",
    "STAGE3B_START",
    "RAEL_POST_FOUNDATION_EXECUTION_AUTHORIZATION",
]

PROHIBITED_ALWAYS = [
    "autonomous_commit",
    "push",
    "production_deploy",
    "canonical_promotion",
    "financial_action",
    "network_credential_changes",
    "destructive_repository_cleanup",
    "secret_export",
    "body_unfreeze",
    "lm_head_training",
    "tokenizer_replacement",
    "transformer_depth_width_change",
    "large_lora",
    "new_base_model",
    "full_sparse_moe",
    "stage3b",
    "rael_training",
    "install_rmr1_in_runtime",
    "rerun_mod02a_by_default",
]
