/**
 * 187-row Master Film Production Capability Matrix mapped onto the 10 HVS production pages.
 * Source: docs/hvs-waves/HVS_MASTER_FILM_PRODUCTION_CAPABILITY_MATRIX.md
 * Do not duplicate rows when page organization changes — update `pages` only.
 */
import type { HvsProductionPageId } from './production-pages'

export type HvsMatrixState = 'SHIPPED' | 'PARTIAL' | 'SHELL' | 'RESEARCHED' | 'NOT STARTED' | 'BLOCKED'

export type HvsMatrixRow = {
  id: string
  group: string
  groupTitle: string
  name: string
  state: HvsMatrixState
  phase: string
  pages: HvsProductionPageId[]
}

export const HVS_MATRIX_ROWS: HvsMatrixRow[] = [
  { id: 'G0-01', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Native HVS section inside War Room', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-02', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: '`.hvsproj` SoT', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-03', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Rational media time', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-04', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Tracks = authoring truth', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-05', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Typed EditCommands human+AI', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-06', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Project persistence', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-07', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'EditTransaction preview vs commit', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-08', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Undo', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-09', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Redo', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G0-10', group: 'G0', groupTitle: 'Production kernel (prerequisite for every later group)', name: 'Immutable originals + no silent delete', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G1-01', group: 'G1', groupTitle: 'Creative development', name: 'Concept / premise / logline / synopsis / treatment', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G1-02', group: 'G1', groupTitle: 'Creative development', name: 'Tone / genre / audience / visual direction', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G1-03', group: 'G1', groupTitle: 'Creative development', name: 'Subject / historical / industry / location / visual / cinematography / technique research', state: 'SHELL', phase: '4', pages: ['ai'] },
  { id: 'G1-04', group: 'G1', groupTitle: 'Creative development', name: 'Creative brief (objective, audience, message, style, tone, runtime, platform, restrictions)', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G1-05', group: 'G1', groupTitle: 'Creative development', name: 'Prompt → structured development project', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G2-01', group: 'G2', groupTitle: 'Script system', name: 'ScriptProject', state: 'SHELL', phase: '4', pages: ['ai'] },
  { id: 'G2-02', group: 'G2', groupTitle: 'Script system', name: 'Scene / Beat / Dialogue / Action / CharacterCue / Transition', state: 'NOT STARTED', phase: '4', pages: ['ai'] },
  { id: 'G2-03', group: 'G2', groupTitle: 'Script system', name: 'Screenplay formatting + scene numbering + page estimates', state: 'NOT STARTED', phase: '4', pages: ['ai'] },
  { id: 'G2-04', group: 'G2', groupTitle: 'Script system', name: 'Revision / ScriptVersion / draft comparison', state: 'NOT STARTED', phase: '4', pages: ['ai'] },
  { id: 'G2-05', group: 'G2', groupTitle: 'Script system', name: 'Notes + character dialogue search', state: 'NOT STARTED', phase: '4', pages: ['ai'] },
  { id: 'G2-06', group: 'G2', groupTitle: 'Script system', name: 'AI write / rewrite / shorten / extend / change tone / continuity / polish / pacing', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G2-07', group: 'G2', groupTitle: 'Script system', name: 'Scripts UI', state: 'SHELL', phase: '4', pages: ['ai'] },
  { id: 'G3-01', group: 'G3', groupTitle: 'Script breakdown', name: 'Breakdown elements: cast, extras, props, wardrobe, makeup, vehicles, locations, sets, VFX, SFX, stunts, animals, equipment, music, sound, notes', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G3-02', group: 'G3', groupTitle: 'Script breakdown', name: 'AI scene → production requirements', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G4-01', group: 'G4', groupTitle: 'Storyboard', name: 'StoryboardFrame on project', state: 'SHELL', phase: '4', pages: ['ai', 'photo'] },
  { id: 'G4-02', group: 'G4', groupTitle: 'Storyboard', name: 'AI storyboard generation', state: 'SHELL', phase: '4', pages: ['ai', 'photo'] },
  { id: 'G4-03', group: 'G4', groupTitle: 'Storyboard', name: 'Manual replace / reorder / variations / visual style lock / shot continuity', state: 'NOT STARTED', phase: '4', pages: ['ai', 'photo'] },
  { id: 'G4-04', group: 'G4', groupTitle: 'Storyboard', name: 'Storyboard UI', state: 'SHELL', phase: '4', pages: ['ai', 'photo'] },
  { id: 'G5-01', group: 'G5', groupTitle: 'Previs / animatics', name: 'Storyboard animatic (timing, temp VO, temp music, temp SFX)', state: 'RESEARCHED', phase: '4', pages: ['ai', 'edit'] },
  { id: 'G5-02', group: 'G5', groupTitle: 'Previs / animatics', name: 'Camera path / shot duration / sequence preview', state: 'RESEARCHED', phase: '4', pages: ['ai', 'edit'] },
  { id: 'G5-03', group: 'G5', groupTitle: 'Previs / animatics', name: 'Basic 3D previs / blocking', state: 'RESEARCHED', phase: '9', pages: ['ai', 'edit'] },
  { id: 'G6-01', group: 'G6', groupTitle: 'Shot planner', name: 'Shot as first-class object (ShotSpec)', state: 'SHELL', phase: '4', pages: ['ai'] },
  { id: 'G6-02', group: 'G6', groupTitle: 'Shot planner', name: 'Shot ID / description / duration / references', state: 'NOT STARTED', phase: '4', pages: ['ai'] },
  { id: 'G6-03', group: 'G6', groupTitle: 'Shot planner', name: 'Generation method + provider requirements on shot', state: 'RESEARCHED', phase: '2-4', pages: ['ai'] },
  { id: 'G7-01', group: 'G7', groupTitle: 'Camera system (generative CameraSpec)', name: 'Camera A ≠ B ≠ C documented in product', state: 'SHIPPED', phase: '1', pages: ['ai', 'edit'] },
  { id: 'G7-02', group: 'G7', groupTitle: 'Camera system (generative CameraSpec)', name: 'CameraSpec structured data', state: 'SHELL', phase: '2', pages: ['ai', 'edit'] },
  { id: 'G7-03', group: 'G7', groupTitle: 'Camera system (generative CameraSpec)', name: 'Shot sizes: EWS, wide, full, medium full, medium, MCU, CU, ECU', state: 'PARTIAL', phase: '2', pages: ['ai', 'edit'] },
  { id: 'G7-04', group: 'G7', groupTitle: 'Camera system (generative CameraSpec)', name: 'Angles: eye, low, high, overhead, bird’s-eye, worm’s-eye, Dutch, profile, 3/4, POV, OTS', state: 'PARTIAL', phase: '2', pages: ['ai', 'edit'] },
  { id: 'G7-05', group: 'G7', groupTitle: 'Camera system (generative CameraSpec)', name: 'Movements: static, pan, tilt, dolly, truck, pedestal, orbit, crane, jib, drone, push, pull, tracking, follow, handheld, Steadicam, whip, rack focus', state: 'PARTIAL', phase: '2', pages: ['ai', 'edit'] },
  { id: 'G7-06', group: 'G7', groupTitle: 'Camera system (generative CameraSpec)', name: 'Framing / lens intent / DOF / focus target / subject target / lighting / trajectory', state: 'PARTIAL', phase: '2', pages: ['ai', 'edit'] },
  { id: 'G8-01', group: 'G8', groupTitle: 'Real camera / multicam', name: 'MulticamGroup type', state: 'SHELL', phase: '9', pages: ['media', 'cut', 'edit'] },
  { id: 'G8-02', group: 'G8', groupTitle: 'Real camera / multicam', name: 'Camera metadata / timecode', state: 'PARTIAL', phase: '9', pages: ['media', 'cut', 'edit'] },
  { id: 'G8-03', group: 'G8', groupTitle: 'Real camera / multicam', name: 'Audio / waveform sync', state: 'RESEARCHED', phase: '9', pages: ['media', 'cut', 'edit'] },
  { id: 'G8-04', group: 'G8', groupTitle: 'Real camera / multicam', name: 'Angle viewer + switch/cut + multicam timeline', state: 'NOT STARTED', phase: '9', pages: ['media', 'cut', 'edit'] },
  { id: 'G8-05', group: 'G8', groupTitle: 'Real camera / multicam', name: 'AI speaker detection / best-angle suggestions', state: 'RESEARCHED', phase: '9', pages: ['media', 'cut', 'edit'] },
  { id: 'G9-01', group: 'G9', groupTitle: 'Subject / person / object tracking', name: 'TrackSubject V1 person in a shot', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G9-02', group: 'G9', groupTitle: 'Subject / person / object tracking', name: 'Kinds: face, body, person, hands, product, object, custom', state: 'PARTIAL', phase: '5', pages: ['edit', 'vfx'] },
  { id: 'G9-03', group: 'G9', groupTitle: 'Subject / person / object tracking', name: 'Mask / attachment / text / graphics attachment / tracked effects', state: 'RESEARCHED', phase: '5', pages: ['edit', 'vfx'] },
  { id: 'G9-04', group: 'G9', groupTitle: 'Subject / person / object tracking', name: 'Occlusion / lost / reacquisition / human correction in record', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G9-05', group: 'G9', groupTitle: 'Subject / person / object tracking', name: 'SAM2 VOS + optional ByteTrack (not Ultralytics AGPL)', state: 'RESEARCHED', phase: '5', pages: ['edit', 'vfx'] },
  { id: 'G9-06', group: 'G9', groupTitle: 'Subject / person / object tracking', name: 'Auto reframe from track', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G10-01', group: 'G10', groupTitle: 'AI follow camera (virtual)', name: 'Follow this person / object', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G10-02', group: 'G10', groupTitle: 'AI follow camera (virtual)', name: 'Modes: face lock, upper-body, full-body, center lock, thirds, cinematic, dynamic social', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G10-03', group: 'G10', groupTitle: 'AI follow camera (virtual)', name: 'Convert tracking → crop / pan / zoom / keyframes / framing', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G11-01', group: 'G11', groupTitle: 'Media library / asset management', name: 'Ingest + proxy + thumbnails + waveforms', state: 'SHIPPED', phase: '1', pages: ['media', 'color'] },
  { id: 'G11-02', group: 'G11', groupTitle: 'Media library / asset management', name: 'AssetRecord', state: 'SHIPPED', phase: '1', pages: ['media'] },
  { id: 'G11-03', group: 'G11', groupTitle: 'Media library / asset management', name: 'Bins / folders / collections / favorites / rejected / ratings / keywords / tags', state: 'NOT STARTED', phase: '6', pages: ['media'] },
  { id: 'G11-04', group: 'G11', groupTitle: 'Media library / asset management', name: 'Metadata: camera, take, scene, slate, date, location, talent, lens, codec, resolution, fps, audio channels', state: 'PARTIAL', phase: '6', pages: ['media', 'color'] },
  { id: 'G11-05', group: 'G11', groupTitle: 'Media library / asset management', name: 'Origins: camera, upload, generated, derived, captured, stock, render, audio, still, graphic', state: 'PARTIAL', phase: '2', pages: ['media', 'deliver'] },
  { id: 'G12-01', group: 'G12', groupTitle: 'Dailies', name: 'Scene/take grouping, slate, takes, selects, circle, rejected, notes, director notes, continuity notes', state: 'RESEARCHED', phase: '6', pages: ['media', 'cut', 'review'] },
  { id: 'G12-02', group: 'G12', groupTitle: 'Dailies', name: 'Sync sound + proxy for dailies', state: 'PARTIAL', phase: '6', pages: ['media', 'cut', 'review'] },
  { id: 'G12-03', group: 'G12', groupTitle: 'Dailies', name: 'AI best-take suggestions', state: 'RESEARCHED', phase: '6', pages: ['media', 'cut', 'review'] },
  { id: 'G13-01', group: 'G13', groupTitle: 'Professional NLE', name: 'Insert / overwrite / append / split / trim / ripple delete / move', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-02', group: 'G13', groupTitle: 'Professional NLE', name: 'Lift / extract', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-03', group: 'G13', groupTitle: 'Professional NLE', name: 'Blade as tool', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-04', group: 'G13', groupTitle: 'Professional NLE', name: 'Roll / slip / slide / extend', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-05', group: 'G13', groupTitle: 'Professional NLE', name: 'Duplicate', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-06', group: 'G13', groupTitle: 'Professional NLE', name: 'Nested sequences / compound clips', state: 'NOT STARTED', phase: '5-9', pages: ['edit', 'cut'] },
  { id: 'G13-07', group: 'G13', groupTitle: 'Professional NLE', name: 'Synchronized clips / multicam clips', state: 'NOT STARTED', phase: '9', pages: ['edit', 'cut'] },
  { id: 'G13-08', group: 'G13', groupTitle: 'Professional NLE', name: 'Adjustment / effect layers', state: 'NOT STARTED', phase: '5', pages: ['edit', 'cut'] },
  { id: 'G13-09', group: 'G13', groupTitle: 'Professional NLE', name: 'Snapping', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-10', group: 'G13', groupTitle: 'Professional NLE', name: 'Markers / ranges', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-11', group: 'G13', groupTitle: 'Professional NLE', name: 'Source monitor', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G13-12', group: 'G13', groupTitle: 'Professional NLE', name: 'Program Viewer', state: 'PARTIAL', phase: '1/5', pages: ['edit', 'cut'] },
  { id: 'G14-01', group: 'G14', groupTitle: 'Keyframe / animation', name: 'Subject/camera keyframes', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G14-02', group: 'G14', groupTitle: 'Keyframe / animation', name: 'General keyframes: position, scale, rotation, opacity, crop, audio, filters, effects, masks, camera, speed', state: 'NOT STARTED', phase: '5', pages: ['edit', 'vfx'] },
  { id: 'G14-03', group: 'G14', groupTitle: 'Keyframe / animation', name: 'Interpolation: linear / ease / bezier', state: 'RESEARCHED', phase: '5', pages: ['edit', 'vfx'] },
  { id: 'G15-01', group: 'G15', groupTitle: 'Speed / motion', name: 'Slow / fast / reverse / freeze', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut'] },
  { id: 'G15-02', group: 'G15', groupTitle: 'Speed / motion', name: 'Variable speed / speed ramp', state: 'RESEARCHED', phase: '5', pages: ['edit', 'cut'] },
  { id: 'G15-03', group: 'G15', groupTitle: 'Speed / motion', name: 'Optical flow / interpolation / motion blur', state: 'SHELL', phase: '5', pages: ['edit', 'cut'] },
  { id: 'G15-04', group: 'G15', groupTitle: 'Speed / motion', name: 'Stabilization', state: 'RESEARCHED', phase: '5', pages: ['edit', 'cut'] },
  { id: 'G15-05', group: 'G15', groupTitle: 'Speed / motion', name: 'Rolling shutter correction', state: 'RESEARCHED', phase: '9', pages: ['edit', 'cut'] },
  { id: 'G16-01', group: 'G16', groupTitle: 'Transitions', name: 'Parameterized transition model', state: 'SHIPPED', phase: '1-5', pages: ['edit', 'cut', 'vfx'] },
  { id: 'G16-02', group: 'G16', groupTitle: 'Transitions', name: 'Full family: cut, dissolve, dip, wipe, push, slide, blur, zoom, spin, glitch, mask, morph, light, 3D, camera', state: 'PARTIAL', phase: '5', pages: ['edit', 'cut', 'vfx'] },
  { id: 'G16-03', group: 'G16', groupTitle: 'Transitions', name: 'Cut (default)', state: 'SHIPPED', phase: '1', pages: ['edit', 'cut', 'vfx'] },
  { id: 'G17-01', group: 'G17', groupTitle: 'Filters / looks', name: 'HVS-owned looks (non-destructive, adjustable)', state: 'SHIPPED', phase: '1', pages: ['edit', 'color'] },
  { id: 'G17-02', group: 'G17', groupTitle: 'Filters / looks', name: 'Rendered look matches preview', state: 'PARTIAL', phase: '1/5', pages: ['edit', 'color', 'deliver'] },
  { id: 'G17-03', group: 'G17', groupTitle: 'Filters / looks', name: 'Versioned looks', state: 'PARTIAL', phase: '5', pages: ['edit', 'color'] },
  { id: 'G18-01', group: 'G18', groupTitle: 'Themes', name: 'ThemeSpec engine (font, caption, title, transition, effects, color, pacing, motion, music, logo, overlays, camera hints)', state: 'SHIPPED', phase: '1', pages: ['edit', 'color'] },
  { id: 'G18-02', group: 'G18', groupTitle: 'Themes', name: 'Genre theme library (commercial, beauty, luxury, documentary, cinematic, horror, gaming, music video, wedding, automotive, real estate, social, YouTube)', state: 'PARTIAL', phase: '2', pages: ['edit', 'color'] },
  { id: 'G18-03', group: 'G18', groupTitle: 'Themes', name: 'No CapCut runtime', state: 'SHIPPED', phase: '1', pages: ['edit', 'color'] },
  { id: 'G19-01', group: 'G19', groupTitle: 'Color grading', name: 'Thin grade: exposure, contrast, saturation, temperature', state: 'SHIPPED', phase: '1', pages: ['color', 'edit'] },
  { id: 'G19-02', group: 'G19', groupTitle: 'Color grading', name: 'Curves, hue curves, wheels, lift/gamma/gain', state: 'PARTIAL', phase: '5', pages: ['color', 'edit'] },
  { id: 'G19-03', group: 'G19', groupTitle: 'Color grading', name: 'Masks, qualifiers, tracking, skin-tone protection', state: 'PARTIAL', phase: '5', pages: ['color', 'edit'] },
  { id: 'G19-04', group: 'G19', groupTitle: 'Color grading', name: 'LUTs', state: 'RESEARCHED', phase: '5', pages: ['color', 'edit'] },
  { id: 'G19-05', group: 'G19', groupTitle: 'Color grading', name: 'Scopes: waveform, parade, vectorscope, histogram', state: 'SHIPPED', phase: '5', pages: ['color', 'edit'] },
  { id: 'G19-06', group: 'G19', groupTitle: 'Color grading', name: 'HDR / log / OCIO / ACES', state: 'RESEARCHED', phase: '5', pages: ['color', 'edit'] },
  { id: 'G20-01', group: 'G20', groupTitle: 'VFX / compositing', name: 'Effect kind registry', state: 'SHELL', phase: '5', pages: ['vfx'] },
  { id: 'G20-02', group: 'G20', groupTitle: 'VFX / compositing', name: 'EffectGraph architecture', state: 'SHIPPED', phase: '5', pages: ['vfx'] },
  { id: 'G20-03', group: 'G20', groupTitle: 'VFX / compositing', name: 'Masks, rotoscope, keying (chroma/luma), planar/motion track, paint/remove, insert, relight, sky/bg replace, matte, alpha, blend, particles, glow, blur, distortion, lens, grain', state: 'PARTIAL', phase: '5-9', pages: ['vfx'] },
  { id: 'G20-04', group: 'G20', groupTitle: 'VFX / compositing', name: 'Future 3D compositing', state: 'RESEARCHED', phase: '9', pages: ['vfx'] },
  { id: 'G21-01', group: 'G21', groupTitle: 'Background / object editing (AI)', name: 'Remove/replace/blur background; remove person/object; insert object; isolate subject/product; relight; sky replace; depth-aware', state: 'SHELL', phase: '2', pages: ['vfx', 'ai', 'photo'] },
  { id: 'G22-01', group: 'G22', groupTitle: 'AI video generation', name: 'Provider-neutral Router', state: 'SHIPPED', phase: '2', pages: ['ai'] },
  { id: 'G22-02', group: 'G22', groupTitle: 'AI video generation', name: 'T2V / I2V / V2V / ref-image / character-ref / first-last frame / continuation / B-roll / style / motion / performance transfer / camera control / relight / bg change / scene extend / insert-remove', state: 'SHELL', phase: '2', pages: ['ai'] },
  { id: 'G22-03', group: 'G22', groupTitle: 'AI video generation', name: 'Sora excluded', state: 'BLOCKED', phase: '—', pages: ['ai'] },
  { id: 'G22-04', group: 'G22', groupTitle: 'AI video generation', name: 'Anti fake-local', state: 'RESEARCHED', phase: '2', pages: ['ai'] },
  { id: 'G23-01', group: 'G23', groupTitle: 'AI image production', name: 'Concept art, storyboard art, posters, thumbnails, key art, characters, locations, backgrounds, product, mattes, textures, promo', state: 'SHELL', phase: '2', pages: ['ai', 'photo'] },
  { id: 'G23-02', group: 'G23', groupTitle: 'AI image production', name: 'Image edit', state: 'SHELL', phase: '2', pages: ['ai', 'photo'] },
  { id: 'G24-01', group: 'G24', groupTitle: 'Character system', name: 'CharacterRecord', state: 'SHELL', phase: '4', pages: ['ai'] },
  { id: 'G24-02', group: 'G24', groupTitle: 'Character system', name: 'CharacterBible: appearance, age, wardrobe, hair, voice, personality, behavior, relationships, approved refs, expressions, gestures, history, canon, usage rights, looks over time', state: 'RESEARCHED', phase: '4', pages: ['ai'] },
  { id: 'G24-03', group: 'G24', groupTitle: 'Character system', name: 'Characters UI', state: 'SHELL', phase: '4', pages: ['ai'] },
  { id: 'G25-01', group: 'G25', groupTitle: 'World bible', name: 'Locations, architecture, geography, history, factions, technology, culture, props, rules, visual language, lighting, weather, time periods', state: 'NOT STARTED', phase: '4-6', pages: ['ai'] },
  { id: 'G26-01', group: 'G26', groupTitle: 'Continuity memory', name: 'Track wardrobe, hair, makeup, injuries, props, location state, object placement, time, weather, knowledge, relationships, dialogue facts, prior actions', state: 'RESEARCHED', phase: '6', pages: ['ai', 'review'] },
  { id: 'G26-02', group: 'G26', groupTitle: 'Continuity memory', name: 'AI continuity warnings', state: 'RESEARCHED', phase: '7', pages: ['ai', 'review'] },
  { id: 'G27-01', group: 'G27', groupTitle: 'Video Intelligence', name: 'Watch / understand / search / remember / learn boundary', state: 'SHIPPED', phase: '3', pages: ['ai', 'media'] },
  { id: 'G27-02', group: 'G27', groupTitle: 'Video Intelligence', name: 'Analyze scenes, shots, people, objects, actions, speech, camera, composition, transitions, effects, color, music, sound, pacing', state: 'SHELL', phase: '3', pages: ['ai', 'media'] },
  { id: 'G27-03', group: 'G27', groupTitle: 'Video Intelligence', name: 'Never scrape the open web automatically', state: 'SHIPPED', phase: '3', pages: ['ai', 'media'] },
  { id: 'G28-01', group: 'G28', groupTitle: 'Video learning / production knowledge', name: 'TechniqueRecord', state: 'SHELL', phase: '8', pages: ['ai'] },
  { id: 'G28-02', group: 'G28', groupTitle: 'Video learning / production knowledge', name: 'VideoAgent-style memory / VideoSeek evidence / VideoAgentTrek procedure extraction', state: 'RESEARCHED', phase: '8', pages: ['ai'] },
  { id: 'G28-03', group: 'G28', groupTitle: 'Video learning / production knowledge', name: 'Human verification → Production Knowledge → Director applies via EditOps', state: 'RESEARCHED', phase: '8', pages: ['ai'] },
  { id: 'G29-01', group: 'G29', groupTitle: 'Media search', name: 'Natural language: close-ups, actions, actor, object, lines, best reaction', state: 'SHELL', phase: '3', pages: ['media', 'ai'] },
  { id: 'G29-02', group: 'G29', groupTitle: 'Media search', name: 'CLIP / clusters', state: 'RESEARCHED', phase: '3', pages: ['media', 'ai'] },
  { id: 'G30-01', group: 'G30', groupTitle: 'AI Director', name: 'Six control modes', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G30-02', group: 'G30', groupTitle: 'AI Director', name: 'Utterance → typed EditCommands', state: 'PARTIAL', phase: '1-7', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G30-03', group: 'G30', groupTitle: 'AI Director', name: 'Rough cut / best takes / scene tense / trailer / missing establishing / fix continuity / add rain / replace background', state: 'SHELL', phase: '7', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G30-04', group: 'G30', groupTitle: 'AI Director', name: 'Tips ≠ Ops', state: 'SHIPPED', phase: '1', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G30-05', group: 'G30', groupTitle: 'AI Director', name: 'LLM-backed director', state: 'NOT STARTED', phase: '7', pages: ['media', 'cut', 'edit', 'vfx', 'color', 'audio', 'photo', 'ai', 'review', 'deliver'] },
  { id: 'G31-01', group: 'G31', groupTitle: 'Audio editing', name: 'Waveform display', state: 'SHIPPED', phase: '1', pages: ['audio', 'edit', 'color'] },
  { id: 'G31-02', group: 'G31', groupTitle: 'Audio editing', name: 'Multitrack + volume + fades + duck', state: 'SHIPPED', phase: '1', pages: ['audio', 'edit'] },
  { id: 'G31-03', group: 'G31', groupTitle: 'Audio editing', name: 'Pan', state: 'SHIPPED', phase: '1', pages: ['audio', 'edit'] },
  { id: 'G31-04', group: 'G31', groupTitle: 'Audio editing', name: 'EQ / compressor / limiter / gate / de-esser / reverb / delay', state: 'PARTIAL', phase: '5-9', pages: ['audio', 'edit'] },
  { id: 'G31-05', group: 'G31', groupTitle: 'Audio editing', name: 'Loudness / normalization / automation / buses / stems', state: 'PARTIAL', phase: '5-9', pages: ['audio', 'edit'] },
  { id: 'G32-01', group: 'G32', groupTitle: 'AI audio', name: 'Denoise, dereverb, isolate, enhance, silence/filler removal, stems, generate SFX/ambience/Foley/music, translation, dubbing', state: 'SHELL', phase: '2', pages: ['audio', 'ai', 'media'] },
  { id: 'G33-01', group: 'G33', groupTitle: 'Voice / ADR', name: 'Insert VO clip', state: 'SHIPPED', phase: '1', pages: ['audio', 'ai'] },
  { id: 'G33-02', group: 'G33', groupTitle: 'Voice / ADR', name: 'Voice Studio: record, generated voice, character voice, ADR, timing, sync', state: 'SHELL', phase: '2-9', pages: ['audio', 'ai'] },
  { id: 'G33-03', group: 'G33', groupTitle: 'Voice / ADR', name: 'Multilingual dubbing / future lip-sync', state: 'RESEARCHED', phase: '9', pages: ['audio', 'ai', 'media'] },
  { id: 'G34-01', group: 'G34', groupTitle: 'Music', name: 'Import + place + duck', state: 'SHIPPED', phase: '1', pages: ['audio', 'ai'] },
  { id: 'G34-02', group: 'G34', groupTitle: 'Music', name: 'Generation', state: 'SHELL', phase: '2', pages: ['audio', 'ai'] },
  { id: 'G34-03', group: 'G34', groupTitle: 'Music', name: 'Score-to-scene / BPM / beat / downbeat / phrase / markers / beat-sync cut', state: 'RESEARCHED', phase: '5', pages: ['audio', 'ai'] },
  { id: 'G35-01', group: 'G35', groupTitle: 'Sound effects / Foley', name: 'SFX library + generated SFX + Foley + ambience + room tone + beds + impacts + transition whooshes + sync', state: 'SHELL', phase: '2-5', pages: ['audio', 'ai'] },
  { id: 'G36-01', group: 'G36', groupTitle: 'Captions / subtitles', name: 'Caption tracks + cues + speaker + theme styling + ASS burn-in', state: 'SHIPPED', phase: '1', pages: ['edit', 'deliver'] },
  { id: 'G36-02', group: 'G36', groupTitle: 'Captions / subtitles', name: 'Transcription / word-level timing / speaker labels', state: 'SHELL', phase: '2', pages: ['edit', 'deliver'] },
  { id: 'G36-03', group: 'G36', groupTitle: 'Captions / subtitles', name: 'Animated / karaoke captions', state: 'PARTIAL', phase: '2', pages: ['edit', 'deliver'] },
  { id: 'G36-04', group: 'G36', groupTitle: 'Captions / subtitles', name: 'Translation + subtitle export + accessibility', state: 'SHELL', phase: '2', pages: ['edit', 'deliver'] },
  { id: 'G37-01', group: 'G37', groupTitle: 'Titles / motion graphics', name: 'Titles, logos, static overlays', state: 'SHIPPED', phase: '1', pages: ['edit', 'vfx'] },
  { id: 'G37-02', group: 'G37', groupTitle: 'Titles / motion graphics', name: 'Lower thirds / CTA / animated text / templates / keyframeable graphics', state: 'PARTIAL', phase: '5', pages: ['edit', 'vfx'] },
  { id: 'G37-03', group: 'G37', groupTitle: 'Titles / motion graphics', name: 'Node/graph motion design', state: 'RESEARCHED', phase: '9', pages: ['edit', 'vfx'] },
  { id: 'G38-01', group: 'G38', groupTitle: 'Opening / end credits', name: 'Cast, crew, roles, legal, music credits, logos, crawl, cards, end titles', state: 'NOT STARTED', phase: '6-9', pages: ['edit', 'deliver', 'vfx'] },
  { id: 'G39-01', group: 'G39', groupTitle: 'Quality control', name: 'ffprobe success gate on render', state: 'SHIPPED', phase: '1', pages: ['review', 'deliver'] },
  { id: 'G39-02', group: 'G39', groupTitle: 'Quality control', name: 'Auto QC: blur, focus, shake, clipped highs/crushed blacks, bad audio, silence, clipping, dup/corrupt frames, missing media, aspect, caption overflow, logo safe, black/flash frames, continuity', state: 'PARTIAL', phase: '6', pages: ['review', 'edit'] },
  { id: 'G39-03', group: 'G39', groupTitle: 'Quality control', name: 'Safe-area / guides', state: 'SHIPPED', phase: '1', pages: ['review'] },
  { id: 'G40-01', group: 'G40', groupTitle: 'Render / mastering', name: 'FFmpeg compose + NVENC or libx264 + queue + output Asset', state: 'SHIPPED', phase: '1', pages: ['deliver'] },
  { id: 'G40-02', group: 'G40', groupTitle: 'Render / mastering', name: 'Render fidelity vs timeline', state: 'PARTIAL', phase: '1/5', pages: ['deliver'] },
  { id: 'G40-03', group: 'G40', groupTitle: 'Render / mastering', name: 'Presets: H.264, H.265, AV1, ProRes (if lawful), DNx, image sequence, alpha, audio masters, subtitles, platform variants', state: 'PARTIAL', phase: '9', pages: ['deliver', 'edit'] },
  { id: 'G40-04', group: 'G40', groupTitle: 'Render / mastering', name: 'Background render / cache / proxies / optimized media', state: 'PARTIAL', phase: '9', pages: ['deliver'] },
  { id: 'G40-05', group: 'G40', groupTitle: 'Render / mastering', name: 'Theatrical / archive master research', state: 'RESEARCHED', phase: '9', pages: ['deliver'] },
  { id: 'G41-01', group: 'G41', groupTitle: 'Project interchange', name: '`.hvsproj` remains SoT', state: 'SHIPPED', phase: '1', pages: ['deliver'] },
  { id: 'G41-02', group: 'G41', groupTitle: 'Project interchange', name: 'OTIO', state: 'RESEARCHED', phase: '9', pages: ['deliver'] },
  { id: 'G41-03', group: 'G41', groupTitle: 'Project interchange', name: 'EDL / FCPXML / AAF research / subtitle formats / media manifests', state: 'RESEARCHED', phase: '9', pages: ['deliver', 'edit'] },
  { id: 'G42-01', group: 'G42', groupTitle: 'Film / show structure', name: 'productionMode enum (COMMERCIAL…FILM_SHOW)', state: 'SHIPPED', phase: '1', pages: ['edit', 'review'] },
  { id: 'G42-02', group: 'G42', groupTitle: 'Film / show structure', name: 'Production → Season → Episode → Act → Sequence → Scene → Shot → Take → Asset', state: 'NOT STARTED', phase: '6', pages: ['edit', 'review'] },
  { id: 'G42-03', group: 'G42', groupTitle: 'Film / show structure', name: 'Film → Act → Sequence → Scene → Shot → Take', state: 'NOT STARTED', phase: '6', pages: ['edit', 'review'] },
  { id: 'G43-01', group: 'G43', groupTitle: 'Version / revision system', name: 'Edit versions + snapshots + derived 9:16 version', state: 'SHIPPED', phase: '1', pages: ['review', 'edit'] },
  { id: 'G43-02', group: 'G43', groupTitle: 'Version / revision system', name: 'Script / storyboard / scene / VFX / color / audio / render versions', state: 'NOT STARTED', phase: '6', pages: ['review', 'edit', 'deliver'] },
  { id: 'G43-03', group: 'G43', groupTitle: 'Version / revision system', name: 'Never silent overwrite of approved work', state: 'PARTIAL', phase: '6', pages: ['review', 'edit'] },
  { id: 'G44-01', group: 'G44', groupTitle: 'Plugin / extension system', name: 'Extension Host for effects/generators/transitions/analyzers/exporters/codecs', state: 'RESEARCHED', phase: '9', pages: ['edit', 'deliver'] },
  { id: 'G44-02', group: 'G44', groupTitle: 'Plugin / extension system', name: 'OpenFX as one integration layer, not SoT', state: 'RESEARCHED', phase: '9', pages: ['edit'] },
  { id: 'G45-01', group: 'G45', groupTitle: 'Production management', name: 'Tasks, scene/shot/production status, notes, assignments, dependencies, approvals', state: 'NOT STARTED', phase: '6', pages: ['review', 'ai'] },
  { id: 'G45-02', group: 'G45', groupTitle: 'Production management', name: 'Call sheets / schedules / shot schedules / budget (later)', state: 'RESEARCHED', phase: '6+', pages: ['review', 'ai'] },
  { id: 'G46-01', group: 'G46', groupTitle: 'Rights / provenance', name: 'AssetProvenance (provider, model, prompt, refs, license/commercialUse, parent, params)', state: 'PARTIAL', phase: '2', pages: ['media', 'review', 'deliver'] },
  { id: 'G46-02', group: 'G46', groupTitle: 'Rights / provenance', name: 'Talent release / location release / music rights / usage on timeline', state: 'RESEARCHED', phase: '2-6', pages: ['media', 'review', 'deliver'] },
  { id: 'G46-03', group: 'G46', groupTitle: 'Rights / provenance', name: 'C2PA evaluate', state: 'RESEARCHED', phase: '5', pages: ['media', 'review', 'deliver'] },
  { id: 'G46-04', group: 'G46', groupTitle: 'Rights / provenance', name: 'Beauty OFF / consent / disclose AI plates', state: 'SHIPPED', phase: '1', pages: ['media', 'review', 'deliver'] },
  { id: 'G47-01', group: 'G47', groupTitle: 'Human / AI collaboration', name: 'Visible, typed, previewable, undoable, versioned, attributable AI ops', state: 'SHIPPED', phase: '1', pages: ['ai', 'edit'] },
  { id: 'G47-02', group: 'G47', groupTitle: 'Human / AI collaboration', name: 'AI can draft; cannot silently publish final', state: 'SHIPPED', phase: '1', pages: ['ai', 'edit'] },
  { id: 'G47-03', group: 'G47', groupTitle: 'Human / AI collaboration', name: 'Observed vs Scenario layers', state: 'RESEARCHED', phase: '7', pages: ['ai', 'edit'] },
  { id: 'G48-01', group: 'G48', groupTitle: 'Create from prompt (on top of real tools)', name: '“Tell HVS what I want” invoking research→script→characters→world→boards→shots→generators→editor→camera→audio→music→color→VFX→render', state: 'RESEARCHED', phase: '10', pages: ['ai', 'deliver'] },
  { id: 'G48-02', group: 'G48', groupTitle: 'Create from prompt (on top of real tools)', name: 'Forbidden: fake prompt-to-film bypass', state: 'SHIPPED', phase: '10', pages: ['ai'] },
  { id: 'GX-01', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'STARRDOM luxury-ad proving path', state: 'PARTIAL', phase: '2', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-02', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'Client Work contracts / commercial tiers', state: 'RESEARCHED', phase: '6', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-03', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'Nebula Linux CUDA/NVENC workers; author UI anywhere', state: 'PARTIAL', phase: '9', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-04', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'War Room typed handoffs (Council, Terra, Foundry, WRIM, Research, Memory)', state: 'SHELL', phase: '7', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-05', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'PreviewTicket cost ladder', state: 'RESEARCHED', phase: '5', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-06', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'Compose spike: custom+FFmpeg vs MLT vs GES (default custom+FFmpeg)', state: 'RESEARCHED', phase: '5', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-07', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'WRIM as Router backend only if production WRIM exists', state: 'BLOCKED', phase: '8', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-08', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'Ultralytics AGPL in tracker', state: 'BLOCKED', phase: '—', pages: ['edit', 'ai', 'deliver'] },
  { id: 'GX-09', group: 'GX', groupTitle: 'Research extras (not in the 48, still in scope)', name: 'Realtime 4K tracking', state: 'BLOCKED', phase: '—', pages: ['edit', 'ai', 'deliver'] },
]

export function matrixRowsForPage(page: HvsProductionPageId): HvsMatrixRow[] {
  return HVS_MATRIX_ROWS.filter(row => row.pages.includes(page))
}

export function matrixPageRollup(page: HvsProductionPageId): Record<HvsMatrixState, number> {
  const counts: Record<HvsMatrixState, number> = { SHIPPED: 0, PARTIAL: 0, SHELL: 0, RESEARCHED: 0, 'NOT STARTED': 0, BLOCKED: 0 }
  for (const row of matrixRowsForPage(page)) counts[row.state] += 1
  return counts
}

