import { CouncilSkill } from './CouncilSkill'
import type { CouncilEntityId } from '../entities/types'
import type {
  CouncilSkillActivationStatus,
  CouncilSkillCategory,
  CouncilSkillDefinition,
  CouncilSkillId,
  CouncilSkillRiskLevel,
} from './types'

const SKILLS_TIMESTAMP = '2026-07-07T00:00:00.000Z'

export const COUNCIL_SKILL_DEFINITIONS: CouncilSkillDefinition[] = [
  {
    id: 'system_architecture',
    displayName: 'System Architecture',
    description: 'Designs durable technical structure, boundaries, and system relationships.',
    category: 'reasoning',
    ownerEntityIds: ['architect'],
    supportingEntityIds: ['engineer', 'skeptic'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'engineering_review',
    displayName: 'Engineering Review',
    description: 'Reviews technical choices for maintainability, correctness, and operational fit.',
    category: 'review',
    ownerEntityIds: ['architect'],
    supportingEntityIds: ['engineer', 'skeptic'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'feasibility_analysis',
    displayName: 'Feasibility Analysis',
    description: 'Evaluates whether a plan can work within technical, operational, and resource limits.',
    category: 'reasoning',
    ownerEntityIds: ['architect'],
    supportingEntityIds: ['engineer', 'skeptic'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'long_reasoning_decomposition',
    displayName: 'Long-Reasoning Decomposition',
    description: 'Breaks complex problems into durable reasoning chains and decision points.',
    category: 'reasoning',
    ownerEntityIds: ['architect'],
    supportingEntityIds: ['strategist', 'engineer'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'business_strategy',
    displayName: 'Business Strategy',
    description: 'Frames business direction, tradeoffs, positioning, and execution options.',
    category: 'planning',
    ownerEntityIds: ['strategist'],
    supportingEntityIds: ['scout', 'skeptic'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'planning',
    displayName: 'Planning',
    description: 'Turns goals into staged plans, milestones, and next actions.',
    category: 'planning',
    ownerEntityIds: ['strategist'],
    supportingEntityIds: ['engineer', 'architect'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'synthesis',
    displayName: 'Synthesis',
    description: 'Condenses multiple inputs into clear decisions, summaries, and connective tissue.',
    category: 'communication',
    ownerEntityIds: ['strategist'],
    supportingEntityIds: ['librarian', 'architect'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'writing',
    displayName: 'Writing',
    description: 'Drafts clear language, messages, briefs, and operator-facing communication.',
    category: 'communication',
    ownerEntityIds: ['strategist'],
    supportingEntityIds: ['librarian'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'command_translation',
    displayName: 'Command Translation',
    description: 'Converts commander intent into structured work requests and council-readable direction.',
    category: 'coordination',
    ownerEntityIds: ['strategist'],
    supportingEntityIds: ['architect', 'engineer'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'knowledge_organization',
    displayName: 'Knowledge Organization',
    description: 'Organizes known information into reusable structure and retrieval paths.',
    category: 'memory',
    ownerEntityIds: ['librarian'],
    supportingEntityIds: ['strategist'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'research_review',
    displayName: 'Research Review',
    description: 'Reviews gathered research for credibility, relevance, and gaps.',
    category: 'research',
    ownerEntityIds: ['librarian'],
    supportingEntityIds: ['scout', 'skeptic'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'pattern_recognition',
    displayName: 'Pattern Recognition',
    description: 'Detects recurring signals, structures, and meaningful similarities across context.',
    category: 'reasoning',
    ownerEntityIds: ['librarian'],
    supportingEntityIds: ['scout', 'strategist'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'cross_reference',
    displayName: 'Cross Reference',
    description: 'Links claims, memories, files, research, and decisions across War Room context.',
    category: 'memory',
    ownerEntityIds: ['librarian'],
    supportingEntityIds: ['architect', 'strategist'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'source_comparison',
    displayName: 'Source Comparison',
    description: 'Compares sources for agreement, contradiction, freshness, and reliability.',
    category: 'research',
    ownerEntityIds: ['librarian'],
    supportingEntityIds: ['scout', 'skeptic'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'current_signal_detection',
    displayName: 'Current Signal Detection',
    description: 'Identifies relevant current signals, movement, and external changes.',
    category: 'research',
    ownerEntityIds: ['scout'],
    supportingEntityIds: ['librarian', 'skeptic'],
    requiredTools: ['internet'],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'requires_tooling',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'internet_awareness',
    displayName: 'Internet Awareness',
    description: 'Uses approved internet tools to understand live external context.',
    category: 'research',
    ownerEntityIds: ['scout'],
    supportingEntityIds: ['librarian', 'skeptic'],
    requiredTools: ['internet'],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'requires_tooling',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'market_intelligence',
    displayName: 'Market Intelligence',
    description: 'Frames market movement, opportunity timing, and competitive signals.',
    category: 'research',
    ownerEntityIds: ['scout'],
    supportingEntityIds: ['strategist', 'librarian', 'skeptic'],
    requiredTools: ['internet'],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'requires_tooling',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'opportunity_sensing',
    displayName: 'Opportunity Sensing',
    description: 'Detects possible opportunities while preserving source, risk, and approval boundaries.',
    category: 'research',
    ownerEntityIds: ['scout'],
    supportingEntityIds: ['strategist', 'skeptic'],
    requiredTools: ['internet'],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'requires_tooling',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'realtime_context_framing',
    displayName: 'Realtime Context Framing',
    description: 'Explains live context without claiming unsupported access or unverified certainty.',
    category: 'research',
    ownerEntityIds: ['scout'],
    supportingEntityIds: ['librarian', 'strategist'],
    requiredTools: ['internet'],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'requires_tooling',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'implementation_planning',
    displayName: 'Implementation Planning',
    description: 'Turns approved work into implementation steps without modifying files directly.',
    category: 'implementation',
    ownerEntityIds: ['engineer'],
    supportingEntityIds: ['architect', 'skeptic'],
    requiredTools: [],
    riskLevel: 'high',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'task_sequencing',
    displayName: 'Task Sequencing',
    description: 'Orders work into dependency-aware execution sequences.',
    category: 'planning',
    ownerEntityIds: ['engineer'],
    supportingEntityIds: ['strategist', 'architect'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'technical_execution_planning',
    displayName: 'Technical Execution Planning',
    description: 'Plans technical execution while keeping edits, commands, and commits approval-gated.',
    category: 'implementation',
    ownerEntityIds: ['engineer'],
    supportingEntityIds: ['architect', 'skeptic'],
    requiredTools: [],
    riskLevel: 'high',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'operations_mapping',
    displayName: 'Operations Mapping',
    description: 'Maps operational workflows, handoffs, and control points.',
    category: 'coordination',
    ownerEntityIds: ['engineer'],
    supportingEntityIds: ['strategist', 'architect'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: true,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'dependency_mapping',
    displayName: 'Dependency Mapping',
    description: 'Identifies dependencies, ordering constraints, and blockers.',
    category: 'planning',
    ownerEntityIds: ['engineer'],
    supportingEntityIds: ['architect', 'strategist'],
    requiredTools: [],
    riskLevel: 'low',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'assumption_challenge',
    displayName: 'Assumption Challenge',
    description: 'Challenges assumptions before they become operational decisions.',
    category: 'risk',
    ownerEntityIds: ['skeptic'],
    supportingEntityIds: ['architect', 'strategist'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'risk_analysis',
    displayName: 'Risk Analysis',
    description: 'Identifies risk, severity, likelihood, and mitigation paths.',
    category: 'risk',
    ownerEntityIds: ['skeptic'],
    supportingEntityIds: ['architect', 'librarian'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'contradiction_checking',
    displayName: 'Contradiction Checking',
    description: 'Finds conflicts between claims, plans, memories, and evidence.',
    category: 'risk',
    ownerEntityIds: ['skeptic'],
    supportingEntityIds: ['librarian', 'architect'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'scam_detection',
    displayName: 'Scam Detection',
    description: 'Flags suspicious claims, payout patterns, identity risks, and credibility gaps.',
    category: 'risk',
    ownerEntityIds: ['skeptic'],
    supportingEntityIds: ['scout', 'librarian'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
  {
    id: 'stress_testing',
    displayName: 'Stress Testing',
    description: 'Tests plans against failure modes, pressure, abuse cases, and edge conditions.',
    category: 'risk',
    ownerEntityIds: ['skeptic'],
    supportingEntityIds: ['architect', 'engineer'],
    requiredTools: [],
    riskLevel: 'medium',
    approvalRequired: false,
    memoryEligible: true,
    learningEligible: true,
    activationStatus: 'foundation',
    createdAt: SKILLS_TIMESTAMP,
    updatedAt: SKILLS_TIMESTAMP,
  },
]

export class CouncilSkillRegistry {
  private readonly skills: Map<CouncilSkillId, CouncilSkill>

  constructor(definitions: CouncilSkillDefinition[] = COUNCIL_SKILL_DEFINITIONS) {
    this.skills = new Map(definitions.map(definition => [definition.id, new CouncilSkill(definition)]))
  }

  getSkill(id: CouncilSkillId): CouncilSkill | null {
    return this.skills.get(id) ?? null
  }

  getAll(): CouncilSkill[] {
    return Array.from(this.skills.values())
  }

  findByCategory(category: CouncilSkillCategory): CouncilSkill[] {
    return this.getAll().filter(skill => skill.getCategory() === category)
  }

  findByEntity(entityId: CouncilEntityId): CouncilSkill[] {
    return this.getAll().filter(skill => skill.isOwnedBy(entityId) || skill.isSupportedBy(entityId))
  }

  findByTool(toolId: string): CouncilSkill[] {
    return this.getAll().filter(skill => skill.getRequiredTools().includes(toolId))
  }

  findByRiskLevel(riskLevel: CouncilSkillRiskLevel): CouncilSkill[] {
    return this.getAll().filter(skill => skill.getRiskLevel() === riskLevel)
  }

  findByActivationStatus(status: CouncilSkillActivationStatus): CouncilSkill[] {
    return this.getAll().filter(skill => skill.getActivationStatus() === status)
  }

  entitySupportsSkill(entityId: CouncilEntityId, skillId: CouncilSkillId): boolean {
    const skill = this.getSkill(skillId)
    return skill ? skill.isOwnedBy(entityId) || skill.isSupportedBy(entityId) : false
  }

  getPrimaryOwner(skillId: CouncilSkillId): CouncilEntityId | null {
    const skill = this.getSkill(skillId)
    return skill?.getOwnerEntityIds()[0] ?? null
  }

  getSupportingEntities(skillId: CouncilSkillId): CouncilEntityId[] {
    return this.getSkill(skillId)?.getSupportingEntityIds() ?? []
  }
}

export const councilSkillRegistry = new CouncilSkillRegistry()
