-- Phase 49-F1 proposal only. Do not apply without Commander authorization.
create table if not exists public.war_room_income_loot_opportunities (
 id text primary key, owner_user_id uuid not null references auth.users(id) on delete cascade, provider text not null, title text not null, description text, category text not null, estimated_reward jsonb, estimated_time_minutes integer, expires_at timestamptz, eligibility text[] not null default '{}'::text[], location_requirement text, evidence_requirement text[] not null default '{}'::text[], external_url text, status text not null default 'DISCOVERED', evidence_label text not null, confidence numeric not null, provenance jsonb not null default '[]'::jsonb, commander_approval_required boolean not null default true, discovered_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint income_loot_category_check check (category in ('SURVEY','STORE_SCAN','RECEIPT_REWARD','CASHBACK','PRICE_MATCH','DEAL','POINTS_REWARD','OTHER_REWARD')), constraint income_loot_status_check check (status in ('DISCOVERED','ELIGIBLE','STARTED','SUBMITTED','PENDING','VERIFIED','REWARDED','CASHOUT_READY','CASHED_OUT','REJECTED','EXPIRED')), constraint income_loot_evidence_label_check check (evidence_label in ('LIVE_SIGNAL_BACKED','HISTORICAL_PATTERN_BASED','PROVIDER_CONFIRMED')), constraint income_loot_confidence_check check (confidence between 0 and 100), constraint income_loot_approval_check check (commander_approval_required is true), constraint income_loot_estimated_value_check check (estimated_reward is null or (estimated_reward->>'basis') = 'ESTIMATED')
);
create table if not exists public.war_room_income_loot_evidence (id text primary key, owner_user_id uuid not null references auth.users(id) on delete cascade, linked_record_type text not null default 'opportunity', linked_opportunity_id text not null references public.war_room_income_loot_opportunities(id) on delete cascade, kind text not null, file_ref text null, original_filename text null, mime_type text null, byte_size bigint null, content_sha256 text null, captured_at timestamptz not null, merchant text null, purchase_date date null, amount numeric null, currency text null, truth_state text not null default 'CAPTURED', redacted boolean not null default false, redaction_notes text null, redacted_fields text[] not null default '{}'::text[], visibility text not null default 'commander_only', notes text null, constraint income_loot_evidence_link_check check (linked_record_type = 'opportunity'), constraint income_loot_evidence_kind_check check (kind in ('receipt','screenshot','provider_confirmation','transaction_reference','reward_balance','payout_confirmation')), constraint income_loot_evidence_truth_check check (truth_state in ('CAPTURED','REVIEWED','VERIFIED','REJECTED')), constraint income_loot_evidence_visibility_check check (visibility in ('commander_only','workforce')), constraint income_loot_evidence_byte_size_check check (byte_size is null or byte_size >= 0), constraint income_loot_evidence_amount_check check (amount is null or amount >= 0));
create index if not exists war_room_income_loot_evidence_owner_opportunity_idx on public.war_room_income_loot_evidence(owner_user_id, linked_opportunity_id, captured_at desc);
create index if not exists war_room_income_loot_opportunities_owner_status_idx on public.war_room_income_loot_opportunities(owner_user_id, status, discovered_at desc);
alter table public.war_room_income_loot_opportunities enable row level security; alter table public.war_room_income_loot_evidence enable row level security;
grant select, insert, update on public.war_room_income_loot_opportunities to authenticated, service_role;
grant select, insert, update on public.war_room_income_loot_evidence to authenticated, service_role;
create policy income_loot_opportunities_owner_all on public.war_room_income_loot_opportunities for all to authenticated using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy income_loot_evidence_owner_all on public.war_room_income_loot_evidence for all to authenticated using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy income_loot_opportunities_service_role_all on public.war_room_income_loot_opportunities for all to service_role using (true) with check (commander_approval_required is true);
create policy income_loot_evidence_service_role_all on public.war_room_income_loot_evidence for all to service_role using (true) with check (true);

