import type { ModelEntry } from './types'

/** The declared first pool (Commander decision). Statuses are policy, not performance claims; routing still requires benchmark evidence. */
export const FIRST_POOL: ModelEntry[] = [
  { id: 'devstral-abliterated-24b', ref: 'huihui_ai/devstral-abliterated:24b', family: 'devstral', generation: 'Devstral Small 2505 (older generation)', roles: ['complete_feature', 'multi_file_implementation', 'debugging'], status: 'ACTIVE', license: { statement: 'open-weight derivative of Mistral Devstral Small (Apache-2.0 base); confirm on the model card', permissive: 'UNKNOWN' }, lineage: { parent: 'mistralai/Devstral-Small-2505', transformation: 'abliteration by third party (huihui_ai); NOT re-ablated by War Room', note: 'primary challenger; benchmark before preferring' }, routing: { eligible: true, reason: 'Commander-authorized active candidate' } },
  { id: 'devstral-small-2-abliterated-24b', ref: 'AliBilge/Huihui-Devstral-Small-2-24B-Instruct-2512-abliterated:q4_k_m', family: 'devstral-small-2', generation: 'Devstral Small 2 24B Instruct 2512 (newer generation)', roles: ['complete_feature', 'multi_file_implementation', 'debugging'], status: 'ACTIVE', license: { statement: 'community abliterated derivative of Devstral Small 2 24B Instruct 2512; base license must be confirmed on the model card', permissive: 'UNKNOWN' }, lineage: { parent: 'mistralai/Devstral-Small-2-24B-Instruct-2512', transformation: 'abliteration by third parties (huihui-ai, re-packaged by AliBilge); NOT re-ablated by War Room', note: 'distinct from the 2505 Devstral; benchmarked separately, never merged into one family score' }, routing: { eligible: true, reason: 'Commander-authorized active candidate' } },
  { id: 'qwen3-abliterated-14b', ref: 'huihui_ai/qwen3-abliterated:14b', family: 'qwen3', generation: 'Qwen3 14B', roles: ['review', 'light_implementation', 'structured_output'], status: 'ACTIVE', license: { statement: 'open-weight derivative of Qwen3 (Apache-2.0 base); confirm on the model card', permissive: 'UNKNOWN' }, lineage: { parent: 'Qwen/Qwen3-14B', transformation: 'abliteration by third party (huihui_ai)', note: 'secondary candidate' }, routing: { eligible: true, reason: 'Commander-authorized active candidate' } },
  { id: 'qwen2.5-coder-14b', ref: 'qwen2.5-coder:14b', family: 'qwen2.5-coder', generation: 'Qwen2.5-Coder 14B', roles: ['historical baseline'], status: 'BASELINE', license: { statement: 'Apache-2.0 (Qwen2.5-Coder 14B)', permissive: 'YES' }, lineage: { note: 'failed the Phase 10 complete-feature fixture (attempts 1-7); kept for baseline comparison only' }, routing: { eligible: false, reason: 'baseline only; Commander directive: not an active preferred worker' } },
  { id: 'devstral-2-abliterated-123b', ref: 'huihui_ai/devstral-2-abliterated:123b', family: 'devstral-2', generation: 'Devstral 2 123B (Instruct 2512 family)', roles: ['heavy escalation (future)'], status: 'FUTURE_HEAVY', license: { statement: 'unverified; check model card before any download', permissive: 'UNKNOWN' }, lineage: { transformation: 'abliteration by third party (huihui_ai)', note: 'NOT downloaded. ~70 GB quantized artifact estimated vs ~46 GiB RAM+VRAM here: REQUIRES_OFFLOAD (estimated, unmeasured). Revisit after the 24B benchmark and load management.' }, routing: { eligible: false, reason: 'not installed; exceeds practical residency; classified from estimate only' } },
]
