"""WRIM-DEV-S3A-COR-000001. DEVELOPMENT_ONLY. Forbidden for training.

Authored synthetic stems in training domains. Not sliced from WR-CORPUS-0/1.
Not copied from CAP-EVAL-0 or any frozen WRIM-EVAL suite.
Allowed for checkpoint selection during WRIM1-RUN-000004. Never a final eval suite.
"""
from __future__ import annotations

from typing import Any

SUITE_ID = "WRIM-DEV-S3A-COR-000001"
SUITE_VERSION = "1.0.0"
CREATED_AT = "2026-09-13T21:40:00+00:00"
AUTHORSHIP = (
    "Authored synthetic DEVELOPMENT_ONLY stems in training domains "
    "(long-form prose, topic persistence, repetition resistance, JSON, lists/CSV, "
    "code termination, instruction, factual continuity). "
    "Not sliced from WR-CORPUS-0 or WR-CORPUS-1. Not CAP-EVAL-0. Not DIAGNOSTIC-0. "
    "Not WRIM-EVAL-S3-000001. Not WRIM-EVAL-S3A-RET-000001. "
    "Not WRIM-EVAL-S3A-STRUCT-000001. Not WRIM-EVAL-S3A-ADJ-000001. "
    "Forbidden for training. Allowed for checkpoint selection only."
)

CATEGORIES = [
    "DEV_LONG_PROSE",
    "DEV_SEMANTIC",
    "DEV_REPETITION",
    "DEV_JSON",
    "DEV_LIST_KV",
    "DEV_CODE",
    "DEV_INSTRUCTION",
    "DEV_FACTUAL",
]


def _item(
    item_id: str,
    category: str,
    prompt: str,
    *,
    max_new: int,
    scores: list[str],
    payload: dict[str, Any] | None,
    notes: str,
    lengths: list[int],
) -> dict[str, Any]:
    return {
        "suite_id": SUITE_ID,
        "suite_version": SUITE_VERSION,
        "item_id": item_id,
        "category": category,
        "prompt_text": prompt,
        "reference_type": "CONSTRAINT" if payload else "NONE",
        "reference_payload": payload,
        "generation_mode": "greedy_argmax",
        "max_new_tokens": max_new,
        "eval_lengths": lengths,
        "scoring_functions": scores,
        "hard_integrity_checks": ["finite_logits"],
        "notes": notes,
        "authorship": AUTHORSHIP,
        "created_at": CREATED_AT,
        "training_use": "FORBIDDEN",
        "evaluation_only": False,
        "development_only": True,
        "checkpoint_selection_allowed": True,
        "final_eval_suite": False,
    }


L32 = [32]
L32_128 = [32, 128]
L32_128_256 = [32, 128, 256]

ITEMS: list[dict[str, Any]] = [
    _item(
        "dev-prose-01",
        "DEV_LONG_PROSE",
        "Pellwick quay-lamps were hooded for the herring run. Joss kept both palms on the wet rail and watched a blue crate bump the piling twice. He told himself he would wait until the crate bumped a third time before",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entropy", "entity_track"],
        payload={"track_entity": "Pellwick"},
        notes="Quay continuation.",
        lengths=L32_128_256,
    ),
    _item(
        "dev-prose-02",
        "DEV_LONG_PROSE",
        "The Sarnholt loft still smelled of cold pitch. Noll hid an unfinished tally under a split shingle and muttered that he would finish the line that began, we still owe",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entity_track"],
        payload={"track_entity": "Sarnholt"},
        notes="Loft beat.",
        lengths=L32_128,
    ),
    _item(
        "dev-prose-03",
        "DEV_LONG_PROSE",
        '"The hatch is yours until first light," said Pell, not looking up. "I did not ask for the hatch," Quill answered, and then added,',
        max_new=128,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="Dialogue turn.",
        lengths=L32_128,
    ),
    _item(
        "dev-prose-04",
        "DEV_LONG_PROSE",
        "By late watch the Quellmere yard had gone pewter. The last barrow left a wet groove that filled from below. When the chain-pin dropped, it only meant",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entity_track"],
        payload={"track_entity": "Quellmere"},
        notes="Yard dusk.",
        lengths=L32_128,
    ),
    _item(
        "dev-prose-05",
        "DEV_LONG_PROSE",
        "On the Ibbotreach sill: a bent awl, a coil of red marline, and a river-stone with a notch. The stone, unlike the marline, did not",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entity_track"],
        payload={"track_entity": "Ibbotreach"},
        notes="Still life.",
        lengths=L32_128,
    ),
    _item(
        "dev-sem-01",
        "DEV_SEMANTIC",
        "Keep the same quay. Joss stayed at Pellwick after the lamps were hooded. The herring boats had gone. He counted slow bumps of the blue crate and decided that if a lantern showed on the south bollard he would",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entity_track"],
        payload={"track_entity": "Pellwick"},
        notes="Topic persistence.",
        lengths=L32_128_256,
    ),
    _item(
        "dev-sem-02",
        "DEV_SEMANTIC",
        "Stay with the Sarnholt loft. Noll sat under the split shingle with the unfinished tally. Pitch ticked as it cooled. Before he slept he told himself he would",
        max_new=128,
        scores=["greedy_32", "entity_track"],
        payload={"track_entity": "Sarnholt"},
        notes="Loft persistence.",
        lengths=L32_128,
    ),
    _item(
        "dev-sem-03",
        "DEV_SEMANTIC",
        "Continue the Quellmere night notice in plain sentences. Wet barrows stand on edge. Eight barrows fill one sled. Clerks must not open a sealed hatch at Lowcinder. The next paragraph explains why sealed hatches stay closed during",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entity_track"],
        payload={"track_entity": "Quellmere"},
        notes="Notice persistence.",
        lengths=L32_128_256,
    ),
    _item(
        "dev-sem-04",
        "DEV_SEMANTIC",
        "Keep Gantspool in view. Heat pooled under the tarps because the flue-cap was jammed. The posted slip went on to describe how a clerk should",
        max_new=128,
        scores=["greedy_32", "entity_track"],
        payload={"track_entity": "Gantspool"},
        notes="Yard persistence.",
        lengths=L32_128,
    ),
    _item(
        "dev-sem-05",
        "DEV_SEMANTIC",
        "Do not change the river. At Ibbotreach the notched stone stayed on the sill while the marline slipped. The next sentences must remain about that sill, because",
        max_new=128,
        scores=["greedy_32", "entity_track"],
        payload={"track_entity": "Ibbotreach"},
        notes="Sill persistence.",
        lengths=L32_128,
    ),
    _item(
        "dev-rep-01",
        "DEV_REPETITION",
        "Describe the Lowcinder close in several different sentences. Mention the Gantspool flue, the quay chain, and the iron pin once each, then invent new duties. After the pin is hung, the clerk still has to",
        max_new=128,
        scores=["greedy_32", "fingerprint", "entropy"],
        payload=None,
        notes="Avoid one-word loop.",
        lengths=L32_128_256,
    ),
    _item(
        "dev-rep-02",
        "DEV_REPETITION",
        "Name distinct quay tools in ordinary sentences without repeating the same tool word over and over. The first tool is a bent awl. The second is red marline. After those, the clerk should mention",
        max_new=128,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="Avoid noun loop.",
        lengths=L32_128,
    ),
    _item(
        "dev-rep-03",
        "DEV_REPETITION",
        "Count upward in words from one to six inside a short notice, then continue in new sentences about Pellwick quay. one two three",
        max_new=128,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="Avoid numeral stall.",
        lengths=L32_128,
    ),
    _item(
        "dev-rep-04",
        "DEV_REPETITION",
        "Advance the scene with new nouns. Do not recycle the last phrase. At Lowcinder the flue-cap still needed",
        max_new=128,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="No copy loop.",
        lengths=L32_128,
    ),
    _item(
        "dev-rep-05",
        "DEV_REPETITION",
        "Give four separate night tasks as full sentences. None of the sentences may be only the word pin. Task one:",
        max_new=128,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="Four tasks.",
        lengths=L32_128,
    ),
    _item(
        "dev-json-01",
        "DEV_JSON",
        "Return a single JSON record. Field names must be quay_tag and crate_mass. Open with a brace: {",
        max_new=32,
        scores=["greedy_32", "json_parse", "json_required_keys"],
        payload={"required_keys": ["quay_tag", "crate_mass"]},
        notes="Two-key object.",
        lengths=L32,
    ),
    _item(
        "dev-json-02",
        "DEV_JSON",
        "Return a JSON array holding three short tool names as strings, then halt. Open with a bracket: [",
        max_new=32,
        scores=["greedy_32", "json_parse", "json_array_len_3"],
        payload={"json_type": "array"},
        notes="Array of 3.",
        lengths=L32,
    ),
    _item(
        "dev-json-03",
        "DEV_JSON",
        "Return JSON whose hatch_ok value is true or false and whose slip value is null. Open: {",
        max_new=32,
        scores=["greedy_32", "json_parse", "json_bool_null"],
        payload={"required_keys": ["hatch_ok", "slip"]},
        notes="Bool and null.",
        lengths=L32,
    ),
    _item(
        "dev-json-04",
        "DEV_JSON",
        "Finish only this JSON record and then stop: {\"quay_tag\": \"P1\", \"crate_mass\":",
        max_new=32,
        scores=["greedy_32", "json_parse_prefix_repair", "json_required_keys"],
        payload={"required_keys": ["quay_tag", "crate_mass"]},
        notes="Prefix repair.",
        lengths=L32,
    ),
    _item(
        "dev-json-05",
        "DEV_JSON",
        "Return one nested JSON record shaped like {\"hatch\":{\"inner_latch\":true}} and then stop.\n",
        max_new=32,
        scores=["greedy_32", "json_parse", "json_nested_outer"],
        payload={"required_keys": ["hatch"], "nested_key": "inner_latch"},
        notes="Nested.",
        lengths=L32,
    ),
    _item(
        "dev-kv-01",
        "DEV_LIST_KV",
        "Use colon lines only. Fill both labels with any short values:\nquay_tag:\ncrate_mass:\n",
        max_new=32,
        scores=["greedy_32", "key_value_lines"],
        payload={"required_keys": ["quay_tag", "crate_mass"]},
        notes="Two KV lines.",
        lengths=L32,
    ),
    _item(
        "dev-kv-02",
        "DEV_LIST_KV",
        "Dash-prefixed quay tools, exactly three lines:\n- ",
        max_new=32,
        scores=["greedy_32", "list_lines"],
        payload={"min_lines": 3},
        notes="Bullet list.",
        lengths=L32,
    ),
    _item(
        "dev-kv-03",
        "DEV_LIST_KV",
        "Print one CSV record with three cells: quay_tag, crate_mass, hatch_ok.\n",
        max_new=32,
        scores=["greedy_32", "csv_row"],
        payload={"min_fields": 3},
        notes="CSV row.",
        lengths=L32,
    ),
    _item(
        "dev-kv-04",
        "DEV_LIST_KV",
        "Complete this label in colon form, then halt.\nlane_id:",
        max_new=32,
        scores=["greedy_32", "key_value_lines"],
        payload={"required_keys": ["lane_id"]},
        notes="Single key.",
        lengths=L32,
    ),
    _item(
        "dev-kv-05",
        "DEV_LIST_KV",
        "Under this CSV header write one data line only:\nquay_tag,crate_mass\n",
        max_new=32,
        scores=["greedy_32", "csv_row"],
        payload={"min_fields": 2},
        notes="Header plus row.",
        lengths=L32,
    ),
    _item(
        "dev-code-01",
        "DEV_CODE",
        "def tally_pellwick(n):\n    # return n sleds if n is a whole number of eights, else 0\n    ",
        max_new=32,
        scores=["greedy_32", "code_has_return", "no_tool_markup"],
        payload={"must_contain_any": ["return"], "forbid_substrings": ["TOOL=", "<|tool"]},
        notes="Unique function.",
        lengths=L32,
    ),
    _item(
        "dev-code-02",
        "DEV_CODE",
        "pairs = [(3, 4), (8, 1), (5, 0)]\nclosed = [\n    a * b for (a, b) in pairs if a < 7\n",
        max_new=32,
        scores=["greedy_32", "code_closes_bracket", "no_tool_markup"],
        payload={"must_contain_any": ["]"], "forbid_substrings": ["```", "TOOL="]},
        notes="Close list.",
        lengths=L32,
    ),
    _item(
        "dev-code-03",
        "DEV_CODE",
        "# remain in python; never open markdown fences\nquay_ready = True\n",
        max_new=32,
        scores=["greedy_32", "no_tool_markup"],
        payload={"forbid_substrings": ["```", "TOOL=", "<|tool"]},
        notes="No fence.",
        lengths=L32,
    ),
    _item(
        "dev-code-04",
        "DEV_CODE",
        "def crate_dry(mass):\n    if mass <= 0:\n        return False\n    ",
        max_new=32,
        scores=["greedy_32", "code_has_return", "no_tool_markup"],
        payload={"must_contain_any": ["return"], "forbid_substrings": ["TOOL="]},
        notes="Branch.",
        lengths=L32,
    ),
    _item(
        "dev-code-05",
        "DEV_CODE",
        "print(\"pellwick-ok\")\n",
        max_new=32,
        scores=["greedy_32", "no_tool_markup", "not_empty"],
        payload={"forbid_substrings": ["TOOL=", "<|assistant", "function_call"]},
        notes="Print then source.",
        lengths=L32,
    ),
    _item(
        "dev-inst-01",
        "DEV_INSTRUCTION",
        "Answer with a single English number-word and stop. How many eights are in forty? ",
        max_new=32,
        scores=["greedy_32", "exactly_one_word", "accepted_word"],
        payload={"accepted_words": ["five", "Five", "FIVE"]},
        notes="One word five.",
        lengths=L32,
    ),
    _item(
        "dev-inst-02",
        "DEV_INSTRUCTION",
        "Copy this quay stamp once, then halt: PELLWICK-QUAY-STAMP",
        max_new=32,
        scores=["greedy_32", "contains_exact_span"],
        payload={"span": "PELLWICK-QUAY-STAMP"},
        notes="Exact stamp.",
        lengths=L32,
    ),
    _item(
        "dev-inst-03",
        "DEV_INSTRUCTION",
        "Include the word marline and forbid the word Alice. The Ibbotreach sill still held",
        max_new=32,
        scores=["greedy_32", "required_terms", "forbidden_terms"],
        payload={"required_terms": ["marline"], "forbidden_terms": ["Alice", "alice"]},
        notes="Required/forbidden.",
        lengths=L32,
    ),
    _item(
        "dev-inst-04",
        "DEV_INSTRUCTION",
        "Output the two steps in this order: first bank, then pin. Do not reverse them. After last watch the clerk must",
        max_new=32,
        scores=["greedy_32", "ordered_terms"],
        payload={"ordered_terms": ["bank", "pin"]},
        notes="Order.",
        lengths=L32,
    ),
    _item(
        "dev-inst-05",
        "DEV_INSTRUCTION",
        "Reply in at most four English words. Name the bollard material at Pellwick: timber",
        max_new=32,
        scores=["greedy_32", "max_words", "required_terms"],
        payload={"max_words": 4, "required_terms": ["timber"]},
        notes="Length bound.",
        lengths=L32,
    ),
    _item(
        "dev-fact-01",
        "DEV_FACTUAL",
        "In the Pellwick quay primer, a blue crate is labeled dry when it holds no standing water and sits on edge. The first handling rule for a dry crate is to",
        max_new=32,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="Primer rule.",
        lengths=L32_128,
    ),
    _item(
        "dev-fact-02",
        "DEV_FACTUAL",
        "Sarnholt sled math is fixed: eight dry crates fill one sled. If a clerk has forty crates, the number of complete sleds is",
        max_new=32,
        scores=["greedy_32", "constraint_substring_any"],
        payload={"expected_token_substrings": ["5", "five"], "arithmetic": "40/8=5"},
        notes="Local arithmetic.",
        lengths=L32,
    ),
    _item(
        "dev-fact-03",
        "DEV_FACTUAL",
        "To close Lowcinder for the night: bank the Gantspool flue, latch the quay chain, then hang the iron pin on the inner peg. After the flue is banked, the next required action is to",
        max_new=32,
        scores=["greedy_32", "constraint_substring_any"],
        payload={"expected_token_substrings": ["latch", "quay chain", "chain"]},
        notes="Ordered close.",
        lengths=L32,
    ),
    _item(
        "dev-fact-04",
        "DEV_FACTUAL",
        "Quellmere clerks count only whole sleds. Partial sleds are written as remainder crates, never as a fraction. Twenty-five crates at eight per sled should be recorded as",
        max_new=32,
        scores=["greedy_32", "constraint_substring_any"],
        payload={"expected_token_substrings": ["3", "three", "1", "one"]},
        notes="Remainder.",
        lengths=L32,
    ),
    _item(
        "dev-fact-05",
        "DEV_FACTUAL",
        "A sealed Lowcinder tin is quiet if it holds no dye. Quiet tins must lie on their side. A tin standing upright on the quay chain is therefore",
        max_new=32,
        scores=["greedy_32", "fingerprint"],
        payload=None,
        notes="Quiet tin.",
        lengths=L32_128,
    ),
]


def assert_inventory() -> None:
    assert len(ITEMS) == 40
    ids = [it["item_id"] for it in ITEMS]
    assert len(ids) == len(set(ids))
    for cat in CATEGORIES:
        n = sum(1 for it in ITEMS if it["category"] == cat)
        assert n == 5, (cat, n)
    for it in ITEMS:
        assert it["training_use"] == "FORBIDDEN"
        assert it["development_only"] is True
        assert it["evaluation_only"] is False
        assert it["final_eval_suite"] is False


def freeze_payload() -> dict[str, Any]:
    assert_inventory()
    return {
        "suite_id": SUITE_ID,
        "suite_version": SUITE_VERSION,
        "created_at": CREATED_AT,
        "authorship": AUTHORSHIP,
        "development_only": True,
        "evaluation_only": False,
        "training_use": "FORBIDDEN",
        "checkpoint_selection_allowed": True,
        "final_eval_suite": False,
        "replaces_cap_eval_0": False,
        "n_items": len(ITEMS),
        "items": ITEMS,
    }
