"""STAGE3A adjudication suite. 80 items, 10 categories x 8. Evaluation-only. Never used for training."""
from __future__ import annotations

from typing import Any

SUITE_ID = "WRIM-EVAL-S3A-ADJ-000001"
SUITE_VERSION = "1.0.0"
CREATED_AT = "2026-09-13T18:20:00+00:00"
AUTHORSHIP = (
    "Authored synthetic STAGE3A adjudication stems. Evaluation-only. "
    "Not sliced from WR-CORPUS-0 or WR-CORPUS-1. Not CAP-EVAL-0. "
    "Not DIAGNOSTIC-0. Not WRIM-EVAL-S3-000001. Not WRIM-EVAL-S3A-RET-000001. "
    "Not WRIM-EVAL-S3A-STRUCT-000001. Forbidden for training."
)

CATEGORIES = [
    "GENERAL_PROSE",
    "FACTUAL_CONTINUATION",
    "CODE",
    "JSON_STRUCTURED_OUTPUT",
    "INSTRUCTION_FOLLOWING",
    "LONG_FORM_CONTINUATION",
    "REPETITION_RESISTANCE",
    "SPECIAL_TOKEN_STABILITY",
    "SEMANTIC_COHERENCE",
    "MIXED_REASONING",
]


def _item(item_id: str, category: str, prompt: str, *, max_new: int, scores: list[str], payload: dict[str, Any] | None, notes: str, lengths: list[int]) -> dict[str, Any]:
    return {
        "suite_id": SUITE_ID,
        "suite_version": SUITE_VERSION,
        "item_id": item_id,
        "category": category,
        "prompt_text": prompt,
        "reference_type": "CONSTRAINT" if payload else "NONE",
        "reference_payload": payload,
        "generation_mode": "greedy_argmax",
        "max_new_tokens": max_new,
        "eval_lengths": lengths,
        "scoring_functions": scores,
        "hard_integrity_checks": ["finite_logits"],
        "notes": notes,
        "authorship": AUTHORSHIP,
        "created_at": CREATED_AT,
        "training_use": "FORBIDDEN",
        "evaluation_only": True,
        "head_to_head": item_id.endswith("-01"),
    }


L32 = [32]
L32_128 = [32, 128]
L32_128_256 = [32, 128, 256]
L512 = [32, 128, 256, 512]

ITEMS: list[dict[str, Any]] = [
    # --- general prose ---
    _item("adj-prose-01", "GENERAL_PROSE",
         "Fog sat on Tharnwick fen until the reed-cutters could not see the far bank. Brin kept one boot in the mud and listened for the bell. When the bell finally moved, it meant that",
         max_new=32, scores=["greedy_32", "fingerprint", "entropy"], payload={"track_entity": "Tharnwick"}, notes="Fen opening.", lengths=L32_128),
    _item("adj-prose-02", "GENERAL_PROSE",
         "The Orrisfen loft smelled of damp wool. Cal kept an unsent note under a cracked bowl and told himself he would finish the line that began, I still owe",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Interior beat.", lengths=L32_128),
    _item("adj-prose-03", "GENERAL_PROSE",
         '"The kiln is yours for an hour," said Wex, not looking up. "I did not ask for the kiln," Hest answered, and then added,',
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Dialogue.", lengths=L32_128),
    _item("adj-prose-04", "GENERAL_PROSE",
         "By dusk the Caldren yard had gone copper. The last barrow left ruts that filled with water. When the gate-chain dropped, it only meant",
         max_new=32, scores=["greedy_32", "fingerprint"], payload={"track_entity": "Caldren"}, notes="Time of day.", lengths=L32_128),
    _item("adj-prose-05", "GENERAL_PROSE",
         "On the Brindlecroft sill: a split spoon, a coil of brown twine, and a white stone with a hole through it. The stone, unlike the twine, did not",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Still life.", lengths=L32_128),
    _item("adj-prose-06", "GENERAL_PROSE",
         "Rain walked sideways across Hestle pond. A boy counted rings in the water and decided that if a third ring appeared he would",
         max_new=32, scores=["greedy_32", "fingerprint"], payload={"track_entity": "Hestle"}, notes="Pond rain.", lengths=L32_128),
    _item("adj-prose-07", "GENERAL_PROSE",
         "Vorrin kept the night-ledger on his knee because the table listed. He dipped the pen, crossed out a name, and wrote instead",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Ledger.", lengths=L32_128),
    _item("adj-prose-08", "GENERAL_PROSE",
         "Nobody used the Wexhollow footbridge after the third plank went soft. Travelers took the long way around the kiln, unless they were",
         max_new=32, scores=["greedy_32", "fingerprint"], payload={"track_entity": "Wexhollow"}, notes="Footbridge.", lengths=L32_128),
    # --- factual ---
    _item("adj-fact-01", "FACTUAL_CONTINUATION",
         "In the Tharnwick fen primer, a bundled reed is labeled dry when it holds no standing water and is stacked on edge. The first handling rule for a dry bundle is to",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Primer rule.", lengths=L32_128),
    _item("adj-fact-02", "FACTUAL_CONTINUATION",
         "Orrisfen tray math is fixed: ten dry bundles fill one tray. If a clerk has forty bundles, the number of complete trays is",
         max_new=32, scores=["greedy_32", "constraint_substring_any"], payload={"expected_token_substrings": ["4", "four"], "arithmetic": "40/10=4"}, notes="Local arithmetic.", lengths=L32),
    _item("adj-fact-03", "FACTUAL_CONTINUATION",
         "Because the Caldren vent was blocked, heat stayed under the roof tiles. The posted yard notice says the immediate result of that blockage was that",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Cause-effect.", lengths=L32_128),
    _item("adj-fact-04", "FACTUAL_CONTINUATION",
         "To close Brindlecroft for the night: bank the Vorrin kiln, latch the fen gate, then hang the iron pin on the inner peg. After the kiln is banked, the next required action is to",
         max_new=32, scores=["greedy_32", "constraint_substring_any"], payload={"expected_token_substrings": ["latch", "fen gate", "gate"]}, notes="Ordered close.", lengths=L32),
    _item("adj-fact-05", "FACTUAL_CONTINUATION",
         "The Wexhollow ledger lists the assay shed as a timber stall on the south bank, not as a living country. The next ledger line after the stall address is expected to name",
         max_new=32, scores=["greedy_32", "no_tool_markup"], payload={"forbid_substrings": ["TOOL=", "<|"]}, notes="Invented stall.", lengths=L32),
    _item("adj-fact-06", "FACTUAL_CONTINUATION",
         "Hestle pond depth marks are painted at one cubit, two cubits, and three cubits. A mark between two and three cubits is read as",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Depth marks.", lengths=L32_128),
    _item("adj-fact-07", "FACTUAL_CONTINUATION",
         "A sealed Vorrin tin is quiet if it holds no dye. Quiet tins must lie on their side. A tin standing upright on the fen gate is therefore",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="Quiet tin.", lengths=L32_128),
    _item("adj-fact-08", "FACTUAL_CONTINUATION",
         "Tharnwick clerks count only whole trays. Partial trays are written as remainder bundles, never as a fraction. Twenty-five bundles at ten per tray should be recorded as",
         max_new=32, scores=["greedy_32", "constraint_substring_any"], payload={"expected_token_substrings": ["2", "two", "5", "five"]}, notes="Remainder.", lengths=L32),
    # --- code ---
    _item("adj-code-01", "CODE",
         "def tally_tharnwick(n):\n    # return n trays if n is a whole number of tens, else 0\n    ",
         max_new=32, scores=["greedy_32", "code_has_return", "no_tool_markup"], payload={"must_contain_any": ["return"], "forbid_substrings": ["TOOL=", "<|tool"]}, notes="Unique function.", lengths=L32),
    _item("adj-code-02", "CODE",
         "pairs = [(2, 5), (4, 1), (9, 0)]\nclosed = [\n    a * b for (a, b) in pairs if a < 6\n",
         max_new=32, scores=["greedy_32", "code_closes_bracket", "no_tool_markup"], payload={"must_contain_any": ["]"], "forbid_substrings": ["```", "TOOL="]}, notes="Close list.", lengths=L32),
    _item("adj-code-03", "CODE",
         "fen_id = ",
         max_new=32, scores=["greedy_32", "not_empty", "no_tool_markup"], payload={"forbid_substrings": ["TOOL=", "<|"]}, notes="Assignment.", lengths=L32),
    _item("adj-code-04", "CODE",
         "count = count",
         max_new=32, scores=["greedy_32", "constraint_substring_any", "no_tool_markup"], payload={"expected_token_substrings": ["+", "+=", "= count +"], "forbid_substrings": ["TOOL="]}, notes="Increment.", lengths=L32),
    _item("adj-code-05", "CODE",
         "# stay in source; do not open a fence\nready = False\n",
         max_new=32, scores=["greedy_32", "no_tool_markup"], payload={"forbid_substrings": ["```", "TOOL=", "<|tool"]}, notes="No fence.", lengths=L32),
    _item("adj-code-06", "CODE",
         "def pond_ok(depth):\n    if depth < 1:\n        return False\n    ",
         max_new=32, scores=["greedy_32", "code_has_return", "no_tool_markup"], payload={"must_contain_any": ["return"], "forbid_substrings": ["TOOL="]}, notes="Branch.", lengths=L32),
    _item("adj-code-07", "CODE",
         "names = [\"brin\", \"wex\"]\nnames.append(\n",
         max_new=32, scores=["greedy_32", "code_closes_bracket", "no_tool_markup"], payload={"must_contain_any": [")", "]"], "forbid_substrings": ["TOOL="]}, notes="Append call.", lengths=L32),
    _item("adj-code-08", "CODE",
         "print(\"tharnwick-ok\")\n",
         max_new=32, scores=["greedy_32", "no_tool_markup", "not_empty"], payload={"forbid_substrings": ["TOOL=", "<|assistant", "function_call"]}, notes="Print then source.", lengths=L32),
    # --- structured ---
    _item("adj-json-01", "JSON_STRUCTURED_OUTPUT",
         "Emit one object. Required names: fen_id (text) and bundle_count (number). Begin: {",
         max_new=32, scores=["greedy_32", "json_parse", "json_required_keys"], payload={"required_keys": ["fen_id", "bundle_count"]}, notes="Two-key object.", lengths=L32),
    _item("adj-json-02", "JSON_STRUCTURED_OUTPUT",
         "Emit a bracket list of exactly three fen-tool names as strings. Begin: [",
         max_new=32, scores=["greedy_32", "json_parse", "json_array_len_3"], payload={"json_type": "array"}, notes="Array of 3.", lengths=L32),
    _item("adj-json-03", "JSON_STRUCTURED_OUTPUT",
         "Write one fen object. The ready field must be a boolean and the note field must be JSON null. Start: {",
         max_new=32, scores=["greedy_32", "json_parse", "json_bool_null"], payload={"required_keys": ["ready", "note"]}, notes="Bool and null.", lengths=L32),
    _item("adj-json-04", "JSON_STRUCTURED_OUTPUT",
         "Repair this object and emit only the finished object: {\"fen_id\": \"T1\", \"bundle_count\":",
         max_new=32, scores=["greedy_32", "json_parse_prefix_repair", "json_required_keys"], payload={"required_keys": ["fen_id", "bundle_count"]}, notes="Prefix repair.", lengths=L32),
    _item("adj-json-05", "JSON_STRUCTURED_OUTPUT",
         "Nest a flag. Skeleton if needed: {\"bin\":{\"inner_flag\":true}} then stop.\n",
         max_new=32, scores=["greedy_32", "json_parse", "json_nested_outer"], payload={"required_keys": ["bin"], "nested_key": "inner_flag"}, notes="Nested.", lengths=L32),
    _item("adj-kv-06", "JSON_STRUCTURED_OUTPUT",
         "Colon lines, not braces. Pattern:\nfen_id: T1\nbundle_count: 10\n",
         max_new=32, scores=["greedy_32", "key_value_lines"], payload={"required_keys": ["fen_id", "bundle_count"]}, notes="KV lines.", lengths=L32),
    _item("adj-list-07", "JSON_STRUCTURED_OUTPUT",
         "Stack exactly three fen tools as separate dashed lines.\n- ",
         max_new=32, scores=["greedy_32", "list_lines"], payload={"min_lines": 3}, notes="Bullet list.", lengths=L32),
    _item("adj-csv-08", "JSON_STRUCTURED_OUTPUT",
         "One comma row in order fen_id then bundle_count then ready. No extra words.\n",
         max_new=32, scores=["greedy_32", "csv_row"], payload={"min_fields": 3}, notes="CSV row.", lengths=L32),
    # --- instruction ---
    _item("adj-inst-01", "INSTRUCTION_FOLLOWING",
         "Answer with a single English number-word and stop. How many tens are in forty? ",
         max_new=32, scores=["greedy_32", "exactly_one_word", "accepted_word"], payload={"accepted_words": ["four", "Four", "FOUR"]}, notes="One word four.", lengths=L32),
    _item("adj-inst-02", "INSTRUCTION_FOLLOWING",
         "Copy this fen stamp once, then halt: THARNWICK-FEN-STAMP",
         max_new=32, scores=["greedy_32", "contains_exact_span"], payload={"span": "THARNWICK-FEN-STAMP"}, notes="Exact stamp.", lengths=L32),
    _item("adj-inst-03", "INSTRUCTION_FOLLOWING",
         "Print these three fen notes separated by slashes only: dry / stacked / sealed",
         max_new=32, scores=["greedy_32", "contains_exact_span"], payload={"span": "dry"}, notes="Slash notes.", lengths=L32),
    _item("adj-inst-04", "INSTRUCTION_FOLLOWING",
         "Write lowercase English only, with no digits. the iron pin on the inner peg is",
         max_new=32, scores=["greedy_32", "lowercase_no_digits"], payload={"mode": "lowercase_no_digits"}, notes="Register.", lengths=L32),
    _item("adj-inst-05", "INSTRUCTION_FOLLOWING",
         "One ordinary sentence about a reed bundle. Do not emit chat markup.",
         max_new=32, scores=["greedy_32", "no_tool_markup"], payload={"forbid_substrings": ["<|", "TOOL=", "```"]}, notes="No markup.", lengths=L32),
    _item("adj-inst-06", "INSTRUCTION_FOLLOWING",
         "Include the word cubit and forbid the word Alice. The Hestle depth mark is painted in",
         max_new=32, scores=["greedy_32", "required_terms", "forbidden_terms"], payload={"required_terms": ["cubit"], "forbidden_terms": ["Alice", "alice"]}, notes="Required/forbidden.", lengths=L32),
    _item("adj-inst-07", "INSTRUCTION_FOLLOWING",
         "Output the two steps in this order: first bank, then latch. Do not reverse them. After dusk the clerk must",
         max_new=32, scores=["greedy_32", "ordered_terms"], payload={"ordered_terms": ["bank", "latch"]}, notes="Order.", lengths=L32),
    _item("adj-inst-08", "INSTRUCTION_FOLLOWING",
         "Reply in at most four English words. Name the stall material in Wexhollow: timber",
         max_new=32, scores=["greedy_32", "max_words", "required_terms"], payload={"max_words": 4, "required_terms": ["timber"]}, notes="Length bound.", lengths=L32),
    # --- long form ---
    _item("adj-long-01", "LONG_FORM_CONTINUATION",
         "Keep the same fen. Brin waited at Tharnwick fen after the fog hid the far bank. The reed-cutters had gone. She counted the slow bells and decided that if a lamp showed on the south stall she would",
         max_new=256, scores=["greedy_256", "fingerprint", "entropy", "entity_track"], payload={"track_entity": "Tharnwick"}, notes="256 fen story. 512 on this item.", lengths=L512),
    _item("adj-long-02", "LONG_FORM_CONTINUATION",
         "Continue this fen notice in plain sentences. Dry bundles stand on edge. Ten bundles fill one tray. Clerks must not open a quiet tin at Hestle pond. The next paragraph explains why quiet tins stay closed during",
         max_new=256, scores=["greedy_256", "fingerprint", "entropy"], payload=None, notes="256 notice. 512 on this item.", lengths=L512),
    _item("adj-long-03", "LONG_FORM_CONTINUATION",
         "Stay in Python source about trays.\n\ndef tray_ok(n):\n    return n > 0\n\n# next helper should mention Caldren\n",
         max_new=256, scores=["greedy_256", "no_tool_markup"], payload={"forbid_substrings": ["TOOL=", "<|tool"]}, notes="Code long.", lengths=L32_128_256),
    _item("adj-long-04", "LONG_FORM_CONTINUATION",
         "Keep telling the Orrisfen loft story without changing the place-name. Cal sat under the cracked bowl with the unsent note. Rain tapped the wool. He told himself that before he slept he would",
         max_new=256, scores=["greedy_256", "entity_track"], payload={"track_entity": "Orrisfen"}, notes="Loft long.", lengths=L32_128_256),
    _item("adj-long-05", "LONG_FORM_CONTINUATION",
         "Continue the Wexhollow footbridge as several sentences. The third plank went soft. Travelers took the kiln road. A night clerk still had to post a warning that",
         max_new=256, scores=["greedy_256", "entity_track"], payload={"track_entity": "Wexhollow"}, notes="Bridge long.", lengths=L32_128_256),
    _item("adj-long-06", "LONG_FORM_CONTINUATION",
         "Keep the Vorrin kiln in view. Heat stayed under the tiles because the vent was blocked. The yard notice went on to describe how a clerk should",
         max_new=256, scores=["greedy_256", "fingerprint"], payload={"track_entity": "Vorrin"}, notes="Kiln long.", lengths=L32_128_256),
    _item("adj-long-07", "LONG_FORM_CONTINUATION",
         "Write a long fen inventory in ordinary prose. Mention bundles, trays, and the iron pin at least once, then invent further duties at Brindlecroft. After the pin is hung,",
         max_new=256, scores=["greedy_256", "required_terms"], payload={"required_terms": ["pin"]}, notes="Inventory long.", lengths=L32_128_256),
    _item("adj-long-08", "LONG_FORM_CONTINUATION",
         "Continue as if completing a small object, then recover in prose about the same tray. {\"fen_id\": \"T1\", \"note\":",
         max_new=256, scores=["greedy_256", "json_parse_optional"], payload={"also_try_json_parse": True}, notes="JSON then prose.", lengths=L32_128_256),
    # --- repetition ---
    _item("adj-rep-01", "REPETITION_RESISTANCE",
         "Describe the Brindlecroft close in several different sentences. Mention the Vorrin kiln, the fen gate, and the iron pin once each, then invent new duties. After the pin is hung, the clerk still has to",
         max_new=256, scores=["greedy_256", "fingerprint", "entropy"], payload=None, notes="Avoid one-word loop. 512 on this item.", lengths=L512),
    _item("adj-rep-02", "REPETITION_RESISTANCE",
         "Name distinct fen tools in ordinary sentences without repeating the same tool word over and over. The first tool is an iron pin. The second is brown twine. After those, the clerk should mention",
         max_new=256, scores=["greedy_256", "fingerprint"], payload=None, notes="Avoid noun loop. 512.", lengths=L512),
    _item("adj-rep-03", "REPETITION_RESISTANCE",
         "Count upward in words from one to eight inside a short notice, then continue in new sentences about Tharnwick fen. one two three",
         max_new=256, scores=["greedy_256", "fingerprint"], payload=None, notes="Avoid numeral stall.", lengths=L32_128_256),
    _item("adj-rep-04", "REPETITION_RESISTANCE",
         "Do not repeat the word fog as a loop. After the fog lifted at Hestle pond, the reed-cutters could finally",
         max_new=256, scores=["greedy_256", "forbidden_terms"], payload={"forbidden_terms": []}, notes="Fog once then new content.", lengths=L32_128_256),
    _item("adj-rep-05", "REPETITION_RESISTANCE",
         "Write five distinct duties for the night clerk, each in its own sentence, none of which is only the word latch. First duty:",
         max_new=256, scores=["greedy_256", "fingerprint"], payload=None, notes="Five duties.", lengths=L32_128_256),
    _item("adj-rep-06", "REPETITION_RESISTANCE",
         "Continue without copying the previous three words again and again. The south stall on the timber bank still needed",
         max_new=256, scores=["greedy_256", "fingerprint"], payload=None, notes="No copy loop.", lengths=L32_128_256),
    _item("adj-rep-07", "REPETITION_RESISTANCE",
         "List new weather details about Orrisfen loft, not a single dripping sound repeated. The wool smelled damp because",
         max_new=256, scores=["greedy_256", "fingerprint"], payload=None, notes="Weather variety.", lengths=L32_128_256),
    _item("adj-rep-08", "REPETITION_RESISTANCE",
         "Advance the Caldren yard story by changing the action each sentence. A barrow left ruts. Water filled them. Next,",
         max_new=256, scores=["greedy_256", "fingerprint"], payload=None, notes="Action change.", lengths=L32_128_256),
    # --- special token ---
    _item("adj-spec-01", "SPECIAL_TOKEN_STABILITY",
         "The iron pin hung from the inner peg and tapped the fen gate once. In the morning someone would take it down and",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload={"special_ids": [0, 1, 2, 3, 4, 5, 6, 7, 8]}, notes="Ordinary prose.", lengths=L32_128_256),
    _item("adj-spec-02", "SPECIAL_TOKEN_STABILITY",
         "Mention a fen stamp that uses parentheses (like this) and end with a plain question about Wexhollow.",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload={"special_ids": [0, 1, 2, 3, 4, 5, 6, 7, 8]}, notes="Delimiters.", lengths=L32_128_256),
    _item("adj-spec-03", "SPECIAL_TOKEN_STABILITY",
         "The tray stencil read 10 then 40 then 80. A clerk adding those three numbers in order would write",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload=None, notes="Digits.", lengths=L32_128_256),
    _item("adj-spec-04", "SPECIAL_TOKEN_STABILITY",
         "Proceed with ordinary fen prose.",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload={"short_stem": True}, notes="Short stem.", lengths=L32_128_256),
    _item("adj-spec-05", "SPECIAL_TOKEN_STABILITY",
         "End the fen notice after one short clause about the iron pin, then stop.",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload={"eos_ok_once": True}, notes="EOS once.", lengths=L32_128_256),
    _item("adj-spec-06", "SPECIAL_TOKEN_STABILITY",
         "Copy punctuation as prose only: quotes \"so\", braces {not control}, and a mark?",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload=None, notes="Punctuation prose.", lengths=L32_128_256),
    _item("adj-spec-07", "SPECIAL_TOKEN_STABILITY",
         "Stay in ordinary English about Tharnwick fen. Do not dump pad tokens as content. The reed-cutters",
         max_new=256, scores=["greedy_256", "special_rate_0_8", "no_tool_markup"], payload={"forbid_substrings": ["<|"]}, notes="No pad dump.", lengths=L32_128_256),
    _item("adj-spec-08", "SPECIAL_TOKEN_STABILITY",
         "A clerk wrote T1 then 10 then ready. Continue as source text, not as a control-token run.",
         max_new=256, scores=["greedy_256", "special_rate_0_8"], payload=None, notes="IDs as prose.", lengths=L32_128_256),
    # --- semantic coherence ---
    _item("adj-coh-01", "SEMANTIC_COHERENCE",
         "Brin is still at Tharnwick fen, not in a city. Continue without moving her to a seaport or a palace. She waited because",
         max_new=256, scores=["greedy_256", "entity_track", "forbidden_terms"], payload={"track_entity": "Tharnwick", "forbidden_terms": ["palace", "seaport", "London"]}, notes="Place lock.", lengths=L32_128_256),
    _item("adj-coh-02", "SEMANTIC_COHERENCE",
         "The quiet tin holds no dye and must lie on its side. Continue without standing it upright. A clerk who finds it upright should",
         max_new=256, scores=["greedy_256", "forbidden_terms"], payload={"forbidden_terms": []}, notes="Tin constraint in prose.", lengths=L32_128_256),
    _item("adj-coh-03", "SEMANTIC_COHERENCE",
         "Keep Cal in the Orrisfen loft with the unsent note. Do not turn the note into a legal contract. He unfolded it and",
         max_new=256, scores=["greedy_256", "entity_track"], payload={"track_entity": "Orrisfen"}, notes="Object lock.", lengths=L32_128_256),
    _item("adj-coh-04", "SEMANTIC_COHERENCE",
         "Ten bundles fill one tray in this notice. Do not change the filling number to twelve. The clerk stacking the twenty-first bundle therefore",
         max_new=256, scores=["greedy_256", "forbidden_terms"], payload={"forbidden_terms": ["twelve", "12"]}, notes="Number lock.", lengths=L32_128_256),
    _item("adj-coh-05", "SEMANTIC_COHERENCE",
         "Hestle pond has cubit marks, not miles. Continue the depth notice without introducing miles or oceans. The water sat near",
         max_new=256, scores=["greedy_256", "forbidden_terms", "entity_track"], payload={"track_entity": "Hestle", "forbidden_terms": ["mile", "ocean", "sea"]}, notes="Scale lock.", lengths=L32_128_256),
    _item("adj-coh-06", "SEMANTIC_COHERENCE",
         "Wex did not look up from the kiln hour. Continue the dialogue without making Wex suddenly a queen. Hest said",
         max_new=256, scores=["greedy_256", "forbidden_terms"], payload={"forbidden_terms": ["Queen", "Alice"]}, notes="Role lock.", lengths=L32_128_256),
    _item("adj-coh-07", "SEMANTIC_COHERENCE",
         "The third plank of the Wexhollow footbridge is soft. Continue without claiming the bridge is new and sound. Travelers",
         max_new=256, scores=["greedy_256", "entity_track"], payload={"track_entity": "Wexhollow"}, notes="Condition lock.", lengths=L32_128_256),
    _item("adj-coh-08", "SEMANTIC_COHERENCE",
         "The iron pin hangs on the inner peg after close. Continue without moving the pin to a harbor crane. At dawn a clerk",
         max_new=256, scores=["greedy_256", "forbidden_terms"], payload={"forbidden_terms": ["crane", "harbor"]}, notes="Tool lock.", lengths=L32_128_256),
    # --- mixed reasoning ---
    _item("adj-mix-01", "MIXED_REASONING",
         "Ten bundles per tray. A clerk has seventy bundles. How many complete trays, as a number-word or digit? ",
         max_new=32, scores=["greedy_32", "constraint_substring_any"], payload={"expected_token_substrings": ["7", "seven"]}, notes="70/10.", lengths=L32),
    _item("adj-mix-02", "MIXED_REASONING",
         "Order: bank, latch, hang. After latching, the next required word in the close is hang. The clerk then",
         max_new=32, scores=["greedy_32", "ordered_terms"], payload={"ordered_terms": ["hang"]}, notes="Third step.", lengths=L32_128),
    _item("adj-mix-03", "MIXED_REASONING",
         "If a tin is upright it is not stored as quiet. This tin is upright, so it is",
         max_new=32, scores=["greedy_32", "fingerprint"], payload=None, notes="If-then.", lengths=L32_128),
    _item("adj-mix-04", "MIXED_REASONING",
         "Marks at 1, 2, and 3 cubits. A reading of two cubits is the middle mark. The middle mark is",
         max_new=32, scores=["greedy_32", "constraint_substring_any"], payload={"expected_token_substrings": ["2", "two"]}, notes="Middle mark.", lengths=L32),
    _item("adj-mix-05", "MIXED_REASONING",
         "Rewrite in lowercase with no digits: THE PIN IS HUNG. Result:",
         max_new=32, scores=["greedy_32", "lowercase_no_digits"], payload={"mode": "lowercase_no_digits"}, notes="Transform.", lengths=L32),
    _item("adj-mix-06", "MIXED_REASONING",
         "Forbidden word: Alice. Required word: fen. Continue: the clerk walked back to the",
         max_new=32, scores=["greedy_32", "required_terms", "forbidden_terms"], payload={"required_terms": ["fen"], "forbidden_terms": ["Alice"]}, notes="Mix constraints.", lengths=L32_128),
    _item("adj-mix-07", "MIXED_REASONING",
         "A stall is timber, not stone. Do not call it stone. The Wexhollow stall is built of",
         max_new=32, scores=["greedy_32", "required_terms", "forbidden_terms"], payload={"required_terms": ["timber"], "forbidden_terms": ["stone"]}, notes="Material.", lengths=L32),
    _item("adj-mix-08", "MIXED_REASONING",
         "Forty bundles at ten per tray leave zero remainder. Record complete trays only. The record should show",
         max_new=32, scores=["greedy_32", "constraint_substring_any"], payload={"expected_token_substrings": ["4", "four"]}, notes="40/10 remainder 0.", lengths=L32),
]


def assert_inventory() -> None:
    assert len(ITEMS) == 80, len(ITEMS)
    ids = [it["item_id"] for it in ITEMS]
    assert len(ids) == len(set(ids))
    for cat in CATEGORIES:
        n = sum(1 for it in ITEMS if it["category"] == cat)
        assert n == 8, (cat, n)


def freeze_payload() -> dict[str, Any]:
    assert_inventory()
    return {
        "suite_id": SUITE_ID,
        "suite_version": SUITE_VERSION,
        "created_at": CREATED_AT,
        "authorship": AUTHORSHIP,
        "evaluation_only": True,
        "training_use": "FORBIDDEN",
        "replaces_cap_eval_0": False,
        "n_items": len(ITEMS),
        "categories": CATEGORIES,
        "items": ITEMS,
    }
