"""WRIM1 CPT Stage B design identity. Pointer/manifest only. Does not train.

Does not construct an optimizer. Does not authorize Stage B execution.
Does not reuse WRIM1-RUN-000013.
"""
from __future__ import annotations

from wrim_cpt_identity import (
    ARCHITECTURE,
    AUTHORIZE_ENV,
    LINUX_CKPT_ROOT,
    LINUX_DATA_ROOT,
    PARAM_COUNT,
    PARENT_SHA,
    TOKENIZER_SHA,
)

STAGE_A_CPT_RUN_ID = "WRIM1-CPT-000001"
PROPOSED_STAGE_B_CPT_RUN_ID = "WRIM1-CPT-000002"
NAMESPACE = "WRIM1-CPT"
SFT_NAMESPACE = "WRIM1-RUN"
RESERVED_SFT_RUN = "WRIM1-RUN-000013"

PROVISIONAL_STAGE_B_PARENT = "STEP_400"
PROVISIONAL_STAGE_B_PARENT_CHECKPOINT = "step-400"
PROVISIONAL_STAGE_B_PARENT_HASH = (
    "f82f4364b16842ca3d43427251299f1ad38d5104f24013251f2ebc6af6607af8"
)
SELECTION_STATUS = "PROVISIONAL_STAGE_B_PARENT"

PARENT_WRIM0_HASH = PARENT_SHA
TOKENIZER_EXPECTED_SHA = TOKENIZER_SHA
ARCHITECTURE_ID = ARCHITECTURE
PARAMETER_COUNT = PARAM_COUNT

INDEPENDENT_NL_PACK_ID = "WR-VAL-NL-INDEPENDENT-1-v1.0.0"
INDEPENDENT_NL_PACK_HASH = "3baa54bcdacc2f872cf9a2537a9336cd245886c965b676fd2e8aa783a242f726"
INDEPENDENT_NL_MANIFEST_HASH = "bc281c24b9cf443e2d3277caff9f810aa81a250c2f733971cca5d29240f28f88"
INDEPENDENT_NL_TRAIN_FORBIDDEN = True

PROPOSED_CORPUS_ID = "WR-CORPUS-CPT-2"
PROPOSED_CORPUS_VERSION = "WR-CORPUS-CPT-2-v1.0.0"
CORPUS_BUILD_AUTHORIZED = False

STAGE_B_EXECUTED = False
SFT_EXECUTED = False
RUN_000013_EXECUTED = False
STAGE3B_EXECUTED = False
WRIM_TRAINING_AUTHORIZATION = "OFF"
WRIM0_MODIFIED = False
TOKENIZER_MODIFIED = False
ARCHITECTURE_MODIFIED = False
CANONICAL_PROMOTED = False

POINTER_FILENAME = "WRIM1_CPT_STAGE_B_PARENT_POINTER.json"
DESIGN_REPORT_FILENAME = "WRIM1_CPT_STAGE_B_DESIGN_REPORT.json"
VAL_PACK_FREEZE_FILENAME = "WR-VAL-NL-INDEPENDENT-1-TRAIN-FORBIDDEN.json"

CKPT_ROOT = LINUX_CKPT_ROOT
DATA_ROOT = LINUX_DATA_ROOT
AUTHORIZE_ENV_NAME = AUTHORIZE_ENV
