"""WRIM-1-PRETRAIN-CORPUS-v1.0.0 identity. Corpus expansion only. Does not train."""
from __future__ import annotations

from pathlib import Path

from wrim_cpt_identity import LINUX_DATA_ROOT, LINUX_VENV_PYTHON
from wrim_pilot_ab_identity import (
    CANONICAL,
    CANONICAL_HASH,
    FROZEN_CORPUS_HASH,
    FROZEN_TOKENIZER_HASH,
    TOKENIZER_DIR,
)

PROGRAM_ID = "WRIM1-CORPUS-BALANCE-60M-01"
CORPUS_ID = "WRIM-1-PRETRAIN-CORPUS"
CORPUS_VERSION = "WRIM-1-PRETRAIN-CORPUS-v1.5.0"
SEED = 20260924
UNIQUE_TARGET = 60_000_000
CHECKPOINT_25M = 25_000_000
CHECKPOINT_40M = 40_000_000
PRIMARY_LANGUAGE = "en"

DATA_ROOT = Path(LINUX_DATA_ROOT)
OUT_DIR = DATA_ROOT / CORPUS_VERSION
RAW_DIR = DATA_ROOT / "WRIM-PRETRAIN-RAW-CACHE"
REPORT_PATH = DATA_ROOT / "WRIM1_CORPUS_50M_EXPANSION_REPORT.json"
PILOT_TOKENIZER_PATH = TOKENIZER_DIR / "tokenizer.json"
PILOT_CORPUS_HASH = FROZEN_CORPUS_HASH
PILOT_TOKENIZER_HASH = FROZEN_TOKENIZER_HASH
CANONICAL_STEP = CANONICAL
CANONICAL_STEP_HASH = CANONICAL_HASH

LOCKED_EVAL_PATHS = (
    DATA_ROOT / "WRIM-FOUNDATION-EVAL-1-v1.0.0" / "WRIM-FOUNDATION-EVAL-1-v1.0.0.json",
    DATA_ROOT / "WRIM-FOUNDATION-GRADUATION-1-v1.0.0" / "first-token-val.jsonl",
    DATA_ROOT / "WRIM-FOUNDATION-GRADUATION-1-v1.0.0" / "two-token-val.jsonl",
    DATA_ROOT / "WR-VAL-NL-INDEPENDENT-1-v1.0.0" / "WR-VAL-NL-INDEPENDENT-1-v1.0.0-PASSAGES.jsonl",
    DATA_ROOT / "WRIM1-PILOT-PROBES-v1" / "probes.json",
)

USER_AGENT = "WarRoomOS-CorpusExpansion/1.0 (Commander-authorized research; local HVU; no commercial scrape)"
PYTHON = LINUX_VENV_PYTHON
