import type { CouncilOrchestrationFamily } from '@/components/council/councilSessionTypes'
import type {
  CouncilShadowSelectionReport,
  RecommendationMatchStatus,
  SynthesizerMatchStatus,
} from './shadowTypes'

export type FamilyDisplayItem = {
  readonly id: string
  readonly label: string
  readonly known: boolean
}

export type RecommendationReasonView = {
  readonly label: string
  readonly text: string
}

export type AdaptiveCouncilReadoutStatus =
  | RecommendationMatchStatus
  | 'shadow_failed'

export type AdaptiveCouncilReadoutSynthesizerStatus =
  | 'match'
  | 'mismatch'
  | 'actual_unresolved'
  | 'recommendation_unresolved'
  | 'not_comparable'

export type AdaptiveCouncilReadoutViewModel = {
  readonly available: boolean
  readonly status: AdaptiveCouncilReadoutStatus
  readonly statusLabel: string
  readonly statusExplanation: string
  readonly advisoryOnly: true
  readonly executionUnaffected: boolean
  readonly recommendedFamilies: readonly FamilyDisplayItem[]
  readonly actualFamilies: readonly FamilyDisplayItem[]
  readonly overlappingFamilies: readonly FamilyDisplayItem[]
  readonly recommendedOnlyFamilies: readonly FamilyDisplayItem[]
  readonly actualOnlyFamilies: readonly FamilyDisplayItem[]
  readonly recommendationReasons: readonly RecommendationReasonView[]
  readonly capabilitiesRequested: readonly string[]
  readonly capabilitiesCovered: readonly string[]
  readonly unresolvedCapabilities: readonly string[]
  readonly evidenceRequired: boolean | null
  readonly liveDataRequired: boolean | null
  readonly recommendedRedTeam: boolean | null
  readonly actualRedTeamIncluded: boolean | null
  readonly recommendedSynthesizer: FamilyDisplayItem | null
  readonly actualSynthesizer: FamilyDisplayItem | null
  readonly synthesizerStatus: AdaptiveCouncilReadoutSynthesizerStatus
  readonly recommendationVersion: string | null
  readonly generatedAt: string | null
  readonly uncertaintyMessages: readonly string[]
  readonly failureMessage: string | null
  readonly sourceLabel: 'Generated by Adaptive Council shadow planning'
}

export type AdaptiveCouncilReadoutEligibilityInput = {
  readonly messageType: string
  readonly responseComplete: boolean
  readonly isUserMessage: boolean
}

const FAMILY_LABELS: Record<CouncilOrchestrationFamily, string> = {
  chatgpt: 'ChatGPT',
  claude: 'Claude',
  grok: 'Grok',
  gemini: 'Gemini',
  red_team: 'Red Team',
  baby: 'Baby AI Observer',
  kimi: 'Kimi',
  bridge_architect: 'Bridge Architect',
}

const CAPABILITY_LABELS: Record<string, string> = {
  general_reasoning: 'General reasoning',
  strategic_planning: 'Strategic planning',
  broad_knowledge_synthesis: 'Knowledge synthesis',
  comparative_analysis: 'Comparative analysis',
  concise_response: 'Concise response',
  deep_analysis: 'Deep analysis',
  synthesis: 'Synthesis',
  tool_eligible: 'Tool eligible',
  systems_architecture: 'Systems architecture',
  software_engineering: 'Software engineering',
  task_decomposition: 'Task decomposition',
  current_information: 'Current information',
  evidence_research: 'Evidence research',
  research_eligible: 'Research eligible',
  visual_reasoning: 'Visual reasoning',
  historical_analysis: 'Historical analysis',
  adversarial_review: 'Adversarial review',
  high_risk_review: 'Risk analysis',
  numerical_analysis: 'Numerical analysis',
}

const STATUS_LABELS: Record<AdaptiveCouncilReadoutStatus, { label: string; explanation: string }> = {
  exact_match: {
    label: 'Exact match',
    explanation: 'The adaptive recommendation matched the Council families actually used.',
  },
  partial_match: {
    label: 'Partial match',
    explanation: 'Some recommended families were used, and some actual or recommended families differed.',
  },
  no_match: {
    label: 'Different Council used',
    explanation: 'The adaptive recommendation and actual Council used different family sets.',
  },
  actual_unresolved: {
    label: 'Actual Council not available',
    explanation: 'The response did not include a finalized actual Council selection snapshot.',
  },
  recommendation_unresolved: {
    label: 'Recommendation incomplete',
    explanation: 'The adaptive recommendation was incomplete or unresolved.',
  },
  not_comparable: {
    label: 'Comparison unavailable',
    explanation: 'The recommendation and actual execution could not be compared truthfully.',
  },
  shadow_failed: {
    label: 'Recommendation unavailable',
    explanation: 'Adaptive Council shadow planning did not complete. The Council response remains usable.',
  },
}

const SYNTHESIZER_LABELS: Record<AdaptiveCouncilReadoutSynthesizerStatus, string> = {
  match: 'Match',
  mismatch: 'Different synthesizer',
  actual_unresolved: 'Actual synthesizer unavailable',
  recommendation_unresolved: 'Recommended synthesizer unavailable',
  not_comparable: 'Comparison unavailable',
}

function unique(values: readonly string[]): string[] {
  const out: string[] = []
  for (const value of values) {
    if (!out.includes(value)) out.push(value)
  }
  return out
}

function readableToken(value: string): string {
  return value
    .replaceAll('_', ' ')
    .replace(/\b\w/g, char => char.toUpperCase())
}

function capabilityLabel(value: string): string {
  return CAPABILITY_LABELS[value] ?? readableToken(value)
}

function familyDisplay(value: string | null | undefined): FamilyDisplayItem | null {
  if (!value) return null
  const label = FAMILY_LABELS[value as CouncilOrchestrationFamily]
  return {
    id: value,
    label: label ?? 'Unknown Council family',
    known: Boolean(label),
  }
}

function familyList(values: readonly string[] | undefined): FamilyDisplayItem[] {
  return unique(values ?? [])
    .map(value => familyDisplay(value))
    .filter((item): item is FamilyDisplayItem => Boolean(item))
}

function statusFromReport(report: CouncilShadowSelectionReport): AdaptiveCouncilReadoutStatus {
  if (report.plannerStatus === 'failed' || report.comparisonStatus === 'failed' || report.eligibilityStatus === 'planner_failed') {
    return 'shadow_failed'
  }
  if (isRecommendationMatchStatus(report.recommendationMatchStatus)) return report.recommendationMatchStatus
  return 'not_comparable'
}

function isRecommendationMatchStatus(value: unknown): value is RecommendationMatchStatus {
  return typeof value === 'string' && value in STATUS_LABELS && value !== 'shadow_failed'
}

function synthesizerStatus(value: SynthesizerMatchStatus | string): AdaptiveCouncilReadoutSynthesizerStatus {
  if (value === 'exact_match') return 'match'
  if (value === 'different') return 'mismatch'
  if (value === 'actual_unresolved' || value === 'recommendation_unresolved' || value === 'not_comparable') return value
  return 'not_comparable'
}

function recommendedRedTeamValue(report: CouncilShadowSelectionReport): boolean | null {
  if (report.recommendedRedTeamPolicy === null) return null
  return report.recommendedRedTeamPolicy === 'mandatory' || report.recommendedRedTeamPolicy === 'conditional'
}

function readoutFailureMessage(report: CouncilShadowSelectionReport, status: AdaptiveCouncilReadoutStatus): string | null {
  if (status !== 'shadow_failed') return null
  if (report.eligibilityReason === 'planner_exception') return 'Adaptive Council recommendation failed safely before display.'
  return 'Adaptive Council recommendation unavailable.'
}

function reportHasDisplayableMetadata(report: CouncilShadowSelectionReport): boolean {
  if (report.eligibilityStatus === 'ineligible' && report.eligibilityReason === 'unsupported_direct_provider_path') return false
  if (report.plannerStatus === 'not_run' && report.comparisonStatus === 'not_run') return false
  return true
}

export function shouldRenderAdaptiveCouncilReadout(
  report: CouncilShadowSelectionReport | null | undefined,
  input: AdaptiveCouncilReadoutEligibilityInput,
): boolean {
  if (!report) return false
  if (input.isUserMessage) return false
  if (input.messageType !== 'response') return false
  if (!input.responseComplete) return false
  return reportHasDisplayableMetadata(report)
}

export function createAdaptiveCouncilReadoutViewModel(
  report: CouncilShadowSelectionReport | null | undefined,
  input: AdaptiveCouncilReadoutEligibilityInput = {
    messageType: 'response',
    responseComplete: true,
    isUserMessage: false,
  },
): AdaptiveCouncilReadoutViewModel {
  if (!shouldRenderAdaptiveCouncilReadout(report, input)) {
    return Object.freeze({
      available: false,
      status: 'not_comparable',
      statusLabel: 'Comparison unavailable',
      statusExplanation: 'Adaptive Council metadata is not available for this completed response.',
      advisoryOnly: true,
      executionUnaffected: false,
      recommendedFamilies: [],
      actualFamilies: [],
      overlappingFamilies: [],
      recommendedOnlyFamilies: [],
      actualOnlyFamilies: [],
      recommendationReasons: [],
      capabilitiesRequested: [],
      capabilitiesCovered: [],
      unresolvedCapabilities: [],
      evidenceRequired: null,
      liveDataRequired: null,
      recommendedRedTeam: null,
      actualRedTeamIncluded: null,
      recommendedSynthesizer: null,
      actualSynthesizer: null,
      synthesizerStatus: 'not_comparable',
      recommendationVersion: null,
      generatedAt: null,
      uncertaintyMessages: [],
      failureMessage: null,
      sourceLabel: 'Generated by Adaptive Council shadow planning',
    })
  }

  const safeReport = report as CouncilShadowSelectionReport
  const status = statusFromReport(safeReport)
  const statusText = STATUS_LABELS[status]
  const unresolvedCapabilities = unique(safeReport.unresolvedCapabilities ?? []).map(capabilityLabel)
  const uncertaintyMessages = unique(safeReport.uncertaintyFlags ?? []).map(readableToken)
  const synthStatus = synthesizerStatus(safeReport.synthesizerMatchStatus)

  return Object.freeze({
    available: true,
    status,
    statusLabel: statusText.label,
    statusExplanation: statusText.explanation,
    advisoryOnly: true,
    executionUnaffected: safeReport.executionUnaffected === true,
    recommendedFamilies: familyList(safeReport.recommendedFamilies),
    actualFamilies: familyList(safeReport.actualFamilies),
    overlappingFamilies: familyList(safeReport.overlappingFamilies),
    recommendedOnlyFamilies: familyList(safeReport.recommendedOnlyFamilies),
    actualOnlyFamilies: familyList(safeReport.actualOnlyFamilies),
    recommendationReasons: [],
    capabilitiesRequested: [],
    capabilitiesCovered: [],
    unresolvedCapabilities,
    evidenceRequired: null,
    liveDataRequired: null,
    recommendedRedTeam: recommendedRedTeamValue(safeReport),
    actualRedTeamIncluded: typeof safeReport.actualRedTeamIncluded === 'boolean' ? safeReport.actualRedTeamIncluded : null,
    recommendedSynthesizer: familyDisplay(safeReport.recommendedSynthesizer),
    actualSynthesizer: familyDisplay(safeReport.actualSynthesizer),
    synthesizerStatus: synthStatus,
    recommendationVersion: safeReport.planVersion == null ? safeReport.schemaVersion : `${safeReport.schemaVersion} · plan v${safeReport.planVersion}`,
    generatedAt: safeReport.generatedAt ?? null,
    uncertaintyMessages,
    failureMessage: readoutFailureMessage(safeReport, status),
    sourceLabel: 'Generated by Adaptive Council shadow planning',
  })
}

export function adaptiveCouncilSynthesizerStatusLabel(status: AdaptiveCouncilReadoutSynthesizerStatus): string {
  return SYNTHESIZER_LABELS[status]
}
