import 'server-only'

import type { ResearchProviderId } from '@/lib/research-engine/core/types'

/**
 * Every host a Research Engine provider is ever allowed to contact. This is
 * an allowlist, not a denylist — callers can never redirect an adapter to an
 * arbitrary upstream host, including via a Location header. Add a host here
 * only when it is the provider's official domain.
 */
export const RESEARCH_PROVIDER_HOST_ALLOWLIST: Record<ResearchProviderId, string[]> = {
  exa: ['api.exa.ai'],
  github: ['api.github.com'],
  sam_gov: ['api.sam.gov'],
  fmcsa: ['mobile.fmcsa.dot.gov'],
  ncbi: ['eutils.ncbi.nlm.nih.gov'],
  fred: ['api.stlouisfed.org'],
  semantic_scholar: ['api.semanticscholar.org'],
  arxiv: ['export.arxiv.org'],
  crossref: ['api.crossref.org'],
  nasa: ['api.nasa.gov'],
  nasa_gibs: ['gibs.earthdata.nasa.gov'],
  uspto: ['api.uspto.gov'],
  courtlistener: ['www.courtlistener.com'],
  internet_archive: ['archive.org', 'ia.us.archive.org'],
  wayback: ['web.archive.org'],
  world_bank_indicators: ['api.worldbank.org'],
  world_bank_data_catalog: ['datacatalogapi.worldbank.org'],
  world_bank_projects: ['search.worldbank.org'],
  world_bank_finances: ['finances.worldbank.org'],
  world_bank_climate: ['climateknowledgeportal.worldbank.org', 'climatedataapi.worldbank.org'],
  imf_sdmx: ['api.imf.org', 'dataservices.imf.org'],
  usgs_water: ['api.waterdata.usgs.gov'],
  usgs_earthquake: ['earthquake.usgs.gov'],
  usgs_earthquake_feed: ['earthquake.usgs.gov'],
  usgs_national_map: ['tnmaccess.nationalmap.gov'],
  usgs_sciencebase: ['www.sciencebase.gov'],
  library_of_congress: ['www.loc.gov'],
  wikidata: ['www.wikidata.org', 'query.wikidata.org'],
  common_crawl: ['index.commoncrawl.org', 'data.commoncrawl.org'],
  mitre_attack: ['attack-taxii.mitre.org'],
  gleif: ['api.gleif.org'],
  osv_dev: ['api.osv.dev'],
  nvd: ['services.nvd.nist.gov'],
  cisa_kev: ['www.cisa.gov'],
  osm_overpass: ['overpass-api.de'],
  geonames: ['secure.geonames.org'],
  eurostat: ['ec.europa.eu'],
  wikipedia: ['en.wikipedia.org'],
  europe_pmc: ['www.ebi.ac.uk'],
  clinicaltrials_gov: ['clinicaltrials.gov'],
  openfda: ['api.fda.gov'],
  pubchem: ['pubchem.ncbi.nlm.nih.gov'],
  gbif: ['api.gbif.org'],
  uniprot: ['rest.uniprot.org'],
  us_census: ['api.census.gov'],
  congress_gov: ['api.congress.gov'],
  govinfo: ['api.govinfo.gov'],
  sec_edgar: ['efts.sec.gov', 'data.sec.gov'],
  orcid: ['orcid.org', 'pub.orcid.org'],
  reliefweb: ['api.reliefweb.int'],
  ensembl: ['rest.ensembl.org'],
  rcsb_pdb: ['search.rcsb.org', 'data.rcsb.org'],
  string_db: ['string-db.org'],
  gnomad: ['gnomad.broadinstitute.org'],
  ebi_ols: ['www.ebi.ac.uk'],
  medlineplus: ['wsearch.nlm.nih.gov'],
  who_gho: ['ghoapi.azureedge.net'],
  rxnorm: ['rxnav.nlm.nih.gov'],
  dailymed: ['dailymed.nlm.nih.gov'],
  chembl: ['www.ebi.ac.uk'],
  open_targets: ['api.platform.opentargets.org'],
  inaturalist: ['api.inaturalist.org'],
  obis: ['api.obis.org'],
  worms: ['www.marinespecies.org'],
  itis: ['www.itis.gov'],
  pypi: ['pypi.org'],
  npm_registry: ['registry.npmjs.org'],
  crates_io: ['crates.io'],
  rubygems: ['rubygems.org'],
  maven_central: ['search.maven.org'],
  github_advisory: ['api.github.com'],
  endoflife: ['endoflife.date'],
  epss: ['api.first.org'],
  alienvault_otx: ['otx.alienvault.com'],
  malwarebazaar: ['mb-api.abuse.ch'],
  threatfox: ['threatfox-api.abuse.ch'],
  urlhaus: ['urlhaus-api.abuse.ch'],
  federal_register: ['www.federalregister.gov'],
  usaspending: ['api.usaspending.gov'],
  uk_legislation: ['www.legislation.gov.uk'],
  opensanctions: ['api.opensanctions.org'],
  companies_house: ['api.company-information.service.gov.uk'],
  ecb_sdw: ['data-api.ecb.europa.eu'],
  bank_of_canada: ['www.bankofcanada.ca'],
  bis_stats: ['stats.bis.org'],
  eia: ['api.eia.gov'],
  statcan_wds: ['www150.statcan.gc.ca'],
  uk_ons: ['api.beta.ons.gov.uk'],
  insee_melodi: ['api.insee.fr'],
  open_meteo: ['api.open-meteo.com'],
  noaa_cdo: ['www.ncei.noaa.gov'],
  met_no: ['api.met.no'],
  noaa_swpc: ['services.swpc.noaa.gov'],
  nominatim: ['nominatim.openstreetmap.org'],
  nasa_cmr: ['cmr.earthdata.nasa.gov'],
  copernicus_dataspace: ['catalogue.dataspace.copernicus.eu'],
  opentopography: ['portal.opentopography.org'],
  celestrak: ['celestrak.org'],
  jpl_horizons: ['ssd.jpl.nasa.gov'],
  jpl_sbdb: ['ssd-api.jpl.nasa.gov'],
  nasa_exoplanet_archive: ['exoplanetarchive.ipac.caltech.edu'],
  simbad: ['simbad.cds.unistra.fr'],
  mast: ['mast.stsci.edu'],
  ror: ['api.ror.org'],
  opencitations: ['api.opencitations.net'],
  biorxiv_medrxiv: ['api.biorxiv.org'],
  hal: ['api.archives-ouvertes.fr'],
  base_search: ['api.base-search.net'],
  inspire_hep: ['inspirehep.net'],
  hepdata: ['www.hepdata.net'],
  zbmath: ['api.zbmath.org'],
  oeis: ['oeis.org'],
  nasa_ads: ['api.adsabs.harvard.edu'],
  epo_ops: ['ops.epo.org'],
  materials_project: ['api.materialsproject.org'],
  oqmd: ['oqmd.org'],
  aflow: ['aflow.org'],
  pleiades: ['pleiades.stoa.org'],
  idai_gazetteer: ['gazetteer.dainst.org'],
  edh: ['edh.ub.uni-heidelberg.de'],
  nomisma: ['www.nomisma.org'],
  whg: ['whgazetteer.org'],
  open_context: ['opencontext.org'],
  cdli: ['cdli.earth'],
  ehri: ['portal.ehri-project.eu'],
  art_institute_chicago: ['api.artic.edu'],
  cleveland_museum: ['openaccess-api.clevelandart.org'],
  va_museum: ['api.vam.ac.uk'],
  smk: ['api.smk.dk'],
  open_library: ['openlibrary.org'],
  unhcr_data: ['api.unhcr.org'],
  ocha_fts: ['api.hpc.tools'],
  opensky: ['opensky-network.org'],
  cbdb: ['cbdb.fas.harvard.edu'],
  eclac_cepalstat: ['api-cepalstat.cepal.org'],
  oecd_data_explorer: ['sdmx.oecd.org'],
  un_sdg: ['unstats.un.org'],
  unesco_uis: ['api.uis.unesco.org'],
  idb_open_data: ['data.iadb.org'],
  iati_datastore: ['api.iatistandard.org'],
  debian_sources: ['sources.debian.org'],
  ietf_datatracker: ['datatracker.ietf.org'],
  wikimedia_commons: ['commons.wikimedia.org'],
  dbpedia: ['lookup.dbpedia.org'],
  dblp: ['dblp.org'],
  mozilla_bugzilla: ['bugzilla.mozilla.org'],
  msrc_cvrf: ['api.msrc.microsoft.com'],
  isni: ['isni.oclc.org'],
  lobid_gnd: ['lobid.org'],
  factgrid: ['database.factgrid.de'],
  ubuntu_security: ['ubuntu.com'],
  redhat_security_data: ['access.redhat.com'],
  cve_org: ['cveawg.mitre.org'],
  conceptnet: ['api.conceptnet.io'],
  ena_portal: ['www.ebi.ac.uk'],
  ncbi_datasets: ['api.ncbi.nlm.nih.gov'],
  alphafold_db: ['alphafold.ebi.ac.uk'],
  reactome: ['reactome.org'],
  intact: ['www.ebi.ac.uk'],
  orphadata: ['api.orphadata.com'],
  guide_to_pharmacology: ['www.guidetopharmacology.org'],
  clinpgx: ['api.clinpgx.org'],
  pbdb: ['paleobiodb.org'],
  nws_weather: ['api.weather.gov'],
  japan_egov_hourei: ['laws.e-gov.go.jp'],
  australia_frl: ['api.prod.legislation.gov.au'],
  uk_gazette: ['www.thegazette.co.uk'],
  eu_ted: ['api.ted.europa.eu'],
  brazil_transparencia: ['api.portaldatransparencia.gov.br'],
  sidra_brazil: ['servicodados.ibge.gov.br'],
  cbs_statline: ['opendata.cbs.nl'],
  gaia_archive: ['gea.esac.esa.int'],
  sdss_skyserver: ['skyserver.sdss.org'],
  apache_jira: ['issues.apache.org'],
  health_canada_dpd: ['health-products.canada.ca'],
  bindingdb: ['bindingdb.org'],
  kegg: ['rest.kegg.jp'],
  metabolights: ['www.ebi.ac.uk'],
  pride_archive: ['www.ebi.ac.uk'],
  libris_xl: ['libris.kb.se'],
  nasjonalbiblioteket: ['api.nb.no'],
  nara_catalog: ['catalog.archives.gov'],
  jstage: ['api.jstage.jst.go.jp'],
  cinii: ['cir.nii.ac.jp'],
  musicbrainz: ['musicbrainz.org'],
  gitlab_api: ['gitlab.com'],
  codeberg: ['codeberg.org'],
  software_heritage: ['archive.softwareheritage.org'],
  launchpad: ['api.launchpad.net'],
  metacpan: ['fastapi.metacpan.org'],
  ecosystems: ['packages.ecosyste.ms'],
  deps_dev: ['api.deps.dev'],
  homebrew: ['formulae.brew.sh'],
  mdn_web_docs: ['developer.mozilla.org'],
  rosetta_code: ['rosettacode.org'],
  greynoise: ['api.greynoise.io'],
  phishstats: ['api.phishstats.info'],
  virustotal: ['www.virustotal.com'],
  abuseipdb: ['api.abuseipdb.com'],
  hybrid_analysis: ['hybrid-analysis.com'],
  ontobee: ['sparql.hegroup.org'],
  umls: ['uts-ws.nlm.nih.gov'],
  loinc_fhir: ['fhir.loinc.org'],
  wikipathways: ['sparql.wikipathways.org'],
  cellosaurus: ['api.cellosaurus.org'],
  metabolomics_workbench: ['www.metabolomicsworkbench.org'],
  npatlas: ['www.npatlas.org'],
  wellcome_collection: ['api.wellcomecollection.org'],
  bhl: ['www.biodiversitylibrary.org'],
  google_kg_search: ['kgsearch.googleapis.com'],
  merriam_webster: ['www.dictionaryapi.com'],
  brave_search: ['api.search.brave.com'],
  checklistbank: ['api.checklistbank.org'],
  eol: ['eol.org'],
  globi: ['api.globalbioticinteractions.org'],
  mushroom_observer: ['mushroomobserver.org'],
  arctic_data_center: ['arcticdata.io'],
  cbeta: ['cbdata.dila.edu.tw'],
  ebl: ['www.ebl.lmu.de'],
  mercado_publico: ['api.mercadopublico.cl'],
  inpe_bdc: ['data.inpe.br'],
  pdok: ['api.pdok.nl'],
  satnogs: ['db.satnogs.org'],
  nomad_repository: ['nomad-lab.eu'],
  kramerius: ['kramerius5.nkp.cz'],
  bdl_poland: ['bdl.stat.gov.pl'],
  israel_cbs: ['api.cbs.gov.il'],
  nomis_uk: ['www.nomisweb.co.uk'],
  abs_australia: ['data.api.abs.gov.au'],
  argentina_series: ['apis.datos.gob.ar'],
  data_gov_my: ['api.data.gov.my'],
  datos_abiertos_colombia: ['api.us.socrata.com'],
  ine_tempus3: ['servicios.ine.es'],
  singstat: ['tablebuilder.singstat.gov.sg'],
  usgs_m2m: ['m2m.cronus.usgs.gov'],
  n2yo: ['api.n2yo.com'],
  ariadne_portal: ['portal.ariadne-infrastructure.eu'],
  ohm_overpass: ['overpass-api.openhistoricalmap.org'],
  stack_exchange: ['api.stackexchange.com'],
  ecmwf_cds: ['cds.climate.copernicus.eu'],
  met_office_datahub: ['data.hub.api.metoffice.gov.uk'],
  ndl_search: ['ndlsearch.ndl.go.jp'],
  swisscovery: ['swisscovery.slsp.ch'],
  yago: ['yago-knowledge.org'],
  data_commons: ['api.datacommons.org'],
  econstor: ['www.econstor.eu'],
  w3c_api: ['api.w3.org'],
  wto_timeseries: ['api.wto.org'],
  e_stat_japan: ['api.e-stat.go.jp'],
  scb_sweden: ['api.scb.se'],
  ssb_norway: ['data.ssb.no'],
  statfin_finland: ['statfin.stat.fi'],
  statistics_denmark: ['api.statbank.dk'],
  un_desa_population: ['population.un.org'],
  nhc_current_storms: ['www.nhc.noaa.gov'],
  nasa_eonet: ['eonet.gsfc.nasa.gov'],
  tsunami_gov: ['www.tsunami.gov'],
}

export function isAllowedHost(provider: ResearchProviderId, hostname: string): boolean {
  const allowed = RESEARCH_PROVIDER_HOST_ALLOWLIST[provider] ?? []
  return allowed.some(host => hostname.toLowerCase() === host.toLowerCase())
}

/** Validates a URL is https and its host is on the given provider's allowlist. Throws otherwise. */
export function assertAllowedProviderUrl(provider: ResearchProviderId, url: string): URL {
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    throw new Error(`Invalid URL for provider ${provider}`)
  }
  if (parsed.protocol !== 'https:') {
    throw new Error(`Blocked non-HTTPS URL for provider ${provider}`)
  }
  if (!isAllowedHost(provider, parsed.hostname)) {
    throw new Error(`Blocked host "${parsed.hostname}" for provider ${provider}: not on the official-host allowlist`)
  }
  return parsed
}
