'use client'
import { useState } from 'react'
import type { SettlementRecord } from '@/lib/settlement-intelligence/types'
const label=(value:string)=>value.replace(/_/g,' ')
function Badge({value}:{value:string}){const tone=/VERIFIED|NO_DOCUMENTATION|NOT_REQUIRED/.test(value)?'border-emerald-400/40 text-emerald-200':/EXPIRED|CONFLICT|UNAVAILABLE|REQUIRED/.test(value)?'border-amber-400/40 text-amber-200':'border-cyan-400/40 text-cyan-200';return <span className={`rounded-sm border px-2 py-1 text-[9px] font-bold uppercase tracking-widest ${tone}`}>{label(value)}</span>}
export function SettlementIntelligencePanel({initialRecords}:{initialRecords:SettlementRecord[]}){
  const [records,setRecords]=useState(initialRecords),[message,setMessage]=useState<string|null>(null),[refreshing,setRefreshing]=useState(false)
  const refresh=async()=>{setRefreshing(true);setMessage('Resolving live listings against official settlement sources…');try{const response=await fetch('/api/settlement-intelligence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'REFRESH'})});const result=await response.json() as {records?:SettlementRecord[];error?:string};if(response.ok&&result.records){setRecords(result.records);setMessage(`Live refresh complete: ${result.records.filter(item=>item.officialSourceState==='OFFICIAL_SOURCE_VERIFIED').length} officially verified. No claim submitted. No external notification sent.`)}else setMessage(result.error??'Live refresh failed.')}finally{setRefreshing(false)}}
  return <section className="mt-8 rounded-sm border border-violet-400/25 bg-slate-950/90 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-violet-300">Settlement Intelligence</p><h2 className="mt-2 text-xl text-white">Official-source claim radar</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-slate-400">Discovery listings are leads only. Verification requires identity-matched official terms. Eligibility answers, attestations, signatures, and submission remain under Commander control.</p></div><button type="button" onClick={()=>void refresh()} disabled={refreshing} className="rounded-sm border border-violet-400/40 bg-violet-400/10 px-4 py-2.5 text-[10px] font-bold uppercase tracking-widest text-violet-100 disabled:opacity-40">{refreshing?'Resolving…':'Refresh live settlements'}</button></div>{message?<p role="status" className="mt-3 text-xs text-cyan-200">{message}</p>:null}<div className="mt-5 flex flex-wrap gap-2"><Badge value="SESSION_ONLY"/><Badge value="NO_EXTERNAL_DELIVERY"/><Badge value="NO_CLAIM_SUBMITTED"/></div>
    {records.length?<div className="mt-5 grid gap-4 lg:grid-cols-2">{records.map(record=><article key={record.id} className="rounded-sm border border-white/10 bg-black/25 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold text-white">{record.name}</h3><Badge value={record.priority}/></div><div className="mt-3 flex flex-wrap gap-2"><Badge value={record.officialSourceState}/><Badge value={record.terms.documentationRequirement}/><Badge value={record.deadlineState}/></div><dl className="mt-4 space-y-2 text-xs"><div><dt className="text-slate-500">Official deadline</dt><dd className="text-slate-200">{record.terms.claimDeadline??'Unknown'}</dd></div><div><dt className="text-slate-500">Potential benefit</dt><dd className="text-slate-200">{record.terms.estimatedBenefit??'Not officially stated'}</dd></div><div><dt className="text-slate-500">Eligibility</dt><dd className="text-amber-200">{label(record.eligibilityState)}</dd></div></dl>{record.eligibilityQuestions.length?<div className="mt-4 rounded border border-amber-400/20 p-3"><p className="text-[9px] font-bold uppercase tracking-widest text-amber-300">Commander facts required</p><ul className="mt-2 space-y-1 text-xs text-slate-300">{record.eligibilityQuestions.map(question=><li key={question.id}>• {question.prompt}</li>)}</ul></div>:null}<div className="mt-4 flex flex-wrap gap-2">{record.terms.claimFormUrl?<a href={record.terms.claimFormUrl} target="_blank" rel="noreferrer" className="rounded border border-cyan-400/30 px-3 py-2 text-[10px] uppercase text-cyan-200">Official claim page</a>:null}{record.officialUrl?<a href={record.officialUrl} target="_blank" rel="noreferrer" className="rounded border border-white/15 px-3 py-2 text-[10px] uppercase text-slate-300">Official source</a>:null}</div><p className="mt-3 text-[9px] font-bold uppercase tracking-widest text-rose-200">No claim has been submitted.</p></article>)}</div>:<p className="mt-5 rounded border border-slate-700 p-4 text-sm text-slate-400">No session settlement records yet. Run a live refresh to discover and independently verify current opportunities.</p>}
  </section>
}
