import type { BrainCandidateMetadata } from './types'

export const BRAIN_CANDIDATE_REGISTRY: BrainCandidateMetadata[] = [
  {
    candidateId: 'static-council-rules',
    providerId: 'war-room-static',
    modelId: null,
    providerFamily: 'static',
    registryOrder: 0,
    baseFitScore: 0.55,
    baseCostScore: 1,
    baseLatencyScore: 1,
    baseReliabilityScore: 0.95,
    basePrivacyScore: 1,
    baseCapabilityScore: 0.35,
    reasoningStyles: ['risk', 'synthesis'],
    supportsLargeContext: false,
    supportsLiveResearch: false,
    supportsToolUse: false,
    hasCachedLocalResearch: true,
    isPremium: false,
    isExternal: false,
    isCostly: false,
    riskLevel: 'low',
    baseStrengths: ['No paid provider needed', 'Highest privacy posture', 'Fast deterministic rule application'],
    baseWeaknesses: ['No generative reasoning', 'Cannot perform live research'],
  },
  {
    candidateId: 'local-llama-general',
    providerId: 'local-ollama',
    modelId: 'llama3.2:3b',
    providerFamily: 'local',
    registryOrder: 1,
    baseFitScore: 0.62,
    baseCostScore: 0.95,
    baseLatencyScore: 0.72,
    baseReliabilityScore: 0.72,
    basePrivacyScore: 0.95,
    baseCapabilityScore: 0.55,
    reasoningStyles: ['synthesis', 'strategic', 'coding'],
    supportsLargeContext: false,
    supportsLiveResearch: false,
    supportsToolUse: false,
    hasCachedLocalResearch: false,
    isPremium: false,
    isExternal: false,
    isCostly: false,
    riskLevel: 'low',
    baseStrengths: ['Local candidate', 'Low cost', 'Good privacy posture'],
    baseWeaknesses: ['Limited context window', 'No live research support in this phase'],
  },
  {
    candidateId: 'anthropic-architectural',
    providerId: 'anthropic',
    modelId: null,
    providerFamily: 'anthropic',
    registryOrder: 2,
    baseFitScore: 0.82,
    baseCostScore: 0.55,
    baseLatencyScore: 0.62,
    baseReliabilityScore: 0.82,
    basePrivacyScore: 0.45,
    baseCapabilityScore: 0.88,
    reasoningStyles: ['architectural', 'risk', 'synthesis'],
    supportsLargeContext: true,
    supportsLiveResearch: false,
    supportsToolUse: true,
    hasCachedLocalResearch: false,
    isPremium: true,
    isExternal: true,
    isCostly: true,
    riskLevel: 'medium',
    baseStrengths: ['Strong architectural reasoning', 'Strong review and risk analysis fit'],
    baseWeaknesses: ['External premium provider', 'No native live research assumption in this phase'],
  },
  {
    candidateId: 'openai-strategic',
    providerId: 'openai',
    modelId: null,
    providerFamily: 'openai',
    registryOrder: 3,
    baseFitScore: 0.82,
    baseCostScore: 0.6,
    baseLatencyScore: 0.7,
    baseReliabilityScore: 0.82,
    basePrivacyScore: 0.45,
    baseCapabilityScore: 0.84,
    reasoningStyles: ['strategic', 'synthesis', 'coding'],
    supportsLargeContext: true,
    supportsLiveResearch: false,
    supportsToolUse: true,
    hasCachedLocalResearch: false,
    isPremium: true,
    isExternal: true,
    isCostly: true,
    riskLevel: 'medium',
    baseStrengths: ['Strong strategy and synthesis fit', 'Strong tool orchestration fit'],
    baseWeaknesses: ['External premium provider', 'No live research call allowed in this phase'],
  },
  {
    candidateId: 'google-librarian',
    providerId: 'google',
    modelId: null,
    providerFamily: 'google',
    registryOrder: 4,
    baseFitScore: 0.78,
    baseCostScore: 0.62,
    baseLatencyScore: 0.66,
    baseReliabilityScore: 0.78,
    basePrivacyScore: 0.45,
    baseCapabilityScore: 0.86,
    reasoningStyles: ['research', 'synthesis'],
    supportsLargeContext: true,
    supportsLiveResearch: false,
    supportsToolUse: true,
    hasCachedLocalResearch: false,
    isPremium: true,
    isExternal: true,
    isCostly: true,
    riskLevel: 'medium',
    baseStrengths: ['Strong large-context research review fit', 'Strong pattern and cross-reference fit'],
    baseWeaknesses: ['External premium provider', 'Live research requires a later execution layer'],
  },
  {
    candidateId: 'xai-scout',
    providerId: 'xai',
    modelId: null,
    providerFamily: 'xai',
    registryOrder: 5,
    baseFitScore: 0.8,
    baseCostScore: 0.58,
    baseLatencyScore: 0.68,
    baseReliabilityScore: 0.75,
    basePrivacyScore: 0.4,
    baseCapabilityScore: 0.82,
    reasoningStyles: ['research', 'strategic'],
    supportsLargeContext: false,
    supportsLiveResearch: true,
    supportsToolUse: true,
    hasCachedLocalResearch: false,
    isPremium: true,
    isExternal: true,
    isCostly: true,
    riskLevel: 'medium',
    baseStrengths: ['Strong current-signal and live-awareness fit', 'Live research capable candidate metadata'],
    baseWeaknesses: ['External premium provider', 'Provider is not called in this phase'],
  },
  {
    candidateId: 'moonshot-engineer',
    providerId: 'moonshot',
    modelId: null,
    providerFamily: 'moonshot',
    registryOrder: 6,
    baseFitScore: 0.74,
    baseCostScore: 0.68,
    baseLatencyScore: 0.64,
    baseReliabilityScore: 0.72,
    basePrivacyScore: 0.45,
    baseCapabilityScore: 0.78,
    reasoningStyles: ['coding', 'strategic'],
    supportsLargeContext: true,
    supportsLiveResearch: false,
    supportsToolUse: true,
    hasCachedLocalResearch: false,
    isPremium: false,
    isExternal: true,
    isCostly: false,
    riskLevel: 'medium',
    baseStrengths: ['Good implementation planning fit', 'Large-context candidate metadata'],
    baseWeaknesses: ['External provider', 'No live research assumption in this phase'],
  },
]
