/**
 * Dedicated AI/ML repository and official-docs registry for the Capability Atlas.
 * No model-weight downloads. No training. Metadata/source research only.
 */
import type { DiscoveryCandidate } from './discoveryCatalog'

export const AI_ML_REPOSITORY_REGISTRY: DiscoveryCandidate[] = [
  {
    sourceId: 'pytorch-github',
    title: 'PyTorch repository',
    url: 'https://github.com/pytorch/pytorch',
    sourceType: 'primary_repository',
    organization: 'PyTorch / Linux Foundation',
    license: 'BSD-3-Clause',
    version: null,
    authorityClass: 'PRIMARY',
    skillIds: ['ml.pytorch', 'ml.training', 'ml.training.memory'],
    notes: 'Official PyTorch source repository. Existence is not competence.',
  },
  {
    sourceId: 'tensorflow-docs',
    title: 'TensorFlow documentation',
    url: 'https://www.tensorflow.org/guide',
    sourceType: 'official_documentation',
    organization: 'Google / TensorFlow',
    license: 'Apache-2.0 (code); documentation as published',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.tensorflow', 'ml.training', 'ml.serving'],
    notes: 'Official TensorFlow guides.',
  },
  {
    sourceId: 'jax-docs',
    title: 'JAX documentation',
    url: 'https://docs.jax.dev/en/latest/',
    sourceType: 'official_documentation',
    organization: 'Google / JAX',
    license: 'Apache-2.0',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.jax', 'ml.training'],
    notes: 'Official JAX documentation.',
  },
  {
    sourceId: 'cuda-programming-guide',
    title: 'CUDA C++ Programming Guide',
    url: 'https://docs.nvidia.com/cuda/cuda-c-programming-guide/',
    sourceType: 'vendor_documentation',
    organization: 'NVIDIA',
    license: 'NVIDIA proprietary documentation',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.cuda', 'ml.cuda.kernel-debugging', 'performance.gpu-memory'],
    notes: 'Official CUDA programming guide. Documentation is not CUDA mastery.',
  },
  {
    sourceId: 'cuda-gdb-docs',
    title: 'CUDA-GDB',
    url: 'https://docs.nvidia.com/cuda/cuda-gdb/',
    sourceType: 'vendor_documentation',
    organization: 'NVIDIA',
    license: 'NVIDIA proprietary documentation',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.cuda.kernel-debugging', 'ml.cuda', 'debugging.runtime'],
    notes: 'Official CUDA-GDB debugger documentation.',
  },
  {
    sourceId: 'rocm-docs',
    title: 'AMD ROCm documentation',
    url: 'https://rocm.docs.amd.com/en/latest/',
    sourceType: 'vendor_documentation',
    organization: 'AMD',
    license: 'AMD documentation license',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.rocm', 'ml.cuda', 'performance.gpu-memory'],
    notes: 'Official ROCm stack documentation. Related to CUDA skills, not a substitute.',
  },
  {
    sourceId: 'huggingface-transformers-docs',
    title: 'Transformers documentation',
    url: 'https://huggingface.co/docs/transformers/index',
    sourceType: 'official_documentation',
    organization: 'Hugging Face',
    license: 'Apache-2.0 (library)',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.huggingface', 'ml.llm-systems', 'ml.tokenization'],
    notes: 'Official Transformers docs. No model weights downloaded.',
  },
  {
    sourceId: 'huggingface-hub',
    title: 'Hugging Face Hub',
    url: 'https://huggingface.co/docs/hub/index',
    sourceType: 'official_documentation',
    organization: 'Hugging Face',
    license: 'Apache-2.0 / Hub terms',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.huggingface', 'ml.datasets', 'ml.serving'],
    notes: 'Official Hub docs for models/datasets/spaces metadata.',
  },
  {
    sourceId: 'vllm-docs',
    title: 'vLLM documentation',
    url: 'https://docs.vllm.ai/en/latest/',
    sourceType: 'official_documentation',
    organization: 'vLLM project',
    license: 'Apache-2.0',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.vllm', 'ml.inference', 'ml.serving'],
    notes: 'Official vLLM inference engine documentation.',
  },
  {
    sourceId: 'vllm-github',
    title: 'vLLM repository',
    url: 'https://github.com/vllm-project/vllm',
    sourceType: 'primary_repository',
    organization: 'vLLM project',
    license: 'Apache-2.0',
    version: null,
    authorityClass: 'PRIMARY',
    skillIds: ['ml.vllm', 'ml.inference'],
    notes: 'Official vLLM repository. Clone-and-run is forbidden in this research phase.',
  },
  {
    sourceId: 'llama-cpp-github',
    title: 'llama.cpp repository',
    url: 'https://github.com/ggerganov/llama.cpp',
    sourceType: 'primary_repository',
    organization: 'ggerganov / llama.cpp',
    license: 'MIT',
    version: null,
    authorityClass: 'PRIMARY',
    skillIds: ['ml.llama-cpp', 'ml.inference', 'ml.quantization'],
    notes: 'Official llama.cpp repository (GGUF inference). No weights downloaded.',
  },
  {
    sourceId: 'onnx-docs',
    title: 'ONNX documentation',
    url: 'https://onnx.ai/onnx/',
    sourceType: 'official_documentation',
    organization: 'LF AI & Data / ONNX',
    license: 'Apache-2.0',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.onnx', 'ml.model-optimization', 'ml.serving'],
    notes: 'Official ONNX format and operator documentation.',
  },
  {
    sourceId: 'onnxruntime-docs',
    title: 'ONNX Runtime docs',
    url: 'https://onnxruntime.ai/docs/',
    sourceType: 'official_documentation',
    organization: 'Microsoft / ONNX Runtime',
    license: 'MIT',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['ml.onnx', 'ml.inference', 'ml.serving'],
    notes: 'Official ONNX Runtime inference documentation.',
  },
]
