import { existsSync } from 'node:fs'
import path from 'node:path'
import { resolveRepoRoot } from '@/lib/repo/paths'
import { createSourceRecord } from './sources'
import { createRelationship } from './graph'
import type { SkillRecord, SourceRecord, SkillRelationship } from './types'

function repoFile(rel: string): string | null {
  const abs = path.join(resolveRepoRoot(), rel)
  return existsSync(abs) ? rel : null
}

function existing(files: string[]): string[] {
  return files.map(repoFile).filter((item): item is string => Boolean(item))
}

function skill(partial: Omit<SkillRecord, 'capabilityStatus' | 'confidence' | 'lifecycle' | 'version' | 'unsupportedReason' | 'lastSourceVerified' | 'lastCapabilityEvaluated'> & {
  lastSourceVerified?: string | null
}): SkillRecord {
  const implementationFiles = existing(partial.evidence.implementationFiles)
  const proofFiles = existing(partial.evidence.proofFiles)
  const validators = existing(partial.evidence.validators)
  return {
    ...partial,
    version: 1,
    lifecycle: 'CURRENT',
    capabilityStatus: 'DISCOVERED',
    confidence: 'none',
    unsupportedReason: null,
    lastSourceVerified: partial.lastSourceVerified ?? null,
    lastCapabilityEvaluated: null,
    productionProofMissions: [],
    evidence: {
      ...partial.evidence,
      implementationFiles,
      proofFiles,
      validators,
      notes: implementationFiles.length
        ? `${partial.evidence.notes} Evidence files verified present in this repository.`
        : `${partial.evidence.notes} Implementation files missing; skill not elevated.`,
    },
    supportedToolBrokerTools: implementationFiles.length ? partial.supportedToolBrokerTools : [],
  }
}

export function seedOfficialSources(): SourceRecord[] {
  const rows: Array<Parameters<typeof createSourceRecord>[0]> = [
    { sourceId: 'ts-handbook', title: 'TypeScript Handbook', sourceUrl: 'https://www.typescriptlang.org/docs/handbook/intro.html', sourceType: 'official_documentation', organization: 'Microsoft', license: 'Apache-2.0', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['software.languages.typescript'], notes: 'Official language documentation.' },
    { sourceId: 'react-docs', title: 'React Documentation', sourceUrl: 'https://react.dev/learn', sourceType: 'official_documentation', organization: 'Meta Open Source', license: 'CC-BY-4.0', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['frontend.react'], notes: 'Official React docs.' },
    { sourceId: 'nextjs-docs', title: 'Next.js Documentation', sourceUrl: 'https://nextjs.org/docs', sourceType: 'official_documentation', organization: 'Vercel', license: 'MIT', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['frontend.nextjs'], notes: 'Official Next.js docs.' },
    { sourceId: 'electron-docs', title: 'Electron Documentation', sourceUrl: 'https://www.electronjs.org/docs/latest', sourceType: 'official_documentation', organization: 'OpenJS Foundation', license: 'MIT', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['desktop.electron'], notes: 'Official Electron docs.' },
    { sourceId: 'playwright-docs', title: 'Playwright Documentation', sourceUrl: 'https://playwright.dev/docs/intro', sourceType: 'official_documentation', organization: 'Microsoft', license: 'Apache-2.0', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['testing.browser-automation', 'foundry.browser-playwright'], notes: 'Official Playwright docs.' },
    { sourceId: 'mdn-web', title: 'MDN Web Docs', sourceUrl: 'https://developer.mozilla.org/en-US/docs/Web', sourceType: 'official_documentation', organization: 'Mozilla', license: 'CC-BY-SA-2.5', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['frontend.html', 'frontend.css', 'frontend.browser-apis', 'networking.http'], notes: 'Official web platform documentation.' },
    { sourceId: 'nodejs-docs', title: 'Node.js Documentation', sourceUrl: 'https://nodejs.org/docs/latest/api/', sourceType: 'official_documentation', organization: 'OpenJS Foundation', license: 'MIT', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['software.languages.javascript', 'software.languages.typescript'], notes: 'Official Node.js API docs.' },
    { sourceId: 'postgres-docs', title: 'PostgreSQL Documentation', sourceUrl: 'https://www.postgresql.org/docs/current/', sourceType: 'official_documentation', organization: 'PostgreSQL Global Development Group', license: 'PostgreSQL', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['database.postgresql', 'database.query-optimization', 'database.indexing', 'database.transactions'], notes: 'Official PostgreSQL docs.' },
    { sourceId: 'kernel-docs', title: 'Linux Kernel Documentation', sourceUrl: 'https://www.kernel.org/doc/html/latest/', sourceType: 'kernel_documentation', organization: 'kernel.org', license: 'GPL-2.0', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'PRIMARY', skillIds: ['kernel.architecture', 'kernel.device-drivers', 'kernel.module-build', 'os.linux'], notes: 'Official kernel documentation.' },
    { sourceId: 'rust-book', title: 'The Rust Programming Language', sourceUrl: 'https://doc.rust-lang.org/book/', sourceType: 'official_documentation', organization: 'Rust Project', license: 'Apache-2.0 / MIT', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['software.languages.rust'], notes: 'Official Rust book.' },
    { sourceId: 'cuda-docs', title: 'CUDA Toolkit Documentation', sourceUrl: 'https://docs.nvidia.com/cuda/', sourceType: 'vendor_documentation', organization: 'NVIDIA', license: 'NVIDIA proprietary documentation', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['ml.cuda', 'performance.gpu-memory'], notes: 'Official CUDA toolkit docs.' },
    { sourceId: 'pytorch-docs', title: 'PyTorch Documentation', sourceUrl: 'https://pytorch.org/docs/stable/index.html', sourceType: 'official_documentation', organization: 'Linux Foundation / PyTorch', license: 'BSD-3-Clause', version: null, lastVerified: null, retrievedAt: null, authorityClass: 'OFFICIAL', skillIds: ['ml.pytorch', 'ml.training', 'ml.training.memory'], notes: 'Official PyTorch docs.' },
    { sourceId: 'earth-knowledge-software', title: 'Earth Knowledge Source Registry — Software & Coding', sourceUrl: 'repo:docs/research/earth-knowledge/earth_knowledge_source_registry.md', sourceType: 'major_community', organization: 'War Room OS research', license: 'War Room internal research', version: '2026', lastVerified: null, retrievedAt: null, authorityClass: 'MAJOR_COMMUNITY', skillIds: ['archaeology.unfamiliar-repositories'], notes: 'Existing War Room research catalog. Not a substitute for official specs.' },
  ]
  return rows.map(row => createSourceRecord(row))
}

export function buildSeedSkills(): SkillRecord[] {
  return [
    skill({
      skillId: 'software.languages.typescript',
      name: 'TypeScript',
      domain: 'software',
      subdomain: 'software.languages',
      description: 'TypeScript language engineering as used in War Room source.',
      capabilityClass: 'LANGUAGE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['node'],
      operatingSystems: ['linux'],
      tools: ['tsc'],
      officialSources: ['ts-handbook', 'nodejs-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['software.languages.javascript'],
      relatedSkills: ['frontend.react', 'frontend.nextjs'],
      requiredContext: ['repo typescriptconfig'],
      supportedToolBrokerTools: ['typecheck.run', 'code.symbol', 'code.refs'],
      validationMethods: ['pnpm exec tsc --noEmit', 'validate:foundry-engineering-depth'],
      knownFailureModes: ['config path alias mismatch', 'implicit any in untyped JS interop'],
      securityConsiderations: ['Do not disable typechecking to force a pass.'],
      governanceRequirements: ['Bounded edit only. Terra protected.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['LOCAL_MODEL_OK', 'FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: ['query:typescript owners'],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryCodeIntelligence.ts', 'lib/native-builder/foundryProtectedBindings.ts', 'tsconfig.json'],
        brokerTools: ['typecheck.run', 'code.symbol'],
        validators: ['lib/native-builder/foundryEngineeringDepth.validation.ts'],
        proofFiles: [],
        notes: 'Foundry uses TypeScript AST and tsc. Not claimed proven in this Atlas pass.',
      },
    }),
    skill({
      skillId: 'frontend.react',
      name: 'React',
      domain: 'frontend',
      subdomain: 'frontend.react',
      description: 'React UI engineering for War Room / Foundry Commander surfaces.',
      capabilityClass: 'FRAMEWORK',
      languages: ['typescript'],
      frameworks: ['react'],
      platforms: ['web', 'electron'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: ['react-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['software.languages.typescript', 'frontend.html'],
      relatedSkills: ['frontend.nextjs', 'frontend.accessibility'],
      requiredContext: ['components/war-room'],
      supportedToolBrokerTools: ['file.read', 'file.replace_unique', 'code.owners'],
      validationMethods: ['validate:foundry'],
      knownFailureModes: ['client component without use client', 'stale testid contracts'],
      securityConsiderations: ['Do not weaken trusted-desktop UI gates.'],
      governanceRequirements: ['Keep Commander homepage clean; Foundry Advanced stays gated.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['LOCAL_MODEL_OK', 'FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: ['feature:Foundry heading'],
      evidence: {
        implementationFiles: ['components/war-room/foundry/FoundryShell.tsx', 'components/war-room/foundry/FoundryOperationsPanel.tsx'],
        brokerTools: ['file.replace_unique', 'code.owners'],
        validators: ['lib/native-builder/foundry.validation.ts'],
        proofFiles: [],
        notes: 'Foundry UI is React 19. Status stays evidence-derived.',
      },
    }),
    skill({
      skillId: 'frontend.nextjs',
      name: 'Next.js',
      domain: 'frontend',
      subdomain: 'frontend.nextjs',
      description: 'Next.js App Router pages and API routes.',
      capabilityClass: 'FRAMEWORK',
      languages: ['typescript'],
      frameworks: ['nextjs', 'react'],
      platforms: ['web'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: ['nextjs-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['frontend.react', 'software.languages.typescript'],
      relatedSkills: ['backend.rest'],
      requiredContext: ['app/'],
      supportedToolBrokerTools: ['file.read', 'code.owners'],
      validationMethods: ['validate:foundry'],
      knownFailureModes: ['route handler runtime mismatch'],
      securityConsiderations: ['Never expose SUPABASE_SERVICE_ROLE_KEY to the client.'],
      governanceRequirements: ['No live deploy from Atlas tools.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['LOCAL_MODEL_OK'],
      engineeringMemoryLinks: ['query:foundry api routes'],
      evidence: {
        implementationFiles: ['app/war-room/engineering/page.tsx', 'app/api/foundry/missions/route.ts'],
        brokerTools: ['file.read'],
        validators: ['lib/native-builder/foundry.validation.ts'],
        proofFiles: [],
        notes: 'App Router is in use. Not automatically PRODUCTION_PROVEN.',
      },
    }),
    skill({
      skillId: 'desktop.electron',
      name: 'Electron',
      domain: 'desktop',
      subdomain: 'desktop.electron',
      description: 'Electron desktop shell for War Room.',
      capabilityClass: 'PLATFORM',
      languages: ['javascript'],
      frameworks: ['electron'],
      platforms: ['desktop'],
      operatingSystems: ['linux'],
      tools: ['electron-builder'],
      officialSources: ['electron-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['software.languages.javascript'],
      relatedSkills: ['foundry.computer-use-atspi', 'release.packaging'],
      requiredContext: ['desktop/src'],
      supportedToolBrokerTools: ['computer.windows', 'runtime.verify'],
      validationMethods: ['validate:trusted-desktop-auth'],
      knownFailureModes: ['trusted desktop auto-entry regression'],
      securityConsiderations: ['Do not weaken desktop trust proofs.'],
      governanceRequirements: ['Production activation stays lease-gated.'],
      localModelCompatibility: 'limited',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'SPECIALIST_TOOL_REQUIRED'],
      engineeringMemoryLinks: ['topic:trusted-desktop-auto-entry'],
      evidence: {
        implementationFiles: ['desktop/src/main.cjs', 'desktop/src/desktopTrust.cjs'],
        brokerTools: ['computer.windows', 'runtime.verify'],
        validators: ['lib/sovereign-runtime/local-ownership/trustedDesktop.validation.ts'],
        proofFiles: [],
        notes: 'Electron main process exists. Atlas does not re-run production proofs in this pass.',
      },
    }),
    skill({
      skillId: 'foundry.tool-broker-governance',
      name: 'Tool Broker Governance',
      domain: 'foundry',
      subdomain: 'foundry.tool-broker-governance',
      description: 'Governed tool dispatch, write-set, and mutating-path authorization.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: ['executeEngineerTool'],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['software.languages.typescript'],
      relatedSkills: ['foundry.bounded-edit', 'foundry.production-lease'],
      requiredContext: ['mission write set'],
      supportedToolBrokerTools: ['engineering.write_set_expand', 'engineering.boundary'],
      validationMethods: ['validate:foundry-pass014-write-set'],
      knownFailureModes: ['silent write-set expansion', 'Terra path mutation'],
      securityConsiderations: ['Terra and WRIM checkpoints are protected subsystems.'],
      governanceRequirements: ['No commit. No push. No live deploy from Atlas.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: ['query:write set'],
      evidence: {
        implementationFiles: ['lib/native-builder/engineerTools.ts', 'lib/native-builder/foundryMissionWriteSet.ts', 'lib/native-builder/foundryToolCatalog.ts'],
        brokerTools: ['engineering.write_set_expand', 'engineering.boundary'],
        validators: ['lib/native-builder/foundryPass014.writeSet.validation.ts'],
        proofFiles: ['lib/native-builder/foundryPass014.production.proof.ts'],
        notes: 'Implementation and validators exist. Proof files are candidate evidence, not auto-PROVEN.',
      },
    }),
    skill({
      skillId: 'foundry.code-intelligence',
      name: 'Code Intelligence',
      domain: 'foundry',
      subdomain: 'foundry.code-intelligence',
      description: 'AST ownership, symbol lookup, and reverse dependents.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: ['ts-handbook'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['compiler.ast.symbol-resolution', 'software.languages.typescript'],
      relatedSkills: ['archaeology.ownership-discovery', 'archaeology.dependency-mapping'],
      requiredContext: ['repo index'],
      supportedToolBrokerTools: ['code.owners', 'code.symbol', 'code.refs', 'code.dependents', 'code.impact'],
      validationMethods: ['validate:foundry-engineering-depth'],
      knownFailureModes: ['stale code-intelligence cache'],
      securityConsiderations: [],
      governanceRequirements: [],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'LOCAL_MODEL_OK'],
      engineeringMemoryLinks: ['query:owners'],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryCodeIntelligence.ts', 'lib/native-builder/foundryEngineeringDepth.ts'],
        brokerTools: ['code.owners', 'code.symbol', 'code.dependents'],
        validators: ['lib/native-builder/foundryEngineeringDepth.validation.ts'],
        proofFiles: [],
        notes: 'Code intelligence is implemented. Not marked PROVEN without a recorded passing evaluation in this registry.',
      },
    }),
    skill({
      skillId: 'compiler.ast.symbol-resolution',
      name: 'AST Symbol Resolution',
      domain: 'compiler',
      subdomain: 'compiler.ast',
      description: 'Resolve symbols and semantic bindings from TypeScript AST.',
      capabilityClass: 'COMPILER',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['node'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: ['ts-handbook'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['compiler.ast', 'software.languages.typescript'],
      relatedSkills: ['foundry.binding-protection'],
      requiredContext: [],
      supportedToolBrokerTools: ['code.symbol', 'code.refs'],
      validationMethods: ['validate:foundry-engineering-depth'],
      knownFailureModes: ['ambiguous match text'],
      securityConsiderations: [],
      governanceRequirements: [],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['LOCAL_MODEL_OK'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryCodeIntelligence.ts', 'lib/native-builder/foundryProtectedBindings.ts'],
        brokerTools: ['code.symbol'],
        validators: ['lib/native-builder/foundryEngineeringDepth.validation.ts'],
        proofFiles: [],
        notes: 'AST symbol tables exist for War Room TS. Not a general compiler backend.',
      },
    }),
    skill({
      skillId: 'foundry.engineering-memory',
      name: 'Engineering Memory',
      domain: 'foundry',
      subdomain: 'foundry.engineering-memory',
      description: 'Repo-specific verified facts. Separate from general Atlas skill knowledge.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: [],
      relatedSkills: ['archaeology.ownership-discovery'],
      requiredContext: ['current repo hashes'],
      supportedToolBrokerTools: ['engineering.memory_recall', 'engineering.memory_remember'],
      validationMethods: ['validate:foundry-engineering-depth'],
      knownFailureModes: ['stale file hash', 'memory treated as general skill docs'],
      securityConsiderations: ['Repo truth always wins over Atlas general knowledge.'],
      governanceRequirements: ['Do not copy repo ownership into general skill records.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'LOCAL_MODEL_OK'],
      engineeringMemoryLinks: ['bootstrap:PASS_007'],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryEngineeringMemory.ts'],
        brokerTools: ['engineering.memory_recall', 'engineering.memory_remember'],
        validators: ['lib/native-builder/foundryEngineeringDepth.validation.ts'],
        proofFiles: [],
        notes: 'Engineering Memory is implemented and bootstrapped. Atlas stores links, not repo facts.',
      },
    }),
    skill({
      skillId: 'foundry.bounded-edit',
      name: 'Bounded Edit',
      domain: 'foundry',
      subdomain: 'foundry.bounded-edit',
      description: 'Unique-anchor file.replace_unique with hash and uniqueness gates.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['foundry.tool-broker-governance'],
      relatedSkills: ['foundry.binding-protection'],
      requiredContext: ['baseline captured'],
      supportedToolBrokerTools: ['file.read', 'file.replace_unique'],
      validationMethods: ['validate:foundry-autonomous-engineering-depth-pass014'],
      knownFailureModes: ['MATCH_NOT_UNIQUE', 'STALE_FILE_HASH'],
      securityConsiderations: ['Anchors are locators, not authorization.'],
      governanceRequirements: ['Write set must include the path.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryBoundedEdit.ts', 'lib/native-builder/foundryEditAnchors.ts'],
        brokerTools: ['file.replace_unique', 'file.read'],
        validators: ['lib/native-builder/foundryAutonomousEngineeringDepth.pass014.validation.ts'],
        proofFiles: [],
        notes: 'Bounded edit is implemented. Not auto-PROVEN by this Atlas foundation.',
      },
    }),
    skill({
      skillId: 'foundry.binding-protection',
      name: 'Binding Protection',
      domain: 'foundry',
      subdomain: 'foundry.binding-protection',
      description: 'Protect semantic AST bindings during edits.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['compiler.ast.symbol-resolution'],
      relatedSkills: ['foundry.bounded-edit'],
      requiredContext: [],
      supportedToolBrokerTools: ['file.replace_unique', 'engineering.review'],
      validationMethods: ['validate:foundry-engineering-depth'],
      knownFailureModes: ['unprotected rename across files'],
      securityConsiderations: [],
      governanceRequirements: [],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryProtectedBindings.ts'],
        brokerTools: ['engineering.review'],
        validators: [],
        proofFiles: [],
        notes: 'Protected bindings module exists.',
      },
    }),
    skill({
      skillId: 'foundry.computer-use-atspi',
      name: 'Computer Use AT-SPI',
      domain: 'foundry',
      subdomain: 'foundry.computer-use-atspi',
      description: 'Semantic desktop computer use through AT-SPI.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['python', 'typescript'],
      frameworks: [],
      platforms: ['linux-desktop'],
      operatingSystems: ['linux'],
      tools: ['at-spi'],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['desktop.system-integration', 'os.linux'],
      relatedSkills: ['frontend.accessibility'],
      requiredContext: ['War Room window'],
      supportedToolBrokerTools: ['computer.find_control', 'computer.click_and_wait', 'computer.observe'],
      validationMethods: ['validate:foundry-semantic-computer-use', 'validate:foundry-pass011-computer-use'],
      knownFailureModes: ['HiDPI coordinate drift', 'AT-SPI action success without state change'],
      securityConsiderations: ['Coordinate fallback is last resort.'],
      governanceRequirements: ['Computer-use governance remains in foundryComputerUse.'],
      localModelCompatibility: 'limited',
      frontierModelCompatibility: 'recommended',
      selfHostable: true,
      modelRouting: ['SPECIALIST_TOOL_REQUIRED', 'FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: ['query:computer use'],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryComputerUse.ts', 'scripts/foundry/computer-use-backend.py'],
        brokerTools: ['computer.find_control', 'computer.click_and_wait'],
        validators: ['lib/native-builder/foundryPass011.computerUse.validation.ts'],
        proofFiles: ['lib/native-builder/foundryPass013.production.proof.ts'],
        notes: 'AT-SPI computer use is implemented. Candidate production proofs are not auto-applied.',
      },
    }),
    skill({
      skillId: 'foundry.browser-playwright',
      name: 'Browser Playwright',
      domain: 'foundry',
      subdomain: 'foundry.browser-playwright',
      description: 'Foundry-governed Playwright Chromium tools.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: ['playwright'],
      platforms: ['linux'],
      operatingSystems: ['linux'],
      tools: ['playwright'],
      officialSources: ['playwright-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['testing.browser-automation'],
      relatedSkills: ['debugging.browser'],
      requiredContext: ['allowlisted URLs'],
      supportedToolBrokerTools: ['browser.navigate', 'browser.inspect', 'browser.screenshot'],
      validationMethods: ['validate:foundry-cdp-governance'],
      knownFailureModes: ['private host navigation', 'CDP misuse'],
      securityConsiderations: ['Browser governance and CDP governance stay intact.'],
      governanceRequirements: ['No arbitrary internet from computer-use path.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryBrowserService.ts'],
        brokerTools: ['browser.navigate', 'browser.inspect'],
        validators: ['lib/native-builder/foundryCdpGovernance.validation.ts'],
        proofFiles: [],
        notes: 'Playwright service exists. Atlas does not claim E2E mastery of every site.',
      },
    }),
    skill({
      skillId: 'testing.targeted',
      name: 'Targeted Testing',
      domain: 'testing',
      subdomain: 'testing.targeted',
      description: 'Select relevant validate:* suites from ownership and impact.',
      capabilityClass: 'TESTING',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['foundry.code-intelligence'],
      relatedSkills: ['testing.regression'],
      requiredContext: ['package.json scripts'],
      supportedToolBrokerTools: ['test.list_suites', 'test.run', 'engineering.test_review'],
      validationMethods: ['validate:foundry-engineering-depth'],
      knownFailureModes: ['running unrelated :live suites'],
      securityConsiderations: [],
      governanceRequirements: ['test.run only accepts registered validate:* scripts.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'LOCAL_MODEL_OK'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/qualityTools.ts', 'lib/native-builder/foundryEngineeringDepth.ts'],
        brokerTools: ['test.run', 'test.list_suites'],
        validators: ['lib/native-builder/foundryEngineeringDepth.validation.ts'],
        proofFiles: [],
        notes: 'Targeted test selection is implemented.',
      },
    }),
    skill({
      skillId: 'systems.processes',
      name: 'Process Management',
      domain: 'systems',
      subdomain: 'systems.processes',
      description: 'Inspect and control local processes through Foundry tools.',
      capabilityClass: 'SYSTEMS',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['linux'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['os.linux'],
      relatedSkills: ['debugging.runtime'],
      requiredContext: [],
      supportedToolBrokerTools: ['process.list', 'process.inspect', 'process.start', 'process.stop', 'port.inspect'],
      validationMethods: [],
      knownFailureModes: ['killing unrelated PIDs'],
      securityConsiderations: ['Only owned processes for start/stop in mission scope.'],
      governanceRequirements: [],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'LOCAL_MODEL_OK'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/processInspector.ts', 'lib/native-builder/terminalExecutor.ts'],
        brokerTools: ['process.list', 'process.inspect'],
        validators: [],
        proofFiles: [],
        notes: 'Process inspection tools exist.',
      },
    }),
    skill({
      skillId: 'release.packaging',
      name: 'Packaging',
      domain: 'release',
      subdomain: 'release.packaging',
      description: 'Package exact War Room builds under shared lock.',
      capabilityClass: 'RELEASE',
      languages: ['typescript'],
      frameworks: ['electron-builder'],
      platforms: ['linux'],
      operatingSystems: ['linux'],
      tools: ['electron-builder'],
      officialSources: ['electron-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['desktop.electron'],
      relatedSkills: ['release.installers', 'release.production-activation'],
      requiredContext: ['completed exact build'],
      supportedToolBrokerTools: ['build.run', 'package.run'],
      validationMethods: [],
      knownFailureModes: ['packaging a dirty or unrelated tree'],
      securityConsiderations: ['Package only the exact current build.'],
      governanceRequirements: ['Production install remains commander-confirmed.'],
      localModelCompatibility: 'limited',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'SPECIALIST_TOOL_REQUIRED'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/packageTool.ts', 'lib/native-builder/qualityTools.ts'],
        brokerTools: ['build.run', 'package.run'],
        validators: [],
        proofFiles: ['lib/native-builder/foundryProductionToolchain.proof.ts'],
        notes: 'Packaging tools exist. Candidate production proof is not auto-applied.',
      },
    }),
    skill({
      skillId: 'release.production-activation',
      name: 'Production Activation',
      domain: 'release',
      subdomain: 'release.production-activation',
      description: 'Install and activate an exact production identity under lease.',
      capabilityClass: 'RELEASE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['linux'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['release.packaging', 'foundry.production-lease'],
      relatedSkills: ['release.rollback'],
      requiredContext: ['commanderConfirmed'],
      supportedToolBrokerTools: ['installer.install_production', 'installer.activate', 'runtime.verify'],
      validationMethods: ['validate:foundry-production-ownership'],
      knownFailureModes: ['activating without lease', 'identity mismatch'],
      securityConsiderations: ['Installed-runtime identity must match.'],
      governanceRequirements: ['Commander confirmation required. No Atlas auto-activate.'],
      localModelCompatibility: 'limited',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'SPECIALIST_TOOL_REQUIRED'],
      engineeringMemoryLinks: ['query:production activation authority'],
      evidence: {
        implementationFiles: ['lib/native-builder/installerTool.ts', 'lib/native-builder/foundryProductionLease.ts', 'lib/native-builder/foundryProductionOwnership.ts'],
        brokerTools: ['installer.activate', 'runtime.verify'],
        validators: ['lib/native-builder/foundryProductionOwnership.validation.ts'],
        proofFiles: ['lib/native-builder/foundryActivationAcceptance.proof.ts'],
        notes: 'Activation machinery exists. Not PRODUCTION_PROVEN in Atlas until evaluation is recorded.',
      },
    }),
    skill({
      skillId: 'foundry.production-lease',
      name: 'Production Lease',
      domain: 'foundry',
      subdomain: 'foundry.production-lease',
      description: 'Exclusive production lease and watchdog.',
      capabilityClass: 'FOUNDRY_NATIVE',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: [],
      relatedSkills: ['release.production-activation'],
      requiredContext: [],
      supportedToolBrokerTools: ['installer.active_status'],
      validationMethods: ['validate:foundry-production-lease-watchdog'],
      knownFailureModes: ['stale lease owner'],
      securityConsiderations: [],
      governanceRequirements: ['One production owner at a time.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryProductionLease.ts', 'lib/native-builder/foundryProductionLeaseWatchdog.ts'],
        brokerTools: ['installer.active_status'],
        validators: ['lib/native-builder/foundryProductionLeaseWatchdog.validation.ts'],
        proofFiles: [],
        notes: 'Lease + watchdog implemented.',
      },
    }),
    skill({
      skillId: 'testing.browser-automation',
      name: 'Browser Automation',
      domain: 'testing',
      subdomain: 'testing.browser-automation',
      description: 'Playwright-based browser automation.',
      capabilityClass: 'TESTING',
      languages: ['typescript'],
      frameworks: ['playwright'],
      platforms: ['linux'],
      operatingSystems: ['linux'],
      tools: ['playwright'],
      officialSources: ['playwright-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['frontend.browser-apis'],
      relatedSkills: ['foundry.browser-playwright'],
      requiredContext: [],
      supportedToolBrokerTools: ['browser.navigate', 'browser.inspect'],
      validationMethods: ['validate:foundry-cdp-governance'],
      knownFailureModes: [],
      securityConsiderations: [],
      governanceRequirements: [],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryBrowserService.ts'],
        brokerTools: ['browser.navigate'],
        validators: ['lib/native-builder/foundryCdpGovernance.validation.ts'],
        proofFiles: [],
        notes: 'Overlaps Foundry Playwright. General Cypress/Selenium are DISCOVERED only.',
      },
    }),
    skill({
      skillId: 'archaeology.ownership-discovery',
      name: 'Ownership Discovery',
      domain: 'archaeology',
      subdomain: 'archaeology.ownership-discovery',
      description: 'Map which files own a feature in an unfamiliar or large repo.',
      capabilityClass: 'ARCHAEOLOGY',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['war-room'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['foundry.code-intelligence'],
      relatedSkills: ['archaeology.dependency-mapping'],
      requiredContext: [],
      supportedToolBrokerTools: ['code.owners', 'code.roles'],
      validationMethods: ['validate:foundry-engineering-depth'],
      knownFailureModes: ['query too vague'],
      securityConsiderations: [],
      governanceRequirements: ['Repo memory wins over general skill text.'],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['FOUNDRY_NATIVE_PROVEN', 'LOCAL_MODEL_OK'],
      engineeringMemoryLinks: ['engineering.memory_recall'],
      evidence: {
        implementationFiles: ['lib/native-builder/foundryCodeIntelligence.ts'],
        brokerTools: ['code.owners'],
        validators: ['lib/native-builder/foundryEngineeringDepth.validation.ts'],
        proofFiles: [],
        notes: 'Ownership mapping is implemented for this repo.',
      },
    }),
    skill({
      skillId: 'backend.rest',
      name: 'REST',
      domain: 'backend',
      subdomain: 'backend.rest',
      description: 'HTTP JSON API routes in Next.js.',
      capabilityClass: 'BACKEND',
      languages: ['typescript'],
      frameworks: ['nextjs'],
      platforms: ['web'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: ['mdn-web', 'nextjs-docs'],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: ['networking.http', 'frontend.nextjs'],
      relatedSkills: ['backend.authentication'],
      requiredContext: ['app/api'],
      supportedToolBrokerTools: ['file.read', 'code.owners'],
      validationMethods: [],
      knownFailureModes: [],
      securityConsiderations: ['Keep service-role keys server-only.'],
      governanceRequirements: [],
      localModelCompatibility: 'ok',
      frontierModelCompatibility: 'ok',
      selfHostable: true,
      modelRouting: ['LOCAL_MODEL_OK'],
      engineeringMemoryLinks: [],
      evidence: {
        implementationFiles: ['app/api/foundry/missions/route.ts', 'app/api/foundry/operations/route.ts'],
        brokerTools: ['file.read'],
        validators: [],
        proofFiles: [],
        notes: 'REST route handlers exist. Not a generic API-platform mastery claim.',
      },
    }),
    skill({
      skillId: 'security.auth',
      name: 'Authentication',
      domain: 'security',
      subdomain: 'security.auth',
      description: 'Trusted-desktop and local session authentication as implemented.',
      capabilityClass: 'SECURITY',
      languages: ['typescript'],
      frameworks: [],
      platforms: ['linux-desktop'],
      operatingSystems: ['linux'],
      tools: [],
      officialSources: [],
      openSourceSources: [],
      referenceImplementations: [],
      prerequisiteSkills: [],
      relatedSkills: ['backend.authentication', 'desktop.electron'],
      requiredContext: [],
      supportedToolBrokerTools: ['engineering.review'],
      validationMethods: ['validate:trusted-desktop-auth'],
      knownFailureModes: ['weakening remote /login'],
      securityConsiderations: ['Never weaken trusted desktop auto-entry or remote login wall.'],
      governanceRequirements: ['Auth files are high-risk; require owner evidence.'],
      localModelCompatibility: 'limited',
      frontierModelCompatibility: 'recommended',
      selfHostable: true,
      modelRouting: ['FRONTIER_RECOMMENDED', 'FOUNDRY_NATIVE_PROVEN'],
      engineeringMemoryLinks: ['topic:trusted-desktop-auto-entry'],
      evidence: {
        implementationFiles: ['lib/sovereign-runtime/local-ownership/desktopTrust.ts', 'desktop/src/desktopTrust.cjs'],
        brokerTools: ['engineering.review'],
        validators: ['lib/sovereign-runtime/local-ownership/trustedDesktop.validation.ts'],
        proofFiles: [],
        notes: 'Local trusted-desktop auth exists. Generic OAuth/OIDC remains DISCOVERED.',
      },
    }),
  ]
}

export function seedRelationships(): SkillRelationship[] {
  const rows: Array<[string, Parameters<typeof createRelationship>[1], string, string]> = [
    ['software.languages.typescript', 'REQUIRES', 'software.languages.javascript', 'TS compiles to JS.'],
    ['frontend.react', 'REQUIRES', 'software.languages.typescript', 'War Room React is TypeScript.'],
    ['frontend.nextjs', 'REQUIRES', 'frontend.react', 'App Router UI is React.'],
    ['desktop.electron', 'RELATED_TO', 'foundry.computer-use-atspi', 'Desktop shell is the computer-use target.'],
    ['foundry.code-intelligence', 'SPECIALIZES', 'compiler.ast.symbol-resolution', 'Foundry AST index.'],
    ['foundry.bounded-edit', 'REQUIRES', 'foundry.tool-broker-governance', 'Edits go through the broker.'],
    ['foundry.binding-protection', 'REQUIRES', 'compiler.ast.symbol-resolution', 'Bindings come from AST.'],
    ['release.production-activation', 'REQUIRES', 'release.packaging', 'Activate packaged artifacts.'],
    ['release.production-activation', 'REQUIRES', 'foundry.production-lease', 'Lease gates production.'],
    ['kernel.device-drivers', 'REQUIRES', 'systems.memory', 'Drivers manipulate memory.'],
    ['kernel.device-drivers', 'REQUIRES', 'systems.interrupts', 'Drivers handle interrupts.'],
    ['kernel.device-drivers', 'REQUIRES', 'systems.concurrency', 'Drivers are concurrent.'],
    ['kernel.device-drivers', 'REQUIRES', 'software.languages.c', 'In-tree drivers are C.'],
    ['ml.training.memory', 'REQUIRES', 'ml.pytorch', 'WRIM training stack is PyTorch-shaped.'],
    ['ml.training.memory', 'REQUIRES', 'ml.cuda', 'GPU memory pressure is CUDA.'],
    ['ml.training.memory', 'RELATED_TO', 'performance.gpu-memory', 'OOM is a GPU memory failure.'],
    ['ml.cuda', 'RELATED_TO', 'debugging.runtime', 'CUDA OOM is a runtime failure.'],
    ['foundry.browser-playwright', 'SPECIALIZES', 'testing.browser-automation', 'Governed Playwright tools.'],
    ['foundry.engineering-memory', 'RELATED_TO', 'archaeology.ownership-discovery', 'Memory stores repo truth; Atlas stores general skill.'],
    ['testing.targeted', 'USES_TOOL', 'foundry.code-intelligence', 'Selection uses ownership.'],
  ]
  return rows.map(([from, kind, to, note]) => createRelationship(from, kind, to, note))
}
