/**
 * Primary operating-system documentation references for the Capability Atlas.
 * References and compact notes only — not full manual ingestion.
 */
import type { DiscoveryCandidate } from './discoveryCatalog'

export const OS_DOC_CORPUS: DiscoveryCandidate[] = [
  {
    sourceId: 'linux-man-pages',
    title: 'Linux man-pages',
    url: 'https://man7.org/linux/man-pages/',
    sourceType: 'operating_system_documentation',
    organization: 'man7.org / Linux man-pages project',
    license: 'GPL-2.0 / BSD (page-dependent)',
    version: null,
    authorityClass: 'PRIMARY',
    skillIds: ['os.linux', 'os.linux.man-pages', 'systems.processes', 'systems.memory', 'systems.ipc'],
    notes: 'Primary Linux syscall, process, memory, and IPC manual pages.',
  },
  {
    sourceId: 'linux-proc-man',
    title: 'proc(5) filesystem',
    url: 'https://man7.org/linux/man-pages/man5/proc.5.html',
    sourceType: 'operating_system_documentation',
    organization: 'Linux man-pages project',
    license: 'GPL-2.0 / BSD (page-dependent)',
    version: null,
    authorityClass: 'PRIMARY',
    skillIds: ['os.linux', 'systems.processes', 'debugging.runtime'],
    notes: 'procfs interface for process and kernel state.',
  },
  {
    sourceId: 'systemd-docs',
    title: 'systemd documentation',
    url: 'https://systemd.io/',
    sourceType: 'operating_system_documentation',
    organization: 'systemd project',
    license: 'LGPL-2.1-or-later (project); documentation as published',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.linux.systemd', 'os.system-services', 'os.linux'],
    notes: 'Official systemd project documentation hub.',
  },
  {
    sourceId: 'systemd-man-systemctl',
    title: 'systemctl(1)',
    url: 'https://www.freedesktop.org/software/systemd/man/latest/systemctl.html',
    sourceType: 'operating_system_documentation',
    organization: 'freedesktop.org / systemd',
    license: 'LGPL-2.1-or-later',
    version: 'latest',
    authorityClass: 'OFFICIAL',
    skillIds: ['os.linux.systemd', 'os.system-services'],
    notes: 'Official systemctl manual for service lifecycle.',
  },
  {
    sourceId: 'windows-sysinternals-docs',
    title: 'Windows hardware and driver documentation',
    url: 'https://learn.microsoft.com/windows-hardware/drivers/',
    sourceType: 'operating_system_documentation',
    organization: 'Microsoft',
    license: 'Microsoft documentation license',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.windows', 'os.drivers', 'kernel.device-drivers'],
    notes: 'Official Windows driver and kernel-mode documentation.',
  },
  {
    sourceId: 'windows-sys-programming',
    title: 'Windows app and system docs',
    url: 'https://learn.microsoft.com/windows/win32/',
    sourceType: 'operating_system_documentation',
    organization: 'Microsoft',
    license: 'Microsoft documentation license',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.windows', 'systems.processes', 'systems.ipc', 'systems.filesystems'],
    notes: 'Official Win32 process, IPC, filesystem, and permissions material.',
  },
  {
    sourceId: 'apple-darwin-kernel',
    title: 'Apple Kernel Programming Guide',
    url: 'https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/KernelProgramming/About/About.html',
    sourceType: 'operating_system_documentation',
    organization: 'Apple',
    license: 'Apple documentation license',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.macos', 'os.kernels', 'kernel.architecture'],
    notes: 'Archived official Darwin/macOS kernel programming guide.',
  },
  {
    sourceId: 'apple-filesystems',
    title: 'Apple File System Guide',
    url: 'https://developer.apple.com/documentation/foundation/file_system',
    sourceType: 'operating_system_documentation',
    organization: 'Apple',
    license: 'Apple documentation license',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.macos', 'systems.filesystems'],
    notes: 'Official Apple filesystem APIs for Darwin/macOS.',
  },
  {
    sourceId: 'freebsd-handbook',
    title: 'FreeBSD Handbook',
    url: 'https://docs.freebsd.org/en/books/handbook/',
    sourceType: 'operating_system_documentation',
    organization: 'The FreeBSD Project',
    license: 'FreeBSD Documentation License',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.bsd', 'os.linux', 'systems.processes'],
    notes: 'Official FreeBSD handbook. BSD family reference, not Linux mastery.',
  },
  {
    sourceId: 'openbsd-docs',
    title: 'OpenBSD FAQ',
    url: 'https://www.openbsd.org/faq/',
    sourceType: 'operating_system_documentation',
    organization: 'The OpenBSD Project',
    license: 'ISC-style / OpenBSD documentation',
    version: null,
    authorityClass: 'OFFICIAL',
    skillIds: ['os.bsd', 'security.secure-coding'],
    notes: 'Official OpenBSD FAQ covering security and system administration.',
  },
  {
    sourceId: 'linux-filesystem-hierarchy',
    title: 'Filesystem Hierarchy Standard',
    url: 'https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html',
    sourceType: 'recognized_standard',
    organization: 'Linux Foundation',
    license: 'FHS license as published',
    version: '3.0',
    authorityClass: 'STANDARD',
    skillIds: ['os.linux', 'systems.filesystems'],
    notes: 'Filesystem layout standard for Linux distributions.',
  },
]
