'use client'
import { useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import type { IncomeLootConsoleOpportunity,IncomeLootConsoleViewModel } from '@/lib/income-loot/consoleViewModel'

const tag=(value:string)=>value.replace(/_/g,' ')
const money=(amount:number,currency:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(amount)
function Badge({value}:{value:string}){const tone=/LIVE|VERIFIED|PAID/.test(value)?'text-emerald-200 border-emerald-400/30':/BLOCKED|REJECTED|EXPIRED|HISTORICAL|RESTRICTED/.test(value)?'text-amber-200 border-amber-400/30':'text-cyan-200 border-cyan-400/30';return <span className={`rounded border bg-black/30 px-2 py-1 text-[9px] font-bold uppercase tracking-widest ${tone}`}>{tag(value)}</span>}
function Empty({children}:{children:string}){return <p className="mt-3 rounded border border-white/10 bg-black/20 p-4 text-sm text-slate-400">{children}</p>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div className="rounded border border-white/10 bg-black/30 p-3"><p className="text-[9px] uppercase tracking-[.2em] text-slate-500">{label}</p><p className="mt-2 font-mono text-sm text-white">{value}</p><p className="mt-1 text-[9px] text-slate-500">{note}</p></div>}
function OpportunityCard({item,onClick,onPrepare}:{item:IncomeLootConsoleOpportunity;onClick:()=>void;onPrepare?:()=>void}){return <div className="rounded border border-white/10 bg-slate-950/60 p-4"><button type="button" onClick={onClick} className="w-full text-left"><div className="flex justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">{item.title}</h3><p className="mt-1 text-[10px] uppercase tracking-widest text-slate-500">{item.provider} · {tag(item.category)}</p></div><Badge value={item.classification}/></div><div className="mt-3 flex flex-wrap gap-4 text-[10px] text-slate-400"><span>Status <b className="text-slate-200">{tag(item.status)}</b></span><span>Reward <b className="text-slate-200">{item.estimatedReward?.amount==null?'Not stated':money(item.estimatedReward.amount,item.estimatedReward.currency)}</b></span><span>Rank <b className="text-cyan-200">{item.ranking.score}</b></span></div></button>{onPrepare?<button type="button" onClick={onPrepare} className="mt-3 rounded border border-emerald-400/30 px-3 py-2 text-[10px] font-bold uppercase tracking-widest text-emerald-200">Prepare application</button>:null}</div>}
function Detail({item,close}:{item:IncomeLootConsoleOpportunity;close:()=>void}){return <div className="fixed inset-0 z-50 flex justify-end bg-black/70"><aside className="h-full w-full max-w-xl overflow-y-auto border-l border-cyan-400/20 bg-slate-950 p-5"><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold text-white">{item.title}</h2><button type="button" onClick={close} className="rounded border border-white/15 px-2 py-1 text-xs text-slate-300">Close</button></div><div className="mt-4 flex gap-2"><Badge value={item.classification}/><Badge value={item.status}/></div><p className="mt-5 text-sm text-slate-300">{item.description??'No description stored.'}</p>{item.externalUrl?<a className="mt-5 inline-flex rounded border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200" href={item.externalUrl} target="_blank" rel="noreferrer">Open official action page</a>:<p className="mt-5 text-xs text-amber-200">No verified official action URL is stored.</p>}<h3 className="mt-7 text-[10px] uppercase tracking-widest text-slate-400">Evidence</h3>{item.evidence.length?<div className="mt-2 space-y-2">{item.evidence.map(e=><div key={e.id} className="rounded border border-white/10 p-2 text-xs text-slate-300"><Badge value={e.truthState}/><span className="ml-2">{tag(e.kind)} · {e.originalFilename??'No filename'}</span></div>)}</div>:<p className="mt-2 text-xs text-slate-500">No evidence attached.</p>}<h3 className="mt-7 text-[10px] uppercase tracking-widest text-slate-400">Provenance</h3>{item.provenance.map((p,index)=><div key={`${p.sourceAdapterId}-${index}`} className="mt-2 rounded border border-white/10 p-2 text-xs text-slate-400"><p>{p.sourceAdapterId} · {p.freshness} · {p.retrievedAt}</p>{p.sourceUrl?<a className="text-cyan-300 underline" href={p.sourceUrl} target="_blank" rel="noreferrer">View source</a>:null}</div>)}</aside></div>}

export function IncomeLootConsole({model}:{model:IncomeLootConsoleViewModel}){
  const router=useRouter()
  const [selectedId,setSelectedId]=useState<string|null>(null)
  const [operationMessage,setOperationMessage]=useState<string|null>(null)
  const selected=useMemo(()=>model.opportunities.find(item=>item.id===selectedId)??null,[model.opportunities,selectedId])
  if(!model.dataAvailable)return <main className="mx-auto max-w-7xl p-8"><h1 className="text-2xl text-white">EARN NOW COMMAND CENTER</h1><Empty>Commander income context is unavailable. No opportunity or financial values are shown.</Empty></main>
  const totals=(key:'estimated'|'confirmedOutstanding'|'cashReceived')=>Object.entries(model.ledgerSummary).length?Object.entries(model.ledgerSummary).map(([currency,value])=>money(value[key],currency)).join(' · '):'NOT TRACKED'
  const prepare=async(item:IncomeLootConsoleOpportunity)=>{setOperationMessage('Preparing application record…');const response=await fetch('/api/income-loot/operations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'PREPARE_APPLICATION',opportunityId:item.id,sourceId:item.provenance[0]?.sourceAdapterId??item.provider})});setOperationMessage(response.ok?'Application record prepared. No external submission occurred.':'Application could not be prepared.');if(response.ok)router.refresh()}
  return <main className="mx-auto max-w-7xl p-4 sm:p-8">
    <header className="border-b border-cyan-400/20 pb-5"><p className="text-[10px] uppercase tracking-[.35em] text-emerald-300">Income Loot · Phase 49-G</p><h1 className="mt-2 text-3xl font-semibold tracking-widest text-white">EARN NOW COMMAND CENTER</h1><p className="mt-2 text-xs text-slate-400">Real stored records only. External submission remains behind participant authority and Commander review.</p><p className="mt-3 text-[10px] uppercase tracking-widest text-amber-200">Session-only storage · no migration applied</p></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Earn now" value={String(model.earnNow.length)} note="Verified action paths"/><Metric label="Needs you" value={String(model.needsCommander.length)} note="Screener questions"/><Metric label="Estimated" value={totals('estimated')} note="Not money earned"/><Metric label="Money owed" value={totals('confirmedOutstanding')} note="Provider-confirmed outstanding"/><Metric label="Cash received" value={totals('cashReceived')} note="Verified receipts only"/></section>
    <section className="mt-8"><p className="text-[10px] uppercase tracking-widest text-emerald-300">Earn now</p><h2 className="mt-1 text-xl text-white">Ready to review and act</h2>{operationMessage?<p className="mt-2 text-xs text-cyan-200" role="status">{operationMessage}</p>:null}{model.earnNow.length?<div className="mt-3 space-y-3">{model.earnNow.map(item=><OpportunityCard key={item.id} item={item} onClick={()=>setSelectedId(item.id)} onPrepare={()=>void prepare(item)}/>)}</div>:<Empty>No stored opportunity meets every EARN NOW gate: real, current, non-invasive, and linked to an official action path.</Empty>}</section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2"><div><p className="text-[10px] uppercase tracking-widest text-amber-300">Needs you</p>{model.needsCommander.length?<div className="mt-3 space-y-2">{model.needsCommander.map(item=><div key={item.id} className="rounded border border-amber-400/20 p-3"><p className="text-xs text-white">{item.question.prompt}</p><p className="mt-1 text-[10px] uppercase text-amber-200">{tag(item.reason)} · {item.sourceId}</p></div>)}</div>:<Empty>No stored screener question needs Commander input.</Empty>}</div><div><p className="text-[10px] uppercase tracking-widest text-cyan-300">In progress</p>{model.inProgress.length?<div className="mt-3 space-y-2">{model.inProgress.map(item=><OpportunityCard key={item.id} item={item} onClick={()=>setSelectedId(item.id)}/>)}</div>:<Empty>No stored applications or opportunities are in progress.</Empty>}</div></section>
    <section className="mt-8"><p className="text-[10px] uppercase tracking-widest text-cyan-300">Applications</p>{model.applications.length?<div className="mt-3 grid gap-3 sm:grid-cols-2">{model.applications.map(application=><button type="button" key={application.id} disabled={!application.opportunity} onClick={()=>application.opportunity&&setSelectedId(application.opportunity.id)} className="rounded border border-white/10 bg-black/20 p-3 text-left"><div className="flex justify-between gap-2"><p className="text-xs text-white">{application.opportunity?.title??'Stored opportunity unavailable'}</p><Badge value={application.status}/></div><p className="mt-2 text-[10px] text-slate-500">{application.sourceId} · {application.updatedAt}</p></button>)}</div>:<Empty>No participant applications are stored. War Room will not imply a submission occurred.</Empty>}</section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2">{([['Money owed',model.moneyOwed,'No provider-confirmed outstanding rewards are stored.'],['Cash received',model.cashReceived,'No verified cash receipt events are stored.']] as const).map(([title,rows,empty])=><div key={title}><p className="text-[10px] uppercase tracking-widest text-emerald-300">{title}</p>{rows.length?<div className="mt-3 space-y-2">{rows.map((row,index)=><div key={`${row.opportunityId}-${row.currency}-${index}`} className="flex justify-between rounded border border-white/10 p-3"><div><p className="text-xs text-white">{row.title}</p><p className="text-[10px] text-slate-500">{row.provider}</p></div><b className="font-mono text-emerald-200">{money(row.amount,row.currency)}</b></div>)}</div>:<Empty>{empty}</Empty>}</div>)}</section>
    <section className="mt-8"><p className="text-[10px] uppercase tracking-widest text-cyan-300">Source health</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{model.sources.map(source=><a key={source.id} href={source.officialUrl} target="_blank" rel="noreferrer" className="rounded border border-white/10 bg-black/20 p-3"><div className="flex justify-between gap-2"><p className="text-xs font-semibold text-white">{source.providerName}</p><Badge value={source.status}/></div><p className="mt-2 text-[10px] text-slate-500">{source.statusReason}</p><p className="mt-2 text-[9px] uppercase tracking-widest text-slate-400">Account: {source.accountStatus?tag(source.accountStatus):'not connected'}</p></a>)}</div></section>
    <section className="mt-8"><p className="text-[10px] uppercase tracking-widest text-emerald-300">War Room Operating Fund</p><p className="mt-1 text-xs text-slate-400">Non-spending readiness view. Funded only by verified CASH_RECEIVED — never by estimates, confirmations, or personal funds.</p>{Object.keys(model.operatingFund.cashReceivedByCurrency).length?<div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(model.operatingFund.cashReceivedByCurrency).map(([currency,cash])=><div key={currency} className="rounded border border-white/10 bg-black/20 p-3"><p className="text-xs font-semibold text-white">{currency}</p><p className="mt-2 text-[10px] text-slate-400">Cash received <b className="text-slate-200">{money(cash,currency)}</b></p><p className="mt-1 text-[10px] text-slate-400">Allocation <b className="text-slate-200">{model.operatingFund.operatingFundAllocationPercent}%</b></p><p className="mt-1 text-[10px] text-slate-400">Operating fund available <b className="text-emerald-200">{money(model.operatingFund.operatingFundAvailableByCurrency[currency]??0,currency)}</b></p></div>)}</div>:null}<p className="mt-3 flex items-center gap-2 text-[10px] uppercase tracking-widest text-cyan-300">Self-funding status <Badge value={model.operatingFund.selfFundingReadiness}/></p>{model.operatingFund.selfFundingReadiness==='NO_REVENUE'?<Empty>NO WAR ROOM OPERATING FUNDS AVAILABLE</Empty>:null}</section>
    {selected?<Detail item={selected} close={()=>setSelectedId(null)}/>:null}
  </main>
}
