"""WR-TOOL-EVAL-6-CANDIDATE cases. TEST_FIXTURE semantic counterfactuals. Not V5/EVAL-5/EVAL-4."""
from __future__ import annotations

from typing import Any

# Pair kinds required by the mission.
WEB_RESEARCH: list[dict[str, Any]] = [
    dict(fid="harbor-tide", topic="Harbor City tide", cf="single_source vs multi_source",
         a=("When does high tide hit Harbor City this evening according to the harbor office page?", "WEB"),
         b=("Compare Harbor City tide claims from the harbor office, the national weather service, and local mariners and say where they disagree.", "RESEARCH")),
    dict(fid="comet-visibility", topic="Comet Lumen visibility", cf="current listing vs competing reports",
         a=("What time does tonight's Comet Lumen viewing window start on the planetarium's public schedule?", "WEB"),
         b=("Reconcile amateur astronomy clubs' reports on Comet Lumen visibility with the planetarium schedule and flag contradictions.", "RESEARCH")),
    dict(fid="ferry-delay", topic="Soundline ferry", cf="live status vs multi-outlet delay analysis",
         a=("Is the last Soundline ferry to Cedar Quay still running tonight?", "WEB"),
         b=("Pull several transit and passenger reports about Soundline Cedar Quay delays and summarize the disagreements.", "RESEARCH")),
    dict(fid="vaccine-trial", topic="Helix-9 trial", cf="sponsor page vs independent synthesis",
         a=("What does the Helix-9 trial's official enrollment page currently say about adult eligibility?", "WEB"),
         b=("Contrast the Helix-9 sponsor enrollment page with independent clinic write-ups and note conflicting eligibility rules.", "RESEARCH")),
    dict(fid="museum-hours", topic="Glassworks Museum", cf="venue hours vs disputed holiday hours",
         a=("What are the Glassworks Museum's Saturday hours on its own site?", "WEB"),
         b=("Check city listings, the museum site, and visitor forums for Glassworks Saturday hours and report conflicts.", "RESEARCH")),
    dict(fid="crop-bulletin", topic="Red valley maize", cf="agency bulletin vs competing yield estimates",
         a=("What yield figure does this week's Red Valley maize bulletin publish?", "WEB"),
         b=("Compare the Red Valley maize bulletin with co-op letters and university notes and explain the yield disagreements.", "RESEARCH")),
    dict(fid="league-table", topic="Northern Arc football", cf="official table vs disputed standings",
         a=("Who sits first in the Northern Arc football table on the league's official page right now?", "WEB"),
         b=("Compare the Northern Arc official table with two sports desks that dispute the standings and say why they differ.", "RESEARCH")),
    dict(fid="patent-status", topic="AeroFold hinge patent", cf="registry record vs competing legal notes",
         a=("What is the current legal status of the AeroFold hinge filing on the patent office register?", "WEB"),
         b=("Synthesize the patent register with two legal commentators on AeroFold and identify where they disagree.", "RESEARCH")),
    dict(fid="ozone-alert", topic="Basin ozone", cf="agency alert vs conflicting monitors",
         a=("What ozone alert level is the Basin Air desk showing for this afternoon?", "WEB"),
         b=("Compare the Basin Air ozone alert with independent monitor networks and say which sources conflict.", "RESEARCH")),
    dict(fid="auction-lot", topic="Lot 441 celadon", cf="house catalog vs provenance debate",
         a=("What estimate does the auction house currently list for Lot 441 celadon jar?", "WEB"),
         b=("Compare the Lot 441 catalog estimate with two specialist write-ups that dispute provenance.", "RESEARCH")),
    dict(fid="orbit-window", topic="Kite-7 launch", cf="operator T-0 vs independent windows",
         a=("What launch window does the Kite-7 operator currently publish?", "WEB"),
         b=("Compare the Kite-7 operator window with two tracking groups and list the disagreements.", "RESEARCH")),
    dict(fid="sugar-price", topic="Refined sugar contract", cf="exchange quote vs multi-desk disagreement",
         a=("What is the latest settlement on the refined sugar contract on the exchange board?", "WEB"),
         b=("Compare the exchange sugar settlement with two commodity desks and explain the gaps.", "RESEARCH")),
    dict(fid="trail-closure", topic="Pinecut Ridge trail", cf="park notice vs conflicting volunteer reports",
         a=("Does the park service currently list Pinecut Ridge as open?", "WEB"),
         b=("Compare the park listing for Pinecut Ridge with volunteer logs and ranger notes and report conflicts.", "RESEARCH")),
    dict(fid="choir-premiere", topic="River Cantata premiere", cf="venue listing vs conflicting press",
         a=("When does the River Cantata premiere according to the concert hall listing?", "WEB"),
         b=("Compare the hall listing for River Cantata with two arts desks that give different start times.", "RESEARCH")),
    dict(fid="bridge-toll", topic="East Span toll", cf="authority rate vs disputed surcharge",
         a=("What overnight toll does the East Span authority currently post?", "WEB"),
         b=("Compare the East Span posted toll with municipal notices and driver reports that claim a surcharge.", "RESEARCH")),
    dict(fid="seed-catalog", topic="Winter rye seed", cf="supplier page vs competing germination claims",
         a=("What germination rate does Amberfield's winter rye seed page currently claim?", "WEB"),
         b=("Compare Amberfield's rye germination claim with two independent seed testers and note disagreements.", "RESEARCH")),
    dict(fid="clinic-wait", topic="Northwell walk-in", cf="clinic board vs conflicting wait reports",
         a=("What wait time is Northwell Walk-in's public board showing right now?", "WEB"),
         b=("Compare Northwell's wait board with patient reports and a city dashboard and flag contradictions.", "RESEARCH")),
    dict(fid="storm-surge", topic="Lowland surge watch", cf="NWS-like desk vs competing surge models",
         a=("What surge watch is the Lowland marine desk currently issuing?", "WEB"),
         b=("Compare the Lowland marine surge watch with two independent flood models and say where they diverge.", "RESEARCH")),
]

FILES_MEMORY: list[dict[str, Any]] = [
    dict(fid="migration-cutover", topic="database cutover", cf="artifact vs stored decision",
         a=("Open the cutover runbook in the workspace and tell me the freeze window it writes down.", "FILES"),
         b=("What freeze window did we already lock in for the database cutover?", "MEMORY")),
    dict(fid="badge-policy", topic="visitor badges", cf="handbook vs remembered rule",
         a=("Read the visitor-badge section of the facilities handbook in the repo.", "FILES"),
         b=("What visitor-badge rule did we already settle on last week?", "MEMORY")),
    dict(fid="ink-budget", topic="print shop ink", cf="spreadsheet vs remembered cap",
         a=("Open the print-shop budget sheet and read the ink line.", "FILES"),
         b=("What ink cap did we already agree to for the print shop?", "MEMORY")),
    dict(fid="stage-plot", topic="solstice concert", cf="plot file vs remembered blocking",
         a=("Open the solstice concert stage plot and tell me where the choir stands.", "FILES"),
         b=("Where did we already decide the choir stands for the solstice concert?", "MEMORY")),
    dict(fid="lab-sop", topic="autoclave SOP", cf="SOP artifact vs remembered setting",
         a=("Open the autoclave SOP and read the hold time.", "FILES"),
         b=("What autoclave hold time did we already adopt?", "MEMORY")),
    dict(fid="lease-clause", topic="greenhouse lease", cf="lease file vs remembered term",
         a=("Open the greenhouse lease draft and read the winter-heat clause.", "FILES"),
         b=("What winter-heat term did we already accept on the greenhouse lease?", "MEMORY")),
    dict(fid="menu-allergen", topic="harbor cafe menu", cf="menu file vs remembered allergen call",
         a=("Open the harbor cafe menu draft and list the allergen callouts.", "FILES"),
         b=("Which allergen callouts did we already approve for the harbor cafe?", "MEMORY")),
    dict(fid="shift-roster", topic="night mill roster", cf="roster file vs remembered swap",
         a=("Open tonight's mill roster sheet and say who is on hopper two.", "FILES"),
         b=("Who did we already assign to hopper two for the night mill?", "MEMORY")),
    dict(fid="wiring-map", topic="loft lighting", cf="wiring diagram vs remembered circuit",
         a=("Open the loft lighting diagram and tell me which circuit feeds the north wall.", "FILES"),
         b=("Which circuit did we already pick for the loft's north wall lights?", "MEMORY")),
    dict(fid="grant-budget", topic="seed-library grant", cf="budget attachment vs remembered ceiling",
         a=("Open the seed-library grant budget attachment and read the travel ceiling.", "FILES"),
         b=("What travel ceiling did we already set for the seed-library grant?", "MEMORY")),
    dict(fid="species-list", topic="wetland survey", cf="survey workbook vs remembered list",
         a=("Open the wetland survey workbook and list the recorded heron counts.", "FILES"),
         b=("What heron counts did we already log for the wetland survey?", "MEMORY")),
    dict(fid="font-spec", topic="wayfinding signs", cf="spec sheet vs remembered typeface",
         a=("Open the wayfinding spec sheet and read the typeface choice.", "FILES"),
         b=("Which typeface did we already choose for wayfinding?", "MEMORY")),
    dict(fid="boiler-log", topic="kiln boiler", cf="log artifact vs remembered setpoint",
         a=("Open yesterday's kiln boiler log and read the overnight setpoint.", "FILES"),
         b=("What overnight kiln setpoint did we already standardize?", "MEMORY")),
    dict(fid="caption-sheet", topic="oral-history captions", cf="caption file vs remembered spelling",
         a=("Open the oral-history caption sheet and check how we spelled Aunt Nima's name.", "FILES"),
         b=("How did we already decide to spell Aunt Nima in the oral-history captions?", "MEMORY")),
    dict(fid="dock-schedule", topic="cold-storage dock", cf="schedule file vs remembered slot",
         a=("Open the cold-storage dock schedule and tell me Thursday's first inbound.", "FILES"),
         b=("Which Thursday inbound slot did we already reserve at cold storage?", "MEMORY")),
    dict(fid="quiz-key", topic="apprentice quiz", cf="answer key file vs remembered scoring",
         a=("Open the apprentice quiz key and read how partial credit is scored.", "FILES"),
         b=("How did we already decide to score partial credit on the apprentice quiz?", "MEMORY")),
    dict(fid="soil-map", topic="orchard drainage", cf="map artifact vs remembered trench line",
         a=("Open the orchard drainage map and trace the east trench.", "FILES"),
         b=("Where did we already decide to put the east orchard trench?", "MEMORY")),
    dict(fid="radio-script", topic="dawn radio", cf="script file vs remembered open",
         a=("Open the dawn-radio script and read the opening line.", "FILES"),
         b=("What opening line did we already lock for dawn radio?", "MEMORY")),
]

MEMORY_NOTOOL: list[dict[str, Any]] = [
    dict(fid="freeze-window", topic="deployment freeze", cf="stored decision vs supplied context",
         a=("Prior turn: We talked about a deployment freeze but I did not restate the hours here.\nCurrent: What did we decide?", "MEMORY"),
         b=("Prior turn: Freeze starts Friday 18:00 UTC because payroll cutover needs a quiet window.\nCurrent: What did we decide?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="ink-cap-state", topic="print ink cap", cf="must recall vs already in prompt",
         a=("Prior turn: We set an ink cap after arguing about waste.\nCurrent: Remind me of the number.", "MEMORY"),
         b=("Prior turn: Ink cap is 12 liters per week, no exceptions for rush jobs.\nCurrent: Remind me of the number.", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="choir-place", topic="choir blocking", cf="prior store vs restated",
         a=("Prior turn: We picked a choir placement I am not repeating.\nCurrent: Where do they stand?", "MEMORY"),
         b=("Prior turn: Choir stands on the stage-left riser, two steps up.\nCurrent: Where do they stand?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="lease-heat", topic="greenhouse heat", cf="remembered clause vs quoted",
         a=("Prior turn: We accepted a winter-heat term I am not quoting again.\nCurrent: What term was that?", "MEMORY"),
         b=("Prior turn: Landlord covers heat below 4 C; we cover the rest.\nCurrent: What term was that?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="hopper-two", topic="mill hopper", cf="stored assignment vs named now",
         a=("Prior turn: We assigned hopper two after the union check.\nCurrent: Who is on it?", "MEMORY"),
         b=("Prior turn: Mara Chen is on hopper two tonight.\nCurrent: Who is on it?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="travel-ceil", topic="grant travel", cf="stored ceiling vs restated",
         a=("Prior turn: We set a travel ceiling for the seed-library grant.\nCurrent: What ceiling?", "MEMORY"),
         b=("Prior turn: Travel ceiling is $2,400, no international legs.\nCurrent: What ceiling?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="typeface", topic="wayfinding type", cf="stored choice vs named",
         a=("Prior turn: We chose a typeface for wayfinding last meeting.\nCurrent: Which one?", "MEMORY"),
         b=("Prior turn: Wayfinding uses Source Serif, 48pt headers.\nCurrent: Which one?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="kiln-set", topic="kiln setpoint", cf="stored standard vs quoted",
         a=("Prior turn: We standardized an overnight kiln setpoint.\nCurrent: What temperature?", "MEMORY"),
         b=("Prior turn: Overnight kiln sits at 92 C.\nCurrent: What temperature?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="nima-spelling", topic="Aunt Nima", cf="stored spelling vs supplied",
         a=("Prior turn: We settled Aunt Nima's spelling in captions.\nCurrent: How is it spelled?", "MEMORY"),
         b=("Prior turn: Captions use 'Nima' without the extra e.\nCurrent: How is it spelled?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="thursday-slot", topic="dock slot", cf="stored reservation vs named",
         a=("Prior turn: We reserved a Thursday inbound at cold storage.\nCurrent: Which slot?", "MEMORY"),
         b=("Prior turn: Thursday inbound is 05:30 bay C.\nCurrent: Which slot?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="partial-credit", topic="quiz scoring", cf="stored rule vs explained",
         a=("Prior turn: We adopted a partial-credit rule for the apprentice quiz.\nCurrent: How does it work?", "MEMORY"),
         b=("Prior turn: Half credit if the method is right even when the number is wrong.\nCurrent: How does it work?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="east-trench", topic="orchard trench", cf="stored line vs described",
         a=("Prior turn: We picked a line for the east orchard trench.\nCurrent: Where is it?", "MEMORY"),
         b=("Prior turn: East trench runs three meters inside the hawthorn hedge.\nCurrent: Where is it?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="dawn-open", topic="radio open", cf="stored line vs quoted",
         a=("Prior turn: We locked a dawn-radio opening line.\nCurrent: What is it?", "MEMORY"),
         b=("Prior turn: Opening line is 'Harbor light, then the weather.'\nCurrent: What is it?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="badge-color", topic="visitor badge color", cf="stored policy vs described",
         a=("Prior turn: We picked a visitor badge color after the incident review.\nCurrent: Which color?", "MEMORY"),
         b=("Prior turn: Visitors wear mustard badges, contractors wear slate.\nCurrent: Which color?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="hold-time", topic="autoclave hold", cf="stored SOP number vs given",
         a=("Prior turn: We adopted an autoclave hold time.\nCurrent: How long?", "MEMORY"),
         b=("Prior turn: Hold time is 18 minutes at 121 C.\nCurrent: How long?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
    dict(fid="choir-count", topic="solstice headcount", cf="stored count vs given",
         a=("Prior turn: We froze the solstice choir headcount.\nCurrent: How many singers?", "MEMORY"),
         b=("Prior turn: Solstice choir is 22 singers including two juniors.\nCurrent: How many singers?", "NO_TOOL"),
         tags=("multi_turn", "information_state")),
]

SHA_NOTOOL: list[dict[str, Any]] = [
    dict(fid="exact-text-alpha", topic="payload ALPHA", cf="execute vs explain",
         a=("I need the checksum of this exact payload so I can compare machines later: ALPHA-441-quiet", "SHA256"),
         b=("In general, why would someone checksum a payload before comparing machines?", "NO_TOOL")),
    dict(fid="exact-text-beta", topic="phrase beta", cf="compute vs concept",
         a=("Produce the 256-bit fingerprint of this exact string: beta/quiet-room", "SHA256"),
         b=("What does a 256-bit fingerprint of a string actually represent, conceptually?", "NO_TOOL")),
    dict(fid="do-not-hash", topic="SHA meaning trap", cf="negation",
         a=("Calculate the digest of: lantern-dock-19", "SHA256"),
         b=("Do not calculate the hash; tell me what SHA-256 means.", "NO_TOOL"),
         tags=("negation_trap", "lexical_adversarial")),
    dict(fid="receipt-line", topic="receipt line", cf="digest this line vs explain receipts",
         a=("Fingerprint this receipt line exactly: QTY 4 LINEN 18.00", "SHA256"),
         b=("Why do warehouses fingerprint receipt lines instead of trusting handwritten totals?", "NO_TOOL")),
    dict(fid="config-blob", topic="config blob", cf="hash blob vs explain integrity",
         a=("Give me the checksum of this exact config blob: mode=dusk;lamps=12", "SHA256"),
         b=("Explain how a checksum on a config blob helps you notice accidental edits.", "NO_TOOL")),
    dict(fid="poem-line", topic="poem line", cf="hash line vs discuss hashing poetry",
         a=("Checksum this exact line: The quay remembers every rope.", "SHA256"),
         b=("Would checksumming a poem line tell you anything about its meaning?", "NO_TOOL")),
    dict(fid="id-token", topic="id token", cf="digest token vs explain",
         a=("I need the digest of this exact token: wr-shadow-991", "SHA256"),
         b=("What is the difference between identifying a token and hashing it?", "NO_TOOL")),
    dict(fid="byte-string", topic="bytes", cf="hash vs encoding lesson",
         a=("Compute the checksum of these exact characters: café::dock", "SHA256"),
         b=("If two strings look the same but hash differently, what usually happened?", "NO_TOOL")),
    dict(fid="manifest-row", topic="manifest row", cf="hash row vs explain manifests",
         a=("Fingerprint this exact manifest row: crate-77,net=14.2", "SHA256"),
         b=("Why might two manifests with the same crate ids still need row fingerprints?", "NO_TOOL")),
    dict(fid="password-not", topic="not a secret store", cf="hash this passphrase-like vs explain",
         a=("Checksum this exact practice string: not-a-password-just-lab", "SHA256"),
         b=("Explain why hashing a practice string is not the same as storing a password.", "NO_TOOL")),
    dict(fid="version-tag", topic="version tag", cf="hash tag vs explain tags",
         a=("Give the digest of this exact tag: release-kite7-rc2", "SHA256"),
         b=("What is a version tag for, without computing anything?", "NO_TOOL")),
    dict(fid="csv-cell", topic="csv cell", cf="hash cell vs explain csv",
         a=("Checksum this exact cell value: 2026-08-31T18:00Z", "SHA256"),
         b=("Why would two timestamps that print the same still need a checksum if encodings differ?", "NO_TOOL")),
    dict(fid="banner", topic="banner text", cf="hash banner vs discuss banners",
         a=("Fingerprint this exact banner: CLOSED FOR SURGE WATCH", "SHA256"),
         b=("What is the point of fingerprinting a public banner string?", "NO_TOOL")),
    dict(fid="json-min", topic="tiny json", cf="hash json vs explain canonical json",
         a=("Checksum this exact JSON: {\"lamps\":12}", "SHA256"),
         b=("Why does JSON spacing change a checksum even when the meaning is the same?", "NO_TOOL")),
    dict(fid="whitespace", topic="whitespace", cf="hash with spaces vs explain",
         a=("Hash this exact text including the spaces: '  dock  '", "SHA256"),
         b=("Why do leading spaces change a digest if humans ignore them when reading?", "NO_TOOL")),
    dict(fid="filename-like", topic="name like a file", cf="hash the name vs open a file",
         a=("I do not need the file opened. Compute the digest of this exact name: runbook-cutover.txt", "SHA256"),
         b=("I do not need you to open the file. Explain what a .txt runbook is for.", "NO_TOOL"),
         tags=("negation_trap", "lexical_adversarial")),
    dict(fid="remember-hash", topic="remember vs hash", cf="hash vs memory",
         a=("Do not use memory. Fingerprint this exact sentence: We already discussed the freeze.", "SHA256"),
         b=("Do not calculate anything. In general, what is a cryptographic digest used for?", "NO_TOOL"),
         tags=("negation_trap", "lexical_adversarial")),
    dict(fid="batch-id", topic="batch id", cf="hash id vs explain ids",
         a=("Checksum this exact batch id: MILL-NIGHT-441", "SHA256"),
         b=("What makes a batch id useful even if you never hash it?", "NO_TOOL")),
    dict(fid="seal", topic="seal string", cf="hash seal vs explain seals",
         a=("Produce the digest of this exact seal string: SEAL/QUAY/19", "SHA256"),
         b=("What is a seal string meant to prove, conceptually?", "NO_TOOL")),
    dict(fid="two-machines", topic="two machines", cf="hash to compare vs explain comparison",
         a=("I will compare two machines; checksum this exact payload: quiet-room-7", "SHA256"),
         b=("If two machines should hold the same payload, what does a matching checksum tell you?", "NO_TOOL")),
]

WEB_NOTOOL: list[dict[str, Any]] = [
    dict(fid="high-tide-now", topic="tide now vs tides in general", cf="current vs timeless",
         a=("When is this evening's high tide in Harbor City according to the live harbor listing?", "WEB"),
         b=("In general, what causes high tide to occur twice most days?", "NO_TOOL")),
    dict(fid="comet-now", topic="comet now vs comets", cf="schedule vs science",
         a=("What start time is on tonight's Comet Lumen public schedule?", "WEB"),
         b=("Why are comets visible only in certain sky windows?", "NO_TOOL")),
    dict(fid="ferry-now", topic="ferry now vs ferries", cf="status vs principle",
         a=("Is Soundline's last Cedar Quay boat still listed as running tonight?", "WEB"),
         b=("Why do passenger ferries usually publish a last sailing?", "NO_TOOL")),
    dict(fid="museum-now", topic="museum hours now vs museums", cf="today vs concept",
         a=("Are Glassworks Saturday hours currently posted as open past 17:00?", "WEB"),
         b=("Why do museums often close earlier on weekdays than Saturdays?", "NO_TOOL")),
    dict(fid="league-now", topic="table now vs league math", cf="live table vs rules",
         a=("Who is currently first on the Northern Arc official table?", "WEB"),
         b=("How does a football table usually decide who sits first?", "NO_TOOL")),
    dict(fid="ozone-now", topic="alert now vs ozone", cf="today vs chemistry",
         a=("What ozone level is the Basin Air desk posting this afternoon?", "WEB"),
         b=("What is ground-level ozone, in general terms?", "NO_TOOL")),
    dict(fid="sugar-now", topic="price now vs markets", cf="quote vs explanation",
         a=("What is the latest refined sugar settlement on the exchange board?", "WEB"),
         b=("Why do agricultural contracts have daily settlements?", "NO_TOOL")),
    dict(fid="trail-now", topic="trail now vs trails", cf="open/closed vs why closures",
         a=("Does the park service currently list Pinecut Ridge as open?", "WEB"),
         b=("Why do ridge trails close after storms even if the rain has stopped?", "NO_TOOL")),
    dict(fid="toll-now", topic="toll now vs tolls", cf="posted rate vs why tolls",
         a=("What overnight rate is the East Span authority posting?", "WEB"),
         b=("Why do some bridges charge more overnight?", "NO_TOOL")),
    dict(fid="wait-now", topic="clinic wait now vs queues", cf="board vs theory",
         a=("What wait is Northwell Walk-in's board showing right now?", "WEB"),
         b=("Why do walk-in clinics post wait times instead of appointments only?", "NO_TOOL")),
    dict(fid="launch-now", topic="window now vs orbits", cf="T-0 vs physics",
         a=("What launch window is the Kite-7 operator publishing today?", "WEB"),
         b=("Why does a launch to low orbit care about a time window?", "NO_TOOL")),
    dict(fid="patent-now", topic="status now vs patents", cf="register vs law intro",
         a=("What status does the patent register currently show for AeroFold?", "WEB"),
         b=("What does 'pending' usually mean on a patent register?", "NO_TOOL")),
    dict(fid="auction-now", topic="estimate now vs auctions", cf="catalog vs how estimates work",
         a=("What estimate is currently listed for Lot 441 celadon?", "WEB"),
         b=("What is an auction estimate, conceptually?", "NO_TOOL")),
    dict(fid="seed-now", topic="germination claim now vs germination", cf="vendor page vs biology",
         a=("What germination rate is Amberfield currently claiming for winter rye?", "WEB"),
         b=("What does a germination rate mean for a seed lot?", "NO_TOOL")),
    dict(fid="surge-now", topic="watch now vs surges", cf="alert vs physics",
         a=("What surge watch is the Lowland marine desk issuing now?", "WEB"),
         b=("What is a storm surge, in plain language?", "NO_TOOL")),
    dict(fid="no-web-explain", topic="already given tide", cf="negation / supplied",
         a=("Don't search the web; from what I already gave you — high tide 21:10 — when is it?", "NO_TOOL"),
         b=("I did not give the time. What is Harbor City's posted high tide this evening?", "WEB"),
         tags=("negation_trap", "information_state", "lexical_adversarial")),
]

FILES_NOTOOL: list[dict[str, Any]] = [
    dict(fid="runbook-open", topic="runbook", cf="open vs explain format",
         a=("Open the cutover runbook and read the freeze window it records.", "FILES"),
         b=("I don't need you to open the file. Explain what a runbook is for.", "NO_TOOL"),
         tags=("negation_trap", "lexical_adversarial")),
    dict(fid="sop-open", topic="SOP", cf="open vs explain SOP",
         a=("Open the autoclave SOP and read the hold time.", "FILES"),
         b=("Without opening anything, what is an SOP in a lab?", "NO_TOOL")),
    dict(fid="lease-open", topic="lease", cf="open vs explain leases",
         a=("Open the greenhouse lease draft and read the winter-heat clause.", "FILES"),
         b=("In general, what is a winter-heat clause doing in a lease?", "NO_TOOL")),
    dict(fid="roster-open", topic="roster", cf="open vs explain rosters",
         a=("Open tonight's mill roster and say who is on hopper two.", "FILES"),
         b=("What is a roster for, without looking one up?", "NO_TOOL")),
    dict(fid="map-open", topic="drainage map", cf="open vs explain maps",
         a=("Open the orchard drainage map and trace the east trench.", "FILES"),
         b=("Why would an orchard keep a drainage map?", "NO_TOOL")),
    dict(fid="script-open", topic="radio script", cf="open vs explain scripts",
         a=("Open the dawn-radio script and read the opening line.", "FILES"),
         b=("What is a radio script supposed to contain, generally?", "NO_TOOL")),
    dict(fid="budget-open", topic="grant budget", cf="open vs explain budgets",
         a=("Open the seed-library grant budget and read the travel ceiling.", "FILES"),
         b=("What is a travel ceiling in a grant budget?", "NO_TOOL")),
    dict(fid="spec-open", topic="type spec", cf="open vs explain specs",
         a=("Open the wayfinding spec and read the typeface.", "FILES"),
         b=("What is a typeface spec for wayfinding, conceptually?", "NO_TOOL")),
    dict(fid="log-open", topic="boiler log", cf="open vs explain logs",
         a=("Open yesterday's kiln boiler log and read the setpoint.", "FILES"),
         b=("Why do kilns keep boiler logs?", "NO_TOOL")),
    dict(fid="caption-open", topic="captions", cf="open vs explain captions",
         a=("Open the oral-history caption sheet and check Aunt Nima's spelling.", "FILES"),
         b=("Why do oral-history projects keep a caption sheet?", "NO_TOOL")),
    dict(fid="menu-open", topic="menu", cf="open vs explain allergen lines",
         a=("Open the harbor cafe menu draft and list allergen callouts.", "FILES"),
         b=("Why do cafe menus list allergen callouts?", "NO_TOOL")),
    dict(fid="remember-file", topic="file word trap", cf="open vs memory word",
         a=("Don't use memory; use the attached report in the workspace and read the freeze window.", "FILES"),
         b=("Don't open anything. Remember, in general, what a freeze window is.", "NO_TOOL"),
         tags=("negation_trap", "lexical_adversarial")),
]

RESEARCH_NOTOOL: list[dict[str, Any]] = [
    dict(fid="tide-conflict", topic="tide conflict", cf="multi-source vs explain disagreement",
         a=("Compare harbor, weather-service, and mariner tide claims for Harbor City and say where they disagree.", "RESEARCH"),
         b=("Why might three tide sources disagree even when they describe the same harbor?", "NO_TOOL")),
    dict(fid="comet-conflict", topic="comet conflict", cf="multi-source vs explain",
         a=("Reconcile club reports and the planetarium schedule on Comet Lumen and flag contradictions.", "RESEARCH"),
         b=("Why might amateur clubs and a planetarium disagree about a comet window?", "NO_TOOL")),
    dict(fid="ferry-conflict", topic="ferry conflict", cf="multi-source vs explain",
         a=("Pull several reports on Soundline Cedar Quay delays and summarize disagreements.", "RESEARCH"),
         b=("Why do passenger reports and an operator board disagree about delays?", "NO_TOOL")),
    dict(fid="trial-conflict", topic="trial conflict", cf="multi-source vs explain",
         a=("Contrast Helix-9 sponsor eligibility with independent clinic write-ups.", "RESEARCH"),
         b=("Why might a sponsor page and a clinic disagree about trial eligibility?", "NO_TOOL")),
    dict(fid="hours-conflict", topic="hours conflict", cf="multi-source vs explain",
         a=("Check city listings, the museum site, and forums for Glassworks Saturday hours and report conflicts.", "RESEARCH"),
         b=("Why do venue hours conflict across city listings and the venue itself?", "NO_TOOL")),
    dict(fid="yield-conflict", topic="yield conflict", cf="multi-source vs explain",
         a=("Compare the maize bulletin with co-op letters and university notes on Red Valley yield.", "RESEARCH"),
         b=("Why would a government bulletin and a co-op letter disagree on yield?", "NO_TOOL")),
    dict(fid="table-conflict", topic="table conflict", cf="multi-source vs explain",
         a=("Compare the Northern Arc official table with two desks that dispute standings.", "RESEARCH"),
         b=("How can two sports desks disagree about the same football table?", "NO_TOOL")),
    dict(fid="patent-conflict", topic="patent conflict", cf="multi-source vs explain",
         a=("Synthesize the AeroFold register with two legal commentators and identify disagreements.", "RESEARCH"),
         b=("Why might legal commentators disagree with a patent register snapshot?", "NO_TOOL")),
    dict(fid="ozone-conflict", topic="ozone conflict", cf="multi-source vs explain",
         a=("Compare the Basin Air ozone alert with independent monitors and say which conflict.", "RESEARCH"),
         b=("Why can nearby ozone monitors disagree on the same afternoon?", "NO_TOOL")),
    dict(fid="surge-conflict", topic="surge conflict", cf="multi-source vs explain",
         a=("Compare the Lowland surge watch with two flood models and say where they diverge.", "RESEARCH"),
         b=("Why do surge models diverge even with the same storm name?", "NO_TOOL")),
    dict(fid="research-word-web", topic="research word trap", cf="lexical: research but WEB",
         pair_kind="WEB_vs_NO_TOOL",
         a=("I already did the research myself. Just open the harbor office page for tonight's tide.", "WEB"),
         b=("Don't search. Explain from general knowledge why multi-source research is slower than one listing.", "NO_TOOL"),
         tags=("lexical_adversarial", "negation_trap")),
    dict(fid="word-research-true", topic="true research", cf="genuine multi-source",
         a=("Do the research: several sources on Kite-7's window, then tell me where they disagree.", "RESEARCH"),
         b=("What does 'several sources disagree' mean as a reasoning task, without looking anything up?", "NO_TOOL"),
         tags=("lexical_adversarial",)),
]

ABSTENTION: list[dict[str, Any]] = [
    dict(fid="calendar", input="Add Thursday's cold-storage slot to my calendar and email Mara.", reason="calendar/email not in six-class tool set", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="deploy", input="Restart production Node01 and flip the Cloudflare flag.", reason="deployment/production control is not a listed classroom tool", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="ambiguous", input="Handle the Harbor City thing.", reason="underspecified: web, files, memory, or none could apply", codes=("IDENTITY_AMBIGUOUS",)),
    dict(fid="equal-web-research", input="I need something about Kite-7's launch window.", reason="WEB and RESEARCH equally plausible without freshness/synthesis cue", codes=("IDENTITY_AMBIGUOUS",)),
    dict(fid="unavailable-fax", input="Fax the lease to the landlord.", reason="fax capability unavailable", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="sms", input="Text the choir the opening line.", reason="SMS not a listed tool", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="two-tools-equal", input="Either recall our freeze window or read it from whatever we have; I cannot tell which exists.", reason="MEMORY and FILES equally plausible", codes=("IDENTITY_AMBIGUOUS",)),
    dict(fid="payment", input="Charge the grant travel ceiling to the card on file.", reason="payments not in six-class router", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="unknown-device", input="Calibrate the spectrophotometer we do not expose as a tool.", reason="device control unavailable", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="vague-latest", input="What's the latest?", reason="no topic; abstain rather than guess WEB", codes=("IDENTITY_AMBIGUOUS",)),
    dict(fid="illegal-not", input="Bypass the badge reader tonight.", reason="not a legitimate listed capability", codes=("NO_COMPATIBLE_TOOL",)),
    dict(fid="both-hash-and-open", input="I might want a checksum or the runbook opened; you pick.", reason="SHA256 and FILES equally plausible", codes=("IDENTITY_AMBIGUOUS",)),
]

MULTI_TOOL: list[dict[str, Any]] = [
    dict(fid="files-research", input="Open the maize bulletin in the workspace, then compare it with co-op letters online and report conflicts.", tools=("FILES", "RESEARCH")),
    dict(fid="memory-web", input="Recall the freeze window we set, then check the harbor office page to see if tonight's tide overlaps it.", tools=("MEMORY", "WEB")),
    dict(fid="web-research", input="Get the official Kite-7 window, then still compare two tracking groups and list disagreements.", tools=("WEB", "RESEARCH")),
    dict(fid="files-memory", input="Read the lease draft, then remind me which winter-heat term we already accepted if it differs.", tools=("FILES", "MEMORY")),
    dict(fid="sha-files", input="Open the banner file, then checksum the exact banner string it contains.", tools=("FILES", "SHA256")),
    dict(fid="memory-files", input="What travel ceiling did we set, and quote the matching line from the grant budget attachment.", tools=("MEMORY", "FILES")),
    dict(fid="web-files", input="Check the park listing for Pinecut Ridge, then open our trail log in the repo and compare.", tools=("WEB", "FILES")),
    dict(fid="research-memory", input="Compare ozone sources, then recall the alert level we already adopted internally.", tools=("RESEARCH", "MEMORY")),
    dict(fid="web-sha", input="Fetch the currently posted East Span toll string and checksum that exact posted text.", tools=("WEB", "SHA256")),
    dict(fid="files-web-research", input="Open our dock schedule, check the live operator board, then reconcile both with driver reports.", tools=("FILES", "WEB", "RESEARCH")),
]


def _pair_rows(kind: str, items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for item in items:
        pair_kind = item.get("pair_kind", kind)
        fid = f"fam.eval6.{pair_kind}.{item['fid']}"
        tags = tuple(item.get("tags") or ())
        for side, (text, cls) in (("a", item["a"]), ("b", item["b"])):
            out.append(
                {
                    "family_id": fid,
                    "pair_kind": pair_kind,
                    "pair_side": side,
                    "topic": item["topic"],
                    "counterfactual": item["cf"],
                    "input": text,
                    "semantic_class": cls,
                    "tags": list(tags),
                    "lane": "SIX_WAY",
                }
            )
    return out


def six_way_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    rows += _pair_rows("WEB_vs_RESEARCH", WEB_RESEARCH)
    rows += _pair_rows("FILES_vs_MEMORY", FILES_MEMORY)
    rows += _pair_rows("MEMORY_vs_NO_TOOL", MEMORY_NOTOOL)
    rows += _pair_rows("SHA256_vs_NO_TOOL", SHA_NOTOOL)
    rows += _pair_rows("WEB_vs_NO_TOOL", WEB_NOTOOL)
    rows += _pair_rows("FILES_vs_NO_TOOL", FILES_NOTOOL)
    rows += _pair_rows("RESEARCH_vs_NO_TOOL", RESEARCH_NOTOOL)
    return rows


def diagnostic_rows() -> list[dict[str, Any]]:
    out = []
    for item in ABSTENTION:
        out.append(
            {
                "family_id": f"fam.eval6.abstention.{item['fid']}",
                "pair_kind": "ABSTENTION",
                "pair_side": "solo",
                "topic": item["fid"],
                "counterfactual": "none",
                "input": item["input"],
                "semantic_class": "ABSTENTION",
                "abstention_codes": list(item["codes"]),
                "abstention_reason": item["reason"],
                "tags": ["abstention"],
                "lane": "ABSTENTION_DIAGNOSTIC",
            }
        )
    for item in MULTI_TOOL:
        out.append(
            {
                "family_id": f"fam.eval6.multi.{item['fid']}",
                "pair_kind": "MULTI_TOOL_DIAGNOSTIC",
                "pair_side": "solo",
                "topic": item["fid"],
                "counterfactual": "none",
                "input": item["input"],
                "semantic_class": "MULTI_TOOL_DIAGNOSTIC",
                "multi_tools": list(item["tools"]),
                "tags": ["multi_tool"],
                "lane": "MULTI_TOOL_DIAGNOSTIC",
            }
        )
    return out
