#!/usr/bin/env python3
"""Emit WR-TOOL V5 development experience cases. No production. No training."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = (
    ROOT
    / "model-lab"
    / "manifests"
    / "wr_tool_trajectories"
    / "WR-TOOL-REAL-TRAJECTORY-POOL-V5"
    / "cases.json"
)

cases: list[dict] = []
fixtures: list[dict] = []


def add(
    cid: str,
    family_id: str,
    kind: str,
    request: str,
    *,
    compact: str,
    source_type: str = "REAL_RUNTIME",
    boundary_pair: str = "",
    files_path: str = "",
    files_search: str = "",
    memory_query: str = "",
    memory_fixture_id: str = "",
    sha_text: str | None = None,
    web_url: str = "",
    web_query: str = "",
    context_dependent: bool = False,
    intended_no_match: bool = False,
    missing_arg: bool = False,
) -> None:
    cases.append(
        {
            "id": cid,
            "family_id": family_id,
            "kind": kind,
            "request": request,
            "compact": compact,
            "source_type": source_type,
            "boundary_pair": boundary_pair,
            "files_path": files_path,
            "files_search": files_search,
            "memory_query": memory_query,
            "memory_fixture_id": memory_fixture_id,
            "sha_text": sha_text,
            "web_url": web_url,
            "web_query": web_query,
            "context_dependent": context_dependent,
            "intended_no_match": intended_no_match,
            "missing_arg": missing_arg,
            "real_wording": True,
        }
    )


def fx(fid: str, kind: str, title: str, content: str) -> None:
    fixtures.append({"id": fid, "kind": kind, "title": title, "content": content})


# --- DEVELOPMENT TEST MEMORY RECORDS (not REAL_RUNTIME) ---
fx("fx_v5_no_promote", "decision", "EXP005 promotion freeze",
   "Commander recorded that even if Experiment 005 demonstrates capability, modules stay CANDIDATE and are not promoted.")
fx("fx_v5_wrim0_frozen", "decree", "WRIM-0 freeze",
   "Official native core remains WRIM-0. EXP002, EXP003, and EXP004 stay unpromoted.")
fx("fx_v5_eval4_holdout", "project_fact", "EVAL-4 holdout",
   "EVAL-4 remains a permanently held-out exam. Its families must not enter V5 training.")
fx("fx_v5_rank_cap", "preference", "LoRA rank cap",
   "V5 training, if authorized by gates, must keep LoRA rank r=2. Rank is not a shortcut.")
fx("fx_v5_real_first", "decision", "Real experience first",
   "V5 attacks evidence breadth first. Do not answer EXP004 failure with hyperparameter fishing.")
fx("fx_v5_observer_raw", "decree", "Observer RAW policy",
   "Development observer records stay RAW until human review. Auto-curriculum is forbidden.")
fx("fx_v5_prod_untouch", "project_fact", "Production prohibition",
   "WarRoomNode01 is out of scope. No production SQL, flags, or deploys from this mission.")
fx("fx_v5_class_map", "project_fact", "Six-class map",
   "Operator classroom classes are NO_TOOL, WEB, MEMORY, FILES, RESEARCH, SHA256. LOOKUP_NOTE and ECHO_INT stay catalog-only.")
fx("fx_v5_git_freeze", "preference", "Git freeze",
   "This mission must not commit, push, merge, rebase, reset, or stash unrelated work.")
fx("fx_v5_tavily_401", "project_fact", "Tavily 401 history",
   "Historical Tavily search returned 401. WEB routing evidence may use direct public page fetch instead.")
fx("fx_v5_memory_thin", "decision", "Memory store thinness",
   "Historical live memory had only 3 rows / 2 unique decree texts. V5 may use labeled development fixtures.")
fx("fx_v5_feature_token", "project_fact", "Pooling feature",
   "The routing head reads assistant_boundary_last_token from frozen WRIM-0 hidden states.")
fx("fx_v5_seed", "preference", "Deterministic seed",
   "Preferred experiment seed is 20260831 with a fresh optimizer and no core params.")
fx("fx_v5_time_bound", "decree", "Sixty minute bound",
   "If remaining runtime is expected to exceed 60 minutes, stop at the last completed checkpoint.")
fx("fx_v5_hard_boundary", "project_fact", "Hard boundary pairs",
   "Required boundary families include WEB vs RESEARCH, FILES vs MEMORY, MEMORY vs NO_TOOL, WEB vs NO_TOOL, SHA256 vs NO_TOOL.")
fx("fx_v5_synth_cap", "preference", "Synthetic cap",
   "Synthetic training rows preferred 0 and may not exceed 10 percent. Volume must not satisfy the 120-row minimum.")
fx("fx_v5_files_bucket", "project_fact", "Storage bucket name",
   "SUPABASE_FILES_BUCKET must match the actual bucket name including spaces and capitalization.")
fx("fx_v5_service_role", "decree", "Service role server-only",
   "SUPABASE_SERVICE_ROLE_KEY stays server-only and must never be prefixed NEXT_PUBLIC_.")
fx("fx_v5_constitution", "project_fact", "Constitution pointer",
   "War Room operating philosophy lives in docs/war-room-constitution.md.")
fx("fx_v5_next_steps", "preference", "Operator next steps",
   "Engineering completions must include NEXT STEPS FOR OPERATOR covering the eight required subsections.")
fx("fx_v5_no_second_run", "decision", "Single training run",
   "If EXP005 fails, do not automatically change LR, rank, alpha, epochs, or seed.")
fx("fx_v5_eval5_blind", "decree", "EVAL-5 blindness",
   "EVAL-5 test stays untouched until after checkpoint selection on validation macro F1.")
fx("fx_v5_core_diff", "project_fact", "Core immutability",
   "Required core max_abs_diff after training is 0. WRIM-0 weights must not move.")
fx("fx_v5_head_shape", "project_fact", "Head shape",
   "The V5 classifier is Linear(256→6) with expected 1542 head parameters.")
fx("fx_v5_trainable", "project_fact", "Trainable budget",
   "Expected trainable parameter count is 38406: LoRA 36864 plus head 1542.")
fx("fx_v5_privacy", "preference", "Sanitized observer",
   "Observer output must remain sanitized. Never print API keys, tokens, or private user data.")
fx("fx_v5_wave42", "project_fact", "Wave 4.2 dataset",
   "Wave 4.2 produced a first real engineering dataset of 3 records and is not WRIM-1 capability READY.")
fx("fx_v5_recovery010", "project_fact", "Recovery-010",
   "TEST-WRIM1.1-RECOVERY-010 passed 250 mixed steps after TOOL_USE supervised removal; cap-eval stayed weak.")
fx("fx_v5_exp002_win", "decision", "EXP002 lesson",
   "EXP002 demonstrated capability acquisition on a bounded 3-class task with LoRA r2 q+v all 18 layers.")
fx("fx_v5_exp003_synth", "decision", "EXP003 lesson",
   "EXP003 did not demonstrate capability. Primary lesson was synthetic-distribution overfit.")
fx("fx_v5_exp004_n26", "project_fact", "EXP004 n=26",
   "EXP004 trained 26 rows, selected train accuracy 0.9231, EVAL-4 test accuracy 0.125.")
fx("fx_v5_tool_vs_notool", "project_fact", "TOOL-vs-NO_TOOL leftover",
   "EXP004 TOOL-vs-NO_TOOL was 0.75 while conditional tool identity was 0.0833.")

# MEMORY retrievals (TEST_FIXTURE) — one query per distinct fact
mem_qs = [
    ("mem_no_promote", "fx_v5_no_promote", "fam.v5.memory.no-promote",
     "What did we previously decide about promoting Experiment 005 modules?", "EXP005 promotion CANDIDATE"),
    ("mem_wrim0", "fx_v5_wrim0_frozen", "fam.v5.memory.wrim0-frozen",
     "Remind me of the stored decree that WRIM-0 stays the official frozen core.", "WRIM-0 official core"),
    ("mem_eval4", "fx_v5_eval4_holdout", "fam.v5.memory.eval4-holdout",
     "What project fact did we store about EVAL-4 staying held out of V5 training?", "EVAL-4 held-out exam"),
    ("mem_rank", "fx_v5_rank_cap", "fam.v5.memory.rank-cap",
     "What preference did we record about LoRA rank for any V5 adapter run?", "LoRA rank r=2"),
    ("mem_real_first", "fx_v5_real_first", "fam.v5.memory.real-first",
     "Recall the stored decision that V5 should collect real experience before another hyperparameter pass.", "evidence breadth first"),
    ("mem_observer", "fx_v5_observer_raw", "fam.v5.memory.observer-raw",
     "What decree did we store about development observer records remaining RAW?", "observer RAW until review"),
    ("mem_prod", "fx_v5_prod_untouch", "fam.v5.memory.prod-untouch",
     "What project fact did we keep about touching WarRoomNode01?", "WarRoomNode01 out of scope"),
    ("mem_classes", "fx_v5_class_map", "fam.v5.memory.class-map",
     "Remind me which six operator classroom routing classes we stored.", "NO_TOOL WEB MEMORY FILES RESEARCH SHA256"),
    ("mem_git", "fx_v5_git_freeze", "fam.v5.memory.git-freeze",
     "What git preference did we record for this mission?", "do not commit or push"),
    ("mem_tavily", "fx_v5_tavily_401", "fam.v5.memory.tavily-401",
     "Recall the stored project fact about historical Tavily search failures.", "Tavily 401"),
    ("mem_thin", "fx_v5_memory_thin", "fam.v5.memory.store-thin",
     "What did we previously decide about a thin historical memory store?", "3 rows 2 unique decree texts"),
    ("mem_pool", "fx_v5_feature_token", "fam.v5.memory.pooling-feature",
     "What project fact did we store about which hidden-state token the routing head reads?", "assistant_boundary_last_token"),
    ("mem_seed", "fx_v5_seed", "fam.v5.memory.seed",
     "What configuration preference did we record for the experiment seed?", "20260831"),
    ("mem_time", "fx_v5_time_bound", "fam.v5.memory.time-bound",
     "Remind me of the stored decree about the sixty-minute remaining-runtime stop.", "60 minutes"),
    ("mem_boundary", "fx_v5_hard_boundary", "fam.v5.memory.hard-boundary",
     "What project fact lists the required hard-boundary pair types?", "WEB vs RESEARCH FILES vs MEMORY"),
    ("mem_synth", "fx_v5_synth_cap", "fam.v5.memory.synth-cap",
     "What preference did we store about synthetic training volume?", "synthetic preferred 0 max 10 percent"),
    ("mem_bucket", "fx_v5_files_bucket", "fam.v5.memory.files-bucket",
     "Recall the stored project fact about matching the files bucket name exactly.", "SUPABASE_FILES_BUCKET"),
    ("mem_service", "fx_v5_service_role", "fam.v5.memory.service-role",
     "What decree did we store about the Supabase service role key prefix?", "never NEXT_PUBLIC_"),
    ("mem_const", "fx_v5_constitution", "fam.v5.memory.constitution",
     "Where did we store that the operating philosophy document lives?", "war-room-constitution.md"),
    ("mem_next", "fx_v5_next_steps", "fam.v5.memory.next-steps",
     "What completion preference did we record about operator next-steps subsections?", "eight required subsections"),
    ("mem_once", "fx_v5_no_second_run", "fam.v5.memory.single-run",
     "Recall the stored decision forbidding automatic second training runs after EXP005.", "do not change LR rank alpha"),
    ("mem_blind", "fx_v5_eval5_blind", "fam.v5.memory.eval5-blind",
     "What decree did we store about when EVAL-5 test may be scored?", "after checkpoint selection"),
    ("mem_diff", "fx_v5_core_diff", "fam.v5.memory.core-diff",
     "What project fact did we keep about core max_abs_diff?", "max_abs_diff 0"),
    ("mem_head", "fx_v5_head_shape", "fam.v5.memory.head-shape",
     "Remind me of the stored Linear head shape for V5.", "Linear 256 to 6"),
    ("mem_trainn", "fx_v5_trainable", "fam.v5.memory.trainable-budget",
     "What trainable parameter budget did we store?", "38406"),
    ("mem_priv", "fx_v5_privacy", "fam.v5.memory.privacy",
     "What observer preference did we record about printing credentials?", "sanitized observer"),
    ("mem_w42", "fx_v5_wave42", "fam.v5.memory.wave42",
     "Recall the stored project fact about the Wave 4.2 engineering dataset size.", "3 records"),
    ("mem_r010", "fx_v5_recovery010", "fam.v5.memory.recovery010",
     "What did we store about Recovery-010 mixed-step outcome?", "250 mixed steps"),
    ("mem_e2", "fx_v5_exp002_win", "fam.v5.memory.exp002",
     "What prior decision did we store as the EXP002 lesson?", "bounded 3-class capability"),
    ("mem_e3", "fx_v5_exp003_synth", "fam.v5.memory.exp003",
     "Recall the stored decision summarizing why EXP003 failed.", "synthetic-distribution overfit"),
    ("mem_e4n", "fx_v5_exp004_n26", "fam.v5.memory.exp004-n",
     "What project fact did we store about EXP004 training set size and test accuracy?", "26 rows test 0.125"),
    ("mem_tnt", "fx_v5_tool_vs_notool", "fam.v5.memory.tool-vs-notool",
     "Remind me of the stored EXP004 TOOL-versus-NO_TOOL leftover numbers.", "0.75 versus 0.0833"),
]
for cid, fxid, fam, req, q in mem_qs:
    add(cid, fam, "MEMORY", req, compact=f"TOOL=memory\nquery={q}",
        source_type="TEST_FIXTURE", memory_query=q, memory_fixture_id=fxid, context_dependent=True)

add("mem_nomatch", "fam.v5.memory.no-match-zx9", "MEMORY",
    "Recall the prior War Room decision about ZX9-V5-MEMORY-PROBE-ABSENT-FACT.",
    compact="TOOL=memory\nquery=ZX9-V5-MEMORY-PROBE-ABSENT-FACT",
    source_type="TEST_FIXTURE", memory_query="ZX9-V5-MEMORY-PROBE-ABSENT-FACT",
    context_dependent=True, intended_no_match=True)

# --- FILES ---
files = [
    ("files_boundary_session", "fam.v5.files.boundary-session",
     "In the tool boundary matrix writeup, where is it stated that WEB is not session memory?",
     "docs/WR_TOOL_BOUNDARY_MATRIX.md", "session memory"),
    ("files_v4_min_n", "fam.v5.files.v4-min-n",
     "Where does the V4 curriculum design document state the MINIMUM viable train n?",
     "docs/WR_TOOL_CURRICULUM_V4_DESIGN.md", "MINIMUM viable"),
    ("files_exp004_test_acc", "fam.v5.files.exp004-test-acc",
     "Pull the canonical EVAL-4 test accuracy figure from the EXP004 training report.",
     "docs/WR_TOOL_EXP_004_TRAINING_REPORT.md", "0.125"),
    ("files_eval4_identity", "fam.v5.files.eval4-identity",
     "Find the EVAL-4 package identity string in the held-out expansion report.",
     "docs/WR_TOOL_EVAL_4_HELD_OUT_EXPANSION_REPORT.md", "WR-TOOL-EVAL-4-CANDIDATE"),
    ("files_schema_fields", "fam.v5.files.trajectory-schema",
     "In the real trajectory schema, which field names the semantic family?",
     "docs/WR_TOOL_REAL_TRAJECTORY_SCHEMA.md", "family"),
    ("files_observer_gold0", "fam.v5.files.observer-gold0",
     "Locate the sentence in the observer-dev report about REAL_RUNTIME gold still being 0 for several classes.",
     "docs/WR_TOOL_REAL_RUNTIME_OBSERVER_DEV_REPORT.md", "REAL_RUNTIME gold still 0"),
    ("files_memory_report_3_2", "fam.v5.files.memory-3-2",
     "Find the 3 rows / 2 unique texts memory-store finding in the memory runtime collection report.",
     "docs/WR_TOOL_MEMORY_RUNTIME_COLLECTION_REPORT.md", "2 unique"),
    ("files_class_div_verdict", "fam.v5.files.class-div-verdict",
     "What mission verdict string is written in the class-diverse runtime collection report?",
     "docs/WR_TOOL_CLASS_DIVERSE_RUNTIME_COLLECTION_REPORT.md", "CLASS-DIVERSE"),
    ("files_research_forensics", "fam.v5.files.research-forensics",
     "Open the research-class forensics note and find how RESEARCH was being lexicalized.",
     "docs/WR_TOOL_RESEARCH_CLASS_FORENSICS.md", "research"),
    ("files_v3_design", "fam.v5.files.v3-design",
     "Extract the V3 curriculum identity from its design document.",
     "docs/WR_TOOL_CURRICULUM_V3_DESIGN.md", "V3"),
    ("files_exp001_design", "fam.v5.files.exp001-design",
     "In the EXP001 design, find the frozen-linear-head description.",
     "docs/WR_TOOL_PARAMETER_ISOLATED_EXPERIMENT_001_DESIGN.md", "linear"),
    ("files_exp002_report", "fam.v5.files.exp002-report",
     "Where does the EXP002 report claim capability acquisition on the bounded 3-class task?",
     "docs/WR_TOOL_PARAMETER_ISOLATED_EXPERIMENT_002_REPORT.md", "CAPABILITY ACQUISITION"),
    ("files_exp003_report", "fam.v5.files.exp003-report",
     "Find EXP003's not-demonstrated verdict in its report.",
     "docs/WR_TOOL_PARAMETER_ISOLATED_EXPERIMENT_003_REPORT.md", "NOT DEMONSTRATED"),
    ("files_eval2_design", "fam.v5.files.eval2-design",
     "Read the EVAL-2 design for the held-out item count discussion.",
     "docs/WR_TOOL_EVAL_2_DESIGN.md", "EVAL-2"),
    ("files_eval3_design", "fam.v5.files.eval3-design",
     "Find how EVAL-3 is scoped in its design note.",
     "docs/WR_TOOL_EVAL_3_DESIGN.md", "EVAL-3"),
    ("files_capture_contract", "fam.v5.files.capture-contract",
     "In the real-runtime capture contract, what must stay unsynthesized?",
     "docs/WR_TOOL_REAL_RUNTIME_CAPTURE_CONTRACT.md", "synthetic"),
    ("files_acquisition", "fam.v5.files.acquisition",
     "Locate pool V1 identity in the real trajectory acquisition report.",
     "docs/WR_TOOL_REAL_TRAJECTORY_ACQUISITION_REPORT.md", "POOL-V1"),
    ("files_evidence_exp", "fam.v5.files.evidence-expansion",
     "What does the evidence expansion report say about synthetic-heavy V3?",
     "docs/WR_TOOL_EVIDENCE_EXPANSION_REPORT.md", "synthetic"),
    ("files_constitution", "fam.v5.files.constitution",
     "Open the War Room constitution and find the Commander approval-gate language.",
     "docs/war-room-constitution.md", "Commander"),
    ("files_claude_md", "fam.v5.files.claude-md",
     "In the repo guidance file, what command is listed for a production build?",
     "CLAUDE.md", "pnpm run build"),
    ("files_eng_standard", "fam.v5.files.eng-standard",
     "Find the eight NEXT STEPS FOR OPERATOR subsections in the engineering completion standard.",
     "docs/ENGINEERING_COMPLETION_STANDARD.md", "NEXT STEPS"),
    ("files_takeover", "fam.v5.files.takeover-exp004",
     "In the master takeover report, find the EXP004 capability line.",
     "docs/WAR_ROOM_AGI_MASTER_TAKEOVER_REPORT.md", "EXP-004"),
    ("files_v4_material", "fam.v5.files.v4-materialization",
     "Where does the V4 materialization review list MEMORY gold n=2?",
     "docs/WR_TOOL_CURRICULUM_V4_MATERIALIZATION_REVIEW.md", "MEMORY"),
    ("files_exp004_design", "fam.v5.files.exp004-design",
     "Extract the Linear(256→6) contract from the EXP004 design review.",
     "docs/WR_TOOL_EXP_004_DESIGN_REVIEW.md", "Linear(256"),
    ("files_router_ts", "fam.v5.files.router-ts",
     "In the tool router module, find the bounded_sha256 execution mode name.",
     "lib/modular-intelligence/toolRouter.ts", "bounded_sha256"),
    ("files_gate_ts", "fam.v5.files.quality-gate-ts",
     "Find the quality labels array in the runtime trajectory quality gate.",
     "lib/modular-intelligence/qualityGateRuntimeTrajectory.ts", "VERIFIED"),
    ("files_obs_gate", "fam.v5.files.obs-gate",
     "Where does the observation gate refuse production NODE_ENV?",
     "lib/modular-intelligence/trajectoryObservationGate.ts", "production"),
    ("files_paths_py", "fam.v5.files.paths-py",
     "Read the WRIM-0 checkpoint SHA constant in the modular paths helper.",
     "scripts/wrim-modular/paths.py", "d1affa599ff967313b476e649062c7d969606b8e"),
    ("files_exp004_hashes", "fam.v5.files.exp004-hashes",
     "Open EXP004 HASHES and find selected_checkpoint_hash.",
     "model-lab/manifests/wr_tool_experiments/WR-TOOL-EXP-004/HASHES.json", "selected_checkpoint_hash"),
    ("files_v4_hashes", "fam.v5.files.v4-train-hash",
     "Find the frozen train.jsonl digest in the V4 HASHES file.",
     "model-lab/manifests/wr_tool_curriculum/design/WR-TOOL-CURRICULUM-V4-CANDIDATE/HASHES.json", "4b8b33f0a44150ebadfbd3c7bc9d0cc09ec3f44836f693222b6e1a83d99d15da"),
]
for cid, fam, req, path, needle in files:
    add(cid, fam, "FILES", req, compact=f"TOOL=files\npath={path}",
        files_path=path, files_search=needle)

# --- WEB (direct public fetch; avoid EVAL-4 npm/iana/unicode/debian topics) ---
web = [
    ("web_gitlab_status", "fam.v5.web.gitlab-status",
     "What's GitLab's current public operational condition according to their status feed?",
     "https://www.gitlabstatus.com/api/v2/status.json", "GitLab current operational condition"),
    ("web_do_status", "fam.v5.web.digitalocean-status",
     "Check DigitalOcean's current public incident indicator from their status JSON.",
     "https://status.digitalocean.com/api/v2/status.json", "DigitalOcean current incident indicator"),
    ("web_hashi_status", "fam.v5.web.hashicorp-status",
     "Pull HashiCorp's current public status description.",
     "https://status.hashicorp.com/api/v2/status.json", "HashiCorp current status description"),
    ("web_kernel_banner", "fam.v5.web.kernel-banner",
     "What does kernel.org currently print on its finger banner for latest mainline?",
     "https://www.kernel.org/finger_banner", "kernel.org latest mainline banner"),
    ("web_go_version", "fam.v5.web.go-version",
     "What Go toolchain version is currently advertised on go.dev's VERSION endpoint?",
     "https://go.dev/VERSION?m=text", "current Go toolchain version"),
    ("web_pypi_requests", "fam.v5.web.pypi-requests",
     "What latest version does the PyPI JSON API currently list for the requests package?",
     "https://pypi.org/pypi/requests/json", "latest requests package version PyPI"),
    ("web_crates_serde", "fam.v5.web.crates-serde",
     "What max_version does crates.io currently report for serde?",
     "https://crates.io/api/v1/crates/serde", "crates.io serde max_version"),
    ("web_usgs_quakes", "fam.v5.web.usgs-significant",
     "What significant earthquakes does USGS currently list for the past week?",
     "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson",
     "USGS significant earthquakes past week"),
    ("web_nws_alerts", "fam.v5.web.nws-active-alerts",
     "Are there any currently active NWS alerts in their public alerts feed?",
     "https://api.weather.gov/alerts/active?status=actual&limit=5", "currently active NWS alerts"),
    ("web_postgres_rel", "fam.v5.web.postgres-releases",
     "What current release notes landing page does PostgreSQL publish?",
     "https://www.postgresql.org/docs/release/", "PostgreSQL current release notes"),
    ("web_tc39", "fam.v5.web.tc39-ecma262",
     "Fetch the current ECMAScript draft landing from TC39.",
     "https://tc39.es/ecma262/", "current ECMAScript draft TC39"),
    ("web_whatwg_html", "fam.v5.web.html-living",
     "Grab the WHATWG HTML living standard developer edition front matter.",
     "https://html.spec.whatwg.org/dev/", "WHATWG HTML living standard"),
    ("web_rfc8259", "fam.v5.web.rfc8259",
     "What does the RFC editor currently show as the abstract line for RFC 8259?",
     "https://www.rfc-editor.org/info/rfc8259", "RFC 8259 JSON media type"),
    ("web_ietf793", "fam.v5.web.rfc793",
     "Retrieve the published TCP specification text from RFC 793.",
     "https://www.ietf.org/rfc/rfc793.txt", "RFC 793 TCP specification"),
    ("web_w3_png", "fam.v5.web.w3-png",
     "What does W3C currently publish as the PNG specification landing?",
     "https://www.w3.org/TR/PNG/", "W3C PNG specification"),
    ("web_py_whatsnew", "fam.v5.web.python-whatsnew",
     "What's on the current Python 3 What's New index?",
     "https://docs.python.org/3/whatsnew/index.html", "Python 3 What's New index"),
    ("web_maven_junit", "fam.v5.web.maven-junit",
     "What versions does Maven Central metadata currently list for junit:junit?",
     "https://repo.maven.apache.org/maven2/junit/junit/maven-metadata.xml", "junit junit maven-metadata"),
    ("web_jsdelivr_jquery", "fam.v5.web.jquery-pkg",
     "What version field is currently in the jsDelivr jquery package.json?",
     "https://cdn.jsdelivr.net/npm/jquery/package.json", "jquery package.json version"),
    ("web_react_npm", "fam.v5.web.react-registry",
     "What version does the npm registry currently advertise for react@latest?",
     "https://registry.npmjs.org/react/latest", "react latest registry version"),
    ("web_node_index", "fam.v5.web.node-dist-index",
     "From nodejs.org's dist index JSON, what is the newest listed version string?",
     "https://nodejs.org/dist/index.json", "nodejs dist index newest version"),
    ("web_rust_channel", "fam.v5.web.rust-stable-channel",
     "What date/version does the current Rust stable channel manifest advertise?",
     "https://static.rust-lang.org/dist/channel-rust-stable.toml", "Rust stable channel manifest"),
]
for cid, fam, req, url, q in web:
    add(cid, fam, "WEB", req, compact=f"TOOL=web\nquery={q}", web_url=url, web_query=q)

# --- RESEARCH (multi-source; contrast with single WEB retrievals) ---
research = [
    ("res_go_vs_rust_release", "fam.v5.research.go-vs-rust",
     "Compare several public sources on whether Go and Rust both shipped a stable toolchain update this month, and note where they disagree."),
    ("res_kernel_lts", "fam.v5.research.kernel-lts",
     "Investigate across more than one outlet which Linux kernel series is currently treated as long-term, and flag conflicting dates."),
    ("res_postgres_eol", "fam.v5.research.postgres-eol",
     "I need a sourced investigation: which PostgreSQL major versions are currently still supported, and where do vendor pages disagree?"),
    ("res_ecma_stage", "fam.v5.research.ecma-stage",
     "Cross-check multiple references about what TC39 currently lists at Stage 3, and synthesize the disagreements."),
    ("res_quake_week", "fam.v5.research.quakes-week",
     "Verify with more than one public feed what significant earthquakes occurred this week and whether catalogs match."),
    ("res_nws_vs_media", "fam.v5.research.alerts-vs-media",
     "Compare official weather-alert listings against public news feeds and say where coverage diverges."),
    ("res_pypi_requests_cve", "fam.v5.research.requests-advisories",
     "Check several sources for whether the Python requests library has a currently discussed security advisory, and cite more than one."),
    ("res_serde_msrv", "fam.v5.research.serde-msrv",
     "Investigate across docs and registry metadata what minimum Rust version serde currently implies, and note conflicts."),
    ("res_html_living", "fam.v5.research.html-living-vs-w3c",
     "Compare WHATWG versus W3C public pages on who currently publishes the HTML living standard, using more than one source."),
    ("res_rfc_json", "fam.v5.research.json-rfc-lineage",
     "Synthesize from multiple references the current RFC lineage for JSON (8259 vs earlier) and where summaries conflict."),
    ("res_node_lts_policy", "fam.v5.research.node-lts-policy",
     "I need independent sources compared: what is the current Node.js LTS policy window, and where do calendars disagree?"),
    ("res_gitlab_incidents", "fam.v5.research.gitlab-incidents",
     "Cross-check GitLab status with public reporting on whether a current incident is actually affecting git operations."),
    ("res_do_status_news", "fam.v5.research.digitalocean-news",
     "Compare DigitalOcean's own status surface with independent reports about current platform health."),
    ("res_hashi_vault", "fam.v5.research.vault-status",
     "Investigate whether HashiCorp Vault has a currently discussed outage or CVE, using multiple public sources."),
    ("res_maven_junit5", "fam.v5.research.junit-line",
     "Compare sources on whether JUnit 5 has fully displaced JUnit 4 in current Maven Central download leadership."),
    ("res_jquery_maintenance", "fam.v5.research.jquery-maint",
     "Verify across several references whether jQuery is currently in active major-version development or maintenance-only."),
    ("res_python_whatsnew", "fam.v5.research.python-whatsnew",
     "Compare the Python What's New pages with independent changelogs for the current 3.x series and flag mismatches."),
    ("res_png_spec", "fam.v5.research.png-spec",
     "I need a multi-source check: is the W3C PNG spec currently the citation people should use versus older ISO text?"),
    ("res_tcp_rfc", "fam.v5.research.tcp-rfc-updates",
     "Compare RFC 793 with later TCP update RFCs and summarize where current practice diverges, using multiple sources."),
    ("res_crates_download", "fam.v5.research.serde-downloads",
     "Investigate from more than one public surface whether serde remains among the most downloaded crates, and cite conflicts."),
    ("res_usgs_vs_emsc", "fam.v5.research.usgs-vs-emsc",
     "Cross-source the past week's significant quakes between USGS and at least one other public catalog."),
    ("res_go_modules", "fam.v5.research.go-proxy",
     "Compare several sources on the current recommended Go module proxy and sum where corporate mirrors disagree."),
    ("res_rust_edition", "fam.v5.research.rust-edition",
     "What do independent sources currently say is the default Rust edition for new cargo projects, and where do they disagree?"),
    ("res_postgres_versus_mysql", "fam.v5.research.pg-vs-mysql-support",
     "Compare current public support calendars for PostgreSQL versus MySQL LTS and synthesize the differences."),
    ("res_ietf_http", "fam.v5.research.http-rfc9110",
     "Verify across multiple references whether RFC 9110 is currently the citation for HTTP semantics, noting leftover RFC 7231 mentions."),
    ("res_tc39_vs_mdn", "fam.v5.research.tc39-vs-mdn",
     "Compare TC39 drafts with MDN's current language about a Stage-3 feature and report mismatches."),
]
for cid, fam, req in research:
    add(cid, fam, "RESEARCH", req, compact=f"TOOL=research\nquery={req[:180]}")

# --- SHA256 (bounded gym; REAL_TEST) ---
sha_payloads = [
    ("sha_plain", "fam.v5.sha256.plain-alpha", "alpha-v5-plain"),
    ("sha_sentence", "fam.v5.sha256.sentence-freeze",
     "V5 keeps WRIM-0 frozen while LoRA r2 may train."),
    ("sha_json", "fam.v5.sha256.structured-json",
     '{"mission":"v5","train":true,"promote":false}'),
    ("sha_short", "fam.v5.sha256.short-k7", "k7"),
    ("sha_long", "fam.v5.sha256.long-paragraph",
     "The Commander authorized one bounded V5 experiment if and only if family-diverse real evidence clears every predeclared data gate. "
     "Synthetic inflation is not a substitute for unused runtime trajectories."),
    ("sha_unicode", "fam.v5.sha256.unicode-arrow", "Linear(256→6) class map"),
    ("sha_digits", "fam.v5.sha256.digits", "38406"),
    ("sha_pathish", "fam.v5.sha256.pathish", "docs/war-room-constitution.md"),
    ("sha_blankish", "fam.v5.sha256.spaces-tabs", "v5 seed 20260831"),
    ("sha_multiline", "fam.v5.sha256.multiline", "line-one\nline-two\nline-three"),
    ("sha_toolish", "fam.v5.sha256.mentions-web", "do not fetch; only digest: gitlab status"),
    ("sha_memoryish", "fam.v5.sha256.mentions-memory", "digest this stored-looking phrase: CANDIDATE not promoted"),
    ("sha_fileish", "fam.v5.sha256.mentions-files", "checksum only, ignore the document path CLAUDE.md"),
    ("sha_researchish", "fam.v5.sha256.mentions-research", "hash this investigation note: compare sources later"),
    ("sha_hex", "fam.v5.sha256.hex-like", "d1affa599ff967313b476e649062c7d9"),
    ("sha_punct", "fam.v5.sha256.punct", "r=2; alpha=2; q+v"),
    ("sha_quote", "fam.v5.sha256.quoted", 'He said "do not promote EXP004."'),
    ("sha_empty_arg", "fam.v5.sha256.missing-arg", None),
]
for cid, fam, text in sha_payloads:
    if text is None:
        add(cid, fam, "SHA256",
            "Run the bounded digest tool but I forgot to give you the payload.",
            compact="TOOL=sha256", source_type="REAL_TEST", missing_arg=True)
        continue
    add(cid, fam, "SHA256",
        f"Fingerprint this payload so I can compare it later: {text}",
        compact=f"TOOL=sha256\ntext={text}", source_type="REAL_TEST", sha_text=text)

# extra SHA256 natural (no 'http')
add("sha_natural_blob", "fam.v5.sha256.natural-blob", "SHA256",
    "I need a checksum of the exact bytes in: WAR-ROOM-V5-KEEL-STONE",
    compact="TOOL=sha256\ntext=WAR-ROOM-V5-KEEL-STONE", source_type="REAL_TEST",
    sha_text="WAR-ROOM-V5-KEEL-STONE")
add("sha_natural_note", "fam.v5.sha256.natural-note", "SHA256",
    "Compute the digest of my lab note: never move EVAL-4 into the workbook.",
    compact="TOOL=sha256\ntext=never move EVAL-4 into the workbook.", source_type="REAL_TEST",
    sha_text="never move EVAL-4 into the workbook.")

# --- NO_TOOL hard negatives ---
notools = [
    ("nt_explain_memory", "fam.v5.notool.explain-memory",
     "In conceptual terms, what is a memory store for an agent? Do not retrieve any prior notes."),
    ("nt_explain_hash", "fam.v5.notool.explain-hash",
     "Explain why a cryptographic digest is one-way. Do not compute one and do not look anything up."),
    ("nt_web_vs_research", "fam.v5.notool.web-vs-research-concept",
     "Using only this conversation, explain the difference between a single-page lookup and a multi-source investigation."),
    ("nt_files_concept", "fam.v5.notool.files-concept",
     "Generally speaking, why would an assistant read a local document instead of guessing? No file access needed — reason it out."),
    ("nt_lora_capacity", "fam.v5.notool.lora-capacity",
     "Given what we already know, why is LoRA rank r=2 a capacity constraint rather than proof that data is irrelevant?"),
    ("nt_supplied_acc", "fam.v5.notool.supplied-numbers",
     "From the numbers already in this prompt — train acc 0.9231 and test acc 0.125 — what does the generalization gap suggest? Do not open reports."),
    ("nt_sha_distractor", "fam.v5.notool.sha-conceptual-distractor",
     "People say SHA-256 fingerprints files. Explain the idea without hashing anything I type."),
    ("nt_recall_without_store", "fam.v5.notool.no-store-recall",
     "If I already told you EXP004 test accuracy was 0.125, repeat that figure from this chat. Do not query durable memory."),
    ("nt_url_as_example", "fam.v5.notool.url-as-example",
     "Suppose someone writes example.com in a sentence about URLs. Explain URL structure; do not fetch any host."),
    ("nt_research_word", "fam.v5.notool.research-as-noun",
     "The word research can mean a graduate thesis. Discuss that academic meaning. Do not start a live investigation."),
    ("nt_docs_word", "fam.v5.notool.docs-as-genre",
     "Software docs are a genre of writing. What makes them different from chat? Do not open a path."),
    ("nt_plus", "fam.v5.notool.arithmetic",
     "What is nineteen plus twenty-three? Answer directly."),
    ("nt_define_lora", "fam.v5.notool.define-lora",
     "Define LoRA adapters in your own words. No papers, no retrieval."),
    ("nt_frozen_core", "fam.v5.notool.frozen-core-reason",
     "Why freeze a base model while training a tiny head? Reason from first principles already stated: isolation."),
    ("nt_keyword_trap", "fam.v5.notool.keyword-trap-web",
     "The terms lookup, website, and https appear in this sentence as vocabulary. Explain why keywords are not routing. Stay in-chat."),
    ("nt_eval_philosophy", "fam.v5.notool.heldout-philosophy",
     "Why must an exam stay unseen during homework? Answer from general ML practice, not from opening EVAL-4."),
    ("nt_confusion", "fam.v5.notool.confusion-matrix-idea",
     "What does a confusion matrix tell you that accuracy hides? No need to compute one on a file."),
    ("nt_overfit", "fam.v5.notool.overfit-idea",
     "If train accuracy is high and validation is low, what happened? Explain; do not load checkpoints."),
    ("nt_privacy", "fam.v5.notool.privacy-idea",
     "Why must observer logs redact tokens? Discuss the principle. Do not print any secrets."),
    ("nt_class_map", "fam.v5.notool.class-map-idea",
     "Why keep LOOKUP_NOTE out of the operator classroom? Reason from the six-class map already described here."),
]
for cid, fam, req in notools:
    add(cid, fam, "NO_TOOL", req, compact="TOOL=none")

# --- HARD BOUNDARY PAIRS (shared family_id, distinct actions) ---
pairs = [
    # WEB vs RESEARCH
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.kernel",
     "web_b_kernel", "WEB", "What's the latest mainline version currently shown on kernel.org's banner?",
     "https://www.kernel.org/finger_banner", "kernel.org latest mainline version",
     "res_b_kernel", "RESEARCH",
     "Compare several sources on what 'latest mainline Linux' currently means and where kernel.org disagrees with distro trackers."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.pypi",
     "web_b_pypi", "WEB", "What version is currently listed for package requests on PyPI's JSON API?",
     "https://pypi.org/pypi/requests/json", "requests current version PyPI JSON",
     "res_b_pypi", "RESEARCH",
     "Investigate across multiple advisories and changelogs whether requests' current PyPI version is considered safe, and cite disagreements."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.go",
     "web_b_go", "WEB", "Read the current Go version string from go.dev's VERSION endpoint.",
     "https://go.dev/VERSION?m=text", "current Go version string",
     "res_b_go", "RESEARCH",
     "I need a sourced comparison of Go's current stable versus last two minors and whether release blogs agree."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.usgs",
     "web_b_usgs", "WEB", "List the significant quakes USGS currently publishes for this week.",
     "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson",
     "USGS this week significant quakes",
     "res_b_usgs", "RESEARCH",
     "Cross-check USGS's current significant-quake list against at least one other public catalog and report mismatches."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.gitlab",
     "web_b_gitlab", "WEB", "What indicator does GitLab currently publish on its status JSON?",
     "https://www.gitlabstatus.com/api/v2/status.json", "GitLab current status indicator",
     "res_b_gitlab", "RESEARCH",
     "Compare GitLab's status JSON with independent outage reports and synthesize whether git hosting is actually degraded."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.rust",
     "web_b_rust", "WEB", "What does the current Rust stable channel manifest list as the stable version?",
     "https://static.rust-lang.org/dist/channel-rust-stable.toml", "Rust stable version manifest",
     "res_b_rust", "RESEARCH",
     "Compare the Rust stable channel manifest with independent release posts and note if they disagree on the current stable."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.react",
     "web_b_react", "WEB", "What version does the npm registry currently advertise for react latest?",
     "https://registry.npmjs.org/react/latest", "react latest version registry",
     "res_b_react", "RESEARCH",
     "Investigate across changelog, registry, and independent posts whether react's current latest is a security release, citing more than one source."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.nws",
     "web_b_nws", "WEB", "Are there currently active alerts in the NWS public alerts feed?",
     "https://api.weather.gov/alerts/active?status=actual&limit=5", "NWS currently active alerts",
     "res_b_nws", "RESEARCH",
     "Compare official NWS active alerts with public news weather coverage and say where the stories diverge."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.tc39",
     "web_b_tc39", "WEB", "Fetch the current TC39 ECMA-262 draft landing page.",
     "https://tc39.es/ecma262/", "TC39 ECMA-262 current draft",
     "res_b_tc39", "RESEARCH",
     "Compare the current TC39 draft landing with secondary explainers about which proposals actually shipped, using multiple sources."),
    ("WEB_vs_RESEARCH", "fam.v5.boundary.web-research.postgres",
     "web_b_pg", "WEB", "Open PostgreSQL's current public release-notes index.",
     "https://www.postgresql.org/docs/release/", "PostgreSQL release-notes index",
     "res_b_pg", "RESEARCH",
     "I need several sources compared on which PostgreSQL majors are still supported versus the release-notes index."),
    # FILES vs MEMORY
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.observer",
     "files_b_obs", "FILES",
     "Find the observer-dev report sentence about REAL_RUNTIME class gold still being 0.",
     "docs/WR_TOOL_REAL_RUNTIME_OBSERVER_DEV_REPORT.md", "REAL_RUNTIME gold still 0",
     "mem_b_obs", "MEMORY",
     "What decree did we previously store about development observer records staying RAW until review?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.exp004",
     "files_b_e4", "FILES",
     "In the EXP004 training report, locate the test accuracy 0.125 line.",
     "docs/WR_TOOL_EXP_004_TRAINING_REPORT.md", "0.125",
     "mem_b_e4", "MEMORY",
     "Recall the stored project fact about EXP004's training n and test accuracy."),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.constitution",
     "files_b_con", "FILES",
     "Open the constitution document and find Commander approval-gate language.",
     "docs/war-room-constitution.md", "Commander",
     "mem_b_con", "MEMORY",
     "Where did we store that the operating philosophy document lives?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.eval4",
     "files_b_eval4", "FILES",
     "Find WR-TOOL-EVAL-4-CANDIDATE in the EVAL-4 expansion report.",
     "docs/WR_TOOL_EVAL_4_HELD_OUT_EXPANSION_REPORT.md", "WR-TOOL-EVAL-4-CANDIDATE",
     "mem_b_eval4", "MEMORY",
     "What project fact did we store about EVAL-4 remaining a held-out exam?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.rank",
     "files_b_rank", "FILES",
     "In the EXP004 design review, find the LoRA r=2 contract.",
     "docs/WR_TOOL_EXP_004_DESIGN_REVIEW.md", "r=2",
     "mem_b_rank", "MEMORY",
     "What preference did we record about keeping LoRA rank r=2 for V5?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.next",
     "files_b_next", "FILES",
     "Find the NEXT STEPS FOR OPERATOR heading in the engineering completion standard.",
     "docs/ENGINEERING_COMPLETION_STANDARD.md", "NEXT STEPS FOR OPERATOR",
     "mem_b_next", "MEMORY",
     "What completion preference did we record about the eight operator subsections?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.v4mem",
     "files_b_v4m", "FILES",
     "In the memory runtime collection report, find the 2 unique texts finding.",
     "docs/WR_TOOL_MEMORY_RUNTIME_COLLECTION_REPORT.md", "2 unique",
     "mem_b_v4m", "MEMORY",
     "What did we previously decide about a historically thin memory store?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.paths",
     "files_b_sha", "FILES",
     "Read the WRIM-0 SHA constant from the modular paths helper.",
     "scripts/wrim-modular/paths.py", "d1affa599ff967313b476e649062c7d969606b8e",
     "mem_b_sha", "MEMORY",
     "What project fact did we keep about required core max_abs_diff?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.promote",
     "files_b_pr", "FILES",
     "In the master takeover report, find the do-not-promote EXP004 language.",
     "docs/WAR_ROOM_AGI_MASTER_TAKEOVER_REPORT.md", "promote",
     "mem_b_pr", "MEMORY",
     "What did we previously decide about promoting Experiment 005 modules?"),
    ("FILES_vs_MEMORY", "fam.v5.boundary.files-memory.classes",
     "files_b_cl", "FILES",
     "In the V4 materialization review, find the six-class Option B list.",
     "docs/WR_TOOL_CURRICULUM_V4_MATERIALIZATION_REVIEW.md", "NO_TOOL",
     "mem_b_cl", "MEMORY",
     "Remind me which six operator classroom routing classes we stored."),
    # MEMORY vs NO_TOOL
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.promote",
     "mem_bn_pr", "MEMORY",
     "What stored decision covers promoting Experiment 005 modules?",
     "", "",
     "nt_bn_pr", "NO_TOOL",
     "In general, what does it mean for a model adapter to stay a candidate rather than production? Do not look up our notes."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.rank",
     "mem_bn_rk", "MEMORY",
     "Recall the stored preference about LoRA rank for V5.",
     "", "",
     "nt_bn_rk", "NO_TOOL",
     "Explain LoRA rank as a capacity knob using only general ML knowledge. Do not retrieve our lab preference."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.tavily",
     "mem_bn_tv", "MEMORY",
     "What project fact did we store about historical Tavily 401 failures?",
     "", "",
     "nt_bn_tv", "NO_TOOL",
     "What does HTTP 401 mean in general? Do not recall our provider history."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.seed",
     "mem_bn_sd", "MEMORY",
     "What configuration preference did we record for the experiment seed?",
     "", "",
     "nt_bn_sd", "NO_TOOL",
     "Why do ML experiments pick a numeric seed? Answer conceptually, not from stored lab config."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.synth",
     "mem_bn_sy", "MEMORY",
     "What preference did we store about synthetic training volume?",
     "", "",
     "nt_bn_sy", "NO_TOOL",
     "Why can synthetic data cause distribution overfit? Reason generally. Do not retrieve our cap."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.time",
     "mem_bn_tm", "MEMORY",
     "Remind me of the stored decree about stopping if remaining runtime exceeds sixty minutes.",
     "", "",
     "nt_bn_tm", "NO_TOOL",
     "Why would a research program budget wall-clock time? Discuss the idea without reading our decree."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.privacy",
     "mem_bn_pv", "MEMORY",
     "What observer preference did we record about printing credentials?",
     "", "",
     "nt_bn_pv", "NO_TOOL",
     "Why shouldn't logs contain API keys? Explain the principle. Do not dump our stored wording."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.head",
     "mem_bn_hd", "MEMORY",
     "Remind me of the stored Linear head shape for V5.",
     "", "",
     "nt_bn_hd", "NO_TOOL",
     "What is a linear classifier head in general terms? Do not recall our 256-to-6 note."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.eval5",
     "mem_bn_e5", "MEMORY",
     "What decree did we store about when EVAL-5 test may be scored?",
     "", "",
     "nt_bn_e5", "NO_TOOL",
     "Why keep a test split untouched until the end? General held-out practice. Do not open our decree."),
    ("MEMORY_vs_NO_TOOL", "fam.v5.boundary.memory-notool.once",
     "mem_bn_1", "MEMORY",
     "Recall the stored decision forbidding automatic second training runs after EXP005.",
     "", "",
     "nt_bn_1", "NO_TOOL",
     "Why is hyperparameter fishing on the same tiny exam a scientific problem? Reason in-chat only."),
    # WEB vs NO_TOOL
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.gitlab",
     "web_bn_gl", "WEB", "What's GitLab's current public operational condition from their status feed?",
     "https://www.gitlabstatus.com/api/v2/status.json", "GitLab current operational condition",
     "nt_bn_gl", "NO_TOOL",
     "What is a status page, conceptually, for a SaaS product? Do not check GitLab live."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.go",
     "web_bn_go", "WEB", "What Go toolchain version is currently advertised on go.dev?",
     "https://go.dev/VERSION?m=text", "current Go toolchain version advertised",
     "nt_bn_go", "NO_TOOL",
     "What does a language toolchain version number usually encode? No need to look up Go's current one."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.usgs",
     "web_bn_us", "WEB", "What significant earthquakes does USGS currently list for the past week?",
     "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson",
     "USGS significant earthquakes past week",
     "nt_bn_us", "NO_TOOL",
     "How does a magnitude scale work, in general? Do not list this week's quakes."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.kernel",
     "web_bn_k", "WEB", "What does kernel.org currently print on its finger banner for latest mainline?",
     "https://www.kernel.org/finger_banner", "kernel.org latest mainline banner",
     "nt_bn_k", "NO_TOOL",
     "What is a Linux mainline kernel, conceptually? Do not fetch kernel.org."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.crates",
     "web_bn_cr", "WEB", "What max_version does crates.io currently report for serde?",
     "https://crates.io/api/v1/crates/serde", "crates.io serde max_version",
     "nt_bn_cr", "NO_TOOL",
     "What is a crate registry in the Rust ecosystem? Do not look up serde's current version."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.html",
     "web_bn_html", "WEB", "Grab the WHATWG HTML living standard developer edition front matter.",
     "https://html.spec.whatwg.org/dev/", "WHATWG HTML living standard",
     "nt_bn_html", "NO_TOOL",
     "What does 'living standard' mean for HTML? Explain; do not fetch the spec."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.rfc8259",
     "web_bn_8259", "WEB", "What does the RFC editor currently show for RFC 8259?",
     "https://www.rfc-editor.org/info/rfc8259", "RFC 8259 current RFC editor page",
     "nt_bn_8259", "NO_TOOL",
     "What is an RFC, in the IETF sense? Do not open RFC 8259."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.node",
     "web_bn_node", "WEB", "From nodejs.org's dist index JSON, what is the newest listed version string?",
     "https://nodejs.org/dist/index.json", "nodejs dist index newest version",
     "nt_bn_node", "NO_TOOL",
     "What is an LTS release line in runtime ecosystems? Do not check Node's current newest."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.nws",
     "web_bn_nws", "WEB", "Are there any currently active NWS alerts in their public alerts feed?",
     "https://api.weather.gov/alerts/active?status=actual&limit=5", "currently active NWS alerts",
     "nt_bn_nws", "NO_TOOL",
     "What is a weather watch versus a warning, conceptually? Do not pull live alerts."),
    ("WEB_vs_NO_TOOL", "fam.v5.boundary.web-notool.do",
     "web_bn_do", "WEB", "Check DigitalOcean's current public incident indicator from their status JSON.",
     "https://status.digitalocean.com/api/v2/status.json", "DigitalOcean current incident indicator",
     "nt_bn_do", "NO_TOOL",
     "Why do infrastructure vendors publish status JSON? Discuss the idea without checking DigitalOcean."),
    # SHA256 vs NO_TOOL
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.oneway",
     "sha_bn_ow", "SHA256",
     "Fingerprint this payload so I can compare it later: one-way-digest-demo",
     "", "one-way-digest-demo",
     "nt_bn_ow", "NO_TOOL",
     "Explain why a cryptographic digest is one-way. Do not compute a digest."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.avalanche",
     "sha_bn_av", "SHA256",
     "I need a checksum of the exact bytes in: avalanche-v5-bytes",
     "", "avalanche-v5-bytes",
     "nt_bn_av", "NO_TOOL",
     "What is the avalanche effect in hashing, conceptually? Do not hash my words."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.hex",
     "sha_bn_hx", "SHA256",
     "Compute the digest of my lab note: hex-output-is-not-encryption",
     "", "hex-output-is-not-encryption",
     "nt_bn_hx", "NO_TOOL",
     "Is a hex digest encryption? Explain the distinction without hashing."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.collision",
     "sha_bn_col", "SHA256",
     "Fingerprint this payload so I can compare it later: collision-resistance-note",
     "", "collision-resistance-note",
     "nt_bn_col", "NO_TOOL",
     "What does collision resistance mean for SHA-256? Teach it; do not emit a digest."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.checksum",
     "sha_bn_cs", "SHA256",
     "I need a checksum of the exact bytes in: checksum-vs-mac",
     "", "checksum-vs-mac",
     "nt_bn_cs", "NO_TOOL",
     "How does a checksum differ from a MAC? Reason only. No digest execution."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.preimage",
     "sha_bn_pre", "SHA256",
     "Compute the digest of my lab note: preimage-resistance-v5",
     "", "preimage-resistance-v5",
     "nt_bn_pre", "NO_TOOL",
     "Define preimage resistance without computing any hash."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.length",
     "sha_bn_len", "SHA256",
     "Fingerprint this payload so I can compare it later: length-extension-chat",
     "", "length-extension-chat",
     "nt_bn_len", "NO_TOOL",
     "What is a length-extension issue at a high level? Do not hash the phrase."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.salt",
     "sha_bn_salt", "SHA256",
     "I need a checksum of the exact bytes in: salt-is-not-sha-by-itself",
     "", "salt-is-not-sha-by-itself",
     "nt_bn_salt", "NO_TOOL",
     "Why do password stores add a salt? Conceptual answer; do not hash passwords or this sentence."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.tree",
     "sha_bn_tree", "SHA256",
     "Compute the digest of my lab note: merkle-tree-is-a-pattern",
     "", "merkle-tree-is-a-pattern",
     "nt_bn_tree", "NO_TOOL",
     "What is a Merkle tree, conceptually? Do not compute leaf hashes."),
    ("SHA256_vs_NO_TOOL", "fam.v5.boundary.sha-notool.file",
     "sha_bn_file", "SHA256",
     "Fingerprint this payload so I can compare it later: files-are-bytes-too",
     "", "files-are-bytes-too",
     "nt_bn_file", "NO_TOOL",
     "Why would someone hash a file rather than read it? Discuss; do not open or hash a path."),
]

for pair in pairs:
    btype, fam, a_id, a_kind, a_req, a_path_or_url, a_q, b_id, b_kind, b_req = pair
    if a_kind == "WEB":
        add(a_id, fam, "WEB", a_req, compact=f"TOOL=web\nquery={a_q}",
            boundary_pair=btype, web_url=a_path_or_url, web_query=a_q)
    elif a_kind == "FILES":
        add(a_id, fam, "FILES", a_req, compact=f"TOOL=files\npath={a_path_or_url}",
            boundary_pair=btype, files_path=a_path_or_url, files_search=a_q)
    elif a_kind == "MEMORY":
        add(a_id, fam, "MEMORY", a_req, compact=f"TOOL=memory\nquery={a_req[:80]}",
            source_type="TEST_FIXTURE", boundary_pair=btype, memory_query=a_req[:80],
            context_dependent=True)
    elif a_kind == "SHA256":
        add(a_id, fam, "SHA256", a_req, compact=f"TOOL=sha256\ntext={a_q}",
            source_type="REAL_TEST", boundary_pair=btype, sha_text=a_q)
    if b_kind == "RESEARCH":
        add(b_id, fam, "RESEARCH", b_req, compact=f"TOOL=research\nquery={b_req[:180]}",
            boundary_pair=btype)
    elif b_kind == "MEMORY":
        add(b_id, fam, "MEMORY", b_req, compact=f"TOOL=memory\nquery={b_req[:80]}",
            source_type="TEST_FIXTURE", boundary_pair=btype, memory_query=b_req[:80],
            context_dependent=True)
    elif b_kind == "NO_TOOL":
        add(b_id, fam, "NO_TOOL", b_req, compact="TOOL=none", boundary_pair=btype)

# Map memory boundary queries onto fixture ids when the text matches known facts
FIXTURE_HINTS = {
    "observer": "fx_v5_observer_raw",
    "EXP004": "fx_v5_exp004_n26",
    "operating philosophy": "fx_v5_constitution",
    "EVAL-4 remaining": "fx_v5_eval4_holdout",
    "LoRA rank r=2": "fx_v5_rank_cap",
    "eight operator": "fx_v5_next_steps",
    "thin memory": "fx_v5_memory_thin",
    "max_abs_diff": "fx_v5_core_diff",
    "promoting Experiment 005": "fx_v5_no_promote",
    "six operator classroom": "fx_v5_class_map",
    "Tavily 401": "fx_v5_tavily_401",
    "experiment seed": "fx_v5_seed",
    "synthetic training": "fx_v5_synth_cap",
    "sixty minutes": "fx_v5_time_bound",
    "printing credentials": "fx_v5_privacy",
    "Linear head": "fx_v5_head_shape",
    "EVAL-5 test": "fx_v5_eval5_blind",
    "second training": "fx_v5_no_second_run",
}
for c in cases:
    if c["kind"] != "MEMORY" or c.get("memory_fixture_id"):
        continue
    req = c["request"]
    for needle, fxid in FIXTURE_HINTS.items():
        if needle.lower() in req.lower():
            c["memory_fixture_id"] = fxid
            break

OUT.parent.mkdir(parents=True, exist_ok=True)
payload = {
    "identity": "WR-TOOL-V5-EXPERIENCE-CASES",
    "fixtures": fixtures,
    "cases": cases,
    "n_cases": len(cases),
    "n_fixtures": len(fixtures),
    "by_kind": {k: sum(1 for c in cases if c["kind"] == k) for k in
                ("NO_TOOL", "WEB", "MEMORY", "FILES", "RESEARCH", "SHA256")},
}
OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
print(json.dumps({"ok": True, "n_cases": len(cases), "n_fixtures": len(fixtures), "by_kind": payload["by_kind"], "out": str(OUT)}))
