export { chunkDocument, chunkText, chunkIdFor } from './chunk'
export { CHUNKING_VERSION } from './types'
export { reciprocalRankFusion } from './rrf'
export { searchLocalHybrid } from './retrieve'
export { indexCorpusDocuments } from './indexCorpus'
export { createFakeEmbedder, createQueryEmbedder, createUnavailableEmbedder, getSharedQueryEmbedder, resetSharedQueryEmbedder, textsForEmbedding } from './embedder'
export { SqliteVectorStore } from './vectors'
export { prepareLocalEmbeddingModel } from './prepareModel'
export { localModelGovernance, resolveHybridPaths, localOnnxModelPresent } from './modelStore'
export { inspectLocalSemanticHealth, resourceGuardrails } from './semanticHealth'
export { EVAL_QUERIES, EVAL_DOCUMENTS, seedEvalCorpus, evaluateRetrievalMode, recallAtK, meanReciprocalRank } from './eval'
export type { HybridSearchHit, HybridSearchResult, DocumentChunk, Embedder, LocalSemanticHealth, LocalRetrievalSignals } from './types'
