export { chunkDocument, chunkText, chunkIdFor } from './chunk'
export { CHUNKING_VERSION } from './types'
export { reciprocalRankFusion } from './rrf'
export { searchLocalHybrid } from './retrieve'
export { indexCorpusDocuments, indexDocumentVectors } from './indexCorpus'
export { createFakeEmbedder, createQueryEmbedder, createUnavailableEmbedder, getSharedQueryEmbedder, resetSharedQueryEmbedder, textsForEmbedding } from './embedder'
export { SqliteVectorStore } from './vectors'
export { prepareLocalEmbeddingModel } from './prepareModel'
export { localModelGovernance, resolveHybridPaths, localOnnxModelPresent } from './modelStore'
export { inspectLocalSemanticHealth, resourceGuardrails } from './semanticHealth'
export { EVAL_QUERIES, EVAL_DOCUMENTS, seedEvalCorpus, evaluateRetrievalMode, evaluateLegacyStrictFts, recallAtK, meanReciprocalRank, mixedTopicCoverage } from './eval'
export { PRODUCTION_RETRIEVAL_PROFILE, getRetrievalProfile, RETRIEVAL_PROFILE_VERSION } from './retrievalProfile'
export { admitSemanticCandidates } from './admission'
export { reembedStoredDocument, reembedStaleDocuments, listStaleVectorDocuments, documentNeedsReembed } from './reembed'
export { runSovereignMaintenance } from './maintain'
export type { HybridSearchHit, HybridSearchResult, DocumentChunk, Embedder, LocalSemanticHealth, LocalRetrievalSignals, LocalSemanticAdmission } from './types'
