export { chunkDocument, chunkText, chunkIdFor } from './chunk'
export { CHUNKING_VERSION } from './types'
export { reciprocalRankFusion } from './rrf'
export { searchLocalHybrid } from './retrieve'
export { indexCorpusDocuments } from './indexCorpus'
export { createFakeEmbedder, createQueryEmbedder, createUnavailableEmbedder } from './embedder'
export { SqliteVectorStore } from './vectors'
export { prepareLocalEmbeddingModel } from './prepareModel'
export { localModelGovernance, resolveHybridPaths, localOnnxModelPresent } from './modelStore'
export type { HybridSearchHit, HybridSearchResult, DocumentChunk, Embedder } from './types'
