/**
 * God's Eye coverage matrix — the honest product surface for Terra world-awareness.
 *
 * Do NOT report GOD'S EYE FULLY ACTIVE. Terrain, imagery, buildings, and Live Intel rendering
 * are necessary but not sufficient. This matrix is the source of truth for what is actually
 * live, static, partial, or unavailable. Global ambition never implies every data class is
 * globally live.
 */

export const GODS_EYE_LAYER_GROUPS = ['EARTH', 'URBAN', 'MOBILITY', 'STREET', 'INTELLIGENCE', 'TIME'] as const
export type GodsEyeLayerGroup = (typeof GODS_EYE_LAYER_GROUPS)[number]

export const GODS_EYE_COVERAGE_SCOPES = ['GLOBAL', 'REGIONAL', 'LOCAL', 'PARTIAL', 'NO_COVERAGE', 'AUTH_REQUIRED'] as const
export type GodsEyeCoverageScope = (typeof GODS_EYE_COVERAGE_SCOPES)[number]

export const GODS_EYE_DATA_MODES = ['LIVE', 'STATIC', 'CACHED', 'STALE', 'PARTIAL', 'NO_COVERAGE', 'AUTH_REQUIRED', 'UNAVAILABLE'] as const
export type GodsEyeDataMode = (typeof GODS_EYE_DATA_MODES)[number]

export const GODS_EYE_ACTIVATION_STATES = ['ACTIVE_WITH_GAPS', 'FULLY_ACTIVE'] as const
export type GodsEyeActivationState = (typeof GODS_EYE_ACTIVATION_STATES)[number]

/** Product rule: never claim FULLY_ACTIVE while any required class is partial/unavailable. */
export const GODS_EYE_ACTIVATION_STATE: GodsEyeActivationState = 'ACTIVE_WITH_GAPS'

export type GodsEyeCoverageRow = {
  id: string
  group: GodsEyeLayerGroup
  label: string
  coverageScope: GodsEyeCoverageScope
  coverageDetail: string
  dataMode: GodsEyeDataMode
  livePhase: 'LIVE' | 'STATIC' | 'NO_COVERAGE' | 'UNAVAILABLE' | 'AUTH_REQUIRED' | 'PROVIDER_DEPENDENT'
  sources: readonly string[]
  catalogLayerIds: readonly string[]
  /** Street-level objects stay hidden at global zoom. */
  streetLevel: boolean
  honesty: string
}

export const GODS_EYE_COVERAGE_MATRIX: readonly GodsEyeCoverageRow[] = [
  {
    id: 'terrain',
    group: 'EARTH',
    label: 'Terrain',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['Cesium World Terrain', 'ownable DEM lane (NOT_INGESTED until ingested)'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Cesium World Terrain when ion is configured. Ownable DEM is a separate lane and stays NOT_INGESTED until a real dataset is ingested. No silent ellipsoid fake mountains.',
  },
  {
    id: 'imagery',
    group: 'EARTH',
    label: 'Imagery',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / PARTIAL DETAIL',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['NASA GIBS True Color', 'Cesium ion World Imagery'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'GIBS is the global photographic surface. ion World Imagery is close-range only and may be unavailable without ion.',
  },
  {
    id: 'elevation',
    group: 'EARTH',
    label: 'Elevation',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / STREAM_ONLY',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['Cesium World Terrain pick heights', 'ownable DEM lane (NOT_INGESTED)'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Click→Info ground picks report Cesium terrain height when ion terrain is live. Ownable OpenTopography DEM stays NOT_INGESTED. Same terrain stack — not a second globe.',
  },
  {
    id: 'volcanoes',
    group: 'EARTH',
    label: 'Volcanoes',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / NAMED INCIDENTS',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['NASA EONET volcanoes'],
    catalogLayerIds: ['nasa_eonet_volcanoes'],
    streetLevel: false,
    honesty: 'Same NASA EONET volcanoes catalog already used by Hazards/Live Intel. Not a duplicate feed.',
  },
  {
    id: 'storms',
    group: 'EARTH',
    label: 'Storms',
    coverageScope: 'PARTIAL',
    coverageDetail: 'GLOBAL STORMS / CONES LINKED',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['NHC current storms'],
    catalogLayerIds: ['nhc_current_storms'],
    streetLevel: false,
    honesty: 'Same NHC catalog already used by Hazards. Forecast cones are linked, not fabricated.',
  },
  {
    id: 'weather',
    group: 'EARTH',
    label: 'Weather',
    coverageScope: 'PARTIAL',
    coverageDetail: 'GLOBAL FORECAST / US ALERTS',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['MET Norway', 'Open-Meteo', 'NWS CAP alerts'],
    catalogLayerIds: ['met_no', 'open_meteo', 'nws_severe_weather_alerts'],
    streetLevel: false,
    honesty: 'Point forecasts are query-bounded. NWS alerts are United States only. No invented global radar mosaic.',
  },
  {
    id: 'earthquakes',
    group: 'EARTH',
    label: 'Earthquakes',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['USGS earthquake feed', 'USGS catalog'],
    catalogLayerIds: ['usgs_earthquake_feed', 'usgs_earthquake'],
    streetLevel: false,
    honesty: 'USGS observed events only. Empty is a real empty catalog, not "all clear."',
  },
  {
    id: 'fires',
    group: 'EARTH',
    label: 'Fires',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / NAMED INCIDENTS',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['NASA EONET wildfires'],
    catalogLayerIds: ['nasa_eonet_wildfires'],
    streetLevel: false,
    honesty: 'Named incidents via EONET, not a raw thermal-anomaly heatmap.',
  },
  {
    id: 'hazards',
    group: 'EARTH',
    label: 'Hazards',
    coverageScope: 'PARTIAL',
    coverageDetail: 'GLOBAL STORMS / US TSUNAMI / NAMED FLOODS',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['NHC storms', 'NASA EONET volcanoes/floods', 'NOAA NTWC tsunami'],
    catalogLayerIds: ['nhc_current_storms', 'nasa_eonet_volcanoes', 'nasa_eonet_floods', 'tsunami_gov'],
    streetLevel: false,
    honesty: 'Forecast cones are linked, not fabricated. Most tsunami bulletins are Information statements.',
  },
  {
    id: 'buildings',
    group: 'URBAN',
    label: 'Buildings',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / PARTIAL DETAIL',
    dataMode: 'STATIC',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap Overpass', 'Cesium OSM Buildings fallback'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'OSM footprints at city/local/street zoom. Height is SOURCE or INFERRED, never a measured occupant. Coverage density follows OSM, not a global 3D city model.',
  },
  {
    id: 'roads',
    group: 'URBAN',
    label: 'Roads',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / DATASET DEPENDENT',
    dataMode: 'STATIC',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap Overpass'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Major roads at city zoom; residential streets at neighborhood zoom. This is map geometry, not live traffic.',
  },
  {
    id: 'intersections',
    group: 'URBAN',
    label: 'Intersections',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / DATASET DEPENDENT',
    dataMode: 'STATIC',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap Overpass'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Shown only where OSM tags a traffic-signal node. Street-level only. Not a complete global intersection census.',
  },
  {
    id: 'traffic_signals',
    group: 'URBAN',
    label: 'Traffic signals',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / DATASET DEPENDENT',
    dataMode: 'STATIC',
    livePhase: 'NO_COVERAGE',
    sources: ['OpenStreetMap Overpass (infrastructure only)'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'STATUS: STATIC INFRASTRUCTURE. LIVE PHASE: NO_COVERAGE. OSM geometry never becomes RED/YELLOW/GREEN. No public live-phase feed is wired.',
  },
  {
    id: 'traffic_cameras',
    group: 'URBAN',
    label: 'Traffic cameras',
    coverageScope: 'REGIONAL',
    coverageDetail: 'REGIONAL / AGENCY_DEPENDENT',
    dataMode: 'LIVE',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['OHGO / ODOT (Ohio)', 'Caltrans CWWP2 (California)', 'Fintraffic Digitraffic (Finland)', 'Ontario 511', 'Québec 511', 'Hong Kong TD', '511NY official viewer'],
    catalogLayerIds: ['ohgo_cameras', 'caltrans_cctv', 'digitraffic_road_cameras', 'ontario_511_cameras', 'quebec_511_cameras', 'hong_kong_td_cameras'],
    streetLevel: true,
    honesty: 'Public agency stills only. Regional / agency-dependent. Caltrans CWWP2 stills are keyless. 511NY is official-viewer only (no redistributable API without an Iteris key). Outside those envelopes: NO_COVERAGE. Never scrape private or access-controlled cameras.',
  },
  {
    id: 'transit_urban',
    group: 'URBAN',
    label: 'Transit',
    coverageScope: 'PARTIAL',
    coverageDetail: 'LOCAL / POI ONLY',
    dataMode: 'PARTIAL',
    livePhase: 'NO_COVERAGE',
    sources: ['OpenStreetMap nearby landmarks (transit POIs)'],
    catalogLayerIds: ['nearby_landmarks'],
    streetLevel: true,
    honesty: 'Named transit POIs near the active location. No live GTFS/vehicle positions are wired. LIVE PHASE: NO_COVERAGE.',
  },
  {
    id: 'addresses',
    group: 'URBAN',
    label: 'Addresses',
    coverageScope: 'PARTIAL',
    coverageDetail: 'LOCAL / SOURCED TAGS',
    dataMode: 'PARTIAL',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap addr:*', 'Overture identity when a Re:Earth feature carries GERS'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'OSM addr:* is the live identity. No competing Overture address store. Missing tags stay unlabeled. Never infer a house number from a neighbor.',
  },
  {
    id: 'road_traffic',
    group: 'MOBILITY',
    label: 'Road traffic',
    coverageScope: 'REGIONAL',
    coverageDetail: 'REGIONAL / PROVIDER DEPENDENT',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['DriveBC Open511', 'Ontario 511', 'Québec 511', 'WSDOT/Iowa/KYTC WZDx', 'WebTRIS (historical)', 'JARTIC (hourly volumes)'],
    catalogLayerIds: [
      'drivebc_events',
      'ontario_511_events',
      'quebec_511_events',
      'wzdx_wsdot',
      'wzdx_iowa_dot',
      'wzdx_kytc',
      'webtris',
      'jartic_traffic_volumes',
    ],
    streetLevel: false,
    honesty: 'Incidents/closures where an agency feed exists. JARTIC hourly traffic volumes are LIVE catalog retrieval of the latest published hour-band (typically ~2h behind wall clock) — LIVE TRAFFIC VOLUMES, not live signal phase. WebTRIS remains historical (~2 months) and is never labeled LIVE. No global congestion mosaic. Empty inside coverage is NO_DATA, not all-clear.',
  },
  {
    id: 'rail',
    group: 'MOBILITY',
    label: 'Rail',
    coverageScope: 'NO_COVERAGE',
    coverageDetail: 'NO_COVERAGE',
    dataMode: 'UNAVAILABLE',
    livePhase: 'NO_COVERAGE',
    sources: ['OSM railway tags (not fetched this pass)'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'No live rail-vehicle feed is installed. OSM railway geometry is not fetched at planet scale. Interface exists; coverage is NO_COVERAGE, not a fake timetable.',
  },
  {
    id: 'aviation',
    group: 'MOBILITY',
    label: 'Aviation',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / VIEW-BOUNDED',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['OpenSky Network'],
    catalogLayerIds: ['opensky'],
    streetLevel: false,
    honesty: 'Live state vectors inside the camera bbox. Coverage is the current view, not every aircraft on Earth at once.',
  },
  {
    id: 'maritime',
    group: 'MOBILITY',
    label: 'Maritime',
    coverageScope: 'REGIONAL',
    coverageDetail: 'REGIONAL / FINLAND EEZ',
    dataMode: 'LIVE',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['Fintraffic Digitraffic AIS'],
    catalogLayerIds: ['digitraffic_marine'],
    streetLevel: false,
    honesty: 'Finnish waters/EEZ only. Outside that envelope: NO_COVERAGE — not a global AIS outage.',
  },
  {
    id: 'public_transit_live',
    group: 'MOBILITY',
    label: 'Public transit (live)',
    coverageScope: 'NO_COVERAGE',
    coverageDetail: 'NO_COVERAGE',
    dataMode: 'UNAVAILABLE',
    livePhase: 'NO_COVERAGE',
    sources: [],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'No authorized live transit-vehicle feed is installed. Do not imply buses/trains are tracked.',
  },
  {
    id: 'street_names',
    group: 'STREET',
    label: 'Street names',
    coverageScope: 'PARTIAL',
    coverageDetail: 'CITY SELECTIVE / NEIGHBORHOOD / STREET',
    dataMode: 'STATIC',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap road name/ref'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Planet/country: hidden. City: major named roads. Neighborhood: street names. Street: names plus sourced house numbers.',
  },
  {
    id: 'house_numbers',
    group: 'STREET',
    label: 'House numbers',
    coverageScope: 'PARTIAL',
    coverageDetail: 'STREET / SOURCED ONLY',
    dataMode: 'PARTIAL',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap addr:housenumber'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Rendered only when addr:housenumber is present on that object. Neighboring properties never fill a missing number.',
  },
  {
    id: 'lanes',
    group: 'STREET',
    label: 'Lanes',
    coverageScope: 'PARTIAL',
    coverageDetail: 'STREET / SOURCED OSM lanes',
    dataMode: 'PARTIAL',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap lanes tag on fetched roads'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Shown only when the OSM lanes tag is present on that way. Highway class never invents a lane count.',
  },
  {
    id: 'road_signs',
    group: 'STREET',
    label: 'Road signs',
    coverageScope: 'NO_COVERAGE',
    coverageDetail: 'NO_COVERAGE / INTERFACE READY',
    dataMode: 'NO_COVERAGE',
    livePhase: 'NO_COVERAGE',
    sources: ['OSM traffic_sign (not fetched this pass)'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Provider-neutral sign class exists on the street-object interface. Overpass does not download planet-wide traffic_sign nodes this pass. NO_COVERAGE, not inferred signs.',
  },
  {
    id: 'entrances',
    group: 'STREET',
    label: 'Entrances',
    coverageScope: 'PARTIAL',
    coverageDetail: 'STREET / SOURCED TAG',
    dataMode: 'PARTIAL',
    livePhase: 'STATIC',
    sources: ['OpenStreetMap entrance tag on the same building'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Entrance is shown only when that building carries an OSM entrance tag. Neighbors never supply an entrance.',
  },
  {
    id: 'panoramax',
    group: 'STREET',
    label: 'Panoramax',
    coverageScope: 'NO_COVERAGE',
    coverageDetail: 'LOCAL / REGIONAL WHEN CONFIGURED',
    dataMode: 'NO_COVERAGE',
    livePhase: 'NO_COVERAGE',
    sources: ['Panoramax self-host / regional instance'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'EVALUATION_ACTIVE architecture. Unconfigured instance = NO_COVERAGE. Never claimed as global Street View.',
  },
  {
    id: 'street_imagery',
    group: 'STREET',
    label: 'Street imagery',
    coverageScope: 'PARTIAL',
    coverageDetail: 'AUTH_REQUIRED / NO_COVERAGE OWN',
    dataMode: 'AUTH_REQUIRED',
    livePhase: 'AUTH_REQUIRED',
    sources: ['MapillaryJS hosted (token)', 'Panoramax instance', 'War Room own imagery (future)'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Street Intelligence viewport: MapillaryJS hosted AUTH_REQUIRED without token; Panoramax LOCAL/REGIONAL when an instance URL is set; own imagery NO_COVERAGE. Cesium stays the globe. No Google Street View.',
  },
  {
    id: 'street_objects',
    group: 'STREET',
    label: 'Street objects',
    coverageScope: 'NO_COVERAGE',
    coverageDetail: 'NO_COVERAGE / INTERFACE ACTIVE',
    dataMode: 'NO_COVERAGE',
    livePhase: 'NO_COVERAGE',
    sources: ['provider-neutral detection interface'],
    catalogLayerIds: [],
    streetLevel: true,
    honesty: 'Detection interface exists. No visual model is verified infrastructure. Label: OBSERVED_BY_MODEL.',
  },
  {
    id: 'live_intel',
    group: 'INTELLIGENCE',
    label: 'Live Intel',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / PARTIAL PROVIDERS',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['USGS', 'public RSS', 'credentialed providers when Commander session authenticates'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Public Earth/RSS may render with AUTH_REQUIRED. Credentialed AIS/Exa stay session-gated. Original language is preserved; English is optional translation.',
  },
  {
    id: 'headlines',
    group: 'INTELLIGENCE',
    label: 'Headlines',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / SOURCE DEPENDENT',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['public RSS / Live Intel panel'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Headlines are source items with provenance. Empty is a real empty set.',
  },
  {
    id: 'breaking',
    group: 'INTELLIGENCE',
    label: 'Breaking',
    coverageScope: 'PARTIAL',
    coverageDetail: 'PARTIAL / SOURCE DEPENDENT',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['Live Intel breaking lane'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Zero breaking items is valid. Never fabricate a flash.',
  },
  {
    id: 'events',
    group: 'INTELLIGENCE',
    label: 'Events',
    coverageScope: 'PARTIAL',
    coverageDetail: 'PARTIAL',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['Live Intel events lane'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Observed events only. No invented battlefield geometry.',
  },
  {
    id: 'conflict',
    group: 'INTELLIGENCE',
    label: 'Conflict',
    coverageScope: 'PARTIAL',
    coverageDetail: 'PARTIAL / RELIEFWEB OPTIONAL',
    dataMode: 'PARTIAL',
    livePhase: 'UNAVAILABLE',
    sources: ['ReliefWeb when RELIEFWEB_APPNAME is set', 'attributed public RSS'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'ReliefWeb stays UNAVAILABLE without RELIEFWEB_APPNAME. Public RSS conflict items remain attributed. No invented boundaries.',
  },
  {
    id: 'local_intel',
    group: 'INTELLIGENCE',
    label: 'Local',
    coverageScope: 'LOCAL',
    coverageDetail: 'LOCAL / ACTIVE LOCATION',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['Live Intel local lane', 'Nominatim reverse', 'nearby landmarks'],
    catalogLayerIds: ['nominatim', 'nearby_landmarks'],
    streetLevel: false,
    honesty: 'Local context follows the active coordinate. No city table of invented neighborhoods.',
  },
  {
    id: 'world_time',
    group: 'TIME',
    label: 'World time',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / IANA',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['IANA via tz-lookup', 'Intl DST', 'NOAA-style solar day/night'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Unresolved coordinates stay UNAVAILABLE. Etc/* zones are PARTIAL. Machine timezone is never used as place time.',
  },
  {
    id: 'event_local_time',
    group: 'TIME',
    label: 'Event-local time',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL / WHEN COORDINATES EXIST',
    dataMode: 'PARTIAL',
    livePhase: 'PROVIDER_DEPENDENT',
    sources: ['event coordinates + IANA'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'Only when the event has real coordinates. No assumed city clock.',
  },
  {
    id: 'day_night',
    group: 'TIME',
    label: 'Day/night',
    coverageScope: 'GLOBAL',
    coverageDetail: 'GLOBAL',
    dataMode: 'LIVE',
    livePhase: 'LIVE',
    sources: ['solar elevation at lat/lon'],
    catalogLayerIds: [],
    streetLevel: false,
    honesty: 'DAY / SUNRISE / SUNSET / NIGHT from solar elevation. Not a city lookup table.',
  },
]

export type GodsEyeClickFeatureClass =
  | 'building'
  | 'road'
  | 'traffic_signal'
  | 'traffic_camera'
  | 'aircraft'
  | 'vessel'
  | 'live_intel'
  | 'terrain'
  | 'street_image'

export const GODS_EYE_CLICK_INFO_LABEL: Record<GodsEyeClickFeatureClass, string> = {
  building: 'BUILDING',
  road: 'ROAD',
  traffic_signal: 'TRAFFIC SIGNAL',
  traffic_camera: 'TRAFFIC CAMERA',
  aircraft: 'AIRCRAFT',
  vessel: 'VESSEL',
  live_intel: 'LIVE INTEL',
  terrain: 'TERRAIN',
  street_image: 'STREET IMAGE',
}

export function godsEyeActivationState(): GodsEyeActivationState {
  return GODS_EYE_ACTIVATION_STATE
}

export function godsEyeRowsByGroup(group: GodsEyeLayerGroup): GodsEyeCoverageRow[] {
  return GODS_EYE_COVERAGE_MATRIX.filter(row => row.group === group)
}

export function liveSignalPhaseFromInfrastructure(): 'NO_COVERAGE' {
  return 'NO_COVERAGE'
}

export function isFabricatedSignalPhase(value: string | null | undefined): boolean {
  if (!value) return false
  const normalized = value.trim().toUpperCase()
  return normalized === 'RED' || normalized === 'YELLOW' || normalized === 'GREEN' || normalized === 'AMBER'
}
