/**
 * WRIM1-RUN-000005 P2 sovereign foundational CLM execution identity.
 * Training authorization is this Commander pass only. After terminal, OFF.
 * STAGE3B remains NO. P3 remains unauthorized.
 */
export const P2_TRAIN_KIND = 'WRIM_FOUNDATIONAL_P2_DIAGNOSTIC' as const
export const P2_AUTHORIZED_RECIPE_SHA256 =
  '5b6237dcad4321111510453c9bfcb6713a8f61a8218c487afd67952a42d18117' as const
export const P2_CLASSIFICATIONS = [
  'P2_SOVEREIGN_FOUNDATIONAL_DIAGNOSTIC_SUCCESS',
  'P2_SOVEREIGN_FOUNDATIONAL_DIAGNOSTIC_MIXED',
  'P2_SOVEREIGN_FOUNDATIONAL_DIAGNOSTIC_INCONCLUSIVE',
  'P2_SOVEREIGN_FOUNDATIONAL_DIAGNOSTIC_FAILED',
  'P2_SOVEREIGN_FOUNDATIONAL_DIAGNOSTIC_STOPPED_BY_POLICY',
  'P2_SOVEREIGN_FOUNDATIONAL_DIAGNOSTIC_INTERRUPTED',
] as const
export type P2Classification = (typeof P2_CLASSIFICATIONS)[number]
