/**
 * WRIM foundational remediation design (design/validation only).
 * Zero optimizer steps. Does not authorize training. STAGE3B remains NO.
 */
export const FOUNDATIONAL_REMEDIATION_DESIGN_ID = 'WRIM1-NEBULA-FOUNDATIONAL-REMEDIATION-DESIGN-000001' as const
export const FOUNDATIONAL_REMEDIATION_DESIGN_STATUS = 'READY' as const
export const FOUNDATIONAL_REMEDIATION_CLASSIFICATION = 'FOUNDATIONAL_REMEDIATION_DESIGN_READY' as const
export const FOUNDATIONAL_OBJECTIVE_RECOMMENDATION = 'C. STAGED_PRETRAINING_THEN_SFT' as const
export const FOUNDATIONAL_ARCHITECTURE_CLASS = 'ARCHITECTURE_ACCEPTABLE_FOR_NEXT_FOUNDATIONAL_PASS' as const
export const FOUNDATIONAL_TOKENIZER_CLASS = 'CONSTRAINING_BUT_USABLE' as const
export const FOUNDATIONAL_PACKING_NEXT = 'DEFICIT_INTERLEAVE_FAMILIES' as const
export const FOUNDATIONAL_EVAL_DECODER = 'GREEDY' as const
export const FOUNDATIONAL_MINIMUM_DIAGNOSTIC_TOKENS = 4_096_000 as const
export const FOUNDATIONAL_PRACTICAL_DEVELOPMENT_TOKENS = 16_384_000 as const
export const FOUNDATIONAL_TARGET_FOUNDATION_TOKENS = 65_536_000 as const
export const FOUNDATIONAL_TOKENS_PER_STEP = 4096 as const
export const FOUNDATIONAL_REMEDIATION_EXECUTION_READINESS = false as const
