import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { ALERT_FEATURE, ALERT_REFERENCE, ALERT_VERIFY_SCRIPT, makeAlertApp } from './alertFixture'
import { mkdtempSync, readFileSync, readdirSync, statSync, renameSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'

/**
 * FIXTURE D — "note-feed" baseline -> persistent ticket desk. Used for the learning proof: MATERIALLY SIMILAR to fixture C (same engineering shape: flag-toggling
 * action sub-resources, derived-state filter, bulk operation, counter endpoint, cross-flag rule, persistence) but NOT identical: different nouns (ticket/note),
 * a different value set (priority low|high|urgent), a different second flag word (closed instead of archived), different routes, file names and environment variable.
 * Generated by a fixed vocabulary map over fixture C, then independently validated (baseline / partial / reference) like every other fixture.
 */
const MAP: [RegExp, string][] = [
  [/ALERTS_FILE/g, 'TICKETS_FILE'], [/alerts\.json/g, 'tickets.json'], [/ALERT/g, 'TICKET'], [/Alert/g, 'Ticket'], [/alert/g, 'ticket'],
  [/Severity/g, 'Priority'], [/severity/g, 'priority'],
  [/\binfo\b/g, 'low'], [/\bwarning\b/g, 'high'], [/\bcritical\b/g, 'urgent'],
  [/archiving/g, 'closing'], [/archived/g, 'closed'], [/Archive/g, 'Close'], [/archive/g, 'close'],
  [/Event(?!Listener)/g, 'Note'], [/event(?!Listener)/g, 'note'],
]
const tr = (s: string) => MAP.reduce((t, [re, to]) => t.replace(re, to), s)
const trKeys = (o: Record<string, string>) => Object.fromEntries(Object.entries(o).map(([k, v]) => [tr(k), tr(v)]))

export const TICKET_FEATURE = { request: tr(ALERT_FEATURE.request), acceptance: ALERT_FEATURE.acceptance.map(tr), hints: ALERT_FEATURE.hints.map(tr) }
export const TICKET_REFERENCE: Record<string, string> = trKeys(ALERT_REFERENCE)
export const TICKET_VERIFY_SCRIPT = tr(ALERT_VERIFY_SCRIPT.replace("severity: 'urgent'", "severity: 'blocker'")) // 'urgent' is the INVALID value in C but a valid one here
export function makeTicketApp(root: string): string {
  const scratch = mkdtempSync(path.join(tmpdir(), 'ticket-base-'))
  makeAlertApp(scratch)
  const walk = (d: string, rel = ''): string[] => readdirSync(d).flatMap((n) => { const p = path.join(d, n); return statSync(p).isDirectory() ? walk(p, path.join(rel, n)) : [path.join(rel, n)] })
  for (const rel of walk(scratch)) { const to = path.join(root, tr(rel)); mkdirSync(path.dirname(to), { recursive: true }); writeFileSync(to, tr(readFileSync(path.join(scratch, rel), 'utf8'))) }
  rmSync(scratch, { recursive: true, force: true })
  return root
}
void renameSync
