/**
 * Council capability registry — index capabilities that actually exist.
 * Does not invent tools. Capability ≠ authority.
 */

import { AUTHORITY_MATRIX_STUB_ROWS } from '@/lib/council/gi/authorityMatrix.stub'
import { FOUNDRY_MUTATION_TOOLS } from '@/lib/council/evidence-board/types'
import { GODS_EYE_CAPABILITY_ID } from '@/lib/terra/godsEye/runtimeState'
import type { CapabilityRecord } from './types'

function cap(record: CapabilityRecord): CapabilityRecord {
  return Object.freeze(record)
}

const INDEXED: CapabilityRecord[] = [
  cap({
    capability_id: 'system.health',
    name: 'Core health probe',
    system: 'Runtime',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'wr.core.health',
    council_executable: true,
    notes: 'GET /api/local/health on 3847',
  }),
  cap({
    capability_id: 'wr.ui.health',
    name: 'UI health probe',
    system: 'Runtime',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'wr.ui.health',
    council_executable: true,
    notes: 'GET /api/health on 3848',
  }),
  cap({
    capability_id: 'wr.ports.list',
    name: 'Port ownership inspect',
    system: 'Runtime',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'wr.ports.list',
    council_executable: true,
    notes: 'ss -ltnp via portInspect',
  }),
  cap({
    capability_id: 'wr.council.backend',
    name: 'Council local backend probe',
    system: 'Council',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'wr.council.backend',
    council_executable: true,
    notes: 'Ollama probe; READY_LOCAL when available',
  }),
  cap({
    capability_id: 'wr.git.branch',
    name: 'Git HEAD inspect',
    system: 'Files',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'wr.git.branch',
    council_executable: true,
    notes: 'rev-parse only',
  }),
  cap({
    capability_id: 'browser.status',
    name: 'Browser Broker status',
    system: 'Broker',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'wr.broker.status',
    council_executable: true,
    notes: 'Existing broker.statusSnapshot',
  }),
  cap({
    capability_id: 'browser.fetch',
    name: 'Browser research fetch',
    system: 'Broker',
    read_or_write: 'read',
    local_or_external: 'external',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'broker.fetch',
    council_executable: true,
    notes: 'Scout workers subordinate; EBC remains SoT',
  }),
  cap({
    capability_id: 'browser.navigate',
    name: 'Browser navigate',
    system: 'Broker',
    read_or_write: 'read',
    local_or_external: 'external',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'broker.navigate',
    council_executable: false,
    notes: 'Exists on Browser Broker. Council research uses broker.fetch, not raw navigate as a truth source.',
  }),
  cap({
    capability_id: 'browser.screenshot',
    name: 'Browser screenshot',
    system: 'Broker',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'broker.screenshot',
    council_executable: true,
    notes: 'Read-only capture. No mutation.',
  }),
  cap({
    capability_id: 'research.web',
    name: 'Web research via EBC',
    system: 'Council',
    read_or_write: 'read',
    local_or_external: 'external',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'evidence-board-council',
    council_executable: true,
    notes: 'DEEP_RESEARCH → EBC. Scouts are not SoT.',
  }),
  cap({
    capability_id: 'files.read',
    name: 'Read repository file',
    system: 'Files',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'foundry.file.read',
    council_executable: false,
    notes: 'Exists in Foundry inspector. Council ENGINEERING does not execute Foundry mutation tools.',
  }),
  cap({
    capability_id: 'terra.search',
    name: 'Terra search',
    system: 'Terra',
    read_or_write: 'read',
    local_or_external: 'hybrid',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'terra',
    council_executable: false,
    notes: 'Terra-owned. Council may consume Terra handoff; does not mutate Terra.',
  }),
  cap({
    capability_id: 'terra.inspect',
    name: 'Terra inspect',
    system: 'Terra',
    read_or_write: 'read',
    local_or_external: 'hybrid',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'terra',
    council_executable: false,
    notes: 'Read-only Terra inspect.',
  }),
  cap({
    capability_id: 'foundry.validate',
    name: 'Foundry validate',
    system: 'Foundry',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'foundry',
    council_executable: false,
    notes: 'Foundry-owned validation. Council does not execute it as a seat.',
  }),
  cap({
    capability_id: 'foundry.build',
    name: 'Foundry build',
    system: 'Foundry',
    read_or_write: 'write',
    local_or_external: 'local',
    reversible: true,
    approval_required: true,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'build.run',
    council_executable: false,
    notes: 'Exists. Council ENGINEERING cannot execute Foundry mutation tools.',
  }),
  cap({
    capability_id: 'git.commit',
    name: 'Git commit',
    system: 'Files',
    read_or_write: 'write',
    local_or_external: 'local',
    reversible: false,
    approval_required: true,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'git.commit',
    council_executable: false,
    notes: 'Dangerous. Commander approval required. Council does not auto-commit.',
  }),
  cap({
    capability_id: 'git.push',
    name: 'Git push',
    system: 'Files',
    read_or_write: 'write',
    local_or_external: 'external',
    reversible: false,
    approval_required: true,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'git.push',
    council_executable: false,
    notes: 'Dangerous. Commander approval required.',
  }),
  cap({
    capability_id: 'deploy.run',
    name: 'Production deploy',
    system: 'Runtime',
    read_or_write: 'write',
    local_or_external: 'external',
    reversible: false,
    approval_required: true,
    financial: false,
    production_mutation: true,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'deploy.run',
    council_executable: false,
    notes: 'Not authorized for this expansion. No /opt overlay.',
  }),
  cap({
    capability_id: 'finance.spend',
    name: 'Spend money',
    system: 'Council',
    read_or_write: 'write',
    local_or_external: 'external',
    reversible: false,
    approval_required: true,
    financial: true,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'none',
    council_executable: false,
    notes: 'No spend executor in Council. Always DENY without Commander authorization.',
  }),
  cap({
    capability_id: 'finance.trade',
    name: 'Trade',
    system: 'Council',
    read_or_write: 'write',
    local_or_external: 'external',
    reversible: false,
    approval_required: true,
    financial: true,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'none',
    council_executable: false,
    notes: 'No trade route.',
  }),
  cap({
    capability_id: 'finance.wager',
    name: 'Wager',
    system: 'Council',
    read_or_write: 'write',
    local_or_external: 'external',
    reversible: false,
    approval_required: true,
    financial: true,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'none',
    council_executable: false,
    notes: 'No wager route.',
  }),
  cap({
    capability_id: 'finance.settlement_submit',
    name: 'Settlement submission',
    system: 'Council',
    read_or_write: 'write',
    local_or_external: 'external',
    reversible: false,
    approval_required: true,
    financial: true,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'none',
    council_executable: false,
    notes: 'No settlement executor.',
  }),
  cap({
    capability_id: 'verification',
    name: 'LUMEN verification',
    system: 'Council',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'LUMEN',
    council_executable: true,
    notes: 'EBC verifier role',
  }),
  cap({
    capability_id: 'adversarial_review',
    name: 'PHOENIX challenge',
    system: 'Council',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'PHOENIX',
    council_executable: true,
    notes: 'Claim support challenge — not SENTINEL',
  }),
  cap({
    capability_id: GODS_EYE_CAPABILITY_ID,
    name: "God's Eye runtime",
    system: 'Terra',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'terra.gods_eye',
    council_executable: false,
    notes: 'Existing Terra God\'s Eye open stack. Council consumes health; it does not mutate Terra.',
  }),
  cap({
    capability_id: 'synthesis',
    name: 'AURORA synthesis',
    system: 'Council',
    read_or_write: 'read',
    local_or_external: 'local',
    reversible: true,
    approval_required: false,
    financial: false,
    production_mutation: false,
    secret_access: false,
    health: 'INDEXED',
    last_success: null,
    last_failure: null,
    latency_ms: null,
    version_provider: 'AURORA',
    council_executable: true,
    notes: 'Board-only synthesis',
  }),
]

export function listIndexedCapabilities(): readonly CapabilityRecord[] {
  return INDEXED
}

export function lookupCapability(id: string): CapabilityRecord | undefined {
  return INDEXED.find(item => item.capability_id === id || item.version_provider === id)
}

export function assertNoInventedCapabilities(): string[] {
  const foundryMutations = FOUNDRY_MUTATION_TOOLS as readonly string[]
  return INDEXED
    .filter(item => foundryMutations.includes(item.version_provider) && item.council_executable)
    .map(item => item.capability_id)
}

export function authorityRowsIndexed(): number {
  return AUTHORITY_MATRIX_STUB_ROWS.length
}
