import type { AuthorityMatrixRow } from './types'

export const AUTHORITY_MATRIX_STUB_ROWS: readonly AuthorityMatrixRow[] = Object.freeze([
  {
    tool_id: 'council.chat.short',
    nl_labels: ['Answer briefly'],
    owner_module: 'Council',
    risk_class: 'LOW',
    authority_class: 'OWNABLE',
    allowed_paths: ['SHORT_PATH'],
    notes: 'SHORT_PATH default dialogue. No six seats.',
  },
  {
    tool_id: 'council.calc.simple',
    nl_labels: ['Calculate', 'What is 45 × 72'],
    owner_module: 'Council',
    risk_class: 'LOW',
    authority_class: 'OWNABLE',
    allowed_paths: ['SHORT_PATH'],
    notes: 'Optional single arithmetic tool on SHORT_PATH.',
  },
  {
    tool_id: 'files.ingest',
    nl_labels: ['Attach file'],
    owner_module: 'Council',
    risk_class: 'LOW',
    authority_class: 'OWNABLE',
    allowed_paths: ['SHORT_PATH', 'AGENT_PATH'],
    notes: 'Hash required. No parse-all.',
  },
  {
    tool_id: 'vision.ingest',
    nl_labels: ['Look at image'],
    owner_module: 'Council',
    risk_class: 'LOW',
    authority_class: 'OWNABLE',
    allowed_paths: ['SHORT_PATH', 'AGENT_PATH'],
    notes: 'AssetRef required. No fake SEEING.',
  },
  {
    tool_id: 'audio.asr',
    nl_labels: ['Transcribe audio'],
    owner_module: 'Council',
    risk_class: 'MED',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['AGENT_PATH'],
    notes: 'HOLD if retention unknown. Cloud ASR is not auto.',
  },
  {
    tool_id: 'voice.session.start',
    nl_labels: ['Start voice session'],
    owner_module: 'Council',
    risk_class: 'MED',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['SHORT_PATH', 'AGENT_PATH'],
    notes: 'Sets capture_truth. No fake LISTENING.',
  },
  {
    tool_id: 'voice.capture',
    nl_labels: ['Use microphone'],
    owner_module: 'Council',
    risk_class: 'MED',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['SHORT_PATH', 'AGENT_PATH'],
    notes: 'LISTENING only if capturing with session id.',
  },
  {
    tool_id: 'email.draft',
    nl_labels: ['Draft email'],
    owner_module: 'Connector',
    risk_class: 'LOW',
    authority_class: 'OWNABLE',
    allowed_paths: ['SHORT_PATH', 'AGENT_PATH'],
    notes: 'Draft only. No send.',
  },
  {
    tool_id: 'email.send',
    nl_labels: ['Send email'],
    owner_module: 'Connector',
    risk_class: 'HIGH',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['AGENT_PATH'],
    dangerous_kind: 'email_send',
    notes: 'Maps to existing dangerous email_send. Never auto on SHORT_PATH.',
  },
  {
    tool_id: 'foundry.handoff',
    nl_labels: ['Send to Foundry'],
    owner_module: 'Foundry',
    risk_class: 'HIGH',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['HANDOFF'],
    notes: 'Typed handoff stub only. No git, no patch, no Foundry execution.',
  },
  {
    tool_id: 'broker.research',
    nl_labels: ['Research on the web'],
    owner_module: 'Broker',
    risk_class: 'MED',
    authority_class: 'HOLD',
    allowed_paths: ['AGENT_PATH', 'HANDOFF'],
    notes: 'STREAM_ONLY mapped to HOLD. Existing Browser Broker owns browse.',
  },
  {
    tool_id: 'hvs.job',
    nl_labels: ['Open in HVS'],
    owner_module: 'HVS',
    risk_class: 'HIGH',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['HANDOFF'],
    notes: 'Handoff only. No HVS execution in GI-ENG-01.',
  },
  {
    tool_id: 'terra.query',
    nl_labels: ['Query world state'],
    owner_module: 'Terra',
    risk_class: 'LOW',
    authority_class: 'OWNABLE',
    allowed_paths: ['AGENT_PATH', 'HANDOFF'],
    notes: 'Read-only. No Terra write from chat.',
  },
  {
    tool_id: 'media.gen.thin',
    nl_labels: ['Make a simple image'],
    owner_module: 'Media',
    risk_class: 'MED',
    authority_class: 'REQUIRE_AUTH',
    allowed_paths: ['HANDOFF'],
    notes: 'Not HVS NLE. Not implemented in GI-ENG-01.',
  },
  {
    tool_id: 'computer_use.os',
    nl_labels: ['Computer use'],
    owner_module: 'Foundry',
    risk_class: 'CRITICAL',
    authority_class: 'REFUSE',
    allowed_paths: [],
    notes: 'REFUSE for this mission.',
  },
  {
    tool_id: 'council.git.push',
    nl_labels: ['Git push'],
    owner_module: 'Foundry',
    risk_class: 'CRITICAL',
    authority_class: 'REFUSE',
    allowed_paths: [],
    dangerous_kind: 'push',
    notes: 'Foundry-only forever. Council cannot push.',
  },
])
