import type { EvidenceAttachment, LootOpportunity, LootStatus } from './types'
import { LOOT_STATUSES } from './types'
import { rankLootOpportunity, type LootRanking } from './ranking'

export type IncomeLootConsoleEvidence = Pick<EvidenceAttachment, 'id' | 'kind' | 'truthState' | 'capturedAt' | 'originalFilename' | 'mimeType'>
export type IncomeLootConsoleOpportunity = Omit<LootOpportunity, 'ownerUserId'> & { ranking: LootRanking; evidence: IncomeLootConsoleEvidence[]; classification: 'LIVE' | 'HISTORICAL' | 'PROVIDER CONFIRMED' | 'SOURCE UNAVAILABLE'; estimatedHourlyValue: { amount: number; currency: string } | null }
export type IncomeLootConsoleViewModel = { dataAvailable: boolean; durableAvailable: false; migrationRequired: true; opportunities: IncomeLootConsoleOpportunity[]; liveOpportunities: IncomeLootConsoleOpportunity[]; historicalOpportunities: IncomeLootConsoleOpportunity[]; inProgress: IncomeLootConsoleOpportunity[]; statusCounts: Record<LootStatus, number>; estimatedByCurrency: Array<{ currency: string; amount: number }> }
function classification(opportunity: LootOpportunity): IncomeLootConsoleOpportunity['classification'] { if (opportunity.evidenceLabel === 'HISTORICAL_PATTERN_BASED' || opportunity.provenance.some(item => item.isHistorical)) return 'HISTORICAL'; if (opportunity.evidenceLabel === 'PROVIDER_CONFIRMED') return 'PROVIDER CONFIRMED'; return opportunity.provenance.length ? 'LIVE' : 'SOURCE UNAVAILABLE' }
function safeSourceUrl(value:string|null):string|null{if(!value)return null;try{const url=new URL(value);for(const key of [...url.searchParams.keys()])if(/(?:key|token|secret|password|credential|auth)/i.test(key))url.searchParams.delete(key);return url.toString()}catch{return null}}
export function buildIncomeLootConsoleViewModel(input: { dataAvailable: boolean; opportunities: LootOpportunity[]; evidence: EvidenceAttachment[]; now?: number }): IncomeLootConsoleViewModel { const statusCounts=Object.fromEntries(LOOT_STATUSES.map(status=>[status,0])) as Record<LootStatus,number>; const evidenceByOpportunity=new Map<string,IncomeLootConsoleEvidence[]>(); for(const attachment of input.evidence){const entries=evidenceByOpportunity.get(attachment.linkedOpportunityId)??[];entries.push({id:attachment.id,kind:attachment.kind,truthState:attachment.truthState,capturedAt:attachment.capturedAt,originalFilename:attachment.originalFilename,mimeType:attachment.mimeType});evidenceByOpportunity.set(attachment.linkedOpportunityId,entries)} const opportunities=input.opportunities.map(opportunity=>{statusCounts[opportunity.status]+=1;const amount=opportunity.estimatedReward?.amount;const estimatedHourlyValue=amount!=null&&opportunity.estimatedTimeMinutes&&opportunity.estimatedTimeMinutes>0?{amount:Math.round((amount/opportunity.estimatedTimeMinutes*60)*100)/100,currency:opportunity.estimatedReward!.currency}:null;const safeOpportunity=Object.fromEntries(Object.entries(opportunity).filter(([key])=>key!=='ownerUserId')) as Omit<LootOpportunity,'ownerUserId'>;safeOpportunity.provenance=safeOpportunity.provenance.map(source=>({...source,sourceUrl:safeSourceUrl(source.sourceUrl)}));return{...safeOpportunity,ranking:rankLootOpportunity(opportunity,input.now),evidence:evidenceByOpportunity.get(opportunity.id)??[],classification:classification(opportunity),estimatedHourlyValue}}).sort((a,b)=>b.ranking.score-a.ranking.score||b.confidence-a.confidence||b.discoveredAt.localeCompare(a.discoveredAt)); const liveOpportunities=opportunities.filter(item=>item.classification==='LIVE'||item.classification==='PROVIDER CONFIRMED');const historicalOpportunities=opportunities.filter(item=>item.classification==='HISTORICAL');const inProgress=opportunities.filter(item=>['STARTED','SUBMITTED','PENDING'].includes(item.status));const totals=new Map<string,number>();for(const opportunity of opportunities){const reward=opportunity.estimatedReward;if(reward?.basis==='ESTIMATED'&&reward.amount!==null)totals.set(reward.currency,(totals.get(reward.currency)??0)+reward.amount)}return{dataAvailable:input.dataAvailable,durableAvailable:false,migrationRequired:true,opportunities,liveOpportunities,historicalOpportunities,inProgress,statusCounts,estimatedByCurrency:[...totals].map(([currency,amount])=>({currency,amount}))} }
