export const PARTICIPANT_ACCOUNT_STATUSES = ['ACCOUNT_NOT_CREATED','ACCOUNT_ACTIVE','ACCOUNT_VERIFICATION_PENDING','WAITLISTED','ACCOUNT_RESTRICTED'] as const
export type ParticipantAccountStatus = (typeof PARTICIPANT_ACCOUNT_STATUSES)[number]
export const PARTICIPANT_CONNECTION_MODES = ['PUBLIC_DISCOVERY','USER_AUTH_REQUIRED','APP_LOCATION_REQUIRED','PARTNER_INTEGRATION','UNSUPPORTED'] as const
export type ParticipantConnectionMode = (typeof PARTICIPANT_CONNECTION_MODES)[number]
export type ParticipantAutomationCapabilities = { canDiscoverPublicly:boolean; canReadPersonalFeed:boolean; canPrepareScreener:boolean; canAutofillKnownAnswers:boolean; canSubmitAutomatically:boolean; requiresCommanderReview:boolean; requiresMobileApp:boolean; requiresLocation:boolean; requiresAccountAuthentication:boolean }
export type ParticipantSourceConnection = { id:string; ownerUserId:string; sourceId:string; accountStatus:ParticipantAccountStatus; connectionMode:ParticipantConnectionMode; capabilities:ParticipantAutomationCapabilities; updatedAt:string }
export const PARTICIPANT_SENSITIVITIES = ['STANDARD','SENSITIVE','RESTRICTED'] as const
export type ParticipantSensitivity = (typeof PARTICIPANT_SENSITIVITIES)[number]
export type ParticipantProfileFact = { id:string; ownerUserId:string; key:string; value:unknown; category:string; source:'COMMANDER_PROVIDED'|'COMMANDER_APPROVED'; approvedByCommander:true; createdAt:string; updatedAt:string; lastConfirmedAt:string|null; sensitivity:ParticipantSensitivity }
export type ParticipantProfile = { ownerUserId:string; facts:ParticipantProfileFact[] }
export const SCREENER_QUESTION_TYPES = ['SINGLE_CHOICE','MULTIPLE_CHOICE','BOOLEAN','SHORT_TEXT','NUMBER','DATE','LOCATION','RANKING_SCALE','FREE_RESPONSE'] as const
export type ScreenerQuestionType = (typeof SCREENER_QUESTION_TYPES)[number]
export const ANSWER_CLASSIFICATIONS = ['KNOWN_FACT','NEEDS_COMMANDER_ANSWER','SUBJECTIVE','TIME_SENSITIVE','SENSITIVE','CONFLICT_WITH_EXISTING_PROFILE'] as const
export type AnswerClassification = (typeof ANSWER_CLASSIFICATIONS)[number]
export type ScreenerQuestion = { questionId:string; provider:string; opportunityId:string; prompt:string; type:ScreenerQuestionType; choices:string[]; required:boolean; sensitivity:ParticipantSensitivity; answerClassification?:AnswerClassification }
export type ScreenerAnswerResult = { classification:AnswerClassification; proposedAnswer:unknown|null; supportingFactIds:string[] }
export const PARTICIPANT_AUTOMATION_ACTIONS = ['DISCOVER','FILTER','RANK','PREPARE','AUTOFILL','SUBMIT','TRACK'] as const
export type ParticipantAutomationAction = (typeof PARTICIPANT_AUTOMATION_ACTIONS)[number]
export type ParticipantAutomationAuthority = Record<ParticipantAutomationAction, boolean>
export const defaultParticipantAuthority = (): ParticipantAutomationAuthority => ({ DISCOVER:true, FILTER:true, RANK:true, PREPARE:true, AUTOFILL:true, SUBMIT:false, TRACK:true })
export const PARTICIPANT_APPLICATION_STATUSES = ['NOT_STARTED','SCREENING','READY_TO_SUBMIT','SUBMITTED','PENDING','ACCEPTED','SCHEDULED','COMPLETED','REJECTED','EXPIRED','PAYMENT_PENDING','PAID'] as const
export type ParticipantApplicationStatus = (typeof PARTICIPANT_APPLICATION_STATUSES)[number]
export type ParticipantApplication = { id:string; ownerUserId:string; opportunityId:string; sourceId:string; status:ParticipantApplicationStatus; updatedAt:string }
export const RESEARCH_SAFETY_CLASSIFICATIONS = ['NON_INVASIVE_CONFIRMED','UNKNOWN_REVIEW_REQUIRED','EXCLUDED_INVASIVE'] as const
export type ResearchSafetyClassification = (typeof RESEARCH_SAFETY_CLASSIFICATIONS)[number]
export type EarnNowTruth = 'LIVE_PAID_OPPORTUNITY_VERIFIED'|'MARKETPLACE_ACTIVE_ACCOUNT_REQUIRED'|'LIVE_OPPORTUNITY_COMPENSATION_UNKNOWN'|'ACCESS_BLOCKED'|'NO_USEFUL_FEED'
export type ParticipantOpportunityAssessment = { isReal:boolean; historicalOnly:boolean; accessPathKnown:boolean; officialActionUrl:string|null; safety:ResearchSafetyClassification; compensationAmount:number|null; truth:EarnNowTruth }

const secretPattern = /password|passcode|credential|token|cookie|\bsession\b|verification code|\bpin\b|\botp\b|api[ -]?key|\blogin\b/i
const subjectivePattern = /\b(prefer|opinion|feel|think|why do you|describe your)\b/i
const timePattern = /\b(today|current|currently|last \d+|past \d+|in the last|recent)\b/i
const sensitivePattern = /\b(health|medical|diagnosis|disability|race|ethnicity|sexual orientation|birth date|date of birth|address|government|social security|financial account|biometric)\b/i
export function classifyResearchSafety(text:string): ResearchSafetyClassification { const value=text.toLowerCase(); const invasiveCheck=value.replace(/\bnon[-\s]?invasive\b/g,''); return /experimental drug|medication trial|vaccine|injection|experimental chemical|ingest|implant|invasive|induced illness|induced injury/.test(invasiveCheck)?'EXCLUDED_INVASIVE':/survey|interview|focus group|usability|website testing|app testing|behavioral|observational|accessibility|product feedback|health-experience|non[-\s]?invasive/.test(value)?'NON_INVASIVE_CONFIRMED':'UNKNOWN_REVIEW_REQUIRED' }
export function isEarnNowEligible(value:ParticipantOpportunityAssessment):boolean { return value.isReal&&!value.historicalOnly&&value.accessPathKnown&&Boolean(value.officialActionUrl)&&value.safety==='NON_INVASIVE_CONFIRMED' }
function escapeRegExp(value:string):string { return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&') }
function matchingFact(question:ScreenerQuestion, facts:ParticipantProfileFact[]):ParticipantProfileFact|undefined { const prompt=question.prompt.toLowerCase(); return facts.find(f=>f.approvedByCommander&&new RegExp(`\\b${escapeRegExp(f.key.toLowerCase())}\\b`).test(prompt)) }
export function answerScreenerQuestion(question:ScreenerQuestion, profile:ParticipantProfile):ScreenerAnswerResult { const prompt=question.prompt; if(secretPattern.test(prompt)) return {classification:'SENSITIVE',proposedAnswer:null,supportingFactIds:[]}; if(subjectivePattern.test(prompt)||question.type==='FREE_RESPONSE'||question.type==='RANKING_SCALE') return {classification:'SUBJECTIVE',proposedAnswer:null,supportingFactIds:[]}; if(timePattern.test(prompt)) return {classification:'TIME_SENSITIVE',proposedAnswer:null,supportingFactIds:[]}; if(question.sensitivity!=='STANDARD'||sensitivePattern.test(prompt)) return {classification:'SENSITIVE',proposedAnswer:null,supportingFactIds:[]}; const fact=matchingFact(question,profile.facts); return fact?{classification:'KNOWN_FACT',proposedAnswer:fact.value,supportingFactIds:[fact.id]}:{classification:'NEEDS_COMMANDER_ANSWER',proposedAnswer:null,supportingFactIds:[]} }
export type RecordCommanderAnswerInput = { ownerUserId:string; question:ScreenerQuestion; key:string; value:unknown; category:string; approvedByCommander:boolean; now?:string }
export type RecordCommanderAnswerResult = { code:'RECORDED'|'APPROVAL_REQUIRED'|'CREDENTIAL_EXCLUDED'|'CONFLICT_REQUIRES_RESOLUTION'; fact:ParticipantProfileFact|null; conflictingFactIds:string[] }
export function recordCommanderAnswer(profile:ParticipantProfile,input:RecordCommanderAnswerInput):RecordCommanderAnswerResult { if(!input.approvedByCommander) return {code:'APPROVAL_REQUIRED',fact:null,conflictingFactIds:[]}; if(profile.ownerUserId!==input.ownerUserId) return {code:'CONFLICT_REQUIRES_RESOLUTION',fact:null,conflictingFactIds:[]}; if(secretPattern.test(input.key)||secretPattern.test(input.question.prompt)) return {code:'CREDENTIAL_EXCLUDED',fact:null,conflictingFactIds:[]}; const conflicts=profile.facts.filter(f=>f.key===input.key&&JSON.stringify(f.value)!==JSON.stringify(input.value)); if(conflicts.length) return {code:'CONFLICT_REQUIRES_RESOLUTION',fact:null,conflictingFactIds:conflicts.map(f=>f.id)}; const now=input.now??new Date().toISOString(); const fact:ParticipantProfileFact={id:`participant_fact_${profile.facts.length+1}`,ownerUserId:input.ownerUserId,key:input.key,value:input.value,category:input.category,source:'COMMANDER_PROVIDED',approvedByCommander:true,createdAt:now,updatedAt:now,lastConfirmedAt:now,sensitivity:input.question.sensitivity}; profile.facts.push(fact); return {code:'RECORDED',fact,conflictingFactIds:[]} }
export function submissionBoundary(connection:ParticipantSourceConnection, authority:ParticipantAutomationAuthority, requiredAnswers:ScreenerAnswerResult[], safety:ResearchSafetyClassification):'SUBMISSION_PERMITTED'|'MANUAL_ACTION_REQUIRED' { return connection.capabilities.canSubmitAutomatically&&authority.SUBMIT&&connection.accountStatus==='ACCOUNT_ACTIVE'&&requiredAnswers.every(answer=>answer.classification==='KNOWN_FACT')&&safety==='NON_INVASIVE_CONFIRMED'?'SUBMISSION_PERMITTED':'MANUAL_ACTION_REQUIRED' }
