export const LOOT_CATEGORIES = ['SURVEY', 'STORE_SCAN', 'RECEIPT_REWARD', 'CASHBACK', 'PRICE_MATCH', 'DEAL', 'POINTS_REWARD', 'OTHER_REWARD'] as const
export type LootCategory = (typeof LOOT_CATEGORIES)[number]
export const LOOT_STATUSES = ['DISCOVERED', 'ELIGIBLE', 'STARTED', 'SUBMITTED', 'PENDING', 'VERIFIED', 'REWARDED', 'CASHOUT_READY', 'CASHED_OUT', 'REJECTED', 'EXPIRED'] as const
export type LootStatus = (typeof LOOT_STATUSES)[number]
export const LOOT_EVIDENCE_LABELS = ['LIVE_SIGNAL_BACKED', 'HISTORICAL_PATTERN_BASED', 'PROVIDER_CONFIRMED'] as const
export type LootEvidenceLabel = (typeof LOOT_EVIDENCE_LABELS)[number]
export const VALUE_BASES = ['ESTIMATED', 'CONFIRMED', 'CASH_RECEIVED'] as const
export type ValueBasis = (typeof VALUE_BASES)[number]
export const LOOT_PROVENANCE_SOURCE_TYPES = ['web_search', 'provider_api', 'commander_manual', 'historical_fallback'] as const
export type LootProvenanceSourceType = (typeof LOOT_PROVENANCE_SOURCE_TYPES)[number]
export type LootProvenance = { sourceAdapterId: string; sourceType: LootProvenanceSourceType; sourceUrl: string | null; retrievedAt: string; searchQuery: string | null; providerRecordId: string | null; freshness: 'current' | 'historical' | 'unknown'; isHistorical: boolean }
export type LootValue = { amount: number | null; currency: string; basis: ValueBasis; notes: string }
export type LootOpportunity = { id: string; ownerUserId: string; provider: string; providerOpportunityId: string | null; title: string; description: string | null; category: LootCategory; estimatedReward: LootValue | null; estimatedTimeMinutes: number | null; expiresAt: string | null; eligibility: string[]; locationRequirement: string | null; evidenceRequirement: string[]; externalUrl: string | null; status: LootStatus; evidenceLabel: LootEvidenceLabel; confidence: number; provenance: LootProvenance[]; discoveredAt: string; updatedAt: string; commanderApprovalRequired: true }
export type SurveyProgress = { opportunityId: string; status: LootStatus; startedAt: string | null; submittedAt: string | null }
export type StoreMission = { opportunityId: string; location: string | null; status: LootStatus; scheduledAt: string | null }
export type ReceiptRecord = { id: string; opportunityId: string; status: LootStatus; evidenceIds: string[] }
export const LEDGER_ENTRY_TYPES = ['ESTIMATED', 'CONFIRMED', 'CASH_RECEIVED', 'ADJUSTMENT'] as const
export type LedgerEntryType = (typeof LEDGER_ENTRY_TYPES)[number]
export type RewardLedgerEntry = { id: string; opportunityId: string; type: LedgerEntryType; value: LootValue; evidenceIds: string[]; createdAt: string }
export type PriceMatchRecord = { id: string; opportunityId: string; claimedValue: LootValue | null; status: LootStatus }
export type DealBundle = { id: string; title: string; opportunityIds: string[]; estimatedValue: LootValue | null }
export const CASHOUT_STATUSES = ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'COMPLETED', 'REJECTED'] as const
export type CashoutStatus = (typeof CASHOUT_STATUSES)[number]
export type CashoutRequest = { id: string; ownerUserId: string; status: CashoutStatus; requestedValue: LootValue; commanderApprovalRequired: true; createdAt: string }
export const EVIDENCE_ATTACHMENT_KINDS = ['receipt', 'screenshot', 'provider_confirmation', 'transaction_reference', 'reward_balance', 'payout_confirmation'] as const
export type EvidenceAttachmentKind = (typeof EVIDENCE_ATTACHMENT_KINDS)[number]
export const EVIDENCE_VISIBILITIES = ['commander_only', 'workforce'] as const
export type EvidenceVisibility = (typeof EVIDENCE_VISIBILITIES)[number]
export type EvidenceAttachment = { id: string; kind: EvidenceAttachmentKind; fileRef: string; capturedAt: string; linkedRecordId: string; redacted: boolean; visibility: EvidenceVisibility }
