export const LOOT_CATEGORIES = ['SURVEY', 'STORE_SCAN', 'RECEIPT_REWARD', 'CASHBACK', 'PRICE_MATCH', 'DEAL', 'POINTS_REWARD', 'OTHER_REWARD'] as const
export type LootCategory = (typeof LOOT_CATEGORIES)[number]
export const LOOT_STATUSES = ['DISCOVERED', 'ELIGIBLE', 'STARTED', 'SUBMITTED', 'PENDING', 'VERIFIED', 'REWARDED', 'CASHOUT_READY', 'CASHED_OUT', 'REJECTED', 'EXPIRED'] as const
export type LootStatus = (typeof LOOT_STATUSES)[number]
export const LOOT_EVIDENCE_LABELS = ['LIVE_SIGNAL_BACKED', 'HISTORICAL_PATTERN_BASED', 'PROVIDER_CONFIRMED'] as const
export type LootEvidenceLabel = (typeof LOOT_EVIDENCE_LABELS)[number]
export const VALUE_BASES = ['ESTIMATED', 'CONFIRMED', 'CASH_RECEIVED'] as const
export type ValueBasis = (typeof VALUE_BASES)[number]
export const LOOT_PROVENANCE_SOURCE_TYPES = ['web_search', 'provider_api', 'commander_manual', 'historical_fallback'] as const
export type LootProvenanceSourceType = (typeof LOOT_PROVENANCE_SOURCE_TYPES)[number]
export type LootProvenance = { sourceAdapterId: string; sourceType: LootProvenanceSourceType; sourceUrl: string | null; retrievedAt: string; searchQuery: string | null; providerRecordId: string | null; freshness: 'current' | 'historical' | 'unknown'; isHistorical: boolean }
export type LootValue = { amount: number | null; currency: string; basis: ValueBasis; notes: string }
export type LootOpportunity = { id: string; ownerUserId: string; provider: string; providerOpportunityId: string | null; title: string; description: string | null; category: LootCategory; estimatedReward: LootValue | null; estimatedTimeMinutes: number | null; expiresAt: string | null; eligibility: string[]; locationRequirement: string | null; evidenceRequirement: string[]; externalUrl: string | null; status: LootStatus; evidenceLabel: LootEvidenceLabel; confidence: number; provenance: LootProvenance[]; discoveredAt: string; updatedAt: string; commanderApprovalRequired: true }
export type SurveyProgress = { opportunityId: string; status: LootStatus; startedAt: string | null; submittedAt: string | null }
export type StoreMission = { opportunityId: string; location: string | null; status: LootStatus; scheduledAt: string | null }
export type ReceiptRecord = { id: string; opportunityId: string; status: LootStatus; evidenceIds: string[] }
export const REWARD_LEDGER_CONFIRMATION_TYPES = ['provider_api', 'provider_dashboard', 'provider_message', 'commander_manual'] as const
export type RewardLedgerConfirmationType = (typeof REWARD_LEDGER_CONFIRMATION_TYPES)[number]
export type RewardLedgerProvenance = { sourceAdapterId: string | null; sourceType: LootProvenanceSourceType; providerRecordId: string | null; sourceUrl: string | null; retrievedAt: string | null; actorId: string | null; notes: string | null }
export type RewardLedgerConfirmation = { type: RewardLedgerConfirmationType; confirmedAt: string }
export type RewardLedgerReceipt = { receivedAt: string; method: string | null }
/** Financial events are append-only. Evidence and opportunity status never create them implicitly. */
export type RewardLedgerEntry = { id: string; ownerUserId: string; opportunityId: string; providerId: string | null; category: LootCategory; currency: string; amount: number; valueBasis: ValueBasis; recordedAt: string; provenance: RewardLedgerProvenance; confirmation: RewardLedgerConfirmation | null; receipt: RewardLedgerReceipt | null; externalEventId: string | null; notes: string | null }
export type RewardLedgerCurrencySummary = { estimated: number; confirmed: number; cashReceived: number; confirmedOutstanding: number }
export type RewardLedgerOwnerSummary = { ownerUserId: string; byCurrency: Record<string, RewardLedgerCurrencySummary> }
export type PriceMatchRecord = { id: string; opportunityId: string; claimedValue: LootValue | null; status: LootStatus }
export type DealBundle = { id: string; title: string; opportunityIds: string[]; estimatedValue: LootValue | null }
export const CASHOUT_STATUSES = ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'COMPLETED', 'REJECTED'] as const
export type CashoutStatus = (typeof CASHOUT_STATUSES)[number]
export type CashoutRequest = { id: string; ownerUserId: string; status: CashoutStatus; requestedValue: LootValue; commanderApprovalRequired: true; createdAt: string }
export const EVIDENCE_ATTACHMENT_KINDS = ['receipt', 'screenshot', 'provider_confirmation', 'transaction_reference', 'reward_balance', 'payout_confirmation'] as const
export type EvidenceAttachmentKind = (typeof EVIDENCE_ATTACHMENT_KINDS)[number]
export const EVIDENCE_VISIBILITIES = ['commander_only', 'workforce'] as const
export type EvidenceVisibility = (typeof EVIDENCE_VISIBILITIES)[number]
export const EVIDENCE_TRUTH_STATES = ['CAPTURED', 'REVIEWED', 'VERIFIED', 'REJECTED'] as const
export type EvidenceTruthState = (typeof EVIDENCE_TRUTH_STATES)[number]
export const EVIDENCE_LINKED_RECORD_TYPES = ['opportunity'] as const
export type EvidenceLinkedRecordType = (typeof EVIDENCE_LINKED_RECORD_TYPES)[number]
export type EvidenceAttachment = { id: string; ownerUserId: string; kind: EvidenceAttachmentKind; fileRef: string | null; originalFilename: string | null; mimeType: string | null; byteSize: number | null; contentSha256: string | null; capturedAt: string; linkedRecordType: EvidenceLinkedRecordType; linkedOpportunityId: string; merchant: string | null; purchaseDate: string | null; amount: number | null; currency: string | null; truthState: EvidenceTruthState; redacted: boolean; redactionNotes: string | null; redactedFields: string[]; visibility: EvidenceVisibility; notes: string | null }
export const EVIDENCE_TRANSITION_AUTHORITIES = ['OWNER', 'COMMANDER', 'WORKFORCE'] as const
export type EvidenceTransitionAuthority = (typeof EVIDENCE_TRANSITION_AUTHORITIES)[number]
export type IncomeLootEvidenceTransitionRequest = { ownerUserId: string; evidenceId: string; targetState: EvidenceTruthState; authority: EvidenceTransitionAuthority; actorId: string; reason?: string | null; workforceReviewAuthorized?: boolean }
export type IncomeLootEvidenceTransitionAudit = { evidenceId: string; ownerUserId: string; fromState: EvidenceTruthState; toState: EvidenceTruthState; actorId: string; authority: EvidenceTransitionAuthority; transitionedAt: string; reason: string | null }
export type IncomeLootEvidenceTransitionCode = 'TRANSITION_APPLIED' | 'NO_CHANGE' | 'EVIDENCE_NOT_FOUND' | 'TRANSITION_NOT_ALLOWED' | 'AUTHORITY_REQUIRED' | 'COMMANDER_APPROVAL_REQUIRED'
export type IncomeLootEvidenceTransitionResult = { changed: boolean; previousState: EvidenceTruthState | null; currentState: EvidenceTruthState | null; targetState: EvidenceTruthState; code: IncomeLootEvidenceTransitionCode; transition: IncomeLootEvidenceTransitionAudit | null }
