import { answerScreenerQuestion, classifyResearchSafety, type ParticipantApplicationStatus, type ParticipantProfile, type ParticipantSourceConnection, type ResearchSafetyClassification, type ScreenerQuestion } from './participantAutomation'

export const USER_INTERVIEWS_CONNECTION_STATES=['DISCONNECTED','AUTHENTICATION_REQUIRED','TWO_FACTOR_REQUIRED','AUTHENTICATED','SESSION_ACTIVE','SESSION_EXPIRED','REAUTHENTICATION_REQUIRED','ACCOUNT_RESTRICTED'] as const
export type UserInterviewsConnectionState=(typeof USER_INTERVIEWS_CONNECTION_STATES)[number]
export const PASSWORD_SECURITY_STATES=['PASSWORD_CURRENT','PASSWORD_UPDATE_REQUIRED','PASSWORD_UPDATE_PENDING','PASSWORD_UPDATED','PASSWORD_UPDATE_FAILED'] as const
export type PasswordSecurityState=(typeof PASSWORD_SECURITY_STATES)[number]
export type SecureVaultResult='STORED'|'REPLACED'|'DELETED'|'BLOCKED_BY_SECURE_VAULT'
export interface CredentialVault { storeCredential(input:{ownerUserId:string;provider:string;credential:string}):SecureVaultResult; replaceCredential(input:{ownerUserId:string;provider:string;credential:string}):SecureVaultResult; deleteCredential(input:{ownerUserId:string;provider:string}):SecureVaultResult; credentialExists(input:{ownerUserId:string;provider:string}):boolean; lastUpdatedAt(input:{ownerUserId:string;provider:string}):string|null }
/** Deliberately does not retain values: configure an approved encrypted backend before live auth. */
export const blockedSecureVault:CredentialVault={storeCredential:()=> 'BLOCKED_BY_SECURE_VAULT',replaceCredential:()=> 'BLOCKED_BY_SECURE_VAULT',deleteCredential:()=> 'BLOCKED_BY_SECURE_VAULT',credentialExists:()=>false,lastUpdatedAt:()=>null}
export type UserInterviewsSecurityEvent={type:'LOGIN_ATTEMPTED'|'LOGIN_SUCCEEDED'|'LOGIN_FAILED'|'TWO_FACTOR_REQUIRED'|'TWO_FACTOR_SUCCEEDED'|'SESSION_CREATED'|'SESSION_EXPIRED'|'SESSION_REVOKED'|'PASSWORD_UPDATE_REQUESTED'|'PASSWORD_UPDATED'|'PASSWORD_UPDATE_FAILED'|'AUTHENTICATED_DISCOVERY_SUCCEEDED'|'AUTHENTICATED_DISCOVERY_FAILED'|'SUBMISSION_PREPARED'|'SUBMISSION_ATTEMPTED'|'SUBMISSION_SUCCEEDED'|'SUBMISSION_FAILED'|'MANUAL_ACTION_REQUIRED';ownerUserId:string;provider:'User Interviews';occurredAt:string;detail:string}
export type UserInterviewsConnection={ownerUserId:string;accountStatus:ParticipantSourceConnection['accountStatus'];state:UserInterviewsConnectionState;sessionExpiresAt:string|null;passwordState:PasswordSecurityState;rotationReminderDays:number|null;passwordLastUpdatedAt:string|null;twoFactor:'ENABLED'|'REQUIRED'|'UNKNOWN';events:UserInterviewsSecurityEvent[]}
const event=(c:UserInterviewsConnection,type:UserInterviewsSecurityEvent['type'],detail:string,now=new Date().toISOString())=>c.events.push({type,ownerUserId:c.ownerUserId,provider:'User Interviews',occurredAt:now,detail})
export function createUserInterviewsConnection(ownerUserId:string,accountStatus:ParticipantSourceConnection['accountStatus']='ACCOUNT_NOT_CREATED'):UserInterviewsConnection{return {ownerUserId,accountStatus,state:accountStatus==='ACCOUNT_RESTRICTED'?'ACCOUNT_RESTRICTED':'DISCONNECTED',sessionExpiresAt:null,passwordState:'PASSWORD_CURRENT',rotationReminderDays:null,passwordLastUpdatedAt:null,twoFactor:'UNKNOWN',events:[]}}
export function requestPasswordUpdate(c:UserInterviewsConnection,days:number|null=null){c.passwordState='PASSWORD_UPDATE_PENDING';c.rotationReminderDays=days;event(c,'PASSWORD_UPDATE_REQUESTED','Commander requested password update.');return c.passwordState}
export function replaceStoredPassword(c:UserInterviewsConnection,vault:CredentialVault,password:string,now=new Date().toISOString()):SecureVaultResult { const r=vault.replaceCredential({ownerUserId:c.ownerUserId,provider:'user-interviews',credential:password}); if(r==='REPLACED'||r==='STORED'){c.passwordState='PASSWORD_UPDATED';c.passwordLastUpdatedAt=now;c.state='REAUTHENTICATION_REQUIRED';c.sessionExpiresAt=null;event(c,'PASSWORD_UPDATED','Stored password replaced; sessions require validation.',now)}else{c.passwordState='PASSWORD_UPDATE_FAILED';event(c,'PASSWORD_UPDATE_FAILED','Secure vault did not replace password.',now)}return r }
export function markPasswordRotated(c:UserInterviewsConnection,now=new Date().toISOString()){c.passwordState='PASSWORD_UPDATED';c.passwordLastUpdatedAt=now;c.state='REAUTHENTICATION_REQUIRED';c.sessionExpiresAt=null;return c}
export function getPasswordSecurityStatus(c:UserInterviewsConnection,now=new Date().toISOString()){const next=c.rotationReminderDays&&c.passwordLastUpdatedAt?new Date(new Date(c.passwordLastUpdatedAt).getTime()+c.rotationReminderDays*86400000).toISOString():null;return {provider:'User Interviews',passwordStoredSecurely:'VAULT_BLOCKED' as const,passwordLastUpdated:c.passwordLastUpdatedAt,rotationReminder:c.rotationReminderDays!==null,nextRecommendedReview:next&&next<now?now:next,sessionStatus:c.state,twoFactor:c.twoFactor,passwordState:c.passwordState}}
export function beginAuthentication(c:UserInterviewsConnection,vault:CredentialVault,now=new Date().toISOString()):'AUTHENTICATION_READY'|'BLOCKED_BY_SECURE_VAULT' {event(c,'LOGIN_ATTEMPTED','Authentication requested.',now);if(!vault.credentialExists({ownerUserId:c.ownerUserId,provider:'user-interviews'})){c.state='AUTHENTICATION_REQUIRED';return 'BLOCKED_BY_SECURE_VAULT'}c.state='AUTHENTICATED';return 'AUTHENTICATION_READY'}
export function requireTwoFactor(c:UserInterviewsConnection,now=new Date().toISOString()){c.state='TWO_FACTOR_REQUIRED';c.twoFactor='REQUIRED';event(c,'TWO_FACTOR_REQUIRED','Commander OTP required; it is not retained.',now);return 'MANUAL_ACTION_REQUIRED' as const}
export function completeTwoFactor(c:UserInterviewsConnection,otp:string,expiresAt:string,now=new Date().toISOString()){if(!otp.trim())return 'MANUAL_ACTION_REQUIRED' as const;c.twoFactor='ENABLED';c.state='SESSION_ACTIVE';c.sessionExpiresAt=expiresAt;event(c,'TWO_FACTOR_SUCCEEDED','Two-factor transaction completed.',now);event(c,'SESSION_CREATED','Authenticated session created.',now);return 'SESSION_ACTIVE' as const}
export function sessionValidity(c:UserInterviewsConnection,now=new Date().toISOString()){if(c.state!=='SESSION_ACTIVE'||!c.sessionExpiresAt||new Date(c.sessionExpiresAt)<=new Date(now)){if(c.state==='SESSION_ACTIVE')event(c,'SESSION_EXPIRED','Session expiry observed.',now);c.state='REAUTHENTICATION_REQUIRED';return false}return true}
export function revokeSession(c:UserInterviewsConnection,now=new Date().toISOString()){c.sessionExpiresAt=null;c.state='DISCONNECTED';event(c,'SESSION_REVOKED','Session revoked.',now)}
export type UserInterviewsOpportunity={providerStudyId:string;title:string;description:string|null;compensation:number|null;currency:string|null;studyFormat:string|null;attendance:'REMOTE'|'IN_PERSON'|null;location:string|null;estimatedDurationMinutes:number|null;scheduled:boolean|null;eligibility:string[];officialApplicationUrl:string|null;status:string|null;retrievedAt:string;safety:ResearchSafetyClassification}
export function normalizeUserInterviewsOpportunity(input:Omit<UserInterviewsOpportunity,'safety'>):UserInterviewsOpportunity{return {...input,safety:classifyResearchSafety([input.title,input.description,...input.eligibility].filter(Boolean).join(' '))}}
export function normalEarnNowOpportunities(items:UserInterviewsOpportunity[]){return items.filter(x=>x.safety==='NON_INVASIVE_CONFIRMED')}
export type PendingCommanderQuestion={provider:'User Interviews';studyId:string;question:ScreenerQuestion;answerType:string;reason:string}
export function prepareUserInterviewsScreener(profile:ParticipantProfile,questions:ScreenerQuestion[]){const pending:PendingCommanderQuestion[]=[];const answers=questions.map(question=>{const answer=answerScreenerQuestion(question,profile);if(answer.classification!=='KNOWN_FACT')pending.push({provider:'User Interviews',studyId:question.opportunityId,question,answerType:question.type,reason:answer.classification});return {question,answer}});return {answers,pending}}
export function authenticatedDiscovery(c:UserInterviewsConnection):'AUTHENTICATED_DISCOVERY_VERIFIED'|'REAUTHENTICATION_REQUIRED'|'MANUAL_ACTION_REQUIRED' {if(!sessionValidity(c))return 'REAUTHENTICATION_REQUIRED';event(c,'AUTHENTICATED_DISCOVERY_FAILED','No approved authenticated browser implementation is configured.');return 'MANUAL_ACTION_REQUIRED'}
export function submissionReadiness(c:UserInterviewsConnection,connection:ParticipantSourceConnection,answers:ReturnType<typeof answerScreenerQuestion>[],safety:ResearchSafetyClassification,commanderSubmitEnabled:boolean){const permitted=sessionValidity(c)&&connection.capabilities.canSubmitAutomatically&&commanderSubmitEnabled&&answers.every(x=>x.classification==='KNOWN_FACT')&&safety==='NON_INVASIVE_CONFIRMED';event(c,permitted?'SUBMISSION_PREPARED':'MANUAL_ACTION_REQUIRED',permitted?'Supported submission prepared.':'Submission needs a supported authenticated flow or Commander action.');return permitted?'SUBMISSION_PERMITTED':'MANUAL_ACTION_REQUIRED' as const}
export function providerPaymentMayConfirm(status:ParticipantApplicationStatus,providerPaymentConfirmed:boolean){return status==='PAID'&&providerPaymentConfirmed}
export function cashReceivedMayRecord(actualFundsVerified:boolean){return actualFundsVerified}
