import { existsSync, readFileSync } from 'node:fs'; import { join } from 'node:path'
import { EVIDENCE_ATTACHMENT_KINDS, EVIDENCE_VISIBILITIES, LOOT_CATEGORIES, LOOT_STATUSES, VALUE_BASES, type LootOpportunity } from './types'
import { __resetIncomeLootStore, INCOME_LOOT_PERSISTENCE, insertIncomeLootOpportunity, listIncomeLootOpportunities, getIncomeLootOpportunityForOwner, listIncomeLootOpportunitiesForOwner } from './store'; import { getIncomeLootPersistenceReadiness } from './durableStore'
import { incomeLootIdentity } from './identity'
import { normalizeLootCandidate } from './normalize'
import { rankLootOpportunity } from './ranking'
import { gateIncomeLootAction } from './approvalGates'
import { sanitizeIncomeLootCommanderContext } from './commanderContext'
import { EVIDENCE_TRUTH_STATES, type EvidenceAttachment } from './types'
import { __resetIncomeLootEvidenceStore, INCOME_LOOT_EVIDENCE_STORE_CAP, insertIncomeLootEvidence, getIncomeLootEvidenceForOwner, listIncomeLootEvidenceForOwner, listIncomeLootEvidenceForOpportunity, findIncomeLootEvidenceDuplicateForOwner } from './evidenceStore'
import { inspectIncomeLootEvidenceFile, MAX_INCOME_LOOT_EVIDENCE_BYTES } from './evidenceFileSafety'
import { __resetIncomeLootEvidenceTransitionHistory, listIncomeLootEvidenceTransitionHistoryForOwner, transitionIncomeLootEvidenceTruthState } from './evidenceGovernance'
import { buildIncomeLootConsoleViewModel } from './consoleViewModel'
export type IncomeLootValidationResult = { id: string; pass: boolean; detail: string }
function item(n: number, ownerUserId = 'validation-user'): Omit<LootOpportunity, 'id'|'discoveredAt'|'updatedAt'|'commanderApprovalRequired'> { return { ownerUserId, provider:'validation-only', providerOpportunityId:null, title:`Validation ${n}`, description:null, category:'SURVEY', estimatedReward:{amount:1,currency:'USD',basis:'ESTIMATED',notes:'deterministic validation value'}, estimatedTimeMinutes:1, expiresAt:null, eligibility:[], locationRequirement:null, evidenceRequirement:[], externalUrl:`https://validation.invalid/${n}`, status:'DISCOVERED', evidenceLabel:'LIVE_SIGNAL_BACKED', confidence:50, provenance:[] } }
export function runIncomeLootValidation(): IncomeLootValidationResult[] { const out: IncomeLootValidationResult[]=[]; const add=(id:string,ok:boolean,detail:string)=>out.push({id,pass:ok,detail}); __resetIncomeLootStore(); add('loot_01_enums', LOOT_CATEGORIES.length===8&&LOOT_STATUSES.length===11&&VALUE_BASES.join(',')==='ESTIMATED,CONFIRMED,CASH_RECEIVED','core truth enumerations'); add('loot_02_evidence', EVIDENCE_ATTACHMENT_KINDS.length===6&&EVIDENCE_VISIBILITIES.join(',')==='commander_only,workforce','evidence enums'); const first=insertIncomeLootOpportunity(item(1)); add('loot_03_approval', first?.commanderApprovalRequired===true,'commander approval invariant'); add('loot_04_duplicate', insertIncomeLootOpportunity(item(1))===null,'duplicate rejected'); for(let i=2;i<=501;i++) insertIncomeLootOpportunity(item(i)); add('loot_05_cap', listIncomeLootOpportunities().length===500,'bounded store'); const ready=getIncomeLootPersistenceReadiness(); add('loot_06_session_only', INCOME_LOOT_PERSISTENCE==='session_only'&&ready.durableAvailable===false&&ready.migrationRequired,'durability truth'); const migration=join(process.cwd(),'supabase/war_room_phase49f_income_loot_core.sql'), rollback=join(process.cwd(),'supabase/rollback/war_room_phase49f_income_loot_core_rollback.sql'); add('loot_07_migrations', existsSync(migration)&&existsSync(rollback)&&readFileSync(migration,'utf8').includes('war_room_income_loot_opportunities')&&readFileSync(rollback,'utf8').includes('war_room_income_loot_opportunities'),'migration pair'); const ownerA=insertIncomeLootOpportunity(item(600,'owner-a-validation')); const ownerB=insertIncomeLootOpportunity(item(601,'owner-b-validation')); add('loot_08_owner_get_isolation', ownerA!==null&&ownerB!==null&&getIncomeLootOpportunityForOwner('owner-b-validation', ownerA.id)===null&&getIncomeLootOpportunityForOwner('owner-a-validation', ownerA.id)?.id===ownerA.id,'cross-owner get isolation'); const ownerAList=listIncomeLootOpportunitiesForOwner('owner-a-validation'); add('loot_09_owner_list_isolation', ownerA!==null&&ownerB!==null&&ownerAList.every(record=>record.ownerUserId==='owner-a-validation')&&ownerAList.some(record=>record.id===ownerA.id)&&!ownerAList.some(record=>record.id===ownerB.id),'cross-owner list isolation')

  const t1a=incomeLootIdentity({provider:'swagbucks',providerOpportunityId:'sb-123',externalUrl:null,title:'Any Title',category:'SURVEY',locationRequirement:null}); const t1b=incomeLootIdentity({provider:'swagbucks',providerOpportunityId:'sb-123',externalUrl:'https://different.example/x',title:'Different Title',category:'DEAL',locationRequirement:'CA'})
  add('loot_10_identity_tier1_provider', t1a.identityStrength==='STRONG'&&t1a.identityKey===t1b.identityKey&&t1a.identityKey==='provider:swagbucks:sb-123','Tier 1 provider ID identity is authoritative regardless of title/url drift')

  const t2a=incomeLootIdentity({provider:'x',providerOpportunityId:null,externalUrl:'https://example.com/offer?ref=abc',title:'Offer A',category:'DEAL',locationRequirement:null}); const t2b=incomeLootIdentity({provider:'x',providerOpportunityId:null,externalUrl:'https://example.com/offer?ref=xyz',title:'Offer A',category:'DEAL',locationRequirement:null}); const t2c=incomeLootIdentity({provider:'x',providerOpportunityId:null,externalUrl:'https://Example.com/offer?ref=abc',title:'Offer A',category:'DEAL',locationRequirement:null})
  add('loot_11_identity_tier2_url_query_distinct', t2a.identityStrength==='CANONICAL_URL'&&t2b.identityStrength==='CANONICAL_URL'&&t2a.identityKey!==t2b.identityKey,'query-distinct URLs remain distinct offers, not collapsed by path alone')
  add('loot_12_identity_tier2_url_stable', t2a.identityKey===t2c.identityKey,'canonical URL identity is host-case-insensitive and stable for an identical query')

  const t3a=incomeLootIdentity({provider:'y',providerOpportunityId:null,externalUrl:null,title:'Take a paid survey',category:'SURVEY',locationRequirement:null}); const t3b=incomeLootIdentity({provider:'y',providerOpportunityId:null,externalUrl:null,title:'Take a paid survey',category:'DEAL',locationRequirement:null})
  add('loot_13_identity_tier3_weak', t3a.identityStrength==='WEAK'&&t3a.identityKey!==t3b.identityKey,'weak identity requires provider+title+category+location match; title alone cannot collapse unrelated offers')

  const dupOwnerC=insertIncomeLootOpportunity(item(700,'owner-c-validation')); const dupOwnerD=insertIncomeLootOpportunity(item(700,'owner-d-validation'))
  add('loot_14_owner_scoped_dedupe', dupOwnerC!==null&&dupOwnerD!==null,'identical identity across different owners does not collapse')

  const provenanceWeb={sourceAdapterId:'tavily',sourceType:'web_search' as const,sourceUrl:'https://example.com/a',retrievedAt:new Date().toISOString(),searchQuery:'test query',providerRecordId:null,freshness:'current' as const,isHistorical:false}
  const normMissing=normalizeLootCandidate({ownerUserId:'validation-user',provider:'tavily',title:'Real opportunity title',provenance:provenanceWeb})
  add('loot_15_normalize_null_handling', normMissing!==null&&normMissing.estimatedReward===null&&normMissing.estimatedTimeMinutes===null&&normMissing.expiresAt===null&&normMissing.eligibility.length===0&&normMissing.providerOpportunityId===null,'missing fields normalize to null/empty and are never invented')
  add('loot_16_normalize_other_reward_fallback', normMissing?.category==='OTHER_REWARD','uncertain category becomes OTHER_REWARD rather than an unsupported guess')

  const normConfirmedRejected=normalizeLootCandidate({ownerUserId:'validation-user',provider:'tavily',title:'Suspicious confirmed claim',reward:{amount:50,currency:'USD',basis:'CONFIRMED',notes:'unverified'},provenance:provenanceWeb})
  add('loot_17_normalize_no_fabricated_confirmation', normConfirmedRejected?.estimatedReward===null,'web-search candidates cannot self-assert a CONFIRMED reward basis')

  const normHistorical=normalizeLootCandidate({ownerUserId:'validation-user',provider:'tavily',title:'Historical pattern candidate',provenance:{...provenanceWeb,sourceType:'historical_fallback',isHistorical:true}})
  add('loot_18_normalize_provenance_truth', normMissing?.evidenceLabel==='LIVE_SIGNAL_BACKED'&&normHistorical?.evidenceLabel==='HISTORICAL_PATTERN_BASED'&&normMissing?.provenance[0].sourceType==='web_search'&&normHistorical?.provenance[0].isHistorical===true,'live web-search data is never labeled historical, and historical fallback is never labeled live; normalizeLootCandidate cannot produce PROVIDER_CONFIRMED at all (proven by its own return type)')

  const rankBase=insertIncomeLootOpportunity(item(800,'owner-rank-validation'))!
  const rankKnown=rankLootOpportunity({...rankBase, confidence:80, evidenceLabel:'LIVE_SIGNAL_BACKED', estimatedReward:{amount:10,currency:'USD',basis:'ESTIMATED',notes:''}, estimatedTimeMinutes:30, expiresAt:null})
  add('loot_19_ranking_deterministic', rankKnown.rankable===true&&rankKnown.score===72,'ranking score is deterministic arithmetic, not fabricated')
  add('loot_20_ranking_explanations', rankKnown.factors.length>0&&rankKnown.factors.every(f=>typeof f.explanation==='string'&&f.explanation.length>0),'every ranking factor carries a human-readable explanation')

  const rankMissing=rankLootOpportunity({...rankBase, confidence:0, evidenceLabel:'HISTORICAL_PATTERN_BASED', estimatedReward:null, estimatedTimeMinutes:null, expiresAt:null})
  add('loot_21_ranking_missing_data_zero', rankMissing.score===0&&rankMissing.factors.every(f=>f.name!=='reward'&&f.name!=='hourly_equivalent'),'missing reward/time data contributes zero rather than being estimated')

  const rankExpired=rankLootOpportunity({...rankBase, expiresAt:'2000-01-01T00:00:00.000Z'})
  add('loot_22_ranking_expired_veto', rankExpired.rankable===false&&rankExpired.vetoReason==='expired'&&rankExpired.score===0,'expired opportunities are vetoed before scoring')

  add('loot_23_approval_allowed', gateIncomeLootAction('research').allowed===true&&gateIncomeLootAction('dedupe').allowed===true&&gateIncomeLootAction('flag_deadline').allowed===true,'internal read-only research actions are allowed')
  add('loot_24_approval_forbidden', gateIncomeLootAction('cash_out').allowed===false&&gateIncomeLootAction('submit_receipt').allowed===false&&gateIncomeLootAction('circumvent_antibot').allowed===false&&gateIncomeLootAction('fabricate_evidence').allowed===false,'external, evidence-fabricating, and antibot-circumventing actions are denied')
  add('loot_25_approval_unknown_deny', gateIncomeLootAction('do_something_unlisted').allowed===false,'unknown actions deny by default')

  const ctxOk=sanitizeIncomeLootCommanderContext({ownerUserId:' owner-ctx-validation ',travelRadiusMiles:25,minimumPayoutUsd:5})
  add('loot_26_commander_context_valid', ctxOk!==null&&ctxOk.ownerUserId==='owner-ctx-validation'&&!('bankAccount' in ctxOk),'valid commander context is sanitized and privacy-minimized')
  const ctxBad=sanitizeIncomeLootCommanderContext({ownerUserId:'owner-ctx-validation',travelRadiusMiles:-5})
  add('loot_27_commander_context_invalid', ctxBad===null,'invalid commander context (negative radius) is rejected, not silently clamped')

  __resetIncomeLootEvidenceStore()
  const evidenceInput = (ownerUserId: string, linkedOpportunityId = 'opp-a'): Omit<EvidenceAttachment, 'id' | 'truthState' | 'visibility'> => ({ ownerUserId, kind: 'receipt', fileRef: null, originalFilename: null, mimeType: null, byteSize: null, contentSha256: null, capturedAt: '2026-01-01T00:00:00.000Z', linkedRecordType: 'opportunity', linkedOpportunityId, merchant: null, purchaseDate: null, amount: null, currency: null, redacted: false, redactionNotes: null, redactedFields: [], notes: null })
  const evA=insertIncomeLootEvidence(evidenceInput('evidence-owner-a')); const evB=insertIncomeLootEvidence(evidenceInput('evidence-owner-b','opp-b'))
  add('loot_28_evidence_truth_states', EVIDENCE_TRUTH_STATES.join(',')==='CAPTURED,REVIEWED,VERIFIED,REJECTED','F3A evidence truth states are exact')
  add('loot_29_evidence_defaults_and_typed_link', evA.visibility==='commander_only'&&evA.truthState==='CAPTURED'&&evA.linkedRecordType==='opportunity'&&evA.linkedOpportunityId==='opp-a','privacy, truth, and opportunity link defaults are exact')
  add('loot_30_evidence_nullable_metadata', [evA.fileRef,evA.originalFilename,evA.mimeType,evA.byteSize,evA.contentSha256,evA.merchant,evA.purchaseDate,evA.amount,evA.currency,evA.redactionNotes,evA.notes].every(x=>x===null)&&evA.redactedFields.length===0,'F3A metadata remains nullable and no checksum/file reference is fabricated')
  add('loot_31_evidence_owner_isolation', getIncomeLootEvidenceForOwner('evidence-owner-b',evA.id)===null&&getIncomeLootEvidenceForOwner('evidence-owner-b',evB.id)?.id===evB.id&&listIncomeLootEvidenceForOwner('evidence-owner-a').length===1&&listIncomeLootEvidenceForOpportunity('evidence-owner-b','opp-a').length===0,'evidence reads remain owner-scoped')
  add('loot_32_evidence_financial_separation', insertIncomeLootEvidence(evidenceInput('evidence-owner-a')).truthState==='CAPTURED'&&VALUE_BASES.includes('CONFIRMED')&&VALUE_BASES.includes('CASH_RECEIVED'),'caller-controlled creation cannot bypass governance into VERIFIED, and evidence truth has no financial mutation path')
  for(let i=0;i<=INCOME_LOOT_EVIDENCE_STORE_CAP;i++) insertIncomeLootEvidence(evidenceInput('evidence-cap',`opp-${i}`))
  add('loot_33_evidence_cap', listIncomeLootEvidenceForOwner('evidence-cap').length===INCOME_LOOT_EVIDENCE_STORE_CAP,'evidence session store cap is bounded and deterministic')
  add('loot_34_evidence_durable_truth', getIncomeLootPersistenceReadiness().durableAvailable===false&&getIncomeLootPersistenceReadiness().migrationRequired===true,'SQL proposal does not claim evidence durability')
  const jpeg=new Uint8Array([0xff,0xd8,1,2,0xff,0xd9]), png=new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1]), pdf=new Uint8Array([0x25,0x50,0x44,0x46,0x2d,1]); const inspect=(name:string,mime:string,bytes:Uint8Array)=>inspectIncomeLootEvidenceFile({originalFilename:name,declaredMimeType:mime,bytes}); const jpg=inspect('receipt.JPG','image/jpeg',jpeg), p=inspect('screen.png','image/png',png), d=inspect('receipt.pdf','application/pdf',pdf)
  add('loot_35_f3b_valid_signatures',jpg.accepted&&p.accepted&&d.accepted,'actual JPEG, PNG, and PDF signature bytes accepted')
  add('loot_36_f3b_sha_actual_bytes',jpg.accepted&&inspect('again.jpg','image/jpeg',jpeg).accepted&&jpg.contentSha256===inspect('again.jpg','image/jpeg',jpeg).contentSha256&&jpg.contentSha256!==d.contentSha256,'SHA-256 is deterministic over actual bytes')
  add('loot_37_f3b_size_and_filename',inspect('empty.png','image/png',new Uint8Array()).accepted===false&&inspect('../../receipt.png','image/png',png).accepted===false&&inspect('C:\\tmp\\receipt.png','image/png',png).accepted===false&&inspect('huge.png','image/png',new Uint8Array(MAX_INCOME_LOOT_EVIDENCE_BYTES+1)).accepted===false,'empty, unsafe, and oversized files rejected')
  add('loot_38_f3b_consistency',inspect('receipt.exe','image/jpeg',jpeg).accepted===false&&inspect('receipt.png','text/html',png).accepted===false&&inspect('receipt.png','image/png',jpeg).accepted===false&&inspect('receipt.jpg','image/jpeg',png).accepted===false,'extension, MIME, and signature mismatch paths reject')
  add('loot_39_f3b_metadata_only',jpg.accepted&&jpg.byteSize===jpeg.length&&typeof jpg.contentSha256==='string'&&!('bytes' in evA)&&!('buffer' in evA),'actual bytes derive metadata and are not stored on evidence')
  const garbageResult=inspect('garbage.jpg','image/jpeg',new Uint8Array([1,2,3,4]))
  add('loot_40_f3b_unsupported_signature', garbageResult.accepted===false&&garbageResult.reason==='UNSUPPORTED_FILE_SIGNATURE','bytes matching no known signature are rejected even with a valid extension and declared MIME type')
  const dupHash=jpg.accepted?jpg.contentSha256:''; const dupOwnerX=insertIncomeLootEvidence({...evidenceInput('evidence-dup-owner-x'),contentSha256:dupHash})
  add('loot_41_f3b_evidence_duplicate_same_owner', findIncomeLootEvidenceDuplicateForOwner('evidence-dup-owner-x',dupHash)?.id===dupOwnerX.id,'same-owner checksum duplicate is detected via ownerUserId+contentSha256')
  add('loot_42_f3b_evidence_duplicate_cross_owner_private', findIncomeLootEvidenceDuplicateForOwner('evidence-dup-owner-y',dupHash)===null,'cross-owner checksum lookup does not reveal another owner\'s evidence')
  __resetIncomeLootEvidenceStore(); __resetIncomeLootEvidenceTransitionHistory()
  const governed=insertIncomeLootEvidence(evidenceInput('governed-owner','governed-opportunity'))
  const fixedNow=()=> '2026-02-03T04:05:06.000Z'
  const request=(targetState: EvidenceAttachment['truthState'], authority: 'OWNER'|'COMMANDER'|'WORKFORCE', overrides: Partial<{ownerUserId:string;evidenceId:string;actorId:string;reason:string|null;workforceReviewAuthorized:boolean}>={})=>({ownerUserId:overrides.ownerUserId??'governed-owner',evidenceId:overrides.evidenceId??governed.id,targetState,authority,actorId:overrides.actorId??'governance-test-actor',...(overrides.reason!==undefined?{reason:overrides.reason}:{}),...(overrides.workforceReviewAuthorized!==undefined?{workforceReviewAuthorized:overrides.workforceReviewAuthorized}:{})})
  add('loot_43_f3c_new_evidence_captured',governed.truthState==='CAPTURED','new evidence begins CAPTURED')
  add('loot_44_f3c_direct_verified_creation_denied',insertIncomeLootEvidence(evidenceInput('bypass-owner')).truthState==='CAPTURED','insertion has no caller-controlled VERIFIED path')
  const reviewed=transitionIncomeLootEvidenceTruthState(request('REVIEWED','OWNER'),fixedNow)
  add('loot_45_f3c_captured_reviewed_owner',reviewed.changed&&reviewed.code==='TRANSITION_APPLIED'&&getIncomeLootEvidenceForOwner('governed-owner',governed.id)?.truthState==='REVIEWED','owner CAPTURED to REVIEWED mutates through governance')
  const ownerVerify=transitionIncomeLootEvidenceTruthState(request('VERIFIED','OWNER'),fixedNow)
  const workforceVerify=transitionIncomeLootEvidenceTruthState(request('VERIFIED','WORKFORCE',{workforceReviewAuthorized:true}),fixedNow)
  add('loot_46_f3c_verified_commander_only',ownerVerify.code==='COMMANDER_APPROVAL_REQUIRED'&&workforceVerify.code==='COMMANDER_APPROVAL_REQUIRED'&&getIncomeLootEvidenceForOwner('governed-owner',governed.id)?.truthState==='REVIEWED','OWNER and WORKFORCE cannot independently verify')
  const verified=transitionIncomeLootEvidenceTruthState(request('VERIFIED','COMMANDER',{actorId:'commander-test',reason:'review accepted'}),fixedNow)
  add('loot_47_f3c_reviewed_verified_commander',verified.changed&&verified.currentState==='VERIFIED'&&verified.transition?.authority==='COMMANDER','only explicit COMMANDER authority verifies reviewed evidence')
  add('loot_48_f3c_audit_metadata',verified.transition?.fromState==='REVIEWED'&&verified.transition?.toState==='VERIFIED'&&verified.transition.actorId==='commander-test'&&verified.transition.transitionedAt===fixedNow()&&verified.transition.reason==='review accepted','successful transition records deterministic audit metadata')
  const terminalTargets: EvidenceAttachment['truthState'][]=['CAPTURED','REVIEWED','REJECTED']
  add('loot_49_f3c_verified_terminal',terminalTargets.every(target=>transitionIncomeLootEvidenceTruthState(request(target,'COMMANDER'),fixedNow).code==='TRANSITION_NOT_ALLOWED')&&getIncomeLootEvidenceForOwner('governed-owner',governed.id)?.truthState==='VERIFIED','VERIFIED is terminal')
  const rejected=insertIncomeLootEvidence(evidenceInput('rejected-owner'))
  const rejectResult=transitionIncomeLootEvidenceTruthState(request('REJECTED','COMMANDER',{ownerUserId:'rejected-owner',evidenceId:rejected.id,actorId:'commander-test'}),fixedNow)
  add('loot_50_f3c_captured_rejected_commander',rejectResult.changed&&rejectResult.currentState==='REJECTED','COMMANDER may reject captured evidence')
  add('loot_51_f3c_rejected_terminal',(['CAPTURED','REVIEWED','VERIFIED'] as EvidenceAttachment['truthState'][]).every(target=>transitionIncomeLootEvidenceTruthState(request(target,'COMMANDER',{ownerUserId:'rejected-owner',evidenceId:rejected.id}),fixedNow).code==='TRANSITION_NOT_ALLOWED'),'REJECTED is terminal')
  const illegal=insertIncomeLootEvidence(evidenceInput('illegal-owner'))
  const directVerify=transitionIncomeLootEvidenceTruthState(request('VERIFIED','COMMANDER',{ownerUserId:'illegal-owner',evidenceId:illegal.id}),fixedNow)
  add('loot_52_f3c_direct_captured_verified_denied',directVerify.code==='TRANSITION_NOT_ALLOWED'&&getIncomeLootEvidenceForOwner('illegal-owner',illegal.id)?.truthState==='CAPTURED','CAPTURED cannot skip REVIEWED')
  const noChange=transitionIncomeLootEvidenceTruthState(request('CAPTURED','OWNER',{ownerUserId:'illegal-owner',evidenceId:illegal.id}),fixedNow)
  add('loot_53_f3c_no_change_no_history',noChange.code==='NO_CHANGE'&&!noChange.changed&&listIncomeLootEvidenceTransitionHistoryForOwner('illegal-owner').length===0,'same-state request returns explicit NO_CHANGE without audit history')
  const workforce=insertIncomeLootEvidence(evidenceInput('workforce-owner'))
  add('loot_54_f3c_workforce_explicit_review_gate',transitionIncomeLootEvidenceTruthState(request('REVIEWED','WORKFORCE',{ownerUserId:'workforce-owner',evidenceId:workforce.id}),fixedNow).code==='AUTHORITY_REQUIRED'&&transitionIncomeLootEvidenceTruthState(request('REVIEWED','WORKFORCE',{ownerUserId:'workforce-owner',evidenceId:workforce.id,workforceReviewAuthorized:true}),fixedNow).changed,'WORKFORCE review requires explicit request authorization')
  const crossOwner=transitionIncomeLootEvidenceTruthState(request('REVIEWED','OWNER',{ownerUserId:'other-owner',evidenceId:workforce.id}),fixedNow)
  add('loot_55_f3c_cross_owner_private',crossOwner.code==='EVIDENCE_NOT_FOUND'&&crossOwner.previousState===null&&crossOwner.currentState===null,'cross-owner mutation fails without record details')
  const missing=transitionIncomeLootEvidenceTruthState(request('REVIEWED','OWNER',{evidenceId:'missing-evidence'}),fixedNow)
  add('loot_56_f3c_missing_evidence',missing.code==='EVIDENCE_NOT_FOUND'&&!missing.changed,'transition requires owner-scoped existing evidence')
  const reviewedReject=insertIncomeLootEvidence(evidenceInput('reviewed-reject-owner'))
  transitionIncomeLootEvidenceTruthState(request('REVIEWED','OWNER',{ownerUserId:'reviewed-reject-owner',evidenceId:reviewedReject.id}),fixedNow)
  add('loot_57_f3c_reviewed_rejected_commander',transitionIncomeLootEvidenceTruthState(request('REJECTED','COMMANDER',{ownerUserId:'reviewed-reject-owner',evidenceId:reviewedReject.id}),fixedNow).changed,'COMMANDER may reject reviewed evidence')
  const noActor=insertIncomeLootEvidence(evidenceInput('no-actor-owner'))
  add('loot_58_f3c_no_implicit_commander',transitionIncomeLootEvidenceTruthState(request('REVIEWED','COMMANDER',{ownerUserId:'no-actor-owner',evidenceId:noActor.id,actorId:''}),fixedNow).code==='AUTHORITY_REQUIRED','blank actor cannot become implicit Commander authority')
  const noReason=insertIncomeLootEvidence(evidenceInput('no-reason-owner'))
  const noReasonTransition=transitionIncomeLootEvidenceTruthState(request('REVIEWED','OWNER',{ownerUserId:'no-reason-owner',evidenceId:noReason.id}),fixedNow)
  add('loot_59_f3c_absent_reason_null',noReasonTransition.transition?.reason===null,'absent reason remains null rather than fabricated')
  const safetyEvidence=insertIncomeLootEvidence({...evidenceInput('safety-owner'),contentSha256:dupHash})
  add('loot_60_f3c_file_and_duplicate_separation',jpg.accepted&&findIncomeLootEvidenceDuplicateForOwner('safety-owner',dupHash)?.id===safetyEvidence.id&&safetyEvidence.truthState==='CAPTURED','file safety and duplicate signals do not review, verify, or reject evidence')
  add('loot_61_f3c_financial_provider_separation',verified.currentState==='VERIFIED'&&VALUE_BASES.join(',')==='ESTIMATED,CONFIRMED,CASH_RECEIVED'&&getIncomeLootEvidenceForOwner('governed-owner',governed.id)?.truthState==='VERIFIED','verification mutates evidence only; it creates no financial, cash-received, or provider-confirmation state')
  add('loot_62_f3c_history_owner_scoped',listIncomeLootEvidenceTransitionHistoryForOwner('governed-owner').some(entry=>entry.evidenceId===governed.id)&&listIncomeLootEvidenceTransitionHistoryForOwner('other-owner').length===0,'transition history is readable only through the requested owner scope')
  const uiLive={...item(900,'ui-owner'),id:'ui-live',discoveredAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',commanderApprovalRequired:true as const,status:'PENDING' as const,evidenceLabel:'LIVE_SIGNAL_BACKED' as const,estimatedReward:{amount:0,currency:'USD',basis:'ESTIMATED' as const,notes:'real zero'},provenance:[{sourceAdapterId:'official-source',sourceType:'provider_api' as const,sourceUrl:'https://example.com/opportunity',retrievedAt:'2026-01-01T00:00:00.000Z',searchQuery:null,providerRecordId:null,freshness:'current' as const,isHistorical:false}]}
  const uiHistorical={...uiLive,id:'ui-historical',ownerUserId:'ui-owner',title:'Historical record',status:'DISCOVERED' as const,evidenceLabel:'HISTORICAL_PATTERN_BASED' as const,estimatedReward:null,provenance:[{...uiLive.provenance[0],isHistorical:true,freshness:'historical' as const}]}
  const uiEvidence={...evidenceInput('ui-owner','ui-live'),id:'ui-evidence',truthState:'VERIFIED' as const,visibility:'commander_only' as const}
  const uiModel=buildIncomeLootConsoleViewModel({dataAvailable:true,opportunities:[uiLive,uiHistorical],evidence:[uiEvidence],now:Date.parse('2026-01-02T00:00:00.000Z')})
  add('loot_63_f3ui_live_historical_classification',uiModel.liveOpportunities.map(item=>item.id).join(',')==='ui-live'&&uiModel.historicalOpportunities.map(item=>item.id).join(',')==='ui-historical','live and historical opportunities are deterministically separated')
  add('loot_64_f3ui_unknown_and_real_zero_truth',uiModel.opportunities.find(item=>item.id==='ui-historical')?.estimatedReward===null&&uiModel.estimatedByCurrency.some(item=>item.currency==='USD'&&item.amount===0),'unknown reward remains unavailable while an actual zero remains zero')
  add('loot_65_f3ui_status_counts_and_in_progress',uiModel.statusCounts.PENDING===1&&uiModel.statusCounts.DISCOVERED===1&&uiModel.inProgress.map(item=>item.id).join(',')==='ui-live','pipeline and in-progress counts derive only from stored statuses')
  add('loot_66_f3ui_evidence_truth_only',uiModel.opportunities.find(item=>item.id==='ui-live')?.evidence[0]?.truthState==='VERIFIED'&&uiModel.estimatedByCurrency.some(item=>item.amount===0),'verified evidence is displayed separately without financial promotion')
  add('loot_67_f3ui_empty_and_owner_scope',buildIncomeLootConsoleViewModel({dataAvailable:true,opportunities:[],evidence:[]}).liveOpportunities.length===0&&uiModel.opportunities.every(item=>!('ownerUserId' in item)),'empty data creates no fake opportunities and the UI read model excludes owner identity')
  const uiSecretUrl={...uiLive,id:'ui-secret-url',provenance:[{...uiLive.provenance[0],sourceUrl:'https://example.com/opportunity?api_key=not-for-ui&safe=yes'}]}
  const uiSecretModel=buildIncomeLootConsoleViewModel({dataAvailable:true,opportunities:[uiSecretUrl],evidence:[]})
  add('loot_68_f3ui_provenance_and_durable_truth',uiModel.opportunities[0]?.provenance[0]?.sourceUrl==='https://example.com/opportunity'&&uiSecretModel.opportunities[0]?.provenance[0]?.sourceUrl==='https://example.com/opportunity?safe=yes'&&uiModel.durableAvailable===false&&uiModel.migrationRequired===true,'display model retains safe source URLs, removes credential-like parameters, and preserves session-only durability truth')
  return out }
