import 'server-only'

import type { ResearchDocument, ResearchHealthStatus, ResearchQuery } from '@/lib/research-engine/core/types'
import { providerEnvDescriptor, resolveBaseUrl } from '@/lib/research-engine/config/providerEnv'
import { safeJsonParse, safeProviderFetch } from '@/lib/research-engine/security/safeFetch'
import { withProviderGate } from '@/lib/research-engine/security/providerGate'
import { cacheGet, cacheSet, CACHE_TTL } from '@/lib/research-engine/cache/ttlCache'
import type { ResearchProviderAdapter } from '@/lib/research-engine/providers/adapter'
import { errorResponse, makeDocument, okResponse, nowIso } from '@/lib/research-engine/providers/shared'

const PROVIDER = 'gleif' as const
const LEI = /^[A-Z0-9]{20}$/
type GLEIFRecord = { id?: string; type?: string; attributes?: { entity?: { legalName?: { name?: string }; status?: string; jurisdiction?: string; legalAddress?: { addressLines?: string[]; city?: string; country?: string } }; registration?: { status?: string; managingLou?: string }; bic?: string[] }; links?: { self?: string; directParent?: string; ultimateParent?: string } }
type GLEIFResponse = { data?: GLEIFRecord | GLEIFRecord[] }
function baseUrl(): string { const d = providerEnvDescriptor(PROVIDER); return (d && resolveBaseUrl('GLEIF_API_BASE_URL', d)) || 'https://api.gleif.org/api/v1' }
function normalize(record: GLEIFRecord): ResearchDocument | null { const lei = record.id?.trim().toUpperCase(); const entity = record.attributes?.entity; const name = entity?.legalName?.name?.trim(); if (!lei || !LEI.test(lei) || !entity || !name) return null; const registration = record.attributes?.registration; const address = entity.legalAddress; const relationshipLinks = [record.links?.directParent, record.links?.ultimateParent].filter((v): v is string => Boolean(v)); const canonical = record.links?.self ?? `${baseUrl().replace(/\/$/, '')}/lei-records/${lei}`; const summary = [entity.status && `entity status: ${entity.status}`, registration?.status && `registration status: ${registration.status}`, entity.jurisdiction && `jurisdiction: ${entity.jurisdiction}`].filter(Boolean).join(' — ') || null; return makeDocument({ id: `gleif:${lei}`, provider: PROVIDER, providerRecordId: lei, title: name, summary, contentSnippet: summary, canonicalUrl: canonical, sourceUrl: canonical, sourceName: 'GLEIF LEI API', contentType: 'lei_record', authors: [], organization: 'Global Legal Entity Identifier Foundation', publishedAt: null, updatedAt: null, geography: [address?.city, address?.country].filter(Boolean).join(', ') || null, language: null, identifiers: { lei, ...(entity.status ? { entity_status: entity.status } : {}), ...(registration?.status ? { registration_status: registration.status } : {}), ...(registration?.managingLou ? { managing_lou: registration.managingLou } : {}), ...(record.attributes?.bic?.[0] ? { bic: record.attributes.bic[0] } : {}), ...(relationshipLinks.length ? { relationship_links: relationshipLinks.join('|') } : {}) }, subjects: relationshipLinks, license: 'GLEIF LEI Data Terms of Use', accessStatus: 'open', warnings: ['Match results should be corroborated against relevant legal-entity reference data.'] }) }
async function run(query: ResearchQuery) { const started = Date.now(); const text = query.text.trim(); if (!text) return errorResponse(PROVIDER, { provider: PROVIDER, category: 'parse_error', message: 'A non-empty LEI or legal entity name is required.', httpStatus: null }, 0); const limit = Math.max(1, Math.min(query.maxResults ?? 10, 50)); const normalizedLei = text.toUpperCase(); const exact = LEI.test(normalizedLei); const cacheKey = `gleif:${exact ? normalizedLei : text.toLowerCase()}:${limit}`; const cached = cacheGet<ReturnType<typeof okResponse>>(cacheKey); if (cached) return { ...cached, fromCache: true }; try { return await withProviderGate(PROVIDER, async () => { const url = new URL(`${baseUrl().replace(/\/$/, '')}/lei-records${exact ? `/${normalizedLei}` : ''}`); if (!exact) { url.searchParams.set('filter[entity.legalName]', text); url.searchParams.set('page[size]', String(limit)); url.searchParams.set('page[number]', '1') } const result = await safeProviderFetch(PROVIDER, url.toString(), { headers: { Accept: 'application/vnd.api+json' }, timeoutMs: 12_000, maxResponseBytes: 1024 * 1024, maxRetries: 0 }); if (!result.ok) return errorResponse(PROVIDER, { provider: PROVIDER, category: result.status === 429 ? 'rate_limited' : 'upstream_error', message: `GLEIF API returned HTTP ${result.status}`, httpStatus: result.status }, Date.now() - started); if (result.truncated) return errorResponse(PROVIDER, { provider: PROVIDER, category: 'parse_error', message: 'GLEIF response exceeded the accepted size.', httpStatus: result.status }, Date.now() - started); const payload = safeJsonParse<GLEIFResponse>(result.text); const records = !payload?.data ? null : Array.isArray(payload.data) ? payload.data : [payload.data]; if (!records) return errorResponse(PROVIDER, { provider: PROVIDER, category: 'parse_error', message: 'GLEIF response did not contain JSON:API data.', httpStatus: result.status }, Date.now() - started); const documents = records.map(normalize).filter((doc): doc is ResearchDocument => doc !== null).slice(0, limit); const response = okResponse(PROVIDER, { documents, durationMs: Date.now() - started }); cacheSet(cacheKey, response, CACHE_TTL.scholarlyMetadata); return response }) } catch (error) { return errorResponse(PROVIDER, { provider: PROVIDER, category: 'upstream_error', message: error instanceof Error ? error.message : String(error), httpStatus: null }, Date.now() - started) } }
async function healthCheck(): Promise<ResearchHealthStatus> { const started = Date.now(); try { const result = await safeProviderFetch(PROVIDER, `${baseUrl().replace(/\/$/, '')}/lei-records/529900T8BM49AURSDO55`, { headers: { Accept: 'application/vnd.api+json' }, timeoutMs: 10_000, maxResponseBytes: 256 * 1024, maxRetries: 0 }); return { provider: PROVIDER, state: result.ok ? 'ready' : result.status === 429 ? 'rate_limited' : 'degraded', checkedAt: nowIso(), detail: result.ok ? 'GLEIF LEI API reachable' : `HTTP ${result.status}`, durationMs: Date.now() - started } } catch (error) { return { provider: PROVIDER, state: 'unavailable', checkedAt: nowIso(), detail: error instanceof Error ? error.message : String(error), durationMs: Date.now() - started } } }
export const gleifAdapter: ResearchProviderAdapter = { id: PROVIDER, run, healthCheck }
