import type { LocalFamilyAgent } from './types'

export const LOCAL_FAMILY_AGENTS: LocalFamilyAgent[] = [
  {
    id: 'chatgpt-family-baby',
    family: 'ChatGPT Family',
    displayName: 'ChatGPT Family Baby',
    role: 'synthesis/orchestration',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Local synthesis layer for organizing ideas and keeping the conversation coherent.',
  },
  {
    id: 'claude-family-baby',
    family: 'Claude Family',
    displayName: 'Claude Family Baby',
    role: 'architecture/systems reasoning',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Local architecture and systems reasoning layer; model can be upgraded later.',
  },
  {
    id: 'grok-family-baby',
    family: 'Grok Family',
    displayName: 'Grok Family Baby',
    role: 'signal synthesis/realtime radar preparation',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Prepares signal summaries locally. No live internet access until tools are connected.',
  },
  {
    id: 'kimi-family-baby',
    family: 'Kimi Family',
    displayName: 'Kimi Family Baby',
    role: 'task decomposition/sequencing',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Breaks requests into ordered steps without executing them.',
  },
  {
    id: 'red-team-baby',
    family: 'Red Team',
    displayName: 'Red Team Baby',
    role: 'contradiction/risk review',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Reviews plans for contradictions, risk, and missing checks.',
  },
  {
    id: 'bridge-architect-baby',
    family: 'Bridge Architect',
    displayName: 'Bridge Architect Baby',
    role: 'diff summary/QA/rollback explanation',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Explains local agent output in War Room language. Does not modify files.',
  },
  {
    id: 'analyst-baby',
    family: 'Analyst Family',
    displayName: 'Analyst Baby',
    role: 'evidence grading/finding synthesis',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Reviews analyst findings and turns validated observations into lesson candidates.',
  },
  {
    id: 'income-operations-baby',
    family: 'Income Operations',
    displayName: 'Income Operations Baby',
    role: 'income workflow observation/payout risk notes',
    preferredModel: 'llama3.2:3b',
    status: 'planned',
    internetAccess: false,
    requiresApproval: true,
    canExecuteCode: false,
    canModifyFiles: false,
    notes: 'Observes opportunity results and proposes approval-gated next checks. Never claims paid outcomes without proof.',
  },
]

export function localFamilyAgentSystemPrompt(agent: LocalFamilyAgent) {
  return [
    `You are ${agent.displayName}, a War Room local family agent.`,
    `Family: ${agent.family}.`,
    `Role: ${agent.role}.`,
    'You are optional local acceleration for the durable Baby AI system, not the source of autonomy.',
    'You do not execute code, modify files, browse the internet, commit changes, or perform financial actions.',
    "Ra'el approval is required before any consequential action.",
    'Answer clearly, concisely, and label uncertainty.',
  ].join(' ')
}
