/**
 * God's Eye open-stack foundation status — additive into existing Terra/Cesium.
 * Do not treat this as FULLY_ACTIVE. Evaluation providers stay behind switches.
 */
import type { GodsEyeEvaluationState } from './coverageStates'
import { PANORAMAX_STATUS } from './panoramax'

export const GODS_EYE_OPEN_STACK_FOUNDATION = 'GODS_EYE_OPEN_STACK_FOUNDATION_ACTIVE' as const

export const GODS_EYE_OPEN_STACK_ENGINE = 'CESIUMJS' as const
export const GODS_EYE_OPEN_STACK_REPLACES_TERRA = false
export const GODS_EYE_OPEN_STACK_CREATES_TERRA2 = false

export const RE_EARTH_BUILDINGS_STATUS: GodsEyeEvaluationState = 'EVALUATION_ACTIVE'
export const RE_EARTH_TERRAIN_STATUS: GodsEyeEvaluationState = 'EVALUATION_ACTIVE'
export const STREET_NAMES_STATUS: GodsEyeEvaluationState = 'ACTIVE'
export const HOUSE_NUMBERS_STATUS: GodsEyeEvaluationState = 'PARTIAL'
export const TRAFFIC_SIGNAL_INFRASTRUCTURE_STATUS: GodsEyeEvaluationState = 'PARTIAL'
export const LIVE_SIGNAL_PHASE_STATUS: GodsEyeEvaluationState = 'NO_COVERAGE'
export const MAPILLARYJS_STATUS: GodsEyeEvaluationState = 'EVALUATION_ACTIVE'
export { PANORAMAX_STATUS }
export const STREET_OBJECT_INTERFACE_STATUS: GodsEyeEvaluationState = 'ACTIVE'
export const CLICK_INFO_STATUS: GodsEyeEvaluationState = 'ACTIVE'
export const LIVE_INTEL_FLOATING_STATUS: GodsEyeEvaluationState = 'ACTIVE'
export const LIVE_INTEL_PIN_STATUS: GodsEyeEvaluationState = 'ACTIVE'
export const DOUBLE_CLICK_SPIN_STATUS: GodsEyeEvaluationState = 'ACTIVE'
export const CONVERSATION_AUTO_EXPAND_STATUS = 'DISABLED' as const

export type GodsEyeOpenStackReport = {
  foundation: typeof GODS_EYE_OPEN_STACK_FOUNDATION
  engine: typeof GODS_EYE_OPEN_STACK_ENGINE
  RE_EARTH_BUILDINGS: typeof RE_EARTH_BUILDINGS_STATUS
  RE_EARTH_TERRAIN: typeof RE_EARTH_TERRAIN_STATUS
  STREET_NAMES: typeof STREET_NAMES_STATUS
  HOUSE_NUMBERS: typeof HOUSE_NUMBERS_STATUS
  TRAFFIC_SIGNAL_INFRASTRUCTURE: typeof TRAFFIC_SIGNAL_INFRASTRUCTURE_STATUS
  LIVE_SIGNAL_PHASE: typeof LIVE_SIGNAL_PHASE_STATUS
  MAPILLARYJS: typeof MAPILLARYJS_STATUS
  PANORAMAX: typeof PANORAMAX_STATUS
  STREET_OBJECT_INTERFACE: typeof STREET_OBJECT_INTERFACE_STATUS
  CLICK_INFO: typeof CLICK_INFO_STATUS
  LIVE_INTEL_FLOATING: typeof LIVE_INTEL_FLOATING_STATUS
  LIVE_INTEL_PIN: typeof LIVE_INTEL_PIN_STATUS
  DOUBLE_CLICK_SPIN: typeof DOUBLE_CLICK_SPIN_STATUS
  CONVERSATION_AUTO_EXPAND: typeof CONVERSATION_AUTO_EXPAND_STATUS
}

export function godsEyeOpenStackReport(): GodsEyeOpenStackReport {
  return {
    foundation: GODS_EYE_OPEN_STACK_FOUNDATION,
    engine: GODS_EYE_OPEN_STACK_ENGINE,
    RE_EARTH_BUILDINGS: RE_EARTH_BUILDINGS_STATUS,
    RE_EARTH_TERRAIN: RE_EARTH_TERRAIN_STATUS,
    STREET_NAMES: STREET_NAMES_STATUS,
    HOUSE_NUMBERS: HOUSE_NUMBERS_STATUS,
    TRAFFIC_SIGNAL_INFRASTRUCTURE: TRAFFIC_SIGNAL_INFRASTRUCTURE_STATUS,
    LIVE_SIGNAL_PHASE: LIVE_SIGNAL_PHASE_STATUS,
    MAPILLARYJS: MAPILLARYJS_STATUS,
    PANORAMAX: PANORAMAX_STATUS,
    STREET_OBJECT_INTERFACE: STREET_OBJECT_INTERFACE_STATUS,
    CLICK_INFO: CLICK_INFO_STATUS,
    LIVE_INTEL_FLOATING: LIVE_INTEL_FLOATING_STATUS,
    LIVE_INTEL_PIN: LIVE_INTEL_PIN_STATUS,
    DOUBLE_CLICK_SPIN: DOUBLE_CLICK_SPIN_STATUS,
    CONVERSATION_AUTO_EXPAND: CONVERSATION_AUTO_EXPAND_STATUS,
  }
}
