/**
 * Conservative production-hardening statuses.
 * PRODUCTION_READY requires all 12 gates. Missing any gate → not PRODUCTION_READY.
 */
export const GODS_EYE_PRODUCTION_STATUSES = [
  'PRODUCTION_READY',
  'PARTIAL',
  'EVALUATION_ACTIVE',
  'INTERFACE_ONLY',
  'NO_COVERAGE',
  'BLOCKED',
] as const
export type GodsEyeProductionStatus = (typeof GODS_EYE_PRODUCTION_STATUSES)[number]

export const GODS_EYE_PRODUCTION_GATES = [
  'CODE_PRESENT',
  'RUNTIME_VERIFIED',
  'VISUALLY_VERIFIED',
  'SOURCE_VERIFIED',
  'FAILURE_STATE_VERIFIED',
  'COVERAGE_STATE_TRUTHFUL',
  'PROVENANCE_PRESENT',
  'PERFORMANCE_ACCEPTABLE',
  'NO_SECRET_LEAKAGE',
  'PACKAGED_3848_COMPATIBLE',
  'SAFE_FALLBACK',
  'LICENSE_DOCUMENTED',
] as const
export type GodsEyeProductionGate = (typeof GODS_EYE_PRODUCTION_GATES)[number]

export type GodsEyeHardeningRow = {
  feature: string
  devRuntime: 'PASS' | 'PARTIAL' | 'FAIL' | 'UNVERIFIED'
  failureState: 'PASS' | 'PARTIAL' | 'FAIL' | 'UNVERIFIED'
  provenance: 'PASS' | 'PARTIAL' | 'FAIL' | 'UNVERIFIED'
  coverage: string
  performance: 'PASS' | 'PARTIAL' | 'FAIL' | 'UNVERIFIED'
  packaged3848: 'UNVERIFIED' | 'PASS' | 'FAIL'
  finalStatus: GodsEyeProductionStatus
  missingGates: readonly GodsEyeProductionGate[]
  notes: string
}

export const GODS_EYE_PRODUCTION_HARDENING = 'GODS_EYE_PRODUCTION_HARDENING_COMPLETE' as const

export function godsEyeHardeningRows(): readonly GodsEyeHardeningRow[] {
  const until3848: GodsEyeProductionGate[] = ['PACKAGED_3848_COMPATIBLE']
  return [
    {
      feature: 'CLICK_INFO_BUILDING',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / OSM density',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Map-mode pick. Sourced addr:* only. Street-scale OSM required.',
    },
    {
      feature: 'CLICK_INFO_ROAD',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / OSM density',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Sourced highway/name/lanes. Live traffic NO_COVERAGE on geometry.',
    },
    {
      feature: 'CLICK_INFO_TRAFFIC_SIGNAL',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / OSM nodes',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'STATIC INFRASTRUCTURE. LIVE PHASE remains NO_COVERAGE.',
    },
    {
      feature: 'CLICK_INFO_TRAFFIC_CAMERA',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'REGIONAL / PROVIDER_DEPENDENT',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Public agency stills only. Not global. Nearby uses local index; images fetch on inspect.',
    },
    {
      feature: 'CLICK_INFO_LIVE_INTEL',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / providers',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Immediate card + sequence-cancelled enrich. Session may 401 reverse-geocode.',
    },
    {
      feature: 'CLICK_INFO_AIRCRAFT',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'GLOBAL / VIEW-BOUNDED',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'OpenSky when layer enabled. Not verified this pass at every zoom.',
    },
    {
      feature: 'CLICK_INFO_VESSEL',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'REGIONAL / Finland EEZ',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Digitraffic AIS envelope only.',
    },
    {
      feature: 'CLICK_INFO_GROUND',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'GLOBAL pick / PARTIAL reverse-geocode',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Ellipsoid vs terrain height is labeled. No fabricated place name.',
    },
    {
      feature: 'LOD_PERFORMANCE',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'ladder-gated',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Urban fetch off at planet/country. Buildings/signals/house numbers gated. Intel clustered globally. HUD reports fps/primitives/entities/heap; GPU stays UNAVAILABLE in browser.',
    },
    {
      feature: 'STREET_NAMES',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Sourced names. City selective. Caps prevent label storms.',
    },
    {
      feature: 'HOUSE_NUMBERS',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / sourced only',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'addr:housenumber only. Street LOD cap 36. Neighbors never fill.',
    },
    {
      feature: 'TRAFFIC_SIGNAL_INFRASTRUCTURE',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / OSM',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Location sourced. Live phase NO_COVERAGE.',
    },
    {
      feature: 'LIVE_SIGNAL_PHASE',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'NO_COVERAGE',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'NO_COVERAGE',
      missingGates: ['RUNTIME_VERIFIED', 'SOURCE_VERIFIED', 'PACKAGED_3848_COMPATIBLE'],
      notes: 'No authorized SPaT provider.',
    },
    {
      feature: 'TRAFFIC_CAMERAS',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'REGIONAL / PROVIDER_DEPENDENT',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Not globally production-ready. Credentialed 511s are AUTH_REQUIRED.',
    },
    {
      feature: 'MAPILLARYJS',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'AUTH_REQUIRED without token',
      performance: 'UNVERIFIED',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'EVALUATION_ACTIVE',
      missingGates: ['RUNTIME_VERIFIED', 'VISUALLY_VERIFIED', 'PACKAGED_3848_COMPATIBLE'],
      notes: 'Viewer MIT installed. DEV showed AUTH_REQUIRED viewport; token never in DOM. Hosted imagery not loaded. No Google Street View.',
    },
    {
      feature: 'PANORAMAX',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'NO_COVERAGE',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'INTERFACE_ONLY',
      missingGates: ['RUNTIME_VERIFIED', 'VISUALLY_VERIFIED', 'SOURCE_VERIFIED', 'PACKAGED_3848_COMPATIBLE'],
      notes: 'No instance configured. Not production active.',
    },
    {
      feature: 'RE_EARTH_BUILDINGS',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / evaluation switch',
      performance: 'UNVERIFIED',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'EVALUATION_ACTIVE',
      missingGates: ['VISUALLY_VERIFIED', 'PERFORMANCE_ACCEPTABLE', 'PACKAGED_3848_COMPATIBLE'],
      notes: 'DEV switch loaded evaluation_active and restored to off. Not default. OSM Buildings remain. Multi-city visual comparison not completed this pass.',
    },
    {
      feature: 'RE_EARTH_TERRAIN',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL / evaluation switch',
      performance: 'UNVERIFIED',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'EVALUATION_ACTIVE',
      missingGates: ['VISUALLY_VERIFIED', 'PERFORMANCE_ACCEPTABLE', 'PACKAGED_3848_COMPATIBLE'],
      notes: 'DEV switch loaded evaluation_active and restored original provider when off. Does not replace Cesium World Terrain globally. Multi-region samples not completed this pass.',
    },
    {
      feature: 'COMMANDER_SESSION_TERRA_LAYERS',
      devRuntime: 'PARTIAL',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'AUTH_REQUIRED without session',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'requireCommanderSession intact. Host-only wr_local_session via Next cookies.set. localhost HTML canonicalizes to 127.0.0.1. Identity not hard-coded. Protected layers stay gated.',
    },
    {
      feature: 'DOUBLE_CLICK_SPIN',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'n/a',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'LEFT_DOUBLE_CLICK toggles cinematic. Single-click inspect delayed.',
    },
    {
      feature: 'LIVE_INTEL_FLOATING',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'PARTIAL',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'Compact HUD + pin. Auth semantics unchanged.',
    },
    {
      feature: 'CONVERSATION_COMPACT_LOCK',
      devRuntime: 'PASS',
      failureState: 'PASS',
      provenance: 'PASS',
      coverage: 'n/a',
      performance: 'PASS',
      packaged3848: 'UNVERIFIED',
      finalStatus: 'PARTIAL',
      missingGates: until3848,
      notes: 'EXPAND control only.',
    },
  ]
}

export function godsEyeHardeningForbidsProductionReadyWithoutAllGates(row: GodsEyeHardeningRow): boolean {
  return row.finalStatus !== 'PRODUCTION_READY' || row.missingGates.length === 0
}
