import { searchTavilyIncomeOpportunities } from '@/lib/income/tavily'
import { searchIncomeOpportunities } from '@/lib/income/firecrawl'
import { runBraveSignalSearch } from '@/lib/signals/providers/brave'
import { normalizeLootCandidate } from '../normalize'; import { insertIncomeLootOpportunity } from '../store'; import { rankLootOpportunity, type LootRanking } from '../ranking'; import type { LootCategory, LootOpportunity } from '../types'
export type IncomeLootDiscovery={opportunities:LootOpportunity[];rankings:LootRanking[];provider:string|null;queryCount:number;failure:string|null}
function category(text:string):LootCategory{const t=text.toLowerCase();if(/survey|research stud|participant/.test(t))return'SURVEY';if(/store audit|shelf|merchandis|mystery shop|barcode/.test(t))return'STORE_SCAN';if(/receipt|rebate/.test(t))return'RECEIPT_REWARD';if(/cashback/.test(t))return'CASHBACK';if(/deal|coupon|discount/.test(t))return'DEAL';return'OTHER_REWARD'}
async function save(ownerUserId:string, provider:string, candidates:{title:string;url:string;reason:string;type?:string;payout?:string|null}[], queryCount:number):Promise<IncomeLootDiscovery>{const out:LootOpportunity[]=[];for(const candidate of candidates){const record=normalizeLootCandidate({ownerUserId,provider,title:candidate.title,description:candidate.reason,url:candidate.url,category:category(`${candidate.title} ${candidate.type??''}`),reward:null,estimatedTimeMinutes:null,confidence:candidate.payout?60:40,provenance:{sourceAdapterId:provider,sourceType:'web_search',sourceUrl:candidate.url,retrievedAt:new Date().toISOString(),searchQuery:null,providerRecordId:null,freshness:'current',isHistorical:false}});if(record){const inserted=insertIncomeLootOpportunity(record);if(inserted)out.push(inserted)}}return{opportunities:out,rankings:out.map(rankLootOpportunity),provider,queryCount,failure:null}}
export async function discoverIncomeLootFromGeneralWeb(ownerUserId:string):Promise<IncomeLootDiscovery>{const failures:string[]=[];try{const r=await searchTavilyIncomeOpportunities();return save(ownerUserId,'tavily',r.opportunities,r.sourcesChecked)}catch(e){failures.push(`tavily: ${e instanceof Error?e.message:String(e)}`)}try{const r=await runBraveSignalSearch(new Date().toISOString());if(r.diagnostics.configured)return save(ownerUserId,'brave',r.items.map(x=>({title:x.title,url:x.url,reason:x.summary,type:x.categories.join(' ')})),typeof r.diagnostics.queryCount==='number'?r.diagnostics.queryCount:0);failures.push('brave: not configured')}catch(e){failures.push(`brave: ${e instanceof Error?e.message:String(e)}`)}try{const r=await searchIncomeOpportunities();return save(ownerUserId,'firecrawl',r.opportunities,r.sourcesChecked)}catch(e){failures.push(`firecrawl: ${e instanceof Error?e.message:String(e)}`)}return{opportunities:[],rankings:[],provider:null,queryCount:0,failure:failures.join('; ')}}

