/**
 * Roadmap #21 — current actor inventory (runtime-traced).
 * Classification: name sounding like an agent does not make it an agent.
 */
import type { ActorClass, RuntimeStatus } from './types'

export type ActorInventoryItem = {
  id: string
  name: string
  class: ActorClass
  runtimeStatus: RuntimeStatus
  canInvokeTools: boolean
  canSpawnWork: boolean
  canMutateState: boolean
  evidencePaths: readonly string[]
  notes: string
}

export const ACTOR_INVENTORY: readonly ActorInventoryItem[] = Object.freeze([
  {
    id: 'research_agent',
    name: 'RESEARCH_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/ascension/research-agent', 'app/api/ascension/research-agent/run'],
    notes: '#22 Phase 2 bounded read-only discovery worker. Invocation-driven. Ascension autonomy OFF.',
  },
  {
    id: 'engineering_agent',
    name: 'ENGINEERING_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: true,
    evidencePaths: [
      'lib/ascension/engineering-agent',
      'app/api/ascension/engineering-agent/run',
      'lib/native-builder/validationRunner.ts',
      'lib/native-builder/patchPolicy.ts',
    ],
    notes:
      '#22 Phase 3 bounded software worker. Isolated worktree writes + allowlisted validation only. No commit/push/deploy. Ascension autonomy OFF.',
  },
  {
    id: 'security_red_team_agent',
    name: 'SECURITY_RED_TEAM_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/security-red-team-agent',
      'app/api/ascension/security-red-team-agent/run',
      'lib/permissions',
      'lib/war-room/governedAudit.ts',
    ],
    notes:
      '#22 Phase 4 bounded security evaluator. Safe probes + findings only. No exploit/deploy/remediation execution. Ascension autonomy OFF.',
  },
  {
    id: 'operations_agent',
    name: 'OPERATIONS_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/operations-agent',
      'app/api/ascension/operations-agent/run',
      'app/api/health/route.ts',
      'lib/deploy/status.ts',
      'ops/production-supervisor',
    ],
    notes:
      '#22 Phase 5 bounded operational observer. Read-only health/process/port/watchdog diagnostics. No restart/deploy/kill. Ascension autonomy OFF.',
  },
  {
    id: 'terra_intelligence_agent',
    name: 'TERRA_INTELLIGENCE_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/terra-intelligence-agent',
      'app/api/ascension/terra-intelligence-agent/run',
      'lib/terra/liveGeoIntelligence.ts',
      'lib/terra/councilHandoff.ts',
    ],
    notes:
      '#22 Phase 6 bounded Terra world-state analyst. Query/normalize/correlate Terra evidence only. No action authority. GPS/traffic NOT_IMPLEMENTED. Ascension autonomy OFF.',
  },
  {
    id: 'council_validator',
    name: 'COUNCIL_VALIDATOR',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/council-validator',
      'app/api/ascension/council-validator/run',
      'lib/council/session-intelligence',
      'lib/council/family-deliberation',
    ],
    notes:
      '#22 Phase 7 bounded Council output validator. Validates claims vs evidence/policy/runtime truth. VALIDATED!=AUTHORIZED. Not a Council member. Ascension autonomy OFF.',
  },
  {
    id: 'data_corpus_agent',
    name: 'DATA_CORPUS_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/data-corpus-agent',
      'app/api/ascension/data-corpus-agent/run',
      'lib/war-room-search/hybrid',
      'lib/war-room-search/crawler',
    ],
    notes:
      '#22 Phase 8 bounded corpus curator. Quality/dedupe/provenance/WR-CORPUS recommendations only. No crawl/train/#23. Ascension autonomy OFF.',
  },
  {
    id: 'navigation_agent',
    name: 'NAVIGATION_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/navigation-agent',
      'app/api/ascension/navigation-agent/run',
      'lib/terra/navigation',
    ],
    notes:
      '#22 Phase 12 bounded navigation reasoning agent over Phase 9 Terra Navigation Foundation. No device control, GNSS, live traffic, or auto-execute. Ascension autonomy OFF. Operational count includes NAVIGATION_AGENT.',
  },
  {
    id: 'world_learning_agent',
    name: 'WORLD_LEARNING_AGENT',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: [
      'lib/ascension/world-learning-agent',
      'app/api/ascension/world-learning-agent/run',
      'lib/world-learning',
      'lib/ascension/research-agent',
      'lib/ascension/data-corpus-agent',
    ],
    notes:
      '#22 Phase 13 bounded world-knowledge acquisition. Reuses Research/Search/Terra/Corpus/Validator. Candidates only. No training/#23/WRIM/Ra\'el. Ascension autonomy OFF. Operational count=9.',
  },
  {
    id: 'commander',
    name: 'COMMANDER',
    class: 'HUMAN',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: true,
    canMutateState: true,
    evidencePaths: ['lib/security/commanderSession.ts', 'lib/security/commanderIdentity.ts'],
    notes: 'Ultimate governed authority. Session gates ASTRA, memory writes, approvals, native-builder apply.',
  },
  {
    id: 'aurora',
    name: 'AURORA',
    class: 'REASONER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts', 'app/api/chat/execute.ts'],
    notes: 'Council synthesis seat. Consumes injected evidence; does not inherit executor authority.',
  },
  {
    id: 'orion',
    name: 'ORION',
    class: 'REASONER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts', 'lib/council/live-orchestration/backends/seatRouter.ts'],
    notes: 'Engineering/architecture primary reasoner.',
  },
  {
    id: 'pulsar',
    name: 'PULSAR',
    class: 'REASONER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts'],
    notes: 'Research/signals reasoner; may consume live research packets injected by server.',
  },
  {
    id: 'lumen',
    name: 'LUMEN',
    class: 'REASONER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts'],
    notes: 'Claim verification reasoner.',
  },
  {
    id: 'nova',
    name: 'NOVA',
    class: 'REASONER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts', 'lib/council/live-orchestration/backends/localBackend.ts'],
    notes: 'Strategy/sequencing; local-first. Kimi/Moonshot is not a War Room capability.',
  },
  {
    id: 'phoenix',
    name: 'PHOENIX',
    class: 'REASONER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts', 'lib/council/family-deliberation/stageContract.ts'],
    notes: 'Adversarial challenge / revision gate in deliberation pipeline.',
  },
  {
    id: 'solara',
    name: 'SOLARA',
    class: 'REASONER',
    runtimeStatus: 'REGISTERED_ONLY',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/nebula/identity.ts'],
    notes: 'Foundation identity; no live seat routing today.',
  },
  {
    id: 'baby',
    name: 'Baby observer',
    class: 'OBSERVER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/baby-ai/model.ts', 'app/api/baby/chat/route.ts', 'lib/baby-ai/privateChatRoute.ts'],
    notes: 'Observational witness; private chat may call web research. canExecute:false; memory proposals approval-gated. Separated from #19 conversation ownership.',
  },
  {
    id: 'astra',
    name: 'ASTRA',
    class: 'ORCHESTRATOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: true,
    canMutateState: true,
    evidencePaths: ['lib/astra/liveMission.ts', 'app/api/astra/missions'],
    notes: 'Creates/executes missions that invoke Council only. constellationSpawned:false always. Does not answer substantively. Terra selection alone never creates a mission.',
  },
  {
    id: 'council_runtime',
    name: 'Council runtime',
    class: 'ORCHESTRATOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: true,
    canMutateState: false,
    evidencePaths: ['app/api/chat/execute.ts', 'lib/council/family-deliberation'],
    notes: 'Deliberation pipeline. May auto-run live research on research intents. Recommendation ≠ authorization.',
  },
  {
    id: 'scout_swarm',
    name: 'Scout swarm',
    class: 'ORCHESTRATOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: true,
    canMutateState: false,
    evidencePaths: ['lib/council/scout-swarm/runtime.ts'],
    notes: 'Parallel seat discovery + optional live research under Council/ASTRA execute.',
  },
  {
    id: 'constellation_temps',
    name: 'Constellation temporary agents',
    class: 'REASONER',
    runtimeStatus: 'DEFERRED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/constellation/planner.ts'],
    notes: 'Plan-only; live spawn deferred. allowedTools:[].',
  },
  {
    id: 'terra',
    name: 'Terra',
    class: 'WORLD_STATE_SOURCE',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/terra', 'app/api/terra', 'lib/terra/councilHandoff.ts'],
    notes: 'World-state Oracle surface. Does NOT authorize action, create missions, or act as a second Council.',
  },
  {
    id: 'research_engine',
    name: 'Research Engine',
    class: 'DATA_SOURCE',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/research-engine', 'app/api/research/search'],
    notes: 'Provider-routed read/fetch. Not an autonomous agent.',
  },
  {
    id: 'search_engine',
    name: 'War Room Search',
    class: 'DATA_SOURCE',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/war-room-search', 'app/api/search'],
    notes: 'Federated search + Council handoff packet.',
  },
  {
    id: 'crawler',
    name: 'Sovereign crawler',
    class: 'TOOL',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: true,
    evidencePaths: ['lib/war-room-search/crawler'],
    notes: 'Approved-URL crawl into local corpus only. Not recursive sitemap scheduler.',
  },
  {
    id: 'ollama_bridge',
    name: 'Ollama local model bridge',
    class: 'TOOL',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/live-orchestration/backends/localBackend.ts', 'lib/native-builder/ollamaClient.ts'],
    notes: 'Model runtime for seats when local routing wins. Not an agent persona.',
  },
  {
    id: 'native_builder',
    name: 'Native-builder / Mission Runtime',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: true,
    evidencePaths: ['lib/native-builder', 'lib/mission-runtime', 'app/api/native-builder'],
    notes: 'Bounded repo patch apply + fixed validation processes under Commander approval. No git commit/push.',
  },
  {
    id: 'codex',
    name: 'Codex engineering agent',
    class: 'EXECUTOR',
    runtimeStatus: 'NOT_IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/engineering/codexEngineeringAgent.ts', 'lib/engineering/engineeringAgentRegistry.ts'],
    notes: 'not_connected; canBeInvokedByWarRoom:false.',
  },
  {
    id: 'cursor_agent',
    name: 'Cursor engineering agent',
    class: 'EXECUTOR',
    runtimeStatus: 'REGISTERED_ONLY',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/engineering/cursorEngineeringAgent.ts'],
    notes: 'available_manual; War Room emits packets only — cannot invoke Cursor.',
  },
  {
    id: 'foundry',
    name: 'Agent Foundry blueprints',
    class: 'OTHER',
    runtimeStatus: 'REGISTERED_ONLY',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/agents/foundry/agentBlueprints.ts', 'lib/agents/foundry/agentCapabilityRegistry.ts'],
    notes: 'Registry/snapshot. external_execution and self_expansion forbidden.',
  },
  {
    id: 'opportunity_agents',
    name: 'Opportunity agents',
    class: 'ORCHESTRATOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/opportunity-agents'],
    notes: 'Approval-bound packet builders. externalActionsExecuted:false by default.',
  },
  {
    id: 'income_workers',
    name: 'Income workers',
    class: 'ORCHESTRATOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/income-workers'],
    notes: 'Scout/score/assign; payouts approval-gated. No autonomous payout.',
  },
  {
    id: 'background_workers',
    name: 'Background workers',
    class: 'EXECUTOR',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: true,
    canSpawnWork: false,
    canMutateState: true,
    evidencePaths: ['lib/workers', 'app/api/workers'],
    notes: 'Ops poll/scan/queue under limits — not Council LLM agents.',
  },
  {
    id: 'production_supervisor',
    name: 'Production supervisor / watchdog',
    class: 'OTHER',
    runtimeStatus: 'IMPLEMENTED',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: true,
    evidencePaths: ['ops/production-supervisor', 'lib/ops/production-supervisor'],
    notes: 'OS scripts outside Council. Ownership-gated restart. Not an in-app agent.',
  },
  {
    id: 'ascension',
    name: 'ASCENSION foundation',
    class: 'OTHER',
    runtimeStatus: 'REGISTERED_ONLY',
    canInvokeTools: false,
    canSpawnWork: false,
    canMutateState: false,
    evidencePaths: ['lib/council/ascension'],
    notes: 'Data model only. Autonomy guards frozen false. #22 not started.',
  },
])

export function actorsByClass(actorClass: ActorClass): ActorInventoryItem[] {
  return ACTOR_INVENTORY.filter(a => a.class === actorClass)
}
