/**
 * Roadmap #21 — canonical capability matrix rows.
 * Every row separates TECHNICAL REACH from POLICY AUTHORITY.
 * TARGET_ASCENSION rows are proposed definitions — not current powers.
 */
import type { CapabilityMatrixEntry } from './types'

function row(
  partial: CapabilityMatrixEntry,
): CapabilityMatrixEntry {
  return partial
}

/**
 * High-signal matrix covering domains × proposed agents × critical actions.
 * Not every domain×action×agent combination — validation enforces invariants across this set.
 */
export const CANONICAL_CAPABILITY_MATRIX: readonly CapabilityMatrixEntry[] = Object.freeze([
  // —— RESEARCH AGENT ——
  row({
    id: 'research.web.read',
    agentRole: 'RESEARCH_AGENT',
    domain: 'WEB_INTERNET',
    action: 'READ',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'POLICY_AUTO_ALLOWED',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'lib/ascension/research-agent — bounded RESEARCH_AGENT; runLiveResearchRouter; SESSION_BOUNDED_READ_ONLY_DISCOVERY',
  }),
  row({
    id: 'research.terra.query',
    agentRole: 'RESEARCH_AGENT',
    domain: 'TERRA_ORACLE',
    action: 'QUERY',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED_BOUNDED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Optional Terra handoff read-only context on RESEARCH_AGENT invocation; Terra remains Oracle',
  }),
  row({
    id: 'research.web.crawl',
    agentRole: 'RESEARCH_AGENT',
    domain: 'CRAWLER',
    action: 'CRAWL',
    technicalReach: 'EXECUTE_CONTROLLED',
    policyAuthority: 'APPROVAL_REQUIRED',
    riskTier: 'TIER_3_EXTERNAL_REMOTE_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'lib/war-room-search/crawler — CrawlApproval required; ASTRA has no crawl wiring',
  }),
  row({
    id: 'research.deploy',
    agentRole: 'RESEARCH_AGENT',
    domain: 'DEPLOYMENT',
    action: 'DEPLOY',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'No research path invokes deploy; kernel autonomousExecutionAllowed:false',
  }),
  row({
    id: 'research.financial',
    agentRole: 'RESEARCH_AGENT',
    domain: 'FINANCIAL_SYSTEMS',
    action: 'PURCHASE_SPEND',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Payments API is deposit ledger visibility only; no outbound spend route',
  }),

  // —— ENGINEERING AGENT ——
  row({
    id: 'eng.repo.read',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'REPOSITORY',
    action: 'READ',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'POLICY_AUTO_ALLOWED',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'lib/repo/status.ts; app/api/tools/repo; repo_scan_readonly standing kind',
  }),
  row({
    id: 'eng.repo.write',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'REPOSITORY',
    action: 'WRITE',
    technicalReach: 'WRITE_BOUNDED',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'ONE_ACTION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'native-builder patchApplier + patchPolicy denylist; assertAutoOrApproval file_modification',
  }),
  row({
    id: 'eng.shell.execute',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'SHELL_POWERSHELL',
    action: 'EXECUTE',
    technicalReach: 'EXECUTE_SANDBOXED',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_1_REVERSIBLE_LOCAL_SANDBOX',
    approvalRequirement: 'ONE_ACTION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'validationRunner fixed argv only (tsc/eslint/build); no free-form shell',
  }),
  row({
    id: 'eng.git.commit',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'GIT',
    action: 'COMMIT',
    technicalReach: 'DISCOVER_ONLY',
    policyAuthority: 'APPROVAL_REQUIRED',
    riskTier: 'TIER_3_EXTERNAL_REMOTE_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'nativeBuilder.validation forbids git commit registration; commitPreparation plans for humans only',
  }),
  row({
    id: 'eng.git.push',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'GIT',
    action: 'PUSH',
    technicalReach: 'DISCOVER_ONLY',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'git_push not a registered native-builder operation; Commander/human only',
  }),
  row({
    id: 'eng.deploy',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'DEPLOYMENT',
    action: 'DEPLOY',
    technicalReach: 'DISCOVER_ONLY',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'app/api/deploy/status status-only; no vercel/netlify deploy in agent APIs',
  }),
  row({
    id: 'eng.git.push.target',
    agentRole: 'ENGINEERING_AGENT',
    domain: 'GIT',
    action: 'PUSH',
    technicalReach: 'EXECUTE_CONTROLLED',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'PLANNED',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'TARGET only — must remain Commander-only even if technical reach is later added',
  }),

  // —— TERRA INTELLIGENCE AGENT (future definition) ——
  row({
    id: 'terra.query',
    agentRole: 'TERRA_INTELLIGENCE_AGENT',
    domain: 'TERRA_ORACLE',
    action: 'QUERY',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'PLANNED',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'TARGET: query Terra feeds; CURRENT Terra APIs are Commander-session tools, not a dedicated agent',
  }),
  row({
    id: 'terra.analyze',
    agentRole: 'TERRA_INTELLIGENCE_AGENT',
    domain: 'TERRA_ORACLE',
    action: 'ANALYZE',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'NO_APPROVAL',
    runtimeStatus: 'PLANNED',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'TARGET: assemble/compare freshness; submit evidence to Council — not authorize action',
  }),
  row({
    id: 'terra.mission.launch',
    agentRole: 'TERRA_INTELLIGENCE_AGENT',
    domain: 'ASTRA',
    action: 'CREATE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'Terra Intelligence Agent must NOT auto-launch missions; ASTRA+Commander only',
  }),
  row({
    id: 'terra.current.read',
    agentRole: 'COMMANDER',
    domain: 'TERRA_ORACLE',
    action: 'READ',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'app/api/terra/* requireCommanderSession; councilHandoff evidence only',
  }),

  // —— OPERATIONS AGENT ——
  row({
    id: 'ops.watchdog.read',
    agentRole: 'OPERATIONS_AGENT',
    domain: 'WATCHDOG',
    action: 'READ',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'lib/ops/production-supervisor validation; deploy/status probes',
  }),
  row({
    id: 'ops.prod.restart',
    agentRole: 'OPERATIONS_AGENT',
    domain: 'PRODUCTION_RUNTIME',
    action: 'RESTART',
    technicalReach: 'EXECUTE_CONTROLLED',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'ops/production-supervisor ownership-gated; agents must not restart production autonomously',
  }),
  row({
    id: 'ops.deploy',
    agentRole: 'OPERATIONS_AGENT',
    domain: 'DEPLOYMENT',
    action: 'DEPLOY',
    technicalReach: 'DISCOVER_ONLY',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'No agent deploy executor; DANGEROUS kind deploy never auto-allowed',
  }),

  // —— SECURITY / RED TEAM ——
  row({
    id: 'sec.analyze',
    agentRole: 'SECURITY_RED_TEAM_AGENT',
    domain: 'SECURITY_DESTRUCTIVE',
    action: 'ANALYZE',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'NO_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'PHOENIX reasoner + red-sentinel scan; advisory/challenge only',
  }),
  row({
    id: 'sec.delete',
    agentRole: 'SECURITY_RED_TEAM_AGENT',
    domain: 'SECURITY_DESTRUCTIVE',
    action: 'DELETE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Red team has no destructive executor path; delete_data is dangerous kind',
  }),
  row({
    id: 'sec.approve.self',
    agentRole: 'SECURITY_RED_TEAM_AGENT',
    domain: 'SECURITY_DESTRUCTIVE',
    action: 'APPROVE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'No-self-escalation: agents cannot approve their own approvals',
  }),

  // —— COUNCIL VALIDATOR ——
  row({
    id: 'council.validate',
    agentRole: 'COUNCIL_VALIDATOR',
    domain: 'COUNCIL_SESSION_INTELLIGENCE',
    action: 'ANALYZE',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'NO_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'PHOENIX/LUMEN challenge+verify roles; session intelligence evidence refs',
  }),
  row({
    id: 'council.authorize.execute',
    agentRole: 'COUNCIL_VALIDATOR',
    domain: 'ASTRA',
    action: 'APPROVE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_3_EXTERNAL_REMOTE_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Council recommendation != authorization; Council cannot authorize itself',
  }),
  row({
    id: 'council.push',
    agentRole: 'COUNCIL_SEAT',
    domain: 'GIT',
    action: 'PUSH',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Seats are reasoners; no git mutation path from Council invoke',
  }),

  // —— ASTRA ——
  row({
    id: 'astra.mission.create',
    agentRole: 'ASTRA_ORCHESTRATOR',
    domain: 'ASTRA',
    action: 'CREATE',
    technicalReach: 'WRITE_BOUNDED',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'POST /api/astra/missions — Commander session; planned status; MISSION_CREATED != ACTION_AUTHORIZED',
  }),
  row({
    id: 'astra.mission.execute',
    agentRole: 'ASTRA_ORCHESTRATOR',
    domain: 'ASTRA',
    action: 'EXECUTE',
    technicalReach: 'EXECUTE_CONTROLLED',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'ONE_ACTION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'POST execute → executeCouncilChatRequest; constellationSpawned:false; PLANNED!=RUNNING',
  }),
  row({
    id: 'astra.spawn.workers',
    agentRole: 'ASTRA_ORCHESTRATOR',
    domain: 'ASTRA',
    action: 'CREATE',
    technicalReach: 'DISCOVER_ONLY',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_3_EXTERNAL_REMOTE_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'DEFERRED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'planBoundedConstellation spawned:false always; SPAWN REQUEST != WORKER SPAWNED',
  }),
  row({
    id: 'astra.deploy',
    agentRole: 'ASTRA_ORCHESTRATOR',
    domain: 'DEPLOYMENT',
    action: 'DEPLOY',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'ASTRA does not deploy; #14 freeze no ASCENSION behavior',
  }),
  row({
    id: 'astra.financial',
    agentRole: 'ASTRA_ORCHESTRATOR',
    domain: 'FINANCIAL_SYSTEMS',
    action: 'TRANSFER',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'No ASTRA payment/transfer path',
  }),

  // —— DATA / CORPUS ——
  row({
    id: 'corpus.read',
    agentRole: 'DATA_CORPUS_AGENT',
    domain: 'SOVEREIGN_SEARCH',
    action: 'QUERY',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'READ_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'POLICY_AUTO_ALLOWED',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'lib/war-room-search hybrid local index query',
  }),
  row({
    id: 'corpus.crawl.write',
    agentRole: 'DATA_CORPUS_AGENT',
    domain: 'CRAWLER',
    action: 'WRITE',
    technicalReach: 'WRITE_BOUNDED',
    policyAuthority: 'APPROVAL_REQUIRED',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Approved crawl mutates local corpus only',
  }),
  row({
    id: 'corpus.sql.alter',
    agentRole: 'DATA_CORPUS_AGENT',
    domain: 'SQL',
    action: 'ALTER_DATABASE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'No arbitrary SQL executor API; migrations are manual operator apply',
  }),

  // —— FUTURE NAVIGATION ——
  row({
    id: 'nav.terra.query',
    agentRole: 'FUTURE_NAVIGATION_AGENT',
    domain: 'TERRA_ORACLE',
    action: 'QUERY',
    technicalReach: 'NO_REACH',
    policyAuthority: 'NOT_APPLICABLE',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'NOT_IMPLEMENTED',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'Navigation/GPS marked FUTURE in Terra Oracle contract; do not claim current reach',
  }),
  row({
    id: 'nav.device.control',
    agentRole: 'FUTURE_NAVIGATION_AGENT',
    domain: 'EXTERNAL_APIS',
    action: 'EXECUTE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'NOT_IMPLEMENTED',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'No device-control surface; must remain denied by default',
  }),

  // —— FUTURE WORLD-LEARNING ——
  row({
    id: 'worldlearn.analyze',
    agentRole: 'FUTURE_WORLD_LEARNING_AGENT',
    domain: 'MEMORY',
    action: 'ANALYZE',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'REGISTERED_ONLY',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'lib/world-learning exists as research foundation; not an authorized executor',
  }),
  row({
    id: 'worldlearn.memory.write',
    agentRole: 'FUTURE_WORLD_LEARNING_AGENT',
    domain: 'MEMORY',
    action: 'WRITE',
    technicalReach: 'WRITE_BOUNDED',
    policyAuthority: 'APPROVAL_REQUIRED',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'PLANNED',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'Memory writes require ExplicitMemoryWriteApproval; ownership boundaries (#19)',
  }),
  row({
    id: 'worldlearn.self.expand',
    agentRole: 'FUTURE_WORLD_LEARNING_AGENT',
    domain: 'SECURITY_DESTRUCTIVE',
    action: 'MODIFY',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'TARGET_ASCENSION',
    evidence: 'ASCENSION selfModificationEnabled:false; foundry self_expansion allowed:false',
  }),

  // —— BABY ——
  row({
    id: 'baby.observe',
    agentRole: 'BABY_OBSERVER',
    domain: 'COUNCIL_SESSION_INTELLIGENCE',
    action: 'READ',
    technicalReach: 'READ_ONLY',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'SESSION_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Baby observational seat; BABY_AI_GUARDRAILS; no shell/fs/deploy',
  }),
  row({
    id: 'baby.execute',
    agentRole: 'BABY_OBSERVER',
    domain: 'SHELL_POWERSHELL',
    action: 'EXECUTE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'STRUCTURALLY_FORBIDDEN',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'canExecute:false; Baby separation from conversation ownership',
  }),

  // —— NATIVE BUILDER / WORKERS / MEMORY / SUPABASE cross-cuts ——
  row({
    id: 'nb.ollama',
    agentRole: 'NATIVE_BUILDER',
    domain: 'LOCAL_MODELS_OLLAMA',
    action: 'QUERY',
    technicalReach: 'EXECUTE_SANDBOXED',
    policyAuthority: 'BOUNDED_ALLOWED',
    riskTier: 'TIER_1_REVERSIBLE_LOCAL_SANDBOX',
    approvalRequirement: 'POLICY_AUTO_ALLOWED',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'ollamaClient /api/tags + generate; empirical #21 probe PASS on localhost:11434',
  }),
  row({
    id: 'nb.browser',
    agentRole: 'NATIVE_BUILDER',
    domain: 'BROWSER',
    action: 'EXECUTE',
    technicalReach: 'NO_REACH',
    policyAuthority: 'NOT_APPLICABLE',
    riskTier: 'TIER_0_READ_OBSERVE',
    approvalRequirement: 'NO_APPROVAL',
    runtimeStatus: 'NOT_IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Playwright is test-only; no agent browser/computer-use tool',
  }),
  row({
    id: 'nb.email',
    agentRole: 'NATIVE_BUILDER',
    domain: 'EMAIL_COMMUNICATIONS',
    action: 'SEND',
    technicalReach: 'NO_REACH',
    policyAuthority: 'DENIED',
    riskTier: 'TIER_3_EXTERNAL_REMOTE_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'NOT_IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'email_send dangerous kind unwired; auth confirmation email only',
  }),
  row({
    id: 'nb.twilio',
    agentRole: 'OPERATIONS_AGENT',
    domain: 'PHONE_TWILIO',
    action: 'SEND',
    technicalReach: 'NO_REACH',
    policyAuthority: 'NOT_APPLICABLE',
    riskTier: 'TIER_3_EXTERNAL_REMOTE_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'NOT_IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'No Twilio adapter/routes found',
  }),
  row({
    id: 'memory.write',
    agentRole: 'COUNCIL_SEAT',
    domain: 'MEMORY',
    action: 'WRITE',
    technicalReach: 'WRITE_BOUNDED',
    policyAuthority: 'APPROVAL_REQUIRED',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'MemoryApprovalVerifier; ExplicitExecutionApproval cannot authorize memory writes',
  }),
  row({
    id: 'supabase.service.role',
    agentRole: 'BACKGROUND_WORKER',
    domain: 'SUPABASE',
    action: 'QUERY',
    technicalReach: 'FULL_TECHNICAL_REACH',
    policyAuthority: 'SYSTEM_INTERNAL',
    riskTier: 'TIER_2_PERSISTENT_INTERNAL_MUTATION',
    approvalRequirement: 'NO_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Service-role credentials exist technically; #19 requireOwnedConversation — service role ≠ policy permission for user data',
  }),
  row({
    id: 'commander.approve.tier4',
    agentRole: 'COMMANDER',
    domain: 'SECURITY_DESTRUCTIVE',
    action: 'APPROVE',
    technicalReach: 'FULL_TECHNICAL_REACH',
    policyAuthority: 'COMMANDER_ONLY',
    riskTier: 'TIER_4_PRODUCTION_DESTRUCTIVE_FINANCIAL_LEGAL',
    approvalRequirement: 'COMMANDER_EXPLICIT_APPROVAL',
    runtimeStatus: 'IMPLEMENTED',
    currentVsTarget: 'CURRENT_RUNTIME',
    evidence: 'Commander remains ultimate authority for governed Tier 4 actions',
  }),
])

export function matrixForAgent(agentRole: CapabilityMatrixEntry['agentRole']): CapabilityMatrixEntry[] {
  return CANONICAL_CAPABILITY_MATRIX.filter(e => e.agentRole === agentRole)
}

export function matrixCurrentRuntime(): CapabilityMatrixEntry[] {
  return CANONICAL_CAPABILITY_MATRIX.filter(e => e.currentVsTarget === 'CURRENT_RUNTIME')
}

export function matrixTargetAscension(): CapabilityMatrixEntry[] {
  return CANONICAL_CAPABILITY_MATRIX.filter(e => e.currentVsTarget === 'TARGET_ASCENSION')
}
