import type { IncomeWorker, IncomeWorkerWorkflowStep } from './types'

export const INCOME_WORKERS: IncomeWorker[] = [
  {
    id: 'job_scout',
    name: 'Job Scout Worker',
    focus: 'W2 and contract job leads with clear application paths.',
    capabilities: ['job search', 'source verification', 'application planning'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'gig_scout',
    name: 'Gig Scout Worker',
    focus: 'Short-cycle gigs, paid studies, user testing, and micro-contracts.',
    capabilities: ['gig search', 'speed ranking', 'risk filtering'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'freight_lead',
    name: 'Freight Lead Worker',
    focus: 'Freight, dispatch, delivery, and transport-adjacent lead discovery.',
    capabilities: ['freight lead intake', 'route/business fit checks', 'broker/source review'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'remote_work',
    name: 'Remote Work Worker',
    focus: 'Remote work and flexible operator tasks.',
    capabilities: ['remote role scan', 'fit scoring', 'application task list'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'contract_opportunity',
    name: 'Contract Opportunity Worker',
    focus: 'Client contracts, RFP-style work, and paid business opportunities.',
    capabilities: ['contract lead review', 'deadline tracking', 'submission prep'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'digital_product',
    name: 'Digital Product Worker',
    focus: 'Digital product ideas, packaging, listing, and launch tasks.',
    capabilities: ['product ideation', 'offer packaging', 'launch checklist'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'affiliate_lead_gen',
    name: 'Affiliate/Lead Gen Worker',
    focus: 'Compliant lead generation and affiliate opportunity tracking.',
    capabilities: ['program review', 'lead source checks', 'compliance notes'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'automation_service',
    name: 'Automation Service Worker',
    focus: 'Automation service offers, client pain points, and delivery scopes.',
    capabilities: ['service scoping', 'proposal outline', 'delivery checklist'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'revenue_tracker',
    name: 'Revenue Tracker Worker',
    focus: 'Expected payout, actual payout, and proof tracking.',
    capabilities: ['expected payout ledger', 'status tracking', 'proof requirement checks'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
  {
    id: 'payout_preparation',
    name: 'Payout Preparation Worker',
    focus: 'Payout readiness and secure approval handoff.',
    capabilities: ['payout checklist', 'secure approval gate', 'provider handoff prep'],
    status: 'idle',
    requiresApproval: true,
    payoutProofRequired: true,
    secureApprovalRequiredForPayouts: true,
  },
]

export const INCOME_WORKER_WORKFLOW: IncomeWorkerWorkflowStep[] = [
  { order: 1, id: 'scout', label: 'scout opportunity', approvalRequired: false },
  { order: 2, id: 'verify', label: 'verify legitimacy', approvalRequired: false },
  { order: 3, id: 'score', label: 'score opportunity', approvalRequired: false },
  { order: 4, id: 'assign', label: 'assign eligible agent/family', approvalRequired: true },
  { order: 5, id: 'plan', label: 'create action plan', approvalRequired: true },
  { order: 6, id: 'queue', label: 'queue task', approvalRequired: true },
  { order: 7, id: 'track', label: 'track progress', approvalRequired: false },
  { order: 8, id: 'expected_payout', label: 'record expected payout', approvalRequired: false },
  { order: 9, id: 'actual_payout', label: 'record actual payout only when confirmed', approvalRequired: true },
  { order: 10, id: 'payout_request', label: 'prepare payout/transfer request only with secure approval', approvalRequired: true },
]

export function getIncomeWorker(workerId: string | undefined) {
  return INCOME_WORKERS.find(worker => worker.id === workerId) ?? null
}
