import type { TerraLocalSource } from './types'

const VERIFIED = '2026-09-17'

/** Seed registry for known lawful public feeds. Not a complete Earth station list. */
export const TERRA_LOCAL_SOURCE_SEEDS: TerraLocalSource[] = [
  {
    id: 'us-oh-wkyc',
    name: 'WKYC 3 Cleveland',
    type: 'TV',
    city: 'Cleveland',
    county: 'Cuyahoga County',
    metro: 'Cleveland',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'METRO',
    serviceArea: 'Cleveland / Akron / Northeast Ohio',
    aliases: ['cleveland', 'akron', 'cuyahoga', 'summit', 'lorain', 'lake county', 'northeast ohio', 'ne ohio'],
    homepage: 'https://www.wkyc.com/',
    feedUrl: 'https://www.wkyc.com/feeds/syndication/rss/news/local',
    feedType: 'RSS',
    language: 'en',
    provider: 'Tegna',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-oh-fox8',
    name: 'Fox 8 WJW Cleveland',
    type: 'TV',
    city: 'Cleveland',
    county: 'Cuyahoga County',
    metro: 'Cleveland',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'METRO',
    serviceArea: 'Cleveland / Akron / Northeast Ohio',
    aliases: ['cleveland', 'akron', 'cuyahoga', 'summit', 'northeast ohio'],
    homepage: 'https://www.fox8.com/',
    feedUrl: 'https://www.fox8.com/feed',
    feedType: 'RSS',
    language: 'en',
    provider: 'Nexstar',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-oh-cleveland-com',
    name: 'cleveland.com',
    type: 'NEWSPAPER',
    city: 'Cleveland',
    county: 'Cuyahoga County',
    metro: 'Cleveland',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'METRO',
    serviceArea: 'Cleveland / Northeast Ohio',
    aliases: ['cleveland', 'akron', 'cuyahoga', 'summit', 'northeast ohio'],
    homepage: 'https://www.cleveland.com/',
    feedUrl: 'https://www.cleveland.com/arc/outboundfeeds/rss/?outputType=xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'Advance Local',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public newspaper RSS.',
  },
  {
    id: 'us-oh-akron-beacon-journal',
    name: 'Akron Beacon Journal',
    type: 'NEWSPAPER',
    city: 'Akron',
    county: 'Summit County',
    metro: 'Akron',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Akron / Summit County',
    aliases: ['akron', 'summit'],
    homepage: 'https://www.beaconjournal.com/',
    feedUrl: 'https://www.beaconjournal.com/news/rss',
    feedType: 'RSS',
    language: 'en',
    provider: 'Gannett',
    lastVerified: VERIFIED,
    status: 'BLOCKED',
    licenseClass: 'RESTRICTED',
    provenance: 'Homepage known; public RSS returned HTTP 403 during verification.',
  },
  {
    id: 'us-nws-point',
    name: 'NWS local alerts',
    type: 'WEATHER',
    city: null,
    county: null,
    metro: null,
    region: null,
    state: null,
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Point alerts for the active US location',
    aliases: [],
    homepage: 'https://www.weather.gov/',
    feedUrl: 'nws:point',
    feedType: 'API',
    language: 'en',
    provider: 'NOAA / NWS',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_API',
    provenance: 'Existing Terra NWS adapter; not a second weather engine.',
  },
  {
    id: 'us-nyc-abc7',
    name: 'ABC7 New York',
    type: 'TV',
    city: 'New York',
    county: 'New York County',
    metro: 'New York City',
    region: 'New York metropolitan area',
    state: 'New York',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'New York City',
    aliases: ['new york', 'nyc', 'manhattan', 'brooklyn', 'queens', 'bronx', 'staten island'],
    homepage: 'https://abc7ny.com/',
    feedUrl: 'https://abc7ny.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'ABC Owned Television Stations',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-nyc-nbc',
    name: 'NBC New York',
    type: 'TV',
    city: 'New York',
    county: 'New York County',
    metro: 'New York City',
    region: 'New York metropolitan area',
    state: 'New York',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'New York City',
    aliases: ['new york', 'nyc', 'manhattan', 'brooklyn', 'queens', 'bronx'],
    homepage: 'https://www.nbcnewyork.com/',
    feedUrl: 'https://www.nbcnewyork.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'NBCUniversal',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-nyc-cbs',
    name: 'CBS New York',
    type: 'TV',
    city: 'New York',
    county: 'New York County',
    metro: 'New York City',
    region: 'New York metropolitan area',
    state: 'New York',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'New York City',
    aliases: ['new york', 'nyc', 'manhattan', 'brooklyn', 'queens', 'bronx'],
    homepage: 'https://www.cbsnews.com/newyork/',
    feedUrl: 'https://www.cbsnews.com/newyork/latest/rss/main',
    feedType: 'RSS',
    language: 'en',
    provider: 'CBS News',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-nyc-gothamist',
    name: 'Gothamist',
    type: 'NEWSPAPER',
    city: 'New York',
    county: 'New York County',
    metro: 'New York City',
    region: 'New York metropolitan area',
    state: 'New York',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'New York City',
    aliases: ['new york', 'nyc', 'manhattan', 'brooklyn', 'queens', 'bronx'],
    homepage: 'https://gothamist.com/',
    feedUrl: 'https://gothamist.com/feed',
    feedType: 'RSS',
    language: 'en',
    provider: 'New York Public Radio',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public local RSS.',
  },
  {
    id: 'uk-london-bbc',
    name: 'BBC News London',
    type: 'TV',
    city: 'London',
    county: 'Greater London',
    metro: 'London',
    region: 'Greater London',
    state: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    coverageLevel: 'CITY',
    serviceArea: 'London',
    aliases: ['london', 'westminster', 'greater london', 'camden', 'islington', 'southwark', 'lambeth'],
    homepage: 'https://www.bbc.co.uk/news/england/london',
    feedUrl: 'https://feeds.bbci.co.uk/news/england/london/rss.xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'BBC',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed BBC London RSS — not BBC World.',
  },
  {
    id: 'uk-england-bbc',
    name: 'BBC News England',
    type: 'TV',
    city: null,
    county: null,
    metro: null,
    region: 'England',
    state: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    coverageLevel: 'REGIONAL',
    serviceArea: 'England',
    aliases: ['england'],
    homepage: 'https://www.bbc.co.uk/news/england',
    feedUrl: 'https://feeds.bbci.co.uk/news/england/rss.xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'BBC',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed BBC England RSS. Story geo-match still required.',
  },
  {
    id: 'uk-london-standard',
    name: 'Evening Standard',
    type: 'NEWSPAPER',
    city: 'London',
    county: 'Greater London',
    metro: 'London',
    region: 'Greater London',
    state: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    coverageLevel: 'CITY',
    serviceArea: 'London',
    aliases: ['london', 'greater london', 'westminster'],
    homepage: 'https://www.standard.co.uk/',
    feedUrl: 'https://www.standard.co.uk/rss',
    feedType: 'RSS',
    language: 'en',
    provider: 'Evening Standard',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public newspaper RSS.',
  },
  {
    id: 'uk-london-gov',
    name: 'Mayor of London / London Assembly',
    type: 'PUBLIC_AGENCY',
    city: 'London',
    county: 'Greater London',
    metro: 'London',
    region: 'Greater London',
    state: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    coverageLevel: 'CITY',
    serviceArea: 'Greater London',
    aliases: ['london', 'greater london', 'city hall'],
    homepage: 'https://www.london.gov.uk/',
    feedUrl: 'https://www.london.gov.uk/rss.xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'Greater London Authority',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed official city RSS.',
  },
  {
    id: 'uk-london-tfl',
    name: 'Transport for London',
    type: 'TRANSPORTATION',
    city: 'London',
    county: 'Greater London',
    metro: 'London',
    region: 'Greater London',
    state: 'England',
    country: 'United Kingdom',
    countryCode: 'GB',
    coverageLevel: 'CITY',
    serviceArea: 'Greater London',
    aliases: ['london', 'tfl', 'underground', 'tube'],
    homepage: 'https://tfl.gov.uk/',
    feedUrl: 'https://api.tfl.gov.uk/Line/Mode/tube,dlr,overground,elizabeth-line/Status',
    feedType: 'JSON',
    language: 'en',
    provider: 'TfL',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_API',
    provenance: 'Live-probed public TfL status API.',
  },
  {
    id: 'za-cape-town-etc',
    name: 'Cape Town ETC',
    type: 'NEWSPAPER',
    city: 'Cape Town',
    county: 'City of Cape Town',
    metro: 'Cape Town',
    region: 'Western Cape',
    state: 'Western Cape',
    country: 'South Africa',
    countryCode: 'ZA',
    coverageLevel: 'CITY',
    serviceArea: 'Cape Town / Western Cape',
    aliases: ['cape town', 'kaapstad', 'western cape', 'cape peninsula'],
    homepage: 'https://www.capetownetc.com/',
    feedUrl: 'https://www.capetownetc.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'Cape Town ETC',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public local RSS.',
  },
  {
    id: 'us-oh-holmes-county',
    name: 'Holmes County, Ohio',
    type: 'PUBLIC_AGENCY',
    city: 'Millersburg',
    county: 'Holmes County',
    metro: null,
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'COUNTY',
    serviceArea: 'Holmes County',
    aliases: ['holmes county', 'millersburg', 'holmes'],
    homepage: 'https://www.holmescountyohio.gov/',
    feedUrl: null,
    feedType: 'NONE',
    language: 'en',
    provider: 'Holmes County',
    lastVerified: VERIFIED,
    status: 'NO_FEED',
    licenseClass: 'PUBLIC_HTML',
    provenance: 'Official county homepage; no public machine feed verified.',
  },
  {
    id: 'us-oh-wooster-daily-record',
    name: 'The Daily Record (Wooster)',
    type: 'NEWSPAPER',
    city: 'Wooster',
    county: 'Wayne County',
    metro: null,
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'REGIONAL',
    serviceArea: 'Wayne / Holmes / Northeast Ohio',
    aliases: ['wooster', 'holmes county', 'millersburg', 'wayne county'],
    homepage: 'https://www.the-daily-record.com/',
    feedUrl: 'https://www.the-daily-record.com/feed',
    feedType: 'RSS',
    language: 'en',
    provider: 'Gannett',
    lastVerified: VERIFIED,
    status: 'BLOCKED',
    licenseClass: 'RESTRICTED',
    provenance: 'Regional paper; public RSS returned HTTP 403 during verification.',
  },
  {
    id: 'us-oh-woio',
    name: 'Cleveland19 WOIO',
    type: 'TV',
    city: 'Cleveland',
    county: 'Cuyahoga County',
    metro: 'Cleveland',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'METRO',
    serviceArea: 'Cleveland / Akron / Northeast Ohio',
    aliases: ['cleveland', 'akron', 'cuyahoga', 'summit', 'northeast ohio'],
    homepage: 'https://www.cleveland19.com/',
    feedUrl: 'https://www.cleveland19.com/arc/outboundfeeds/rss/?outputType=xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'Gray Television',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS with items.',
  },
  {
    id: 'us-oh-akron-city',
    name: 'City of Akron',
    type: 'PUBLIC_AGENCY',
    city: 'Akron',
    county: 'Summit County',
    metro: 'Akron',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Akron',
    aliases: ['akron', 'summit'],
    homepage: 'https://www.akronohio.gov/',
    feedUrl: 'https://www.akronohio.gov/rss.xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'City of Akron',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed official city RSS (25 items on 2026-09-17).',
  },
  {
    id: 'us-oh-holmes-herald',
    name: 'Holmes County Herald',
    type: 'NEWSPAPER',
    city: 'Millersburg',
    county: 'Holmes County',
    metro: null,
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'COUNTY',
    serviceArea: 'Holmes County',
    aliases: ['holmes county', 'millersburg', 'holmes'],
    homepage: 'https://www.holmescountyherald.com/',
    feedUrl: 'https://www.holmescountyherald.com/feed',
    feedType: 'RSS',
    language: 'en',
    provider: 'Holmes County Herald',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed county newspaper RSS.',
  },
  {
    id: 'us-oh-canton-rep',
    name: 'Canton Repository',
    type: 'NEWSPAPER',
    city: 'Canton',
    county: 'Stark County',
    metro: 'Canton',
    region: 'Northeast Ohio',
    state: 'Ohio',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Canton / Stark County',
    aliases: ['canton', 'stark'],
    homepage: 'https://www.cantonrep.com/',
    feedUrl: 'https://www.cantonrep.com/feed',
    feedType: 'RSS',
    language: 'en',
    provider: 'Gannett',
    lastVerified: VERIFIED,
    status: 'BLOCKED',
    licenseClass: 'RESTRICTED',
    provenance: 'Canton paper; public RSS returned HTTP 403 during verification.',
  },
  {
    id: 'jp-tokyo-metro',
    name: 'Tokyo Metro',
    type: 'TRANSPORTATION',
    city: 'Tokyo',
    county: 'Tokyo',
    metro: 'Tokyo',
    region: 'Kanto',
    state: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    coverageLevel: 'CITY',
    serviceArea: 'Tokyo subway',
    aliases: ['tokyo', '東京', '東京都', 'tokyo metro'],
    homepage: 'https://www.tokyometro.jp/',
    feedUrl: 'https://www.tokyometro.jp/news/rss/news.xml',
    feedType: 'RSS',
    language: 'ja',
    provider: 'Tokyo Metro',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed official Tokyo Metro news RSS (20 items).',
  },
  {
    id: 'jp-tokyo-jma',
    name: 'JMA Tokyo forecast',
    type: 'WEATHER',
    city: 'Tokyo',
    county: 'Tokyo',
    metro: 'Tokyo',
    region: 'Kanto',
    state: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    coverageLevel: 'CITY',
    serviceArea: 'Tokyo Prefecture (130000)',
    aliases: ['tokyo', '東京', '東京都'],
    homepage: 'https://www.jma.go.jp/',
    feedUrl: 'https://www.jma.go.jp/bosai/forecast/data/overview_forecast/130000.json',
    feedType: 'JSON',
    language: 'ja',
    provider: 'Japan Meteorological Agency',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_API',
    provenance: 'Live-probed JMA Tokyo-prefecture overview JSON (targetArea 東京都).',
  },
  {
    id: 'jp-tokyo-weekender',
    name: 'Tokyo Weekender',
    type: 'NEWSPAPER',
    city: 'Tokyo',
    county: 'Tokyo',
    metro: 'Tokyo',
    region: 'Kanto',
    state: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    coverageLevel: 'CITY',
    serviceArea: 'Tokyo',
    aliases: ['tokyo', '東京', '東京都'],
    homepage: 'https://www.tokyoweekender.com/',
    feedUrl: 'https://www.tokyoweekender.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'Tokyo Weekender',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed English Tokyo city magazine RSS. Non-Tokyo Japan stories still require geo-match.',
  },
  {
    id: 'jp-tokyo-bousai',
    name: 'Tokyo Disaster Prevention',
    type: 'EMERGENCY',
    city: 'Tokyo',
    county: 'Tokyo',
    metro: 'Tokyo',
    region: 'Kanto',
    state: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    coverageLevel: 'CITY',
    serviceArea: 'Tokyo Metropolis',
    aliases: ['tokyo', '東京', '東京都'],
    homepage: 'https://www.bousai.metro.tokyo.lg.jp/',
    feedUrl: 'https://www.bousai.metro.tokyo.lg.jp/news.rss',
    feedType: 'RSS',
    language: 'ja',
    provider: 'Tokyo Metropolitan Government',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Official Tokyo disaster RSS retrieved 200; channel was empty at verification (no invented items).',
  },
  {
    id: 'us-la-abc7',
    name: 'ABC7 Los Angeles',
    type: 'TV',
    city: 'Los Angeles',
    county: 'Los Angeles County',
    metro: 'Los Angeles',
    region: 'Southern California',
    state: 'California',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Los Angeles',
    aliases: ['los angeles', 'l.a.', 'la county'],
    homepage: 'https://abc7.com/',
    feedUrl: 'https://abc7.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'ABC Owned Television Stations',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-la-ktla',
    name: 'KTLA 5',
    type: 'TV',
    city: 'Los Angeles',
    county: 'Los Angeles County',
    metro: 'Los Angeles',
    region: 'Southern California',
    state: 'California',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Los Angeles',
    aliases: ['los angeles', 'l.a.'],
    homepage: 'https://ktla.com/',
    feedUrl: 'https://ktla.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'Nexstar',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-la-cbs',
    name: 'CBS Los Angeles',
    type: 'TV',
    city: 'Los Angeles',
    county: 'Los Angeles County',
    metro: 'Los Angeles',
    region: 'Southern California',
    state: 'California',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Los Angeles',
    aliases: ['los angeles', 'l.a.'],
    homepage: 'https://www.cbsnews.com/losangeles/',
    feedUrl: 'https://www.cbsnews.com/losangeles/latest/rss',
    feedType: 'RSS',
    language: 'en',
    provider: 'CBS News',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-la-times',
    name: 'Los Angeles Times Local',
    type: 'NEWSPAPER',
    city: 'Los Angeles',
    county: 'Los Angeles County',
    metro: 'Los Angeles',
    region: 'Southern California',
    state: 'California',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Los Angeles / Southern California',
    aliases: ['los angeles', 'l.a.'],
    homepage: 'https://www.latimes.com/',
    feedUrl: 'https://www.latimes.com/local/rss2.0.xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'Los Angeles Times',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed LA Times local RSS. Statewide California items still require geo-match.',
  },
  {
    id: 'us-chi-abc7',
    name: 'ABC7 Chicago',
    type: 'TV',
    city: 'Chicago',
    county: 'Cook County',
    metro: 'Chicago',
    region: 'Chicagoland',
    state: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Chicago',
    aliases: ['chicago', 'cook county'],
    homepage: 'https://abc7chicago.com/',
    feedUrl: 'https://abc7chicago.com/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'ABC Owned Television Stations',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-chi-cbs',
    name: 'CBS Chicago',
    type: 'TV',
    city: 'Chicago',
    county: 'Cook County',
    metro: 'Chicago',
    region: 'Chicagoland',
    state: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Chicago',
    aliases: ['chicago', 'cook county'],
    homepage: 'https://www.cbsnews.com/chicago/',
    feedUrl: 'https://www.cbsnews.com/chicago/latest/rss',
    feedType: 'RSS',
    language: 'en',
    provider: 'CBS News',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-chi-wbez',
    name: 'WBEZ Chicago',
    type: 'RADIO',
    city: 'Chicago',
    county: 'Cook County',
    metro: 'Chicago',
    region: 'Chicagoland',
    state: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Chicago',
    aliases: ['chicago', 'cook county'],
    homepage: 'https://www.wbez.org/',
    feedUrl: 'https://www.wbez.org/rss',
    feedType: 'RSS',
    language: 'en',
    provider: 'Chicago Public Media',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public radio RSS (atom/rss items present).',
  },
  {
    id: 'us-chi-block-club',
    name: 'Block Club Chicago',
    type: 'NEWSPAPER',
    city: 'Chicago',
    county: 'Cook County',
    metro: 'Chicago',
    region: 'Chicagoland',
    state: 'Illinois',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Chicago',
    aliases: ['chicago', 'cook county'],
    homepage: 'https://blockclubchicago.org/',
    feedUrl: 'https://blockclubchicago.org/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'Block Club Chicago',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed neighborhood newspaper RSS.',
  },
  {
    id: 'us-mia-cbs',
    name: 'CBS Miami',
    type: 'TV',
    city: 'Miami',
    county: 'Miami-Dade County',
    metro: 'Miami',
    region: 'South Florida',
    state: 'Florida',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Miami / South Florida',
    aliases: ['miami', 'miami-dade', 'dade'],
    homepage: 'https://www.cbsnews.com/miami/',
    feedUrl: 'https://www.cbsnews.com/miami/latest/rss',
    feedType: 'RSS',
    language: 'en',
    provider: 'CBS News',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'us-mia-nbc6',
    name: 'NBC 6 South Florida',
    type: 'TV',
    city: 'Miami',
    county: 'Miami-Dade County',
    metro: 'Miami',
    region: 'South Florida',
    state: 'Florida',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Miami / South Florida',
    aliases: ['miami', 'miami-dade'],
    homepage: 'https://www.nbcmiami.com/',
    feedUrl: 'https://www.nbcmiami.com/news/local/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'NBCUniversal',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed local station RSS (homepage feed was empty; /news/local/feed/ returned items).',
  },
  {
    id: 'us-mia-local10',
    name: 'Local 10 WPLG',
    type: 'TV',
    city: 'Miami',
    county: 'Miami-Dade County',
    metro: 'Miami',
    region: 'South Florida',
    state: 'Florida',
    country: 'United States',
    countryCode: 'US',
    coverageLevel: 'CITY',
    serviceArea: 'Miami / South Florida',
    aliases: ['miami', 'miami-dade', 'hialeah'],
    homepage: 'https://www.local10.com/',
    feedUrl: 'https://www.local10.com/arc/outboundfeeds/rss/?outputType=xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'WPLG',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed public station RSS.',
  },
  {
    id: 'ca-toronto-cbc',
    name: 'CBC Toronto',
    type: 'TV',
    city: 'Toronto',
    county: null,
    metro: 'Toronto',
    region: 'Greater Toronto',
    state: 'Ontario',
    country: 'Canada',
    countryCode: 'CA',
    coverageLevel: 'CITY',
    serviceArea: 'Toronto',
    aliases: ['toronto', 'gta', 'etobicoke', 'scarborough', 'north york'],
    homepage: 'https://www.cbc.ca/news/canada/toronto',
    feedUrl: 'https://www.cbc.ca/webfeed/rss/rss-canada-toronto',
    feedType: 'RSS',
    language: 'en',
    provider: 'CBC',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed CBC Toronto RSS. National Canada items require geo-match.',
  },
  {
    id: 'ca-toronto-city',
    name: 'City of Toronto',
    type: 'PUBLIC_AGENCY',
    city: 'Toronto',
    county: null,
    metro: 'Toronto',
    region: 'Greater Toronto',
    state: 'Ontario',
    country: 'Canada',
    countryCode: 'CA',
    coverageLevel: 'CITY',
    serviceArea: 'Toronto',
    aliases: ['toronto', 'etobicoke', 'scarborough'],
    homepage: 'https://www.toronto.ca/',
    feedUrl: 'https://www.toronto.ca/news/feed/',
    feedType: 'RSS',
    language: 'en',
    provider: 'City of Toronto',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed official city news RSS.',
  },
  {
    id: 'fr-paris-20minutes',
    name: '20 Minutes Paris',
    type: 'NEWSPAPER',
    city: 'Paris',
    county: 'Paris',
    metro: 'Paris',
    region: 'Île-de-France',
    state: 'Île-de-France',
    country: 'France',
    countryCode: 'FR',
    coverageLevel: 'CITY',
    serviceArea: 'Paris',
    aliases: ['paris', 'île-de-france', 'ile-de-france'],
    homepage: 'https://www.20minutes.fr/paris/',
    feedUrl: 'https://www.20minutes.fr/feeds/rss-paris.xml',
    feedType: 'RSS',
    language: 'fr',
    provider: '20 Minutes',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed Paris RSS. National France items require geo-match.',
  },
  {
    id: 'fr-paris-events',
    name: 'Que faire à Paris',
    type: 'EVENTS',
    city: 'Paris',
    county: 'Paris',
    metro: 'Paris',
    region: 'Île-de-France',
    state: 'Île-de-France',
    country: 'France',
    countryCode: 'FR',
    coverageLevel: 'CITY',
    serviceArea: 'Paris',
    aliases: ['paris'],
    homepage: 'https://www.paris.fr/',
    feedUrl: 'https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/que-faire-a-paris-/records?limit=20',
    feedType: 'JSON',
    language: 'fr',
    provider: 'Ville de Paris',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_API',
    provenance: 'Live-probed official Paris open-data events API.',
  },
  {
    id: 'au-nsw-smh',
    name: 'Sydney Morning Herald NSW',
    type: 'NEWSPAPER',
    city: 'Sydney',
    county: null,
    metro: 'Sydney',
    region: 'New South Wales',
    state: 'New South Wales',
    country: 'Australia',
    countryCode: 'AU',
    coverageLevel: 'REGIONAL',
    serviceArea: 'Sydney / New South Wales',
    aliases: ['sydney', 'nsw', 'new south wales'],
    homepage: 'https://www.smh.com.au/',
    feedUrl: 'https://www.smh.com.au/rss/national/nsw.xml',
    feedType: 'RSS',
    language: 'en',
    provider: 'Nine',
    lastVerified: VERIFIED,
    status: 'ACTIVE',
    licenseClass: 'PUBLIC_RSS',
    provenance: 'Live-probed SMH NSW RSS. Not a Sydney-only city feed; story geo-match required. ABC Sydney feed 8056986 returned HTTP 500.',
  },
]

