import type { LearningEvidence, TrainingCandidate } from '@/lib/active-learning/types'
import type { Wave4DatasetRecord } from '@/lib/training-checkpoint/types'

export type EngineeringTerminalStatus = 'completed_verified' | 'completed_unverified' | 'failed_verification' | 'failed_execution' | 'cancelled' | 'blocked' | 'awaiting_review'
export type EngineeringActionRecord = { actionId: string; missionId: string; actionType: 'shell_command' | 'file_edit' | 'patch_application' | 'test' | 'typecheck' | 'lint' | 'build' | 'validator' | 'artifact_creation' | 'git_diff_inspection' | 'repo_inspection'; executor: string; startedAt: string; completedAt: string; description: string; command: string | null; exitCode: number | null; stdoutArtifactRef: string | null; stderrArtifactRef: string | null; inputArtifactRefs: string[]; outputArtifactRefs: string[]; contentHash: string; resultStatus: 'passed' | 'failed'; validatorType: string | null; metadata: Record<string, unknown> }
export type ObjectiveValidatorRecord = { validatorId: string; missionId: string; actionId: string; validatorType: string; passed: boolean; exitCode: number; artifactRefs: string[]; contentHash: string; observedAt: string }
export type EvidenceArtifactRecord = { artifactId: string; missionId: string; kind: 'stdout' | 'stderr' | 'diff' | 'validation_report' | 'generated_file' | 'schema_report'; path: string; mediaType: string; sizeBytes: number; contentHash: string; createdAt: string; secretScanPassed: boolean; hiddenCotScanPassed: boolean }
export type EngineeringMissionRecord = { missionId: string; projectId: string | null; conversationId: string | null; promptArtifactId: string | null; initiatedBy: 'commander' | 'code_operator'; executor: string; repoPath: string; worktreePath: string; branch: string; baseCommit: string; startedAt: string; completedAt: string | null; terminalStatus: EngineeringTerminalStatus; objective: string; capabilityTags: string[]; curriculumTags: string[]; sourceTaskLineageId: string; patchLineageId: string; actionIds: string[]; validatorIds: string[]; artifactIds: string[]; auditEventIds: string[]; auditSegment: string; metadata: Record<string, unknown> }
export type MaterializedRealEvidence = { mission: EngineeringMissionRecord; evidence: LearningEvidence; candidate: TrainingCandidate; datasetRecord: Wave4DatasetRecord }
export type RealDatasetManifest = { datasetId: string; version: 'wave4.2-v1'; createdAt: string; sourceEvidenceIds: string[]; contentHashes: string[]; curriculumTags: string[]; capabilityTags: string[]; parentCheckpoint: 'WRIM-0:checkpoint-final'; parentCheckpointHash: string; tokenizerId: 'WR-TOKENIZER-0'; tokenizerHash: string; corpusLineage: string[]; splitSeed: number; trainIds: string[]; validationIds: string[]; testIds: string[]; datasetManifestHash: string; leakageCheck: { passed: boolean; collisions: string[] }; admissionRuleVersion: 'wave4.2-real-v1'; trainingStarted: false }
