import type { SourcePermission } from './types'

const VERIFIED_AT = '2026-08-05T00:00:00.000Z'

const commonBlockedRetention = 'Unknown extraction permission defaults to blocked. Do not fetch or retain content.'

export const SOURCE_PERMISSION_REGISTRY: readonly SourcePermission[] = [
  {
    sourceId: 'gdelt',
    sourceName: 'GDELT 2.1 DOC API',
    category: 'news_discovery',
    officialDocumentation: 'https://blog.gdeltproject.org/gdelt-2-1-api-debuts/',
    accessMethod: 'PUBLIC_NEWS_API',
    accountRequirement: 'none',
    credentialRequirement: 'none',
    licenseClass: 'public metadata/news index',
    commercialUseStatus: 'TERMS_REVIEW_REQUIRED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'SNIPPET_ONLY',
    attributionRequirement: 'Preserve original publisher and URL.',
    pollingLimit: 'bounded query batches only',
    rateLimit: 'respect HTTP 429 and back off',
    sourceAuthority: 'NEWS_SIGNAL',
    extractionPermission: 'SNIPPET_ONLY',
    connectionState: 'BOUNDARY_ONLY',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Store metadata, permitted snippet, publisher URL, timestamps, and hash only.',
    permittedAgentUses: ['Global News Signal Agent'],
  },
  {
    sourceId: 'federal_register',
    sourceName: 'Federal Register API',
    category: 'official_rules',
    officialDocumentation: 'https://www.federalregister.gov/developers/documentation/api/v1',
    accessMethod: 'PUBLIC_OFFICIAL_API',
    accountRequirement: 'none',
    credentialRequirement: 'none',
    licenseClass: 'official public government API',
    commercialUseStatus: 'ALLOWED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve Federal Register official URL.',
    pollingLimit: 'bounded search only',
    rateLimit: 'respect HTTP 429',
    sourceAuthority: 'OFFICIAL_PRIMARY',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'BOUNDARY_ONLY',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Store official metadata and dates; do not store full document text.',
    permittedAgentUses: ['Official Source Corroboration Agent', 'Law and Rule Change Agent'],
  },
  {
    sourceId: 'congress_gov',
    sourceName: 'Congress.gov API',
    category: 'legislation',
    officialDocumentation: 'https://api.congress.gov/',
    accessMethod: 'FREE_KEY_COMMERCIAL',
    accountRequirement: 'API key',
    credentialRequirement: 'CONGRESS_GOV_API_KEY',
    licenseClass: 'official public government API with key',
    commercialUseStatus: 'ALLOWED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve Congress.gov official URL.',
    pollingLimit: 'key-limited bounded reads only',
    rateLimit: 'respect provider rate limits and HTTP 429',
    sourceAuthority: 'OFFICIAL_PRIMARY',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'NOT_CONFIGURED',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Store bill metadata and legislative state only.',
    permittedAgentUses: ['Official Source Corroboration Agent', 'Law and Rule Change Agent'],
  },
  {
    sourceId: 'regulations_gov',
    sourceName: 'Regulations.gov API',
    category: 'rulemaking',
    officialDocumentation: 'https://open.gsa.gov/api/regulationsgov/',
    accessMethod: 'FREE_KEY_COMMERCIAL',
    accountRequirement: 'API key',
    credentialRequirement: 'REGULATIONS_GOV_API_KEY',
    licenseClass: 'official public government API with key',
    commercialUseStatus: 'ALLOWED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve docket/document IDs and official URL.',
    pollingLimit: 'read-only bounded reads',
    rateLimit: 'respect provider rate limits and HTTP 429',
    sourceAuthority: 'OFFICIAL_PRIMARY',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'NOT_CONFIGURED',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Store docket metadata and deadlines; no public comment submission.',
    permittedAgentUses: ['Official Source Corroboration Agent', 'Law and Rule Change Agent'],
  },
  {
    sourceId: 'courtlistener',
    sourceName: 'CourtListener',
    category: 'court_authority',
    officialDocumentation: 'https://www.courtlistener.com/help/api/',
    accessMethod: 'PUBLIC_OFFICIAL_API',
    accountRequirement: 'none for public unauthenticated boundary',
    credentialRequirement: 'none in Phase 49-E-1',
    licenseClass: 'public legal metadata API',
    commercialUseStatus: 'TERMS_REVIEW_REQUIRED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve court, jurisdiction, citation, and URL.',
    pollingLimit: 'bounded public searches',
    rateLimit: 'respect HTTP 429',
    sourceAuthority: 'COURT_AUTHORITY',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'BOUNDARY_ONLY',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Store metadata and jurisdiction; no nationwide claim from limited authority.',
    permittedAgentUses: ['Official Source Corroboration Agent', 'Legal and Tax Escalation Agent'],
  },
  {
    sourceId: 'sam_gov',
    sourceName: 'SAM.gov Opportunities',
    category: 'procurement',
    officialDocumentation: 'https://open.gsa.gov/api/get-opportunities-public-api/',
    accessMethod: 'FREE_KEY_COMMERCIAL',
    accountRequirement: 'API key',
    credentialRequirement: 'SAM_GOV_API_KEY',
    licenseClass: 'official government procurement API',
    commercialUseStatus: 'ALLOWED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve notice ID, solicitation number, and official URL.',
    pollingLimit: 'bounded Phase 49-C adapter pagination',
    rateLimit: 'respect Phase 49-C rate-limit handling',
    sourceAuthority: 'OFFICIAL_PRIMARY',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'BOUNDARY_ONLY',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Reuse Phase 49-C normalized records only.',
    permittedAgentUses: ['Lawful Opportunity Pathway Agent', 'Eligibility Agent'],
  },
  {
    sourceId: 'usaspending',
    sourceName: 'USAspending',
    category: 'historical_awards',
    officialDocumentation: 'https://api.usaspending.gov/docs/',
    accessMethod: 'PUBLIC_OFFICIAL_API',
    accountRequirement: 'none',
    credentialRequirement: 'none',
    licenseClass: 'official public government API',
    commercialUseStatus: 'ALLOWED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve award identifiers.',
    pollingLimit: 'bounded Phase 49-C adapter requests',
    rateLimit: 'respect HTTP 429',
    sourceAuthority: 'HISTORICAL_AWARD_INTELLIGENCE',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'BOUNDARY_ONLY',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Historical award intelligence only; never open opportunity.',
    permittedAgentUses: ['Revenue and Value Agent'],
  },
  {
    sourceId: 'simpler_grants',
    sourceName: 'Simpler.Grants.gov',
    category: 'grants',
    officialDocumentation: 'https://simpler.grants.gov/',
    accessMethod: 'FREE_KEY_COMMERCIAL',
    accountRequirement: 'API key or approved public API access',
    credentialRequirement: 'SIMPLER_GRANTS_API_KEY',
    licenseClass: 'official grants boundary',
    commercialUseStatus: 'TERMS_REVIEW_REQUIRED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'METADATA_ONLY',
    attributionRequirement: 'Preserve opportunity ID and official application URL.',
    pollingLimit: 'read-only bounded metadata',
    rateLimit: 'respect provider rate limits',
    sourceAuthority: 'OFFICIAL_PRIMARY',
    extractionPermission: 'METADATA_ONLY',
    connectionState: 'NOT_CONFIGURED',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: null,
    retentionRule: 'Store grant metadata and eligibility facts only.',
    permittedAgentUses: ['Lawful Opportunity Pathway Agent', 'Eligibility Agent'],
  },
  {
    sourceId: 'guardian',
    sourceName: 'The Guardian Open Platform',
    category: 'news',
    officialDocumentation: 'https://open-platform.theguardian.com/documentation/',
    accessMethod: 'TERMS_REVIEW_REQUIRED',
    accountRequirement: 'API key',
    credentialRequirement: 'GUARDIAN_API_KEY',
    licenseClass: 'license status unverified',
    commercialUseStatus: 'TERMS_REVIEW_REQUIRED',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'SNIPPET_ONLY',
    attributionRequirement: 'Preserve Guardian URL and attribution.',
    pollingLimit: 'bounded metadata/snippet use',
    rateLimit: 'respect platform limits',
    sourceAuthority: 'NEWS_SIGNAL',
    extractionPermission: 'SNIPPET_ONLY',
    connectionState: 'TERMS_REVIEW_REQUIRED',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: 'Commercial license not verified.',
    retentionRule: 'No full article retention without verified commercial license.',
    permittedAgentUses: ['Global News Signal Agent'],
  },
  {
    sourceId: 'newsapi',
    sourceName: 'NewsAPI',
    category: 'news',
    officialDocumentation: 'https://newsapi.org/docs',
    accessMethod: 'DEVELOPMENT_ONLY',
    accountRequirement: 'API key',
    credentialRequirement: 'NEWS_API_KEY',
    licenseClass: 'developer/free access remains development-only unless upgraded',
    commercialUseStatus: 'DEVELOPMENT_ONLY',
    metadataUseStatus: 'ALLOWED',
    fullTextUseStatus: 'SNIPPET_ONLY',
    attributionRequirement: 'Preserve publisher and URL.',
    pollingLimit: 'development-only bounded tests',
    rateLimit: 'respect plan limits',
    sourceAuthority: 'NEWS_SIGNAL',
    extractionPermission: 'SNIPPET_ONLY',
    connectionState: 'DEVELOPMENT_ONLY',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: 'Developer/free credentials are not Production-connected.',
    retentionRule: 'No full article retention; metadata/snippet only.',
    permittedAgentUses: ['Global News Signal Agent'],
  },
  {
    sourceId: 'tavily_firecrawl',
    sourceName: 'Tavily and Firecrawl Research Stack',
    category: 'retrieval',
    officialDocumentation: 'https://docs.tavily.com/ and https://docs.firecrawl.dev/',
    accessMethod: 'APPROVED_EXTRACTION',
    accountRequirement: 'API keys',
    credentialRequirement: 'TAVILY_API_KEY / FIRECRAWL_API_KEY',
    licenseClass: 'provider terms and domain permission required',
    commercialUseStatus: 'TERMS_REVIEW_REQUIRED',
    metadataUseStatus: 'TERMS_REVIEW_REQUIRED',
    fullTextUseStatus: 'LICENSE_REQUIRED',
    attributionRequirement: 'Preserve original source URL and extraction provider.',
    pollingLimit: 'approved domains only',
    rateLimit: 'respect provider limits and source permissions',
    sourceAuthority: 'SEARCH_METADATA',
    extractionPermission: 'EXTRACTION_NOT_AUTHORIZED',
    connectionState: 'TERMS_REVIEW_REQUIRED',
    lastVerifiedAt: VERIFIED_AT,
    lastSuccessfulRefresh: null,
    lastFailure: null,
    failureReason: 'Arbitrary domains are blocked; explicit domain permission is required.',
    retentionRule: 'Metadata/snippets only unless source license permits more.',
    permittedAgentUses: ['Official Source Corroboration Agent'],
  },
] as const

export function getSourcePermission(sourceId: string): SourcePermission {
  return SOURCE_PERMISSION_REGISTRY.find(source => source.sourceId === sourceId) ?? {
    sourceId,
    sourceName: sourceId,
    category: 'unknown',
    officialDocumentation: 'unknown',
    accessMethod: 'EXTRACTION_NOT_AUTHORIZED',
    accountRequirement: 'unknown',
    credentialRequirement: 'unknown',
    licenseClass: 'unknown',
    commercialUseStatus: 'TERMS_REVIEW_REQUIRED',
    metadataUseStatus: 'BLOCKED',
    fullTextUseStatus: 'BLOCKED',
    attributionRequirement: null,
    pollingLimit: 'none',
    rateLimit: 'none',
    sourceAuthority: 'UNKNOWN',
    extractionPermission: 'EXTRACTION_NOT_AUTHORIZED',
    connectionState: 'TERMS_REVIEW_REQUIRED',
    lastVerifiedAt: null,
    lastSuccessfulRefresh: null,
    lastFailure: 'unknown_source',
    failureReason: commonBlockedRetention,
    retentionRule: commonBlockedRetention,
    permittedAgentUses: [],
  }
}

export function canUseSourceInProduction(sourceId: string, env: NodeJS.ProcessEnv = process.env): boolean {
  const permission = getSourcePermission(sourceId)
  if (sourceId === 'guardian') return false
  if (sourceId === 'newsapi') return env.NODE_ENV !== 'production' && Boolean(env.NEWS_API_KEY?.trim())
  return permission.connectionState === 'CONNECTED' && permission.commercialUseStatus === 'ALLOWED'
}
